### ISSUE TITLE
Selecting the "Docker" option in Configure does not ask for a container registry

### ISSUE THREAD

**Issue by steamwings** [MicrosoftDocs/azure-devops-docs#6560] opened 2019-12-04 20:09 UTC
I even created the service connection to my registry in Project Settings first, but the Docker option only has one field 'Dockerfile' for the Dockerfile path. I tried manually adding the name of the service connection I created `containerRegistry: $(my_connection)`, but when I try to run the pipeline, I get:

The pipeline is not valid. Job BuildAndPush: Step Docker1 input containerRegistry references service connection $(my_connection) which could not be found. The service connection does not exist or has not been authorized for use.

UPDATE: I got my pipeline working by using `containerRegistry: my_connection`. The Docker Configure option still does not behave as described for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ba2ebe-27c4-111b-18b4-0192d8c3fb3a
* Version Independent ID: f48fdf00-e04f-b406-93f3-20b7fad568be
* Content: [Build and push to Azure Container Registry - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/acr-template?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/containers/acr-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/containers/acr-template.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment] 2019-12-05 18:11
@steamwings Thank you for the feedback, assigning this to the author for review.

Please checkout [this post](https://stackoverflow.com/questions/56024471/azure-pipelines-build-docker-image-from-container-registry) for a similar issue and work-around using `containerregistrytype` and `dockerRegistryEndpoint` or vote for the built-in Docker container registry [here](https://developercommunity.visualstudio.com/idea/365911/have-a-built-in-docker-container-registry-in-vsts.html).

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
