### ISSUE TITLE
Addition to release trigger troubleshooting

### ISSUE THREAD

**Issue by DrBushyTop** [MicrosoftDocs/azure-devops-docs#8371] opened 2020-05-18 15:38 UTC
Hey, I think it would be good idea to add a link to this default branch page somewhere in the "My pipeline isn't triggering" section. Resource triggers not working has caused me the most headache out of all of these, and this default branch setting is so obscure that it should be mentioned here as well.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#default-branch-for-triggers 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e834fd0-59c9-3f45-a09d-88571d94c62e
* Version Independent ID: b798ba39-ef08-55eb-3fa0-731782a1d7e0
* Content: [Troubleshoot builds and releases - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=azure-devops#feedback)
* Content Source: [docs/pipelines/troubleshooting.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/troubleshooting.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment] 2020-05-19 21:32
@DrBushyTop Thank you for the suggestion, this is a great idea, and I'm sorry that you ran into trouble. I am updating this content right now, and I will include this update.

@msebolt I am doing some other work in this topic right now so I'll go ahead and catch this one and add it to that work.

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
