### ISSUE TITLE
Can Azure Dev Ops Server 2019 Organizations be leveraged through Azure Services (Functions) Deployment Center?

### ISSUE THREAD

**Issue by cperson** [MicrosoftDocs/azure-devops-docs#4815] opened 2019-07-10 17:41 UTC
I'm attempting to use this guide to auto-configure a Pipeline for Azure Functions, however this documentation suggests:|

We recommend this simple approach if:
You're not connecting from Azure DevOps Server 2019 or earlier versions of TFS

Is there any guidance for consumers that are connecting from Azure DevOps Server 2019 or earlier versions of TFS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26477658-d1ad-a4c9-0d9e-59aeead8a71e
* Version Independent ID: 45dfbd24-b9f4-fdf2-48a2-5648220204fe
* Content: [Connect to Microsoft Azure - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#feedback)
* Content Source: [docs/pipelines/library/connect-to-azure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/connect-to-azure.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cperson** [comment] 2019-11-15 21:42
Any update here?

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri1, devops-cicd/tech, devops/prod
