### ISSUE TITLE
Doc for Service Hooks hasn't been updated since 2016, and they have added more event

### ISSUE THREAD

**Issue by fafa-npu** [MicrosoftDocs/azure-devops-docs#6450] opened 2019-11-22 04:59 UTC
[Doc](https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops) for Service Hooks event hasn't been updated since 2016, and they have added more event since then. 
For example, they added a 'Pull Request Commented On' event but I don't know how to trigger it. 
Could you help update it?

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri3, doc-bug
