### ISSUE TITLE
What's the default branch?

### ISSUE THREAD

**Issue by PaulVipond** [MicrosoftDocs/azure-devops-docs#6812] opened 2020-01-03 12:24 UTC
From this statement: "The default branch is checked out unless you designate a specific ref."

If my pipeline is only triggered from other pipelines, is the default branch the branch that was committed to in the triggering pipeline build? It would be good to clarify what you mean by 'default' in general. I assume it means the branch which was committed to in the triggering commit for a typical repo change triggered pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2020-01-06 21:03
@PaulVipond Thank you for the question, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
