### ISSUE TITLE
Document Inconsistancies

### ISSUE THREAD

**Issue by hecflores** [MicrosoftDocs/azure-devops-docs#7129] opened 2020-01-31 14:03 UTC
I noticed some an inconsistencies in the documentation. resourceGroupName description mentions the dependency on the variable deployToSlotOrASE  but that variable is not listed in the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4a09e1d-5fe6-cac3-47c9-cb2f4422a473
* Version Independent ID: 4cf6d896-5421-d32f-5fca-90134ddcdfa1
* Content: [Azure App Service Settings task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-app-service-settings?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-app-service-settings.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-app-service-settings.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
