### ISSUE TITLE
List Subversion Users for complete repository

### ISSUE THREAD

**Issue by LodewijkSioen** [MicrosoftDocs/azure-devops-docs#4229] opened 2019-05-15 14:34 UTC
The docs have the following text:
"To extract a list of all SVN users from the root of your local Subversion checkout, run this PowerShell command"
However, most people have a specific branch checked out and not the entire subversion repository. If you run the command on a branch, there is a big chance you'll get errors about unknown users.
You can also run svn log for a remote repository by specifying the url in the command:
    svn.exe log ["SVN repo URL"] --quiet (...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Migrate from Subversion (SVN) to Git](https://docs.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops#feedback)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/perform-migration-from-svn-to-git.md)
* Product: **devops**
* Technology: **devops-whitepapers**
* GitHub Login: @hkamel
* Microsoft Alias: **hkamel**

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri1, devops-whitepapers/tech, devops/prod, doc-bug, investigating
