### ISSUE TITLE
machine level stage variable

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/azure-devops-docs#6993] opened 2020-01-20 00:39 UTC
"For example: the script can set a machine level stage variable which the application uses, like database connection string." maybe should read "...machine-level environment variable..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5233d9b7-e301-998a-f37b-91494dc55b10
* Version Independent ID: bcb2f43d-5b24-3df2-0515-9e724e03fb55
* Content: [Azure VM Scale Set Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-vmss-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-vmss-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-vmss-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri2, devops-cicd/tech, devops/prod

**Comment by HughDevlin** [comment] 2020-12-02 21:13
Please re-open this issue.

Please clarify the example cited in the description of the Custom script directory argument.
