### ISSUE TITLE
'Manage' permissions

### ISSUE THREAD

**Issue by daniel-dorroh** [MicrosoftDocs/azure-devops-docs#3836] opened 2019-04-02 00:19 UTC
The document mentions:

&gt; The account under which the agent runs needs **Manage** permissions for the C:\Windows\system32\inetsrv\ directory.

What are 'manage' permissions? As you can imagine, searching for 'manage permissions' in a search engine yields pretty generic results. Since this note describes a specific configuration, please be specific about what that configuration is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1c5394-611b-b119-dbf3-b88404e351d5
* Version Independent ID: fcc23259-21ec-f9fa-4e25-f587e1e0f41b
* Content: [Deploy to IIS on a Windows VM - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups?view=azure-devops)
* Content Source: [docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri1, devops-cicd/tech, devops/prod
