### ISSUE TITLE
Can the YAML list schema shown or the list of arguments be corrected

### ISSUE THREAD

**Issue by cicorias** [MicrosoftDocs/azure-devops-docs#8255] opened 2020-05-08 18:15 UTC
The YAML shown does not match the argument list shown. And there are serious gaps in things like including the Resource Group name when using service connections and RM and the clarity of that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcada909-0670-815f-66e7-abc3dfc3f10e
* Version Independent ID: e9e42b5b-1f86-94dd-8c47-2ed91aba743d
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy-version3?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy-version3.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy-version3.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment] 2020-05-12 02:49
@cicorias Thank you for the feedback.

It appears the article's YAML for `AzureFileCopy@3` needs a complete update to the latest [AzureFileCopyV4](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFileCopyV4). The sample is also using `AzureFileCopy@2`.  

Re-assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
