### ISSUE TITLE
Keyvault ip restrictions

### ISSUE THREAD

**Issue by haymansfield** [MicrosoftDocs/azure-devops-docs#7163] opened 2020-02-05 12:34 UTC
Does this task bypass ip restrictions on the keyvault or come under trusted services?
If not the page should indicate that suitable ip access should be configured, especially if using hosted agents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51c58837-c915-0dad-ec76-716dd45be7bb
* Version Independent ID: 3212c33a-fdbd-688a-5670-079d858a97ec
* Content: [Azure Key Vault task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-key-vault?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-key-vault.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
