### ISSUE TITLE
Artifacts - PyPi Package Outdated (Artifact Feed Not Refreshing)

### ISSUE THREAD

**Issue by Chapi15** [MicrosoftDocs/azure-devops-docs#12752] opened 2022-10-04 00:49 UTC
This appears to be an issue from a long long time, hope it gets fixed soon.

My software project has **mkdocs** as a dependecy, this package was updated on September 27 and since that day it hasn't updated on my artifacts feed.

These are the steps I followed to force a refresh in my Azure DevOps Artifact Feed:
1. Delete package from your system or dev environment
2. Delete package from your Azure DevOps Feed
3. Install the package via CLI **including the URL of my feed** inside Azure DevOps
    `pip install -U --extra-index-url https://pkgs.dev.azure.com/[Organization]/_packaging/[feed_name]/pypi/simple/ package_name` 

My theory is that pip looks for the package in the upstream source if it's not found in your Azure DevOps feed, by doing that the package's version is updated.

I suppose @carlin-q-scott was right regarding the permissions of your feed, you need to be admin for pulling a newer version of the package:

> What I've found is that the user performing the request for the package must have owner/admin permissions in order for the request to pull in an upstream package (version). This same limitation applies to the API request you shared, as well as `nuget install $packageName` or `dotnet add package $packageName`.
> 
> From [looking at this permissions table](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops#permissions-table), I'd imagine the permission needed would be: "Save packages from upstream sources". However, my pipeline System.AccessToken has that permission and the call fails for it, even though it succeeds using my Owner level Personal Access Token (PAT).

#8382

_Originally posted by @Chapi15 in https://github.com/MicrosoftDocs/azure-devops-docs/issues/8382#issuecomment-1266250279_

**Comment by WilliamAntonRohm** [comment] 2022-10-04 21:53
Closing as duplicate of #8382.

cc @ramiMSFT for awareness

**Closed by WilliamAntonRohm** 2022-10-04 21:53 UTC
Labels: cba, Pri3
