### ISSUE TITLE
Example for CodeCoverage XML

### ISSUE THREAD

**Issue by MJECloud** [MicrosoftDocs/azure-devops-docs#2901] opened 2019-01-03 08:43 UTC
Hey, 

can you please provide an example on how the XML needs to be formatted for AzureDevOps. 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=vsts)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **vinojos**

**Comment by wgv-srsedate** [comment] 2019-02-06 17:30
Since the task only supports formats using **Cobertura** or **JaCoCo**, I found some examples online:

**Cobertura**
https://raw.githubusercontent.com/jenkinsci/cobertura-plugin/master/src/test/resources/hudson/plugins/cobertura/coverage-with-data.xml

**JaCoCo**
https://www.jacoco.org/jacoco/trunk/doc/

**Comment by trajano** [comment] 2019-04-03 11:02
I think it would be better if they had two examples showing both Cobertura and Jacoco as well as what the default files they would be looking for. e.g. for jacoco the default file is jacaco.exec

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
