### ISSUE TITLE
Pre-deployment Policy check question

### ISSUE THREAD

**Issue by jmarcotte1981** [MicrosoftDocs/azure-devops-docs#6396] opened 2019-11-16 17:13 UTC
Hi - just to make sure I understand let me ask a question and provide feedback.
Question: 
Is this feature truly a pre-release "assessment", so that the validation of an ARM template for example _against existing Azure Policies_ for the subscription is done BEFORE the deployment attempt. So this would allow teams to get policy feedback (particularly on items that would fail on a DENY) **days or weeks** before the planned production deployment. Is that right? And that this capability is not solely for the deployments of Azure policies themselves.
Feedback: Up till now there has been no ARM linting tool (like an AWS CFN-NAG scan for example), so if this policy pre-deployment assessment works as outlined it will add great value.
Pleases add a real example of a pre-deployment assessment of an ARM document. 
I'm very excited about the potential of this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1523fd9c-07c8-5b51-da53-329145377f33
* Version Independent ID: 18550c10-4a5d-ad2a-bdd1-51824bce9b09
* Content: [Azure Policy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-policy?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/azure-policy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/azure-policy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri2, devops-cicd/tech, devops/prod
