### ISSUE TITLE
How to reference pipeline variables?

### ISSUE THREAD

**Issue by cawoodm** [MicrosoftDocs/azure-devops-docs#8307] opened 2020-05-13 12:37 UTC
This page references "Pipeline Variables" without saying how to use them. How would we name the release after the pipeline variable Foo?

Something like `Parts-$(Release.Foo)` or `Parts-$(Foo)` except these do not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=powershell&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri1, devops-cicd-release/tech, devops/prod, doc-enhancement
