### ISSUE TITLE
Argument name not mentioned when describing the argument in detailed (Applicable for almost entire docs.microsoft.com documentation)

### ISSUE THREAD

**Issue by srikcgaa2** [MicrosoftDocs/azure-devops-docs#3677] opened 2019-03-18 18:52 UTC
In all documentation pages, the argument name is not mentioned when explaining the arguments in detail.  For example, the word msbuildarguments appears just once in the entire page while the detailed document describes as "MSBuild Arguments".  In this case it is at least straight forward, but we have to remember the position of the argument above and come down to the same position to understand the meaning of it. 

This comment is applicable for ALL documentation page, not just this one page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22342679-18af-7c79-f902-fe9c0bb55379
* Version Independent ID: a8e7c201-6593-458b-5a81-b54e93fde4b5
* Content: [MSBuild build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/msbuild?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/msbuild.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/msbuild.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by clifmo** [comment] 2019-03-29 12:18
Agreed. I only know to use /p: prefixes because of the task default settings. Too much is to be inferred or implied in this article, and that appears to be a norm

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
