### ISSUE TITLE
"Authorize Resources" does not exist -  https://aka.ms/yamlauthz

### ISSUE THREAD

**Issue by neilp-snow** [MicrosoftDocs/azure-devops-docs#5888] opened 2019-10-08 14:15 UTC
I have built a release pipeline in Azure DevOps.

https://aka.ms/yamlauthz describes that there should be a "Authorize Resources" button as button, however there is no such thing. Please update the documentation to include a fix for release pipelines as well as builds.

> Exception Message: The pipeline is not valid. Job Phase_1: Step AzureResourceGroupDeployment input ConnectedServiceName references service connection 
> which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, 
> refer to https://aka.ms/yamlauthz. (type PipelineValidationException)

![image](https://user-images.githubusercontent.com/55080478/66403268-330cd000-e9de-11e9-8708-6c7328d0eb20.png)

**Comment by msebolt** [comment] 2019-10-08 17:45
@neilp-snow  Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri3, doc-enhancement
