### ISSUE TITLE
Documentation on expression is missing how to filter an array of json based on a field of type String

### ISSUE THREAD

**Issue by GSManganneau** [MicrosoftDocs/azure-devops-docs#7068] opened 2020-01-27 14:03 UTC
Hi everyone !

I call an API with a Invoke Rest API task in my pipeline.
The body of the answer looks like this:

```
{
  "count": 2,
  "value": [
    {

      "maxParallelism": 1,
      "createdOn": "2020-01-20T14:49:29.217Z",
      "id": 103,
      "name": "mydockeragent",
      "version": "2.163.1",
      "enabled": true,
      "status": "online",
      "provisioningState": "Provisioned",
      "accessPoint": "CodexAccessMapping"
    },
    {
     
      "maxParallelism": 1,
      "createdOn": "2020-01-23T16:02:18.47Z",
      "id": 104,
      "name": "mydockeragent2",
      "version": "2.163.1",
      "enabled": true,
      "status": "offline",
      "provisioningState": "Provisioned",
      "accessPoint": "CodexAccessMapping"
    }
  ]
}
```

I struggle to find the good expression to know if I have more than 0 elementsin my 'value' array which have the field "status" equals to  "online".

I went trough the documentation and even trough github, the closest things I found but which did not work are:

```
gt(count(jsonpath('value[?(@.status==online)]')), 0)
gt(count(jsonpath('value[?(@.status=\'online\’)]')), 0)
gt(count(jsonpath('value[?(@.status=="online")]')), 0)
gt(count(jsonpath('value[?(@.status==\"online\")]')), 0)
```
I tried the same kind of filter on non String field and it works.
For instance, i was able to do:
`
gt(count(jsonpath('value[?(@.id>100)]')), 0)`

Does anyone has an idea how to do that ?
Or any documentation which might help ?

Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment] 2020-01-28 19:51
@GSManganneau Thank you for the question.

The documentation in [Invoke REST API task](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/http-rest-api) seems to have no clear description on using `jsonpath`.

Assigning this to the author for further review.

In the meantime, please refer to [this post](https://developercommunity.visualstudio.com/content/problem/291331/filter-jsonpath-results-using-variable.html) or try to [solicit further feedback](https://developercommunity.visualstudio.com/spaces/21/index.html) from the product team.

**Comment by RoopeshNair** [comment] 2020-01-29 09:07
@sashban for invoke REST api task

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri3, doc-enhancement
