### ISSUE TITLE
Template reference syntax is not documented when using multiple repos

### ISSUE THREAD

**Issue by mtaylorfsmb** [MicrosoftDocs/azure-devops-docs#6894] opened 2020-01-10 19:00 UTC
With the support for multiple repos we can now use `checkout` to check out a template repo. When using the `resource`  syntax we reference templates using the resource name.

```yaml
resources:
  repositories:
    - repository: templates
       type: git
      name: build-tools

steps:
- template: my-build.yml@templates
```

But this doesn't appear to work with the `checkout` syntax.

```yaml
- checkout: git://build-tools
   path: templates

steps:
- template: my-build.yml@templates
```
Provide documentation on the correct syntax for this. It seems like it would be just prefixing the template path with the path used in `checkout` but that doesn't work either.

```yaml
- checkout: git://build-tools
   path: templates

steps:
- template: templates/my-build.yml
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#template-references)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2020-01-13 19:25
@mtaylorfsmb Thank you for the feedback, assigning this to the author for review.

In the meantime, please see if either [this post](https://developercommunity.visualstudio.com/content/problem/579283/azure-devops-pipeline-with-template-does-not-check.html) or [this post](https://stackoverflow.com/questions/57808193/is-it-possible-to-refrence-files-inside-azure-devops-pipeline-templates-when-the) can resolve your issue.

**Comment by mtaylorfsmb** [comment] 2020-01-13 19:51
Unfortunately neither of these would resolve the issue. Theses posts seem to pre-date multi repo checkouts which literally check out the repo to the agent's build directory. For now I'm using the `resources` attribute so I can reference them but it seems like you'd need to use the full path to where the repo was checked out if you just wanted to use `checkout`. A working example would help clarify the correct approach.

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
