### ISSUE TITLE
How to increase parameter set limit in TFS?

### ISSUE THREAD

**Issue by NissehBeh** [MicrosoftDocs/azure-devops-docs#3779] opened 2019-03-26 15:19 UTC
We have about 200 parameter sets, if i add another parameter set the last parameter set will disapear from the list.
How can we increase the max parameter set limit in TFS 2018?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7761a45-1375-dd7d-a3e8-d1d6d4bdbf9c
* Version Independent ID: 11be5092-02c1-37f7-3e52-e398b0cb6abd
* Content: [Repeat a test with different data - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/repeat-test-with-different-data?view=azure-devops#feedback)
* Content Source: [docs/test/repeat-test-with-different-data.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/repeat-test-with-different-data.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri2, devops/prod
