### ISSUE TITLE
The example in the dependencies section is not consistent with the section 

### ISSUE THREAD

**Issue by clix455** [MicrosoftDocs/azure-devops-docs#5492] opened 2019-09-05 04:06 UTC
In the Dependencies section, when switching to the 'Classic' option, it is using the 'Release Pipeline' as the demonstration example for dependencies, unfortunately 'Release Pipeline' does not support Job dependencies. 'Build pipeline' would be a better example for demonstrating 'Dependencies'.  
Also, this example is more about 'Conditions', rather than dependencies, it is not the best section for it.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines, Azure DevOps Server, and TFS - Azure Pipelines](https://docs.microsoft.com/en-au/azure/devops/pipelines/process/phases?view=azure-devops&tabs=classic#feedback)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by clix455** [comment] 2019-09-18 00:17
Just to follow up, any progress?

**Comment by clix455** [comment] 2019-11-10 21:49
just to follow up, has this been done yet?

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
