### ISSUE TITLE
Limits for overriding parameters in devops

### ISSUE THREAD

**Issue by mslot** [MicrosoftDocs/azure-devops-docs#7130] opened 2020-01-31 14:24 UTC
When reading about devops I can't find any information on how many parameters you can override when releasing ARM templates. Does this kind of information regarding max limits of parameters exist? I have a lot of parameters that I need to override, so I want to be sure I don't hit an upper limit. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Cbrowser%2Ctfs-2018-2)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug

**Comment by mslot** [comment] 2020-11-27 08:52
@cxwtool i have specifically requested info on the subject, because i cant find anything about it in the docs, so is there more info on this in the docs, or dont we want to include more info on the subject?

I cant see why we should close this, because i actually see it as relevant info to know when doing deployment with DevOps.
