### ISSUE TITLE
Missing description for externalFeedCredentials

### ISSUE THREAD

**Issue by sid-dahiya** [MicrosoftDocs/azure-devops-docs#4980] opened 2019-07-23 22:50 UTC
On page: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops, there is no documentation for `externalFeedCredentials` attribute. This YAML parameter is extremely useful when connecting to multiple authenticated feeds via Service Connections.

For reference, this string may contain a comma separated list of Service Connections such as:
`externalFeedCredentials: 'SC1,SC2,SC3,...,SCn'`

**Comment by sid-dahiya** [comment] 2019-07-24 16:37
Sent out PR #4981 to address this.

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri3, doc-bug
