### ISSUE TITLE
Provide a working sample for iOS

### ISSUE THREAD

**Issue by apacha** [MicrosoftDocs/azure-devops-docs#6860] opened 2020-01-08 12:53 UTC
See https://github.com/MicrosoftDocs/vsts-docs/issues/6766 for details. It would be great to see how the documentation https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/xcuitest relates to this build step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9bddcbb-0f53-0f19-2a72-08be46e02de2
* Version Independent ID: 7a75fbe0-089e-bb0a-cea4-3909418a69a9
* Content: [App Center Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/app-center-test?view=azure-devops#q--a)
* Content Source: [docs/pipelines/tasks/test/app-center-test.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/app-center-test.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment] 2020-01-09 02:59
@apacha Thank you for the feedback, assigning this to the author for review.

In the meantime, please refer to [this](https://docs.microsoft.com/appcenter/build/react-native/ios/) **App Center** doc for an example using React Native and iOS.

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
