### ISSUE TITLE
Agent types are mutually exclusive

### ISSUE THREAD

**Issue by cadull** [MicrosoftDocs/azure-devops-docs#7497] opened 2020-03-05 02:02 UTC
A single agent can't be configured to be in an agent pool and a deployment group or environment at the same time. You can however create a deployment group utilising the deployment pool for an environment. Any agents added to the environment will also be in the deployment group. Alternatively, multiple agents can be installed. Found this when looking for ways to transition from deployment groups to environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy an Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#remove-and-re-configure-an-agent)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment] 2020-03-09 14:39
@cadull Thank you for this information, I will get this clarified in our docs.

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri1, devops-cicd-agents/tech, devops/prod, doc-bug
