### ISSUE TITLE
Xamarin.iOS task needs clarification

### ISSUE THREAD

**Issue by VitorRigoni** [MicrosoftDocs/azure-devops-docs#3957] opened 2019-04-14 16:43 UTC
The `solutionFile` argument for `Xamarin.iOS@2` task also accepts the iOS csproj file, but this is not clear in the documentation.
Pointing to the solution file will build all existing apps (in my case, both iOS and Android apps) but, depending on the pipeline, we need to simply build the iOS app.

Clarifying the docs with a note that this argument also accepts the iOS csproj file would help developers avoid doing trial and error to figure out this also works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d91aa34-87c4-d934-28e2-456eac57432d
* Version Independent ID: 5725c1ab-d894-f79c-f7e0-0c5b8b5cca56
* Content: [Xamarin.iOS build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xamarin-ios?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/xamarin-ios.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/xamarin-ios.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by Mikilll94** [comment] 2020-04-25 13:40
@VitorRigoni 

Theoretically, this is fixed, but:

```
(Required) Relative path from the repository root of the Xamarin.iOS solution or csproj project to build. May contain wildcards.
```

I think this description is confusing bad-written. This will be better:

```
(Required) Relative path from the repository root to the Xamarin.iOS solution file (.sln) or .csproj file. May contain wildcards.
```

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
