### ISSUE TITLE
The run --once documentation for Linux containers is a bit unclear

### ISSUE THREAD

**Issue by nwchandler** [MicrosoftDocs/azure-devops-docs#8416] opened 2020-05-21 12:59 UTC
The documentation states: "If you want a fresh agent container for every pipeline run, you should pass the --once flag to the run command." The call to run is hidden a bit in the Linux agent, though, as it goes through AgentService.js. It may be clearer to indicate that the --once flag would be added to the AgentService call; i.e., "exec ./externals/node/bin/node ./bin/AgentService.js interactive --once"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-cicd-agents/tech, devops/prod, doc-enhancement
