### ISSUE TITLE
this article maybe old

### ISSUE THREAD

**Issue by tamitarai** [MicrosoftDocs/azure-devops-docs#4780] opened 2019-07-08 06:32 UTC
An error below  occurred when  following the steps in this page, but  was successful when I follow  steps of and fork this URL https://github.com/MachineIearning/MLOpsPython/blob/master/README.md .

[Occuered Error]
"The pipeline is not valid. Job Job: Step AzureCLI1 input connectedServiceNameARM references service connection build-demo which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.,Job Job: Step AzureCLI2 input connectedServiceNameARM references service connection &lt;xxxxxx&gt; which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa0194a9-ffa7-fa79-e6c7-8ecb5e8c93ec
* Version Independent ID: 4f5a9f04-b629-b8b1-1332-9260c95d13b7
* Content: [Azure Machine Learning service training and deployment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-machine-learning?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-machine-learning.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/azure-machine-learning.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @jpe316
* Microsoft Alias: **jordane**

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
