### ISSUE TITLE
Azure Pipelines - run vs artifact retention

### ISSUE THREAD

**Issue by razidare** [MicrosoftDocs/azure-devops-docs#5969] opened 2019-10-14 07:01 UTC
Hello,

We use Azure Pipelines (enabled preview feature `multi-stage pipelines` for our organization) and we create [pipeline artifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops) for each run. We plan to use `az pipelines runs artifact download` command from `az cli` in a different process and the question is, what's the retention policy on these pipeline artifacts?

The documentation is rather vague, saying that retention policies for Azure Pipelines are still under development and we don't understand if, when the run is deleted, the artifact is lost as well? Also, are there limits on the artifacts (retention periods/sizes)?
What would happen if a run is deleted? Could we still access the artifact attached to it if we needed to?

Thank you

**Comment by msebolt** [comment] 2019-10-14 22:19
@razidare Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri3, doc-enhancement
