### ISSUE TITLE
Add info for publishing symbols from *nix build agents?

### ISSUE THREAD

**Issue by buck-mbeer** [MicrosoftDocs/azure-devops-docs#5349] opened 2019-08-23 14:38 UTC
It would be great if this article could be updated for publishing symbols from *nix build agents for us .NET Core folks. I'm aware that dotnet nuget push let's you pass a --symbol-source argument, so maybe it would be enough if the article explains what the URL format is of the Azure Devops symbol server (which I'm guessing is different between Services and Server).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cddddb9-2731-3366-2a76-9089b58d7f96
* Version Independent ID: b34de428-c3d2-14d6-a452-302c68b74c87
* Content: [Publish symbols for debugging - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/pipelines/artifacts/symbols.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/symbols.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **amullans**

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
