### ISSUE TITLE
How to properly configure Get Sources for TFVC when Triggers > Path filters includes $/Project/Main and $/Project/Features/*

### ISSUE THREAD

**Issue by ericnewton76** [MicrosoftDocs/azure-devops-docs#2682] opened 2018-12-07 04:23 UTC
This is confusing on the TFVC Get Sources screen... 

Type     Mapping                           Local Path
Map v   [$/Project/Main            ]   [                                    ]

this will work fine when a changeset is committed for $/Project/Main... but what about when a changeset is committed in $/Project/Features/* branch?  How do you get sources properly for that situation?

Triggers and Get Sources are too disjoint to work properly... Triggers is directly related to Get Sources... so Get Sources should be under Triggers instead of under Pipeline

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=designer)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by phroiland** [comment] 2019-07-17 21:03
Triggers for branches don't work with the default Get Sources branch. THAT YAML FILE IS NEVER UPDATED!

I have branch qa as my default in Get Sources.
my yaml file has triggers for branches which include: qa/*

According to EVERYTHING I'm reading--if I branch from qa, I can build with that trigger and subsequent wildcard. 

Why would one have to go in and MANUALLY update the branch triggers as well as the default branch in Get Sources (beacuase that's the only way I can get it to work), EVERYTIME you branch? What the hell is the point of DevOps if you have Developers (non-DevOps) making changes to your yaml files?

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri1, devops/prod
