### ISSUE TITLE
Language Commands for julia are out of date.

### ISSUE THREAD

**Issue by mhangaard** [MicrosoftDocs/azure-devops-docs#7034] opened 2020-01-23 09:38 UTC
Instead do 
    wget -nv https://julialang-s3.julialang.org/bin/linux/x64/1.3/julia-1.3.1-linux-x86_64.tar.gz
    tar zxf julia-1.3.1-linux-x86_64.tar.gz
    ./julia-1.3.1/bin/julia --project=@. -e 'using Pkg; Pkg.instantiate()'
but adapt the above to the desired version, e.g. set version using an environment variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035d0e47-a927-1e99-34a4-181e34578af3
* Version Independent ID: ab6853d8-98cf-dd68-7425-4644cc7e0492
* Content: [Migrate from Travis to Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-travis?view=azure-devops#feedback)
* Content Source: [docs/pipelines/migrate/from-travis.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/migrate/from-travis.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
