### ISSUE TITLE
Reference please

### ISSUE THREAD

**Issue by sevaa** [MicrosoftDocs/azure-devops-docs#769] opened 2018-05-11 17:39 UTC
For register(), what exactly is the "object instance"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f699a190-5e7e-1103-8d9d-c3d58e698e3a
* Version Independent ID: 1e54fe20-7e4d-d5ff-1682-8659f7a8fba8
* Content: [Core Client SDK](https://docs.microsoft.com/en-us/vsts/extend/reference/client/core-sdk?view=vsts#method_register)
* Content Source: [docs/extend/reference/client/core-sdk.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/reference/client/core-sdk.md)
* Service: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment] 2018-05-18 13:58
Hi @sevaa , I've reached out to the product team with your issue, just waiting on a response!

**Comment by kduenke** [comment] 2018-07-14 13:22
Yes, the documentation for this is terrible.  It's especially bad when the object properties are so ad hoc (onFieldChanged, onLoaded, load, onUnloaded, onSaved, onSave).  They're essentially random.

https://docs.microsoft.com/en-us/vsts/extend/develop/add-workitem-extension?view=vsts
https://docs.microsoft.com/en-us/vsts/report/extend-analytics/widget-extension-against-analytics-service-configuration?view=vsts

**Comment by cxwtool** [comment] 2020-11-24 23:50
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:50 UTC
Labels: Pri2, devops-ecosystem/tech, devops/prod, devops/svc, doc-bug, help wanted
