### ISSUE TITLE
Q&A Question Discrepancy 

### ISSUE THREAD

**Issue by RyanMathewson** [MicrosoftDocs/azure-devops-docs#403] opened 2018-03-26 12:52 UTC
Under Q&A the question "Are there C# libraries that I can use to create subscriptions?" provides an example for the a receiver, not the programmatic creation of a subscription.
https://docs.microsoft.com/en-us/vsts/service-hooks/create-subscription?view=vsts#q-are-there-c-libraries-that-i-can-use-to-create-subscriptions

If the question was intended to be "Are there C# libraries that I can use to CONSUME subscriptions?" then the answer would yes and should point to the receivers Nuget project: https://www.nuget.org/packages/Microsoft.AspNet.WebHooks.Receivers.VSTS/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162ea8ce-f3c4-5ea1-fecc-663ac351a60b
* Version Independent ID: 7f40bf79-259f-43bc-0582-7e8f5721a294
* Content: [Subscribe to VSTS events from another service](https://docs.microsoft.com/en-us/vsts/service-hooks/create-subscription?view=vsts#q-are-there-c-libraries-that-i-can-use-to-create-subscriptions)
* Content Source: [docs/service-hooks/create-subscription.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/service-hooks/create-subscription.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment] 2018-12-18 19:56
I know it's been a while @RyanMathewson , but thanks for your feedback. adding @roofers here to help me find out what change needs to be made here.

**Comment by fiksen99** [comment] 2019-08-17 00:24
This issue is still present - the example shows a receiver to an event hook, but the question is about programmatically *creating* a subscription to an event hook

**Comment by juangps96** [comment] 2020-03-06 18:09
Yes,  @RyanMathewson, We need a real example  of Microsoft.AspNet.WebHooks.Receivers.VSTS

**Comment by brentlyjdavid** [comment] 2020-03-07 01:02
@elbatk @flksen99 @juangps96
Install Microsoft.VisualStudio.Services.ServiceHooks.WebApi and  Microsoft.TeamFoundationServer.Client (same versions) and the results are similar to all the other types, getting a particular client. in this case the http client is in the first nuget package and not in the core client library it looks like.  class name is 'ServiceHooksPublisherHttpClient'

**Comment by cxwtool** [comment] 2020-11-24 23:50
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:50 UTC
Labels: Pri2, devops-collab/tech, devops/prod, doc-bug, help wanted, unspecified/svc
