### ISSUE TITLE
UI testing with Azure Pipelines inside Docker container

### ISSUE THREAD

**Issue by rolfik** [MicrosoftDocs/azure-devops-docs#3270] opened 2019-02-07 09:28 UTC
It would be nice to have some instructions how to use Azure Pipelines UI testing (with Appium) inside Docker container with local agent.

Thank You

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c96ae1b3-ab4c-540e-c4ca-79075f55f202
* Version Independent ID: c7b3e395-c55e-51a1-0f7e-8f5fb0430ee8
* Content: [Configure for UI testing - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops&tabs=mstest#visible-ui-testing-using-self-hosted-windows-agents)
* Content Source: [docs/pipelines/test/ui-testing-considerations.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/ui-testing-considerations.md)
* Product: **devops**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
