### ISSUE TITLE
Download Pipeline Artifact error

### ISSUE THREAD

**Issue by richardgavel** [MicrosoftDocs/azure-devops-docs#6455] opened 2019-11-22 20:57 UTC
When using Download Pipeline Artifact within a release pipeline, I get the following error. This works fine when the artifact is published with "Publish pipeline artifact (0.140.0)", but this error is coming from a pipeline using "Publish build artifacts (1.158.1)". Doesn't this conflict with the fact the description below is "Download build and pipeline artifacts"?

2019-11-22T20:54:17.3018438Z ##[section]Starting: Download artifact - _configuration - configuration
2019-11-22T20:54:17.3141147Z ==============================================================================
2019-11-22T20:54:17.3141222Z Task         : Download Pipeline Artifacts
2019-11-22T20:54:17.3141254Z Description  : Download build and pipeline artifacts
2019-11-22T20:54:17.3141447Z Version      : 2.1.1
2019-11-22T20:54:17.3141478Z Author       : Microsoft Corporation
2019-11-22T20:54:17.3141524Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-pipeline-artifact
2019-11-22T20:54:17.3141554Z ==============================================================================
2019-11-22T20:54:19.2887314Z Download from the specified build: #29383
2019-11-22T20:54:19.2898274Z Download artifact to: C:\vsts-agent-1\_work\r31\a/_configuration/Configuration
**2019-11-22T20:54:19.4756506Z ##[error]The container 1513296 could not be found.**
2019-11-22T20:54:19.5045301Z ##[section]Finishing: Download artifact - _configuration - configuration

**Comment by msebolt** [comment] 2019-11-25 20:52
@richardgavel Thank you for the feedback, assigning this to the author for review.

Please see if https://github.com/microsoft/azure-pipelines-yaml/issues/215 addresses the issue, and that you're using the latest version with [this fix](https://developercommunity.visualstudio.com/content/problem/529677/artifact-not-found-using-download-pipeline-artifac.html).

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri3, doc-enhancement
