### ISSUE TITLE
How to get the type of update for "Pull request updated" event

### ISSUE THREAD

**Issue by nishantsny** [MicrosoftDocs/azure-devops-docs#4509] opened 2019-06-13 18:34 UTC
The page mentions to use "NotifcationType"
```
notificationType: The type of pull request change
Valid values:
PushNotification - Source branch updated
ReviewersUpdateNotification - Reviewers changed
StatusUpdateNotification - Status changed
ReviewerVoteNotification - Votes score changed
```

But I do not see "notificationType" in the response on this page, or on the logs of my test-setup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033d681-9093-547c-20fd-b31183c2bb33
* Version Independent ID: 0d92e3f0-7fb4-57e5-d913-f305a055a819
* Content: [Service hooks event reference](https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops#feedback)
* Content Source: [docs/service-hooks/events.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/events.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri2, devops-collab/tech, devops/prod, doc-bug
