### ISSUE TITLE
It's not clear to on-prem service connections

### ISSUE THREAD

**Issue by sadedil** [MicrosoftDocs/azure-devops-docs#6027] opened 2019-10-17 12:34 UTC
I can't find any information how to add an on prem service connection for example K8s service connection. Especially over the private IP.

I think there should be a site to site vpn or similar functionality to make connection between Azure DevOps and my private network.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment] 2019-10-17 19:58
@sadedil  - are you looking for creating connection to K8s cluster running on-premises? or connecting to On-prem Azure DevOps Server?

**Comment by sadedil** [comment] 2019-10-17 20:02
@RoopeshNair, the first one.

My K8s cluster is running in my office building. Azure DevOps is the cloud one, not the Azure DevOps Server.

**Comment by RoopeshNair** [comment] 2019-10-17 20:03
@sadedil  are you creating a service connection or setting up an environment with k8s resource?

**Comment by sadedil** [comment] 2019-10-17 20:04
Yes, I'm trying to create a K8s service connection.

**Comment by RoopeshNair** [comment] 2019-10-17 20:06
The steps to configure the service connection is [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-kuber). However, you need to ensure that the agent has line of sight to the k8s cluster.

**Comment by sadedil** [comment] 2019-10-17 20:13
Hmm, there is no agent selection in the service connection popup. How Azure DevOps knows the which agent to use when creating a service connection?

If my kubeconfig like this, how to Azure DevOps resolve the server Url? In this example _https://192.168.99.111:8443_

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LaS0tLS1CRUdJTiBDRVJUSUZ...
    server: https://192.168.99.111:8443
  name: 192-168-99-111:8443
```

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
