### ISSUE TITLE
.NET Framework ConnectionStrings cannot be set

### ISSUE THREAD

**Issue by bcrosnier** [MicrosoftDocs/azure-devops-docs#2949] opened 2019-01-07 17:32 UTC
Using the task (3.* and 4.* in preview), I can set Azure App Service Application settings and Site settings using the `-key value -key value` format in the *App settings* and *Configuration settings* fields respectively.

How do I set *Connection strings*?

To be clear, *I am not talking about .NET Core Connection strings* (which are simply all values within the `ConnectionStrings` section), I am talking about **.NET Framework Connection Strings** - I am deploying a .NET Framework app, I am not deploying a .NET Core app. Those are the one in the `connectionStrings` section of the legacy `web.config`, as well as the **Connection strings** section in the Azure App Service Application settings page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by olaj** [comment] 2019-02-13 08:06
Any comment on this? I also wondering how to do this?

**Comment by derekmckinnon** [comment] 2019-05-16 01:37
One somewhat unofficial way of setting `connectionStrings` and others in Azure DevOps is by adding an "Azure CLI" task (inline script) and supplying it with appropriate values.

Example:

```batch
call az webapp config connection-string set -g "$(Group)" -n "$(App)" -t SQLServer --settings DefaultContext='"$(ConnectionString)"'
```

This will add/update the connection string you want to inject. Use env/variables as needed by setting them in DevOps -> Library.

Hope this helps.

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
