### ISSUE TITLE
Run Test and Collect Code Coverage information section confusing

### ISSUE THREAD

**Issue by abelsquidhead** [MicrosoftDocs/azure-devops-docs#7884] opened 2020-04-09 19:35 UTC
This is for the Build, test and deploy .NET core apps - Azure Pipelines docs page
https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops

The Run your tests and Collect code coverage sections are super confusing because the forked repo does not have any tests. We should add some tests in the repo so the end user can see real tests being run and code coverage being gathered as they run through this tutorial.

**Comment by spboyer** [comment] 2020-04-09 20:47
@juliakm

**Comment by cxwtool** [comment] 2020-11-24 23:28
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:28 UTC
Labels: Pri3, doc-enhancement
