### ISSUE TITLE
Add information on how to add the package sources to VS for macOS

### ISSUE THREAD

**Issue by TomasHubelbauer** [MicrosoftDocs/azure-devops-docs#5399] opened 2019-08-28 10:57 UTC
Azure DevOps Artifacts feeds have a Connect to Feed button which when on the NuGet page shows a link to "How to add these in Visual Studio". This button leads to https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/consume which talks about Visual Studio for Windows. No word on Visual Studio for macOS. VS for macOS suffers from this insufferable modal when restoring a project which uses packages from private organizational feeds: https://developercommunity.visualstudio.com/content/problem/190904/vs-mac-asks-for-credentials-i-dont-know-which-cred.html

Unlike the poster there I do want to use private feeds and have not had them in Preferences > NuGet but when I added them as per the Azure DevOps Artifacts modal, they said Unreachable. I do not know what user name and password to use because my AAD credentials clearly are not enough.

When I attempt to restore I am hit with the NuGet prompt which just keeps reappearing every time I submit it. The error in VS for macOS shows the correct private feed URL, so I assume once it is explained how to add private feeds to VS for macOS including which credentials to use I will be able to restore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 899a78d6-9d08-7744-108d-10add2ba7e2c
* Version Independent ID: 6ab31e96-fed8-4335-ed81-b97663d8300f
* Content: [Consume NuGet packages in Visual Studio](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/consume?view=azure-devops)
* Content Source: [docs/artifacts/nuget/consume.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/consume.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by chasewilson** [comment] 2019-09-23 20:27
@TomasHubelbauer Thanks for the input. Artifacts will be releasing a new Connect to Feed experience soon which will update all of this. The experience should be much better and I will make sure to follow up then. I just wanted to let you know I have my eyes on this and will be working with you on it :) Thank you again and talk to you soon

**Comment by chasewilson** [comment] 2019-10-01 19:53
This will be updated with some new information based on a new credential provider. But it does appear that there is documentation for [VS for Mac](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/consume?view=azure-devops#macos-add-the-feed-to-your-nuget-configuration). Is there some information there you feel is missing?

**Comment by TomasHubelbauer** [comment] 2019-10-01 19:55
This part of my original question:

> Unlike the poster there I do want to use private feeds and have not had them in Preferences > NuGet but when I added them as per the Azure DevOps Artifacts modal, they said Unreachable. I do not know what user name and password to use because my AAD credentials clearly are not enough.

However the link you provided is super useful and for sure should be linked to from the page VSTS shows when clicking on the link in the Connect to Feed modal there.

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri1, devops-artifacts/tech, devops/prod, doc-enhancement
