### ISSUE TITLE
Docker build with tags requires containerRegistry

### ISSUE THREAD

**Issue by gedeh** [MicrosoftDocs/azure-devops-docs#5281] opened 2019-08-17 23:39 UTC
Thanks for the updating the task to version 2. Unfortunately the task input and example for each command is still not clear enough :( I tried over and over to use `build` and `push` docker image separately, the `tags` I put during `build` kept missing when pushing. 

Turns out, reading from https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DockerV2/dockerbuild.ts, it requires `containerRegistry`  defined so `tags` will be added to the fully qualified image name to push. Can you please update this page as containerization in CI/CD is more common these days.

```typescript
    let imageNames: string[] = [];    
    // if container registry is provided, use that
    // else, use the currently logged in registries
    if (tl.getInput("containerRegistry")) {
        let imageName = connection.getQualifiedImageName(repositoryName, true);
        if (imageName) {
            imageNames.push(imageName);
        }
    }
    else {
        imageNames = connection.getQualifiedImageNamesFromConfig(repositoryName, true);
    }
    ...
    let tags = tl.getDelimitedInput("tags", "\n");
    let tagArguments: string[] = [];
    // find all the tag arguments to be added to the command
    if (imageNames && imageNames.length > 0) {
        imageNames.forEach(imageName => {
            if (tags && tags.length > 0) {
                tags.forEach(tag => {
                    tagArguments.push(imageName + ":" + tag);
                });
            }
            else {
                // pass just the imageName and not the tag. This will tag the image with latest tag as per the default behavior of the build command.
                tagArguments.push(imageName);
            }
        });
    }
    else {
        tl.debug(tl.loc('NotAddingAnyTagsToBuild'));
    }
```

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#task-inputs)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **shasb**

**Comment by winstonhenke** [comment] 2019-08-19 01:21
Unsure about your specific reason for wanting the build and push to be separate but I was able to follow the example under 'Build and Push' to login to both my Docker Hub & Azure Container Registry and then do one 'Build and Push'. This resulted in both of my registries each getting a copy of each image/tag combo. It sounds like this might be the behavior you're looking for?

**Comment by gedeh** [comment] 2019-08-19 18:51
My scenario is after all unit tests passed, I run the image as container then perform separate set of integration tests.

Images only tagged as latest and pushed to registry when all integration tests against a running container passed so I am sure that when Azure container service spin it up there will be no issue in containerised app.

**Comment by polamarasetti** [comment] 2019-08-29 13:50
I am able to run docker task (Run ) in background and task completes successfully. I am looking to stop container at the end of pipeline (Docker stop .....) in another task at the end of pipeline. I do not see stop command in docker task. Any suggestion to stop containers in docker task.

**Comment by celamb4** [comment] 2019-11-04 21:56
I agree with this issue. Docker build and docker tag dont require credentials (dockerregistry connection) to run. Why are they a requirement? If the team only wants to run docker build, why is a service connection required?

**Comment by thviQit** [comment] 2019-11-26 10:45
We noticed this too, while converting to yaml pipelines. We only use this task for building the docker file and then use an AWS task to push the image to ECR. 
That means we cannot tag our image with the docker task.

**Comment by rnarayana** [comment] 2019-12-16 04:43
Workaround is to pass --tag in build arguments like this:
 --tag $(ImageTag)

**Comment by K3UL** [comment] 2020-01-13 23:40
Another case for separating Build and Push is also simply to pass build arguments, which is clearly indicated on this documentation page.
It happens for example if you want to use `--build-arg`, you can't `buildAndPush` then.

**Comment by strikeout** [comment] 2020-04-23 10:51
This cost us an hour to figure out. Please update the documentation.

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
