### ISSUE TITLE
Is this process automated, or manual?

### ISSUE THREAD

**Issue by ronnyek** [MicrosoftDocs/azure-devops-docs#1753] opened 2018-09-14 19:38 UTC
I'm just genuinely interested in how the release branches are created... a person manually going and creating a branch at the beginning of the sprint? Have you guys set up some form of automation to create the sprint release branch?

I appreciate the input!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1235ec4-e7e9-b0c2-8f1f-ee9682175a05
* Version Independent ID: a473750a-fbb6-4eed-e0e6-34e8a5009507
* Content: [Release Flow - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2frelease-flow.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2frelease-flow.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **ethomson**

**Comment by true-zanuda** [comment] 2019-05-01 05:36
I'm still interested in a response.

**Comment by alainvezina** [comment] 2019-05-08 01:07
Me too super interested!!

**Comment by tgdane** [comment] 2019-05-09 08:57
We are using this branching strategy and have automated the release branching using a script that essentially determines the next version number (by getting a list of branches matching releases/*, last version +1) then creates a new branch with the new version number. Push the new branch and have your CI/CD triggers on master and releases/*. The creation of a new release is essentially a business decision, so automate the process but trigger it on demand. But it could be scheduled if that works better. Hope that helps.

**Comment by FixRM** [comment] 2019-08-06 10:29
Hi @tgdane, can you please share more details about CI/СD triggers you use?

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri1, devops-learn/tech, devops/prod, doc-bug
