### ISSUE TITLE
This Python Package should be mentioned

### ISSUE THREAD

**Issue by dciborow** [MicrosoftDocs/azure-devops-docs#7283] opened 2020-02-14 06:12 UTC
https://github.com/pytest-dev/pytest-nunit

Within their readme they have a create Azure example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Publish Test Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
