### ISSUE TITLE
JUnit: incorrect 'run duration' in summary of test resuls

### ISSUE THREAD

**Issue by CeesGlas** [MicrosoftDocs/azure-devops-docs#7501] opened 2020-03-05 15:05 UTC
The documentation suggests the run duration in the summary is automatically calculated as the difference between the Date completed and Date started. Date started is the timestamp attribute on the testsuite node. Date Completed is calculated as Date started of the testsuite + SUM(/testsuites/testsuite/testcase.Attributes["time"].Value) for all test cases in the test suite.
If I do it like that the run duration in the summary is producing incorrect results. It can be 0, or contain a rather random value.
If I supply an additional time attribute on the testsuite node (containing the summation of the underlying time values of the test cases) it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Publish Test Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, doc-bug
