### ISSUE TITLE
Arguments section does not match YAML snippet

### ISSUE THREAD

**Issue by ian-craig** [MicrosoftDocs/azure-devops-docs#8353] opened 2020-05-15 23:14 UTC
e.g. Yaml has `azureSubscription:` but the arguments section talks about `ConnectedServiceName`

The Yaml snippet is also empty, so it's not at all clear what the format required is. Is this the subscription name, the GUID, both?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69ff8e50-4187-3622-1beb-155f006af5f5
* Version Independent ID: bc56fa96-bded-95f8-39a4-a9e5242db1bf
* Content: [Azure Key Vault task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-key-vault?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-key-vault.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment] 2020-05-18 19:05
@ian-craig Thank you for the feedback, assigning this to the author for further review.

In the meantime, please refer to the [Azure Key Vault task repo](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureKeyVaultV1) documentation.

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, doc-enhancement
