### ISSUE TITLE
Add support for JUnit attachments

### ISSUE THREAD

**Issue by guillaume86** [MicrosoftDocs/azure-devops-docs#8254] opened 2020-05-08 15:50 UTC
I would be nice to add support for JUnit attachments in addition to VSTest and NUnit ones.
I tried to look in https://github.com/microsoft/azure-pipelines-tasks/tree/14e133b26af7115fc46a2b19e3c1fb710000cd96/Tasks/PublishTestResultsV2
to see if I could add it myself and I couldn't find the code that parse and sends attachements.

The attachment format is described here: https://plugins.jenkins.io/junit-attachments/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Publish Test Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment] 2020-05-11 20:28
@guillaume86 Thank you for the feedback and for bringing this to the product team's attention, see [here](https://developercommunity.visualstudio.com/idea/1023731/support-junit-attachments-in-the-publishtestresult.html).

This forum is for documentation issues and will keep this issue open until the product team provides an adequate response.

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, doc-enhancement
