### ISSUE TITLE
Where is the complete list of extensibility points?

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/azure-devops-docs#1794] opened 2018-09-18 20:46 UTC
[This page](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=tfs-2017) lists a few, but not all, contribution points.  For example, [this extension](https://github.com/snuziale/vsts-extension-split-work)  has a contribution target "ms.vss-work-web.work-item-context-menu", which is not listed on the documentation page above.

**Comment by elbatk** [comment] 2019-01-29 21:48
Hi @pabrams , the page you linked is what we have currently for our extensibility points. There are some points that try to keep for internal use only, I know. Adding @willsmythe for his thoughts on if there are more we should add, and then we will work to get them added!

**Comment by pabrams** [comment] 2019-01-30 23:35
That sounds promising.  Good to know that there are some points not intended to be used by third-party developers.  I also remember running into some that were previously valid, but aren't any longer. It would be good to know about those, or I wonder if you'll consider opening up the ones you say are only meant for internal use, or at least maybe document them and just tell us not we shouldn't use them... we're going to find them in your code anyway, unless you keep it closed whenever you use those extension points.

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri3, devops-ecosystem/tech, devops/prod, doc-bug, help wanted
