### ISSUE TITLE
Documentation on $[] is missing

### ISSUE THREAD

**Issue by heaths** [MicrosoftDocs/azure-devops-docs#3711] opened 2019-03-21 17:01 UTC
When and where you can use `$[]` is missing. It's mentioned here a few times, but there is no other documentation I can find in this particular TOC that describes it, unlike variable expression and template expressions. For example, can I use this in a task parameter value to set it to true or false using, for example, the `eq` or `ne` variable function?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
