### ISSUE TITLE
Add note explaining that dotnet CLI doesn't support pushing to feeds that require API Key

### ISSUE THREAD

**Issue by babelshift** [MicrosoftDocs/azure-devops-docs#7716] opened 2020-03-26 13:49 UTC
Using the DotNetCoreCLI nuget push task doesn't work if the feed requires an API Key (like nuget.org). See: https://github.com/microsoft/azure-pipelines-tasks/issues/7160

Workaround is below where `$(NuGetSourceServerUrl)` and  `$(NuGetSourceServerApiKey)` are defined in pipeline variables.
```
- task: DotNetCoreCLI@2
  displayName: Push Nuget Package
  inputs:
    command: custom
    custom: nuget
    arguments: >
      push $(Build.ArtifactStagingDirectory)/**.nupkg
      -s $(NuGetSourceServerUrl)
      -k $(NuGetSourceServerApiKey)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by evman182** [comment] 2020-03-28 22:34
The `>` got encoded when you were copying the custom task

**Comment by babelshift** [comment] 2020-03-28 23:52
Thanks. Fixed that and a typo in the title.

**Comment by cxwtool** [comment] 2020-11-24 23:28
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:28 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, doc-bug
