### ISSUE TITLE
Domain name to white list for auto-update

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/azure-devops-docs#6032] opened 2019-10-17 14:19 UTC
Please document the domain name to white list in the firewall to allow auto-update.

I also requested this information through https://developercommunity.visualstudio.com/content/problem/782203/self-hosted-agent-auto-update-domain-name-to-white.html , but keep this issue open so the information can be added to the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#communication)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2019-10-18 17:34
@Styxxy  Thank you for starting an issue with the [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

Assigning this to the author for review.

**Comment by Styxxy** [comment] 2019-10-21 13:51
I figured it out, below a snippet from the agent logs.
So this answers kind of my question, the domain name **vstsagentpackage.azureedge.net** needs to be white listed. I would suggest to add this to the "to white list domain names".

```
[2019-10-21 11:53:48Z WARN SelfUpdater] Failed to get package 'D:\temp\myagent\_work\_update\agent1.zip' from 'https://vstsagentpackage.azureedge.net/agent/2.158.0/vsts-agent-win-x64-2.158.0.zip'. Exception System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Error 12030 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The connection with the server was terminated abnormally'.    at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()    at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state)    --- End of inner exception stack trace ---    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at System.Net.Http.HttpClient.FinishGetStreamAsync(Task`1 getTask)    at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.DownloadLatestAgent(CancellationToken token)
```

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
