### ISSUE TITLE
Missing Library Role - Creator

### ISSUE THREAD

**Issue by wgv-srsedate** [MicrosoftDocs/azure-devops-docs#1728] opened 2018-09-13 20:12 UTC
There is a new role for managing library artifacts called "Creator", but I don't know what that means.  It's not included here alongside "Reader", "User", and "Administrator".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c6f274-a008-fac6-7d99-13d2ce7c8dc3
* Version Independent ID: 916fef9e-d644-2114-b466-e5bda8028ee9
* Content: [Build and release permissions and security roles - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/permissions?view=vsts#library-roles-and-permissions)
* Content Source: [docs/pipelines/policies/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/permissions.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment] 2018-09-14 13:41
I believe it is similar to Administrator, except that it does not include administering other's permissions. Adding @RoopeshNair .

**Comment by RoopeshNair** [comment] 2018-09-14 14:05
Creator is now enabled so that you can control who gets to create the library items. We need to add this to the docs. Thanks for reporting it.

**Comment by andyjlewis** [comment] 2018-09-25 12:02
Still needs to be added to the docs.

**Comment by wgv-srsedate** [comment] 2019-04-18 14:16
Can someone with more information please add this to the documentation?  Nobody seems to know the full scope of this security role.  Again, this is in regards to the **Creator** security role for managing the **Library**.

**Comment by wgv-srsedate** [comment] 2019-04-18 14:49
Can someone with more information on this please update the documentation to include the new security role.  To reiterate, this is the **Creator** security role for the **Library** service in Azure DevOps.

**Comment by andyjlewis** [comment] 2019-07-03 12:29
@ashokirla any news?

**Comment by ashokirla** [comment] 2019-12-17 12:51
Creator role is a hub level role that decides who can create an entity. It has no impact at individual variable group level once it is created. This creator of the variable group will become administrator by default for that particular variable group.

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
