### ISSUE TITLE
Will the full JsonPath specification be supported?

### ISSUE THREAD

**Issue by novanettor** [MicrosoftDocs/azure-devops-docs#7829] opened 2020-04-04 23:09 UTC
Hi. The JsonPath supported by the App Service Deploy task, useful as it is, falls short of the full 'specification' (such as it is) for JsonPath (the nearest thing to a spec I can find is here: https://goessner.net/articles/JsonPath/index.html)

For example, a path such as:

   Messaging.MessageTargets[?(@.Name=='Default')].ConnectionString

is valid according to that spec and works as expected in the online evaluator at https://jsonpath.com/. It singles out an element in an array not by index but by the value of a property (Name). This makes for less brittle substitutions inside arrays without depending on a specific number or order of elements.

Such a path is a valid variable name for the App Service Deploy task, which allows all the characters in it.

Are there any plans to expand the JsonPath support for the deploy task?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:28
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:28 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod
