### ISSUE TITLE
No mention of global.json feature?

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/azure-devops-docs#5332] opened 2019-08-22 09:51 UTC
According to this, it should now be possible to install the dotnet version from a global.json file. Is this the case, and if so can this feature be included in this documentation?

https://github.com/microsoft/azure-pipelines-tasks/pull/10734/files/3aef8199d06e7b83dbcbddd3a07f242913ae35be#diff-5952be6806f8423fdfa8986c5c93b42e

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9660c58-3366-f1be-8380-d6cf1d3c0150
* Version Independent ID: 226a4fd8-bce8-3333-d8d6-7af933c7b060
* Content: [.NET Core Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/dotnet-core-tool-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/dotnet-core-tool-installer.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by hiyadav** [comment] 2019-08-22 09:58
@pulkitaggarwl can we get the documentation updated. It is already present in the task.json and readme.md in azure-pipelines-task repo

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement

**Comment by dazinator** [comment] 2020-11-25 10:43
Looks like this was done based on latest documentation. Cheers
