### ISSUE TITLE
Visual Studio-dependent

### ISSUE THREAD

**Issue by yevster** [MicrosoftDocs/azure-devops-docs#2567] opened 2018-11-26 18:12 UTC
This doc is only useful for Visual Studio users. What if I'm developing with Rider on Linux?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bd04c64-4ce0-3e69-5936-df95c3870465
* Version Independent ID: f7f8f838-155a-839c-4ead-28af620a92ca
* Content: [CI/CD to Linux, Docker, and Azure Container Registry (ACR) - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/azure/aspnet-core-to-acr?view=vsts)
* Content Source: [docs/pipelines/apps/cd/azure/aspnet-core-to-acr.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/azure/aspnet-core-to-acr.md)
* Product: **devops**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
