### ISSUE TITLE
It's not clear how can we recover from status server downtime. Will devops retry? 

### ISSUE THREAD

**Issue by ashwinifly** [MicrosoftDocs/azure-devops-docs#6065] opened 2019-10-19 13:05 UTC
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by WilliamAntonRohm** [comment] 2019-10-21 21:39
@ashwinifly -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by ashwinifly** [comment] 2019-10-22 13:45
My issue is for the design here - https://docs.microsoft.com/en-us/azure/devops/repos/git/create-pr-status-server-with-azure-functions?view=azure-devops

So if we build a status server to listen to devops events, how do we recover from status server downtime. Meaning it is certainly possible that status server will go down some time in future for whatever reason, how will the status server know what events it missed? This is a fundamental thought missing in the design.
Let me know if you need any other info.

**Comment by WilliamAntonRohm** [comment] 2019-11-08 17:37
@ashwinifly -- thank you for clarifying.

@apawast -- please look into this issue.

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri3, doc-bug
