### ISSUE TITLE
Add UserProfile Variable to Documentation

### ISSUE THREAD

**Issue by brminnick** [MicrosoftDocs/azure-devops-docs#2547] opened 2018-11-23 19:44 UTC
The predefined build variable "$(UserProfile)" resolves to the user folder but is currently undocumented.

It currently evaluates on the Hosted build agent to "C:\Users\VssAdministrator\".

Credit to this answer on StackOverflow for pointing this out:
https://stackoverflow.com/a/48520553/5953643

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by brminnick** [comment] 2019-02-28 16:35
@stale[bot] the docs still need to add “$(UserProfile)

**Comment by chrisseed** [comment] 2019-04-17 17:40
Presumably $(UserProfile) isn't listed because it is not added by Azure DevOps - it's a standard Window environment variable.

**Comment by brminnick** [comment] 2019-04-17 18:47
Interesting point!

What if, on the Azure DevOps Predefined Variables page, we added a link pointing to the [Windows 10 Environment Variables page](https://docs.microsoft.com/windows/deployment/usmt/usmt-recognized-environment-variables), noting that these are all also valid environment variables for Azure DevOps?

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri1, devops/prod

**Comment by Grendizr** [comment] 2021-05-31 17:01
Sorry to revive this od thread, but something related: I am trying to create a group variable that will be composed of the Win 10 env. variable USERPROFILE, but this does not seem to be working. 

I tried all notations $(UserProfile) %USERPROFILE% $env:UserProfile but the variable is never parsed properly.

Any hint ? Thanks.
