### ISSUE TITLE
parameters task groups are not exposed as environnement variable to powershell

### ISSUE THREAD

**Issue by Cestbienmoi** [MicrosoftDocs/azure-devops-docs#3606] opened 2019-03-11 14:34 UTC
Hi,

I converted a working tasks list to a task group but there is a problem the parameter of the task group is not passed as environnement variable to powershell in this situation.
My parameter call Destination, if i use in other "normal" task of the task group, it is working.
But in a powershell script:
Write-Host "Destination: $env:Destination"
Destination: 
Environnement variable is empty.

It added gci env:* | sort-object name
i see the parameter Destination but it is empty (after 2 read because it was defined as variable of the release, if i delete the variable, there is no environnement variable).

If i add the variable in the release, then the environnement variable is set to the value of the variable (not the value of the parameter).
Workaround : use $(Destination) in script.

Weird example:
Write-Host "Destination : $(Destination)"
Write-Host "Destination: $env:Destination"

Set variable Destination in the release: cc
Set parameter Destination: dd

Execution:
2019-03-11T14:28:42.0086423Z Destination : dd
2019-03-11T14:28:42.0111392Z Destination: cc

Not sure it was a bug, but the documentation is poor. 
Parameters of task groups are not passed as environnement variable but variables are.

**Comment by thomps23** [comment] 2019-05-22 22:40
@Cestbienmoi could you provide the topic you used as reference?

**Comment by vtbassmatt** [comment] 2019-06-14 14:26
This is an RM question; not sure who from the product or docs team should take a look.

**Comment by RoopeshNair** [comment] 2019-06-17 05:59
@ashokirla - can you please take a look?

**Comment by ashokirla** [comment] 2019-12-17 12:32
Taskgroup pararmeters are not passed as env variables. This is as per design. The value provided to the task group parameter just replaces the variable in the task definition. In your case, $(Destination) in your underlying task is exposed as a taskgroup parameter called Destination and it is replaced with the value you have provided 'dd'. But it will not be considered as a variable available to you environment.

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri3, devops-cicd/tech, devops/prod, doc-bug, needs-more-info
