### ISSUE TITLE
Document the GUID for the task

### ISSUE THREAD

**Issue by nerdile** [MicrosoftDocs/azure-devops-docs#7173] opened 2020-02-06 02:28 UTC
Sometimes Azure Pipelines fails with an error that it the name NuGetCommand@2 is ambiguous.  Usually because someone thought they would be clever and onboard a forked version of NuGetCommand to their AZDO instance, but didn't change the name.  The GUID for this task is: 333b11bd-d341-40d9-afcf-b32d5ce6f23b
Which means that it can be referred to in pipelines as
task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2
Although this breaks the Yaml Assistant pane, of course.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by chasewilson** [comment] 2020-02-08 00:58
@WilliamAntonRohm Sorry about this, but I'm not on this docs set anymore, would you be able to remove me from all issues associated with this doc set?

**Comment by nerdile** [comment] 2020-02-18 00:42
@chasewilson - ping?

**Comment by WilliamAntonRohm** [comment] 2020-02-28 00:42
@nerdile -- Daniel, my apologies for the delay in responding.

@mijacobs -- Mike, please assign this issue to the appropriate author, or bounce it back to me.

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
