### ISSUE TITLE
Where did the Multiple Configuration option go?

### ISSUE THREAD

**Issue by pauska** [MicrosoftDocs/azure-devops-docs#5286] opened 2019-08-19 12:23 UTC
This guide says to use the "options" tab to enable the MultiConfiguration configuration variable, but there is no options tab? The task setting doesn't have anything related to MultiConfiguration either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f86c97-f534-50ad-bfb1-a2cf78c7af94
* Version Independent ID: acea40e3-512b-4d9a-9389-71b8b24327be
* Content: [Visual Studio Build build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/visual-studio-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/visual-studio-build.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by dauger** [comment] 2019-10-09 19:47
The documentation is out of date. The Multi-configuration option is now on phase settings in the pipeline tasks.

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
