### ISSUE TITLE
PrepSQL - really for TFS 2018?

### ISSUE THREAD

**Issue by edgyduck** [MicrosoftDocs/azure-devops-docs#3788] opened 2019-03-27 12:15 UTC
How come this step is still listed in the instructions when PrepSQL is not even available since TFS 2017?
TFSConfig PrepSQL /SQLInstance: ServerName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 448c3c37-253d-7080-987e-07dbf6560bce
* Version Independent ID: 709df38e-6c43-025e-4842-1a8c12a3abe4
* Content: [Restore data to a different server than the current one - Azure DevOps Server & TFS](https://docs.microsoft.com/en-us/azure/devops/server/admin/backup/restore-data-different-instance?view=azure-devops#step-7-prepare-sql-server)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fadmin%2fbackup%2frestore-data-different-instance.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fadmin%2fbackup%2frestore-data-different-instance.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Git Login: **aaronhallberg**
* Microsoft Alias: **aaronha**

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri2, devops-server/prod
