### ISSUE TITLE
Track Changes

### ISSUE THREAD

**Issue by seapeter** [MicrosoftDocs/azure-devops-docs#6152] opened 2019-10-27 19:56 UTC
The answer to the question "Can I track changes to test plans and test suites that I create with Azure DevOps?", it states that "Yes, you can track changes to test plans and test suites. Open the work item for the test plan or test suite, then view the work item history.  For test suites, other actions are tracked in the Test Suite Audit field. For example, adding and removing test cases from a test suite are tracked in this field." However, in Azure DevOps Server 2019 Update 1, when viewing the Test Suite audit field for a Requirement-Based Suite, there is no tracked changes.  Although there is for a Static Suite as well as a Query-Based Suite. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985ecee3-e347-43bb-5ed2-08ce3aee7621
* Version Independent ID: fdf465fc-a9e1-0198-2e8c-e859c74252b3
* Content: [FAQs and problem solutions - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/reference-qa?view=azure-devops-2019#feedback)
* Content Source: [docs/test/reference-qa.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/reference-qa.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri1, devops-test/tech, devops/prod, doc-enhancement
