### ISSUE TITLE
There is no documentation for the findBugsRunAnalysis flag

### ISSUE THREAD

**Issue by colwin** [MicrosoftDocs/azure-devops-docs#4779] opened 2019-07-08 05:33 UTC
Can we please add documentation about the findBugsRunAnalysis flag

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00499395-fdc3-b150-3469-aee2f9fb7cbc
* Version Independent ID: 44e630e1-1689-2d2e-212b-3ce2baf8771f
* Content: [Gradle build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/gradle.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/gradle.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
