### ISSUE TITLE
Missing Link

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/azure-devops-docs#902] opened 2018-05-26 12:07 UTC
For option 2, please include a link to the below page, as well as the PDF link.  I missed the docs page, used the PDF, then later found that the page below is better than the PDF in some respects (has much more detail).
https://docs.microsoft.com/en-gb/vsts/articles/migration-import

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 848d1786-556b-cd92-7a84-a4bd0b16facd
* Version Independent ID: ebf6bd4c-9e27-2faf-2b86-d3b3332ac189
* Content: [Migration options for migrating from TFS to VSTS](https://docs.microsoft.com/en-us/vsts/articles/migrate-to-vsts-from-tfs?view=vsts)
* Content Source: [docs/articles/migrate-to-vsts-from-tfs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/articles/migrate-to-vsts-from-tfs.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by cxwtool** [comment] 2020-11-24 23:50
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:50 UTC
Labels: Pri2, devops-whitepapers/tech, devops/prod, doc-bug, unspecified/svc
