### ISSUE TITLE
Case-sensitive branch policy clarity.

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/azure-devops-docs#9547] opened 2020-10-26 17:31 UTC
This page has the following Q&A:
_Are the required code reviewer paths case-sensitive?
No, branch policies aren't case-sensitive at this time._

We have found ourselves in the situation that we have a "pbi" branch and a "PBI" branch, both of which have different policies. The lowercase version is matching the project-level policy that is set on pattern "pbi/*". Additionally, at the repo level, the two branches have different policies configured.

What we really want is the option to treat uppercase and lowercase branches the same, but that doesn't seem to be likely.

Do we have any options to ensure that items must go through specific branches before they can get into the default branch?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment] 2021-01-05 22:55
@GaTechThomas Thank you for the feedback.

Unfortunately the product team has designated this by design, see [this post](https://developercommunity.visualstudio.com/content/problem/1031279/case-sensitive-search-option-missing.html).  Instead please try using [tags](https://docs.microsoft.com/azure/devops/repos/git/git-tags) or re-naming the branch.

Additional support options can be found at:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by GaTechThomas** [comment] 2021-01-12 13:28
The most important part is the last bit: 

"Do we have any options to ensure that items must go through specific branches before they can get into the default branch?"

This is a big deal for audit.

**Comment by msebolt** [comment] 2021-01-27 22:30
Perhaps [locking a branch](https://docs.microsoft.com/azure/devops/repos/git/lock-branches?view=azure-devops) would serve this purpose best?

Flexibility in regards to specific branches can be achieved using calls to the REST API, for a relevant post see [here](https://developercommunity.visualstudio.com/content/problem/594300/is-there-an-api-for-lock-a-branch.html).

Closing the issue now, for additional questions please use the comments below.

**Closed by msebolt** 2021-01-27 22:30 UTC
Labels: Pri2, devops-code-git/tech, devops/prod, support-request

**Comment by GaTechThomas** [comment] 2021-01-30 22:58
The branch needs to remain unlocked, just tightly controlled. 

I gather that MS efforts are shifting from Azure Repos to GitHub. We'll wait to see what GutHub offers before spending the money to customize things.

**Comment by WilliamAntonRohm** [comment] 2021-02-23 02:47
@GaTechThomas -- Thomas, thank you for clarifying.

You are welcome to @ mention me for any followup.  We hope to hear from you again.
