### ISSUE TITLE
No mention of .webtest use in Application Insights Availability tests

### ISSUE THREAD

**Issue by vhhughes** [MicrosoftDocs/azure-devops-docs#3793] opened 2019-03-27 16:34 UTC
One of the primary features of Application Insights that we rely on is its support for .webtest-based Availability tests. (i.e., multi-step tests that can extract and pass values from one step to another) The announcement here does not address these and should be updated, so customers can plan accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde00a22-c654-f6e9-5bad-c4deb0852899
* Version Independent ID: 88ff6f31-199d-e3f6-bc68-be91dc695b0e
* Content: [Load test overview - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/overview?view=azure-devops#feedback)
* Content Source: [docs/test/load-test/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/overview.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment] 2019-03-28 14:09
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by L0G1C** [comment] 2019-05-08 18:30
I agree. This is a major bummer because of .webtest's implementation within Application Insights Availability. I really wish they would at least add an update to the App Insights availability tool to take in jmx files or something if that is the alernative they are suggesting.

**Comment by nevesing** [comment] 2019-05-08 19:16
I am also checking about the support for .webtest with App Insights if it is depreciated. I dont see any alternative solution for the same.

**Comment by geeliano** [comment] 2019-05-10 13:35
Nowadays this is probably the biggest growing usage for .webtest, load it up to Application Insights. Weird how there is no mention of the roadmap for that. Would be great to know how we will continue to use Application Insights multi-step tests as soon as possible.

**Comment by plcos** [comment] 2019-05-10 14:02
We really need an explanation on how to import the .webtest from other tools like JMeter

**Comment by PBoraMSFT** [comment] 2019-05-13 08:28
Looping in @morgangrobin for guidance on App Insights.

**Comment by morgangrobin** [comment] 2019-05-20 19:01
Despite being deprecated, you will be able to create .webtest files using Visual Studio 2019 and below indefinitely. 

Application Insights will drop support for multi-step web tests authored in Visual Studio at some point in the future. However, we recently invested in an overhaul of our backend service to ensure that we can continue running these tests for the next 2 years. We will make a deprecation announcement 1 year before support will be dropped, and provide migration guidance. We plan to move towards a custom code model, where more complex availability tests will be written in .NET or Javascript.

**Comment by geeliano** [comment] 2019-05-20 20:05
That is not what says in the article.

"For existing Azure customers using the performance test feature in App Services or Application Insights, this feature will no longer be available as of March 31, 2020."

Running .webtests in application insights seems to be discontinued in less than a year.

**Comment by zakimaksyutov** [comment] 2019-05-20 23:08
Performance Testing feature is different offering than Availability. The former will not be available as of March 31, 2020. The latter will be available within a year after announcement (which hasn't happened yet). 

![image](https://user-images.githubusercontent.com/15914532/58057295-30860880-7b19-11e9-951a-9f94c9c5ab0f.png)

Right now our current thinking that we'll do announcement around March 2020. The deprecation will happen in a year (around March 2021). Our goal is to provide an alternative to multi-step by March 2020.

Note, Single URL offering is not affected and we will continue to run these tests.

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri1, devops/prod
