### ISSUE TITLE
URL for Proxy Settings

### ISSUE THREAD

**Issue by StephenRSkinner** [MicrosoftDocs/azure-devops-docs#5891] opened 2019-10-08 16:49 UTC
In order to configure a proxy to allow traffic for this task, the URL needs to be supplied. There is no URL in the logs showing what the task is calling. Please provide the URL the task is using, either in the logs or in the documentation.

**Comment by msebolt** [comment] 2019-10-08 20:51
@StephenRSkinner Thank you for the feedback.

Please include the task name or article referenced and I can assign an author.

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri3, doc-enhancement
