### ISSUE TITLE
"packages" resource documentation missing?

### ISSUE THREAD

**Issue by kbuley** [MicrosoftDocs/azure-devops-docs#8757] opened 2020-07-01 22:09 UTC
Where is the documentation for package resources?

It would appear the schema looks like this:
```
  packages:
    - package: 
      type: 
      connection: 
      name: 
      tag: 
      trigger:
      version: 
```
However, I'm unable to find any documentation on how these fields related to an ADO feed. I've been doing some trial and error and "universal" for type results in "No artifact type found corresponding to ID universal. Make sure that the artifact type extension is available and try again."

What should "connection" contain? I do not see a service connection type that appears appropriate, and I doubt the feed URL goes here (if so, how do you authenticate?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by oliverstopp** [comment] 2020-07-03 06:23
could this be a duplicate of #7861 ?

**Comment by kbuley** [comment] 2020-07-04 02:41
It's a valid option (or appears to be, autocomplete works for the online editor). Entering something like "npm" for "type" doesn't throw an error when validating the yaml, either.

**Closed** 2020-07-10 13:59 UTC
Labels: Pri2, devops-cicd-process/tech, devops/prod, doc-enhancement

**Comment by juliakm** [comment] 2020-07-10 14:03
@kbuley Thanks for flagging this. We just pushed an update to the [resources article](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema) that should be live shortly. The packages type only is for to GitHub packages now.

**Comment by kbuley** [comment] 2020-07-10 20:57
> @kbuley Thanks for flagging this. We just pushed an update to the [resources article](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema) that should be live shortly. The packages type only is for to GitHub packages now.

Is there WIP to include Universal packages? My use case is to allow for a specific rpm (since rpm is not supported by artifacts) to be selected at run time, defaulting to 'latest'. Much the same way that a build artifact is selectable at release creation time.

**Comment by juliakm** [comment] 2020-07-16 16:54
@kbuley I don't know offhand. Can you ask that question in our [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)?

**Comment by johncrim** [comment] 2020-08-18 20:46
@kbuley - I also want to know how to use Universal packages as a pipeline resource. Seems like a major oversight if it's not supported (also a major oversight if it's implemented and not documented).

I posted this request here:
https://developercommunity.visualstudio.com/idea/1154402/support-universal-packages-as-pipeline-resources.html
