### ISSUE TITLE
New article "Reducing the gap between operations and development using Azure DevOps"

### ISSUE THREAD

**Issue by suxstellino** [MicrosoftDocs/azure-devops-docs#6164] opened 2019-10-28 17:31 UTC
Hi there,
I'm Alessandro Alpi, an Italian data platform MVP. I'd like to send a new article about Azure DevOps. I think that this tricky article could be useful. Here is what I'm trying to describe:

- problem: Dev vs Ops, too much isolated, too much waste of time, and so on
- obstacles: culture, communication, single point of work
- solution: using multiple backlogs, with multiple teams, with new custom items, in a single team project
- tooling: visualizing the graph
- conclusions: advantages in terms of time and readability/reliability of the process itself

I have to translate the article, it's in Italian right now. But I'd like to understand whether you'd love to get it or not. If you need more details, I can attach the doc here or send you as you want.

Looking forward to hearing from you soon 
thanks

**Comment by msebolt** [comment] 2019-10-28 20:29
@suxstellino  Thank you for the suggestion, assigning this to an author for review.

**Comment by suxstellino** [comment] 2019-11-22 12:49
Hi there, any update on this?

**Comment by suxstellino** [comment] 2020-02-10 08:25
I'm publishing this as a blog post, please keep me updated.

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri3, doc-enhancement
