### ISSUE TITLE
how to setup limited ref

### ISSUE THREAD

**Issue by HuzefaShabbir** [MicrosoftDocs/azure-devops-docs#2869] opened 2018-12-27 13:30 UTC
Hi, 
Want to enable limited ref for my project.
 However the article doesn't cover the "how to setup limited ref". 
Can you please provide steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cc997b4-66b2-486a-8a67-68ee5219eb17
* Version Independent ID: 7157acbc-0feb-2414-8eb8-b1db010371c0
* Content: [Limited Refs - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/limited-refs)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2flimited-refs.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2flimited-refs.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **sanoursa**

**Comment by steved0x** [comment] 2019-01-03 20:31
@HuzefaShabbir I am asking the author of the article and will reply back.

**Comment by keremispirli** [comment] 2019-05-09 14:02
@HuzefaShabbir Did you manage to find how it's set up?
@steved0x Is there any response from the author?

**Comment by AJH16** [comment] 2019-05-31 14:30
I'm also curious about this and what versions it is supported in.

**Comment by AJH16** [comment] 2019-06-05 19:36
For those who wish to experiment and live dangerously, I give you "[dbo].[prc_UpdateGitLimitedRefCriteria]".  I'm going to be doing some experimenting in a test instance and see what happens.

**Comment by AJH16** [comment] 2019-06-17 19:31
Finally had enough time poking around to figure it out:
https://stackoverflow.com/questions/56598474/how-do-you-enabled-limited-refs-in-tfs-git

**Comment by AJH16** [comment] 2019-06-17 19:37
@HuzefaShabbir See above

**Comment by AJH16** [comment] 2019-11-06 20:31
An important thing to note when using limited refs.  It can result in large fetches when a previously limited ref is joined to a ref that people do have links to.  This can be hard to diagnose at first glance.  We had a situation occur with an old limited ref that we rarely used.  We reused it for another purpose using an "ours" merge and that joined a substantial part of limited tree in to the main tree and resulted in large fetches when it was pushed back.  Be sure to exercise caution when a large branch is limited and gets merged.

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-learn/tech, devops/prod, doc-bug
