### ISSUE TITLE
"go get -d ./..." not able to get/download the dependency, if the repository is hosted in visualstudio.com

### ISSUE THREAD

**Issue by Encounter27** [MicrosoftDocs/azure-devops-docs#4019] opened 2019-04-19 21:21 UTC
"Get dependencies" step works for public repositories or other private repositories. But fails to get dependencies from the repository is hosted in visualstudio.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1199cdec-3d76-5693-6295-6f36ce05f3bf
* Version Independent ID: 04ae7849-e91d-caf3-d48a-926473996248
* Content: [Build and test Go projects - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/go?view=azure-devops#feedback)
* Content Source: [docs/pipelines/languages/go.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/go.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by caringco** [comment] 2019-04-26 08:11
Facing the same issue here. Hoping for a fix!

**Comment by GrimTheReaper** [comment] 2019-08-05 16:41
If I remember its because by default golang clones with HTTPS, and the HTTPS GIT url contains `_git` which go get will trim off after that. We resolved this by having a vanity url.

**Comment by nazneen84** [comment] 2019-08-08 23:14
We do a 
go get -d -v <package name>
go build -o $GOPATH/pkg/<architecture>/<package name>.a -x
on all sub packages in decreasing level of dependency
and reference them like custom packages in the code

then try doing a go get/ go install on it

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
