### ISSUE TITLE
Suggest either removing blazemeter or listing other providers

### ISSUE THREAD

**Issue by sdecker** [MicrosoftDocs/azure-devops-docs#8066] opened 2020-04-23 15:46 UTC
&gt;&gt;Many commercial services such as Blazemeter support running Apache JMeter tests.
I'm not sure how appropriate it is for MS to be calling out one company unless this is an official endorsement. Other companies we found are FloodIO and Loadium. We ended up going with Loadium for our needs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde00a22-c654-f6e9-5bad-c4deb0852899
* Version Independent ID: 88ff6f31-199d-e3f6-bc68-be91dc695b0e
* Content: [Load test overview - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/overview?view=azure-devops)
* Content Source: [docs/test/load-test/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/load-test/overview.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri1, devops-test/tech, devops/prod
