### ISSUE TITLE
The default build number is now a blank field, not `$(Date:yyyyMMdd).$(Rev:r)`

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#11397] opened 2021-09-23 01:29 UTC
From a new empty pipeline...
![image](https://user-images.githubusercontent.com/15381181/134442553-67be4c2f-e18e-4a86-8997-1496795ee3a7.png)

Personally I think the docs page is right and this is a bug in the program, but how am I supposed to know which it is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run (build) number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment] 2022-12-21 21:59
I think this must have been a product bug. Closing because I wasn't able to reproduce.

**Closed by juliakm** 2022-12-21 21:59 UTC
Labels: devops/prod, doc-bug, Pri2, devops-cicd-process/tech
