### ISSUE TITLE
refs/heads/trunk not found

### ISSUE THREAD

**Issue by wisgit** [MicrosoftDocs/azure-devops-docs#3940] opened 2019-04-12 07:47 UTC
Thanks for these detailed instructions. 
However, after the command "git branch -m trunk master" (isssued in the bare local repository)  I receive the error message "error: refname refs/heads/trunk not found".
What might have gone wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Migrate from Subversion (SVN) to Git](https://docs.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops#feedback)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/perform-migration-from-svn-to-git.md)
* Product: **devops**
* Technology: **devops-whitepapers**
* GitHub Login: @hkamel
* Microsoft Alias: **hkamel**

**Comment by axhussain** [comment] 2019-05-30 12:47
Try "git branch -m svn/trunk master"

Also in the section for creating a bare repo, the command should be "git symbolic-ref HEAD refs/heads/svn/trunk"

**Comment by cpboyd** [comment] 2019-09-26 15:31
This also affects the references for tags as well.

**Comment by skylee91** [comment] 2019-10-25 08:24
I also hit this error. Try `git branch` to list the available branches. Then change the command accordingly. 
For example, `git branch -m bare/svn/trunk master` instead of `git branch -m trunk master`

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri1, devops-whitepapers/tech, devops/prod, doc-bug
