### ISSUE TITLE
Please update your documentation!

### ISSUE THREAD

**Issue by BiribiriJaNai** [MicrosoftDocs/azure-devops-docs#5115] opened 2019-08-02 12:05 UTC
I opened a issue more than a year ago, asking how to use secure files in a custom task [here](https://github.com/microsoft/azure-pipelines-tasks/issues/5577).
I still need this functionality today, and your documentation **STILL** points to the [common module](https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/Common/securefiles-common), which is **NOT** available in custom tasks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140dcb9a-2ed0-11d5-064b-068f863ed97f
* Version Independent ID: 672d2aa3-cf0d-9207-c97c-e2eba14506b7
* Content: [Secure files for Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops)
* Content Source: [docs/pipelines/library/secure-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/secure-files.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **madhurig**

**Comment by steved0x** [comment] 2019-11-05 20:29
@BiribiriJaNai I am sorry that this issue has persisted for so long, I am going to see if I can find the answer and get our documentation updated.

**Comment by scaldwell-alienvault** [comment] 2020-01-27 15:36
This is not documentation.  The links here refer to your code-base.  I really don't have time to reverse-engineer everything I touch.  

If Microsoft wants me to use their solution, they should add documentation to their definition of done.

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
