### ISSUE TITLE
Upstream Stream Sources not supported on Azure DevOps Server 2019 that's behind a HTTP Proxy

### ISSUE THREAD

**Issue by AdrianSanguineti** [MicrosoftDocs/azure-devops-docs#5525] opened 2019-09-09 05:39 UTC
As I discovered through a [Stackoverflow question](https://stackoverflow.com/questions/57817219/using-upstream-sources-on-azure-devops-server-thats-behind-a-http-proxy/57847985#57847985) I had raised, upstream sources are not supported when the Azure DevOps Application Tier is behind a HTTP Proxy server. That extremely critical information is not included anywhere on this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5f022df-36c3-34b1-cac1-ac33995a7d73
* Version Independent ID: 9634b0c8-7b14-4453-2c04-aedabbf331f1
* Content: [Upstream sources](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops-2019)
* Content Source: [docs/artifacts/concepts/upstream-sources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by AdrianSanguineti** [comment] 2019-09-12 05:30
Quick update. As I've posted in the [stackoverflow question](https://stackoverflow.com/questions/57817219/using-upstream-sources-on-azure-devops-server-thats-behind-a-http-proxy/57900197#57900197), the Azure DevOps application tier can work behind a HTTP Proxy server. Our mistake was that our HTTP Proxy server CA certificates was missing from the host.  

The modifications we guessed that we should make to our web.config were correct also. 

As I do not see this scenario in any of the documentation, it would be still good if they could be updated to include that information also. Plus it would be nice to have some official verification that we did to solve the issue was the correct thing to do.

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri1, devops-artifacts/tech, devops/prod, doc-bug
