### ISSUE TITLE
Conditional insertion for templates

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/azure-devops-docs#8345] opened 2020-05-15 13:25 UTC
We saw few examples of Conditional insertion, but you didn't tell about most important and interesting things: 
conditional insert templates/stages/jobs/steps when we have some variable based on which we wanna do or skip some actions. 
For example something like this:
stages:
  -  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    - template: t1.yml
  - template: just-another-stage.yml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-cicd-process/tech, devops/prod, doc-enhancement
