### ISSUE TITLE
andoid project way out of date

### ISSUE THREAD

**Issue by syendev** [MicrosoftDocs/azure-devops-docs#4918] opened 2019-07-18 15:37 UTC
Can owner of the project update the project so that it actually can be loaded in android studio?

https://github.com/MicrosoftDocs/pipelines-android

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955d694a-7285-45b6-56b9-3a86ddbb0820
* Version Independent ID: 0d226e23-1ddd-f6de-abf7-5b112533ec78
* Content: [Build, test, and deploy Android apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/android?view=azure-devops)
* Content Source: [docs/pipelines/languages/android.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/android.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **dastahel**

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
