### ISSUE TITLE
Dockerfile missing ARG PHATOM="xyz"

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/azure-devops-docs#1017] opened 2018-06-10 00:18 UTC
Unless I am blind, your Dockerfile is missing a declaration for `$PHANTOM` variable.

As the Phantom project is not being developed (at the moment), it is safe to add the line:

`ARG PHANTOM="phantomjs-2.1.1-linux-x86_64"`

Straight after `# install phantomjs`

I think this Dockerfile needs some expansion, explaining what it does differently to all the Dockerfiles mention https://hub.docker.com/r/microsoft/vsts-agent/.

Also, please add details on how to run it non-interactively.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3660a83d-0a9e-b864-6c9d-f2d846c1ef4a
* Version Independent ID: 5f4da709-3037-e566-e796-3ae69907de2c
* Content: [Configure a private Docker build agent for your Java project with VSTS](https://docs.microsoft.com/en-us/vsts/java/labs/dockerbuildagent/?view=vsts)
* Content Source: [docs/java/labs/dockerbuildagent/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/labs/dockerbuildagent/index.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by cxwtool** [comment] 2020-11-24 23:50
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:50 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
