### ISSUE TITLE
In a release in Azure Pipelines, Build.BuildId is a hash, not an integer as shown in documentation

### ISSUE THREAD

**Issue by dparkar** [MicrosoftDocs/azure-devops-docs#5999] opened 2019-10-15 22:55 UTC
I was attempting to use "Build.BuildId" in a release pipeline in a Azure pipeline. Build.BuildId maps to Release.Artifacts.{alias}.BuildId as per here : 

![image](https://user-images.githubusercontent.com/208161/66875638-e38d4d80-ef63-11e9-98c8-ab00860433b1.png)

which in turn is suppose to look like "130" for Azure pipelines. 

![image](https://user-images.githubusercontent.com/208161/66875569-a0cb7580-ef63-11e9-98dc-aa853746b7a3.png)

But it is a hash instead. Should the example be updated accordingly ?

I switched to use Release.ReleaseId.

**Comment by msebolt** [comment] 2019-10-16 17:15
@dparker  Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri3, doc-enhancement
