### ISSUE TITLE
Please include information on the .path file in the Update environment variables section

### ISSUE THREAD

**Issue by webbermt** [MicrosoftDocs/azure-devops-docs#6361] opened 2019-11-13 21:40 UTC
The PATH environment variable is written to a file called .path and not the .env file.  If you need to change the PATH environment variable that the agent uses, the .path file needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a Azure Pipelines agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2019-11-14 05:38
@webbermt  Thank you for the feedback, assigning this to the author.

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
