### ISSUE TITLE
Request, Response and Event tabs are missing for certain users when viewing webhook history

### ISSUE THREAD

**Issue by DevonBritton** [MicrosoftDocs/azure-devops-docs#7461] opened 2020-03-02 09:14 UTC
Hi everyone. 

Some users in our client's TFS instance are unable to see the Request, Response and Event tabs when they view the history for webhooks. Other users can see the tabs. 

Is there any sort of specific visibility around those tabs based on authorisation/access level?

That's the only reason I can think that only certain people would be having this issue...

Thanks in advance. 
Devon Britton.

**Comment by WilliamAntonRohm** [comment] 2020-03-02 23:46
@DevonBritton -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by DevonBritton** [comment] 2020-03-03 07:01
Hi William. 

Thanks for your response. The issue is as follows...

- Under Project Settings --> Service Hooks,  my client has a number of service hooks defined.
- When clicking the ellipse menu next to a Service Hook and selecting "History" it opens a modal window showing previous "runs" of the service hook in question. 
- On the right hand side of the modal window there are several tabs. Summary, Request, Response and Event (Screenshot attached)
- There are some users, who are members of the administrators group, and have been given the required access (supposedly) who can ONLY view the "Summary" tab. The "Response", "Request" and "Event" tabs are missing. 

I hope this gives you enough details?

![image](https://user-images.githubusercontent.com/33623085/75750684-05297e80-5d25-11ea-93a1-2fe8d1414913.png)

**Comment by WilliamAntonRohm** [comment] 2020-03-04 18:40
@DevonBritton -- thank you for clarifying.  Are you reading a particular docs.microsoft.com article?

**Comment by DevonBritton** [comment] 2020-03-05 07:20
I can't find any documentation on permissions level regarding this.

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri3, doc-bug
