### ISSUE TITLE
Referencing another variable defined within the same or different group, or in a pipeline

### ISSUE THREAD

**Issue by TASlavens** [MicrosoftDocs/azure-devops-docs#3902] opened 2019-04-08 17:40 UTC
In the value of a group variable, is it supported to reference another variable within the same group ?  For example:

group_var_root = "\\UncShare\Base\Path"
group_var_deep = "$(group_var_root)\some\deep\folder"

What about referencing a variable in a different variable group (seems like a bad approach, but someone might have a need)?  What about referencing a variable defined in a pipeline (effectively making the library group variable require a specific pipeline variable to be defined)?

In essence, this question boils down to "Is all variable group linking resolved before variable value substitution is begun?"  Please document this behavior regardless of the answers.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=tfs-2018&tabs=designer)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by nikhil2007rock** [comment] 2019-05-06 17:01
Can we reuse the value of a key in the same variable group? If this is possible, what is the syntax to refer to the key?
As in, I have a variable `App.URL : www.contoso.com`. I am using the key to substitute value in my next variable like this `Login.URL : $(App.URL)\Login` and this doesn't work.

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
