### ISSUE TITLE
a bit misleading ..

### ISSUE THREAD

**Issue by papiermache** [MicrosoftDocs/azure-devops-docs#4306] opened 2019-05-22 17:35 UTC
This strategy is working for Azure, I got that. But to diss gitflow - an arguably far more popular branching strategy - is unnecessary and misleading: (1) I don't think anyone ever advocated "testing in production" - see Vince Driessen's original article https://nvie.com/posts/a-successful-git-branching-model/ - and 'release' branches.  (2) Author states "our branching strategy looks like a typical trunk-based development model" - yes it does looks like TFVC legacy, taking little advantage of the scope of functionality of distributed vc. (3)  "After merge, we run additional acceptance tests that take more time to run." - and if tests fail at this point? What, now you have a broken master. There should not be any need for testing of changes being merged into master.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1235ec4-e7e9-b0c2-8f1f-ee9682175a05
* Version Independent ID: a473750a-fbb6-4eed-e0e6-34e8a5009507
* Content: [Release Flow - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2frelease-flow.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2frelease-flow.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **ethomson**

**Comment by yannduran** [comment] 2019-06-13 03:06
My first thought was this sounds a lot like GitFlow, with the branches names changed (master instead of develop, and releases instead of master), and some pull request magic tacked on.. 

Btw Edward compared to GitHub Flow, not GitFlow. It certainly a bit misleading to compare to GitHub Flow, as what they're doing is much closer to GitFlow than GitHub Flow. It's like comparing apples to oranges, instead of one type of apple to another type of apple.

This sentence alone screams to me that the branches are not named very well: "we continue **developing** in our **master** branch". Developing in our master branch??? Surely developing in our development branch makes a lot more sense. The master branch is usually the **latest compilable code**, and what is usually gets deployed. GitFlow also has release branches (based off of master), as well as hotfix branches (also based off of master). Both of those branches are **automatically** then merged back into both master and develop during the "finish" operation of releases and hotfixes.

**Comment by jkdmyrs** [comment] 2019-06-24 20:14
@papiermache 
> But to diss gitflow ... is unnecessary and misleading

The article does not mention GitFlow, but instead GitHub Flow, a simple feature branching pull request strategy. Also, lets not be so sensitive... suggesting another way to use git doesn't mean the author is **dissing** anything.

@papiermache 

> I don't think anyone ever advocated "testing in production"

That's actually exactly what GitHub flow, which the author was referencing, advocates:
https://guides.github.com/introduction/flow/

 @yannduran 

> This sentence alone screams to me that the branches are not named very well. Developing in our master branch??? Surely developing in our develop branch makes a lot more sense.

Then rename `master` to `develop` and don't have a `master`. Release flow only has the 1 branch, so I don't really see the problem here other than arguing semantics. You could call it whatever you wanted.

@yannduran 
>  The master branch ... is usually what gets deployed.

Sure, maybe in other branching strategies, but that is strictly not true for this strategy. `master` contains code for the next release, not what's in the current release. If you're looking for what gets deployed, look at the current `release/` branch.

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri2, devops-learn/tech, devops/prod, doc-enhancement
