### ISSUE TITLE
Add explicit guidance for Xamarin Forms

### ISSUE THREAD

**Issue by irongut** [MicrosoftDocs/azure-devops-docs#3895] opened 2019-04-07 18:28 UTC
This guide could use some explicit instructions for builing Xamarin Forms apps with Pipelines. By following the first pipeline guide, reading this guide and some guess work I've managed to set up a build pipeline for a Forms app but specific instructions would be better.

I'd also suggest an update to include using the wizards built into Pipelines to generate your yaml.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c45a95ce-73c8-861e-f92d-a26f1667aa60
* Version Independent ID: ecb82128-cdf4-3834-62c1-2cf61989ab5e
* Content: [Build Xamarin apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/xamarin?view=azure-devops#feedback)
* Content Source: [docs/pipelines/languages/xamarin.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/xamarin.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by dfoulk** [comment] 2019-08-13 16:54
Yes, we really need guidance for Xamarin.Forms!

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
