### ISSUE TITLE
Explain what happens what the stage/job is skipped

### ISSUE THREAD

**Issue by Mikilll94** [MicrosoftDocs/azure-devops-docs#8124] opened 2020-04-28 18:51 UTC
There is no information about how the `conditions` and `dependsOn` work when a stage/job is skipped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by jamers99** [comment] 2020-05-06 00:42
It seems it still runs even if a depending stage was skipped.  This seems like the wrong behavior.  Is there a way to implement this?

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri1, devops-cicd-process/tech, devops/prod, doc-bug
