### ISSUE TITLE
Prerequisites for service hook with Microsoft Teams incorrect

### ISSUE THREAD

**Issue by Cadacious** [MicrosoftDocs/azure-devops-docs#8410] opened 2020-05-21 00:31 UTC
This page states the below while it appears the current requirement to create a connector in teams is Team Administrator, not Project Admin or Project Collection Administrator.

> You must be a member of the Project Administrators or Project Collection Administrators group to configure the connector.

This can be confirmed by having a user account that is not a Project Administrator or Project Collection Administrator, but is a Team Administrator within an Azure DevOps Project. That user can successfully create a connector on a channel in Teams. Users that are not Team Administrators on any team are not able to create connectors on channels in Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* Content: [Create a service hook Microsoft Teams - Azure DevOps Services, TFS 2017](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/teams?view=azure-devops)
* Content Source: [docs/service-hooks/services/teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/services/teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-collab/tech, devops/prod, doc-bug
