### ISSUE TITLE
Updates docs to show how we can configure this task to queue jenkins multibranch pipeline jobs

### ISSUE THREAD

**Issue by rkapoor028** [MicrosoftDocs/azure-devops-docs#4020] opened 2019-04-20 17:27 UTC
With trial & error we were able to figure out that in case you are using multibranch pipelines in Jenkins you need to specify below task parameters:-
"Job name": $(multibranchpipelinename) 
 "Multibranch pipeline branch":/$(Build.SourceBranchName)

However, in this particular scenario, on jenkins the specific branch job must already exist in the multibranchpipeline project, otherwise this task will fail with 400 Bad Request.

A working configurations to use to queue multibranch pipeline jobs in Jenkins using this task would have been really helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f04c9f75-8530-88da-50df-a8bfbf6f56cf
* Version Independent ID: 096edafb-ac9e-6477-4a92-906e90f2f654
* Content: [Jenkins Queue Job build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/jenkins-queue-job?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/jenkins-queue-job.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/jenkins-queue-job.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by bbarman4u** [comment] 2019-07-03 14:55
I like this idea as well.

**Comment by bbarman4u** [comment] 2019-07-04 13:03
@rkapoor028 How did you resolve the 400 error, I am still getting the error despite what you suggested, am I missing something ?

**Comment by rkapoor028** [comment] 2019-07-04 19:36
@bbarman4u I solved it by making sure the Jenkins branch Jobs already exists in a multibranch pipeline setup. In Jenkins Multibranch Pipeline setup you scan/index the repo to discover new branches but suppress their trigger. 

I would then trigger them using Azure Devops

**Comment by bbarman4u** [comment] 2019-07-04 23:51
@rkapoor028 Thanks for replying, I had done that exactly i.e. had the jobs ready, already before I posted the question. Turning on debug did not help much. I thought may be issues with the branch names having special characters and tried it out on other names, did not help. I though folder names in the job name might be an issue, eliminated that by moving the jobs to the Jenkins root, and still it did not help. Mine is not a YAML job in Azure DevOps, its a classic one which does nothing but just triggers the Multi branch. I also verified the branch name is being passed correctly.

Here is a screenshot of the job configuration. 

![image](https://user-images.githubusercontent.com/20643454/60690374-9a216280-9e8c-11e9-82fb-3a4d67f18d6f.png)

**Comment by bbarman4u** [comment] 2019-07-07 04:42
@rkapoor028 @thomps23 So I figured out the mistake by hit and trial. So it turns out the branch name has to be supplied without the leading "/". So I was using the earlier suggestion from @rkapoor028 and had the multi branch name as - `/$(Build.SourceBranchName)` ,instead it needed to be `$(Build.SourceBranchName)`

Please see below screenshot of the working configuration -

![image](https://user-images.githubusercontent.com/20643454/60764074-3b541880-a047-11e9-8196-970c5fc2e7ae.png)

**Comment by rkapoor028** [comment] 2019-07-08 17:12
@bbarman4u Ohh, not sure why that happened.. Good that you figured it out. Thanks a ton!

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
