### ISSUE TITLE
VSTS JWT Token verification

### ISSUE THREAD

**Issue by Spragalas** [MicrosoftDocs/azure-devops-docs#764] opened 2018-05-11 07:52 UTC
https://docs.microsoft.com/en-us/vsts/extend/develop/auth?view=vsts#calling-rest-apis-from-your-extension

I followed the sample how verify your extension's token in your app.
- token which was retrieved using VSS.getAppToken()
- secret I used was downloaded from marketplace for that specific extension
- I copied code snippet from url above

This workflow does not work. I seems that the secret downloaded from market place is another JWT token

Also the code snippet uses outdated nuget package

**Comment by Spragalas** [comment] 2018-11-09 14:10
any updates ?

**Comment by elbatk** [comment] 2018-11-12 14:10
Hi @willsmythe , could you help here? Sorry for the embarrassing delay, @Spragalas .

**Comment by cxwtool** [comment] 2020-11-24 23:50
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:50 UTC
Labels: Pri3, devops-collab/tech, devops/prod, doc-bug, help wanted
