### ISSUE TITLE
Parameter for connection strings would be nice

### ISSUE THREAD

**Issue by tntwist** [MicrosoftDocs/azure-devops-docs#4340] opened 2019-05-25 15:42 UTC
It would be nice if we could specify connection strings for an azure function app with an optional parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82ad1fa-cee5-c5c6-7050-21aaec6b714a
* Version Independent ID: 617316ff-2dab-d021-880f-c1c79313c320
* Content: [Azure Function App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-function-app.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-function-app.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug, doc-enhancement
