### ISSUE TITLE
Is it possible to add more info about codeCoverageEnabled?

### ISSUE THREAD

**Issue by Rogeriohsjr** [MicrosoftDocs/azure-devops-docs#6461] opened 2019-11-23 14:39 UTC
I think would be nice to have more info on how we can use the codeCoverageEnabled, some information answering some questions like:
If I enabled the codeCoverageEnabled do I see that in the Code Coverage Tab in the pipeline automatically?
Do I need to use any other Task to see a report on Code Coverage Tab?
Am I supposed to see only a link to Code Coverage Tab?

As far as I could understand, the Publish Code Coverage Results task says that we don't need it to publish our Code Coverage Results if we are using Visual Studio Test Task, but when I enabled the codeCoverageEnabled, it seems to generate only the .coverage file, and add it to Coverage Tab as a link to download, if this is the only purpose of codeCoverageEnabled to add a link to download, would be nice to have it documented, and would be nice to also add that the information that this attribute, won't show a nice report in the Code Coverage tab, if we want something like that, we have to do something else.

That is my feedback! :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment] 2019-11-25 21:58
@Rogeriohsjr Thank you for the feedback, assigning this to the author for review.

**Comment by zingaroo** [comment] 2020-04-21 15:11
How is this going?

**Comment by PBoraMSFT** [comment] 2020-04-22 06:52
@Rogeriohsjr @zingaroo - information about viewing coverage results is documented, but not linked from the VSTest task doc.

@steved0x - can you pls help with this?
Please update the codeCoverageEnabled argument to say that coverage results can then be viewed as outlined in the below docs.

https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops
https://docs.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
