### ISSUE TITLE
Add State Previous DAX Code Does Not Work

### ISSUE THREAD

**Issue by rernst-IQ** [MicrosoftDocs/azure-devops-docs#5983] opened 2019-10-15 02:47 UTC
The DAX code for the Add State Previous example is not working. Based on the DAX docs LOOKUPVALUE expects a scalar value for the search_value parameter. search_value can not refer to any column in the current table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71c046b7-9bc7-2b63-9401-72af0e1a577e
* Version Independent ID: d9d85ca9-74ba-63bd-0edf-8f95754d4991
* Content: [Add a time-in-state measure to a PowerBI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/create-timeinstate-report?view=azure-devops#add-state-previous)
* Content Source: [docs/report/powerbi/create-timeinstate-report.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/create-timeinstate-report.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @thomps23
* Microsoft Alias: **kaelli**

**Comment by rernst-IQ** [comment] 2019-10-15 03:04
I'm working on finding an alternative formula, but I am by no means a DAX expert. If I find something I can make a pull request.

**Comment by WilliamAntonRohm** [comment] 2019-10-15 23:35
@rernst-IQ -- thank you for your feedback and researches.

@thomps23 -- please look into this issue 5983.

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri2, devops-analytics/tech, devops/prod, doc-bug
