### ISSUE TITLE
helmVersionToInstall is ignored, installs helm 3.0.0 and breaks instead

### ISSUE THREAD

**Issue by Crayeth** [MicrosoftDocs/azure-devops-docs#6421] opened 2019-11-20 15:37 UTC
We used to have a working pipeline that installs helm 2.14.3 but now for some reason the helmVersionToInstall is ignored, my pipeline reports installing helm 3.0.0 and then tripping over options it doesn't know (--save).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e81d5c7-25b8-e6b2-6184-411cd62922be
* Version Independent ID: 5da377d1-b781-bdc0-9584-6a4b0d9fc474
* Content: [Helm installer task - Azure Pipelines & TFS](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/tool/helm-installer?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/tool/helm-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/helm-installer.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
