### ISSUE TITLE
Missing guide for steps in Grafana

### ISSUE THREAD

**Issue by cforce** [MicrosoftDocs/azure-devops-docs#6068] opened 2019-10-19 17:50 UTC
The page is missing what todo in Grafana after trigger is configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 847579c6-9fbb-d9b7-3472-f733e4e2aa93
* Version Independent ID: 73f7444c-472a-666c-a6c3-09a9273bdefc
* Content: [Create a service hook for Azure DevOps Services and TFS with Grafana](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/grafana?view=azure-devops)
* Content Source: [docs/service-hooks/services/grafana.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/grafana.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri2, devops-collab/tech, devops/prod, doc-bug
