### ISSUE TITLE
E2E doc for UWP apps 

### ISSUE THREAD

**Issue by PBoraMSFT** [MicrosoftDocs/azure-devops-docs#6240] opened 2019-11-04 04:36 UTC
Have heard from a few customers that they would like to see E2E UWP doc in the ecosystem section.
A recent example is [here](https://github.com/MicrosoftDocs/vsts-docs/issues/6108) 
Creating this issue to track.

**Comment by PBoraMSFT** [comment] 2019-11-05 04:41
@vijayma - who owns the UWP ecosystem now? 
I can contribute the test portion of the doc, but we need the UWP ecosystem owner to drive the E2E documentation.

**Comment by mateialexandru** [comment] 2019-12-11 16:04
Highly recommend getting the documentation in ; spent hours researching online about what and how to do and tried billion of things without success just to find out that you need to do some magic by specificing "*.appxrecipe" patter for mstest build task; yet that is not enough because in some weird scenarios your output would contain multiple "*.appxrecipe" files; so then it's even better to specify smth like "Release\*.appxrecipe" etc.
But even with these changes there was no easy explanation that if you want to automate testing in VSTS you need a private agent customized with Developer mode on, etc..

My instant reaction was: leave UWP testing aside since everything is "magic" and try a cppwinrt test :|

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri3, doc-enhancement
