### ISSUE TITLE
Should say how to set the Java version

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/azure-devops-docs#5246] opened 2019-08-14 14:33 UTC
This shows how to set the java version for gradle and maven tasks, but if you're using some of the examples provided in the other pages which just use `script: mvn` this page does not show how to set the version of Java in that context.

It should show how to set up with the JavaToolInstaller task

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d340719a-67b0-01bc-7bd3-c3492eb23abd
* Version Independent ID: dd9064fa-235f-65f9-eca7-66564b09f440
* Content: [Build Java apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/java?view=azure-devops#feedback)
* Content Source: [docs/pipelines/languages/java.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/java.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by chasewilson** [comment] 2019-08-29 18:06
@trajano, Thanks for the feedback! In the context of scripts, it would be difficult to document all the possibilities using scripts as well as when you set up your pipeline, it has a Java version defined. I don't think that more definition falls under this documentation. 

What do you think?

**Comment by trajano** [comment] 2019-08-29 19:24
Its actually important to show this especially unlike https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops the JavaInstaller tool needs an existing java rather downloading from known public sources.

So people who are using mvn via scripts would be wondering why java installer does not work and there's no proper java version they need installed

**Comment by trajano** [comment] 2019-08-30 12:33
Hmm i seem to have lost my original message.  I think it is important because `JavaInstaller` has two key deficiencies compared to the \node tool.

1. JavaInstaller requires the user to specify the location on where to get the JDK.  No such option in the node tool.
2. JavaInstaller does not add to the PATH.  Node installer updates PATH automatically.

Because of those two deficiencies someone who requires a different version of Java may get confused on why they are not able to run with the proper version of Java.

In other cases I also use Docker in Docker with Java which is less efficient in order to get a proper version of Java.

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
