### ISSUE TITLE
YAML Instructions?

### ISSUE THREAD

**Issue by TaylorBogle** [MicrosoftDocs/azure-devops-docs#8428] opened 2020-05-22 14:40 UTC
This article describes the process for a Classic deployment. I'm looking for information about how to do this with YAML.  Our company is looking at moving all classic pipelines/release pipelines to YAML and this will be a requirement to make that happen. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc105eb0-4766-77a1-dfec-c0cc2b4b3f08
* Version Independent ID: 8bd8c066-745b-5c89-39c3-bb0a959cb7a2
* Content: [Control deployments by using approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/approvals?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/approvals/approvals.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/approvals/approvals.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **shashban**

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-cicd-release/tech, devops/prod, doc-enhancement
