### ISSUE TITLE
Missing description for runNugetRestore optional element

### ISSUE THREAD

**Issue by srikcgaa2** [MicrosoftDocs/azure-devops-docs#3766] opened 2019-03-25 16:29 UTC
The documentation above is missing reference of runNugetRestore and corresponding detailed description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d91aa34-87c4-d934-28e2-456eac57432d
* Version Independent ID: 5725c1ab-d894-f79c-f7e0-0c5b8b5cca56
* Content: [Xamarin.iOS build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xamarin-ios?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/xamarin-ios.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/xamarin-ios.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri2, devops/prod
