### ISSUE TITLE
Documentation page is missing key information

### ISSUE THREAD

**Issue by allenzhang83** [MicrosoftDocs/azure-devops-docs#7670] opened 2020-03-22 19:19 UTC
The docker task documentation page states that the 'command' parameter takes a fixed set of parameters. 
link to the page
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops

But this is incomplete/incorrect, it should be able to take 'run' as value and run a docker command with arguments. Ref::
https://stackoverflow.com/questions/60712923/how-to-run-a-docker-image-on-azure-devops-agent-with-docker-task-v2/60719452?noredirect=1#comment107457381_60719452

**Comment by cxwtool** [comment] 2020-11-24 23:29
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:29 UTC
Labels: Pri3, doc-bug
