### ISSUE TITLE
clarify documentation that "Create Test Suites by Referencing Existing Test Cases" is not available into Azure Devops as it is in MTM

### ISSUE THREAD

**Issue by spashx** [MicrosoftDocs/azure-devops-docs#4667] opened 2019-06-27 13:58 UTC
https://docs.microsoft.com/en-us/azure/devops/test/mtm/guidance-mtm-usage?view=azure-devop

The documentation here says  "Azure Test Plans or the Test hub in TFS is a richer, faster, and easier-to-use solution for manual testing as compared to the Test Center in Microsoft Test Manager".
This is partially wrong since there are no ability to perform MTM's "Create Test Suites by Referencing Existing Test Cases" into Azure Devops neither in the test plan view or test case explorer extensions.

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri3, doc-bug
