### ISSUE TITLE
Integration with Azure build pipelines

### ISSUE THREAD

**Issue by nicholas-brooks** [MicrosoftDocs/azure-devops-docs#3853] opened 2019-04-03 22:54 UTC
Similar to #3202, it would be great to see the official way of how to integrate the Azure Artifacts Nuget feed with the projects using Azure build pipelines.  I've come across this external article (Option #3 using nuget.config) https://www.paraesthesia.com/archive/2019/02/07/using-azure-devops-artifacts-nuget-feeds-in-pipelines/ , however imo it should be documented on docs.microsoft.com.

Thanks!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 899a78d6-9d08-7744-108d-10add2ba7e2c
* Version Independent ID: 6ab31e96-fed8-4335-ed81-b97663d8300f
* Content: [Consume NuGet packages in Visual Studio](https://docs.microsoft.com/en-gb/azure/devops/artifacts/nuget/consume?view=azure-devops#feedback)
* Content Source: [docs/artifacts/nuget/consume.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/consume.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by magleaso** [comment] 2020-05-22 21:44
We use a new flow now with the NuGet Authenticate task. We have docs here with examples on how to configure auth and do common NuGet operations: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops#examples

**Comment by edgarrs** [comment] 2020-05-22 21:46
This look a duplicate of https://github.com/MicrosoftDocs/azure-devops-docs/issues/3202

**Comment by ramiMSFT** [comment] 2020-06-18 19:20
@nicholas-brooks Thank you for your feedback. We have several articles on how to setup and work with Artifacts in Azure Pipelines. Please check out the following articles:

- [Artifacts in Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/artifacts-overview?view=azure-devops)

- [How to publish and consume Artifacts (YAML/Classic)](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml)

- [Publish to NuGet feeds (YAML/Classic)](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml)

See also [NuGet Authenticate task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops) and [NuGet task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops) for more details on Pipeline tasks.

**Closed by ramiMSFT** 2020-06-18 19:20 UTC
Labels: Pri1, devops-artifacts/tech, devops/prod
