### ISSUE TITLE
Test Run Titles for Multiple Files

### ISSUE THREAD

**Issue by MarkKoz** [MicrosoftDocs/azure-devops-docs#4604] opened 2019-06-23 00:24 UTC
If `mergeTestResults` is not set to `true`, then each file found by `testResultsFiles` will get its own test run. However, there seems to be no way further customise the name for each test run. At the least it's not even explained that a number will just be appended to the `testRunTitle`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Publish Test Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by goudarzi** [comment] 2019-09-16 22:05
Any update on this? We have the same issue. :)

**Comment by PBoraMSFT** [comment] 2019-10-03 06:34
@Additi - can you look at updating the docs for the behavior when mergeTestResults is false?

@MarkKoz @goudarzi - we will update the docs with the current behavior. If you are looking for feature work here, please raise an issue on the [tasks repo](https://github.com/microsoft/azure-pipelines-tasks), where we track issues and enhancements to the pipeline tasks.

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
