### ISSUE TITLE
Test Payload for Checkin Service Hook differs from documentation

### ISSUE THREAD

**Issue by 45software** [MicrosoftDocs/azure-devops-docs#7048] opened 2020-01-23 21:33 UTC
When setting up a service hook for the checkin event for a TFVC repository it's possible to send a test payload to the service hook.  The JSON payload sent with that test differs from the documentation.  I see four differences:

- root: subscriptionId exists in the test payload but does not appear in the documentation sample.

- root: notificationId exists in the test payload but does not appear in the documentation sample.

- root: resourcesContainers: project exists in the test payload but does not appear in the documentation sample.

- root: scope exists in the documentation sample but does not appear in the test payload.

I Haven't tested a real payload so I don't know what will be passed in reality.  Also, consider documenting what each of the elements are in the payload.  Many things can be assumed from context but it would be nice to have a formal description of what each piece of data describes.

**Comment by msebolt** [comment] 2020-01-24 19:07
@45software Thank you for the feedback and for providing the set analyses.  

Please include a reference to the documentation and we can assign this to the author for review.

**Comment by 45software** [comment] 2020-01-29 13:21
https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops#tfvc.checkin

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri3, doc-enhancement
