### ISSUE TITLE
More guidance around build artifact name needed

### ISSUE THREAD

**Issue by elafnitzegger** [MicrosoftDocs/azure-devops-docs#7396] opened 2020-02-26 00:11 UTC
The attribute is described as "It can be whatever you want". I attempted to use build variables in the name, such as "MyApp-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)" and the build failed because of the name. It failed due to the name. It would be nice to be able to used these variables when declaring the artifact name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by KATHIRAVANG** [comment] 2020-05-19 09:08
Is the fix released?

**Comment by cxwtool** [comment] 2020-11-24 23:31
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:31 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
