### ISSUE TITLE
"Install dependencies" command is broken

### ISSUE THREAD

**Issue by janpio** [MicrosoftDocs/azure-devops-docs#4814] opened 2019-07-10 16:27 UTC
The command `CALL gem install bundler` it includes doesn't work, it should probably be just `gem install bundler`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45d010e9-7e5a-3f62-8c10-29c0c1b64846
* Version Independent ID: d274c8a4-aca9-6e8e-5b28-5a62d1e7c85d
* Content: [Build and test Ruby apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/ruby?view=azure-devops#feedback)
* Content Source: [docs/pipelines/languages/ruby.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/ruby.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
