### ISSUE TITLE
'Project' vs 'solution' parameter docs are unclear

### ISSUE THREAD

**Issue by andersforsgren** [MicrosoftDocs/azure-devops-docs#3413] opened 2019-02-19 08:26 UTC
The yaml example specifies "solution" as an argument, but the parameter details only documents a "Project" argument. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22342679-18af-7c79-f902-fe9c0bb55379
* Version Independent ID: a8e7c201-6593-458b-5a81-b54e93fde4b5
* Content: [MSBuild build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/msbuild?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/msbuild.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/msbuild.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andersforsgren** [comment] 2019-02-20 20:29
Actually: the whole parameter section is lacking: the parameter name column doesn't have actual parameter names, that's the problem (it has for many other tasks), and there are also some missing and confusing. E.g. is the parameter "maxCpuCount" really a boolean?

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
