### ISSUE TITLE
undocumented variables

### ISSUE THREAD

**Issue by cccs-cat001** [MicrosoftDocs/azure-devops-docs#8398] opened 2020-05-20 12:15 UTC
Hi there, 

   In the yaml snippet on this page it lists a bunch of optional variables that aren't described below. Can this be fixed please? I'm not sure what they do exactly but I'm thinking they might be useful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff16109-cc76-cea4-d41b-3fc9c4e9c534
* Version Independent ID: efd08832-ddbc-921a-f682-3ea68ecd27c3
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, doc-enhancement
