### ISSUE TITLE
Reasons to add another project

### ISSUE THREAD

**Issue by JvanderStad** [MicrosoftDocs/azure-devops-docs#8304] opened 2020-05-13 11:24 UTC
We have a project in DevOps. The product is deployed to multiple locations within different companies (clients). 

We have broken the project down into multiple teams and areas. This works great for planning and overview; The parent team sees all the items on one board, on the team board you only see the relevant items for that team.

We want to give **stakeholders** (clients) access to specific team(s). With the permissions it is possible, but there a 3 items I can't find the setting of:

- The summary page shows a global overview, even for the teams you don't have access to. I want to hide/disable this.
- The summary page shows all the users (names + e-mail addresses) of the entire project, even ones you don't have access to (privacy, sensitive business information)

![image](https://user-images.githubusercontent.com/5426370/81806959-5c856f80-955c-11ea-8f2f-a207fee6ccf1.png)

- @Mentions show team members of other teams. I want to hide this (privacy, sensitive business information)

If I can configure these options I'm happy, if not, it ipso facto means I need to add a separate project and lose the insights we have now. Can you confirm this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8327ce3e-a6f7-74ba-7cc0-95885c247a75
* Version Independent ID: ae36a4ea-20cb-4f29-e760-8f6c362c5a47
* Content: [About projects and scaling your organization - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/about-projects?view=azure-devops)
* Content Source: [docs/organizations/projects/about-projects.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/projects/about-projects.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment] 2020-05-15 14:57
Hi @JvanderStad, Thanks for reaching out. I'm looking into this and will be in touch.

**Comment by chcomley** [comment] 2020-05-15 17:05
Hi @JvanderStad, Unfortunately, there's no way to hide the pages/experiences you are concerned about. We're tracking this issue on the Developer Community (see here: https://developercommunity.visualstudio.com/content/problem/485973/userstakeholder-has-access-to-organization-setting.html), and it's currently under consideration. 

The best practice we recommend for the time being is to either avoid inviting clients to the organization or use a separate organization for each client.  Thank you.

**Comment by JvanderStad** [comment] 2020-05-16 04:06
Please update documentation to reflect Azure DevOps is **not GDPR compliant for the stakeholder role**. 

We have multiple external organizations in stakeholder-roles in other projects. This is a **data breach**, and a **serious issue** and should be addressed **ASAP**. 

The issue @ Developer Community you are referring to has no activity from Microsoft. It is _Under Consideration_, so this is not going to be fixed in the foreseeable future. Let other customers know about this issue before they could face the same problem.

We need to restrict access immediately. We also need to consider in the next 72 hours if we need to notify our national privacy watchdog as we are required by national law ❗

Is there an audit trail available to these pages?

**Comment by JvanderStad** [comment] 2020-05-16 04:28
Related issue

- https://developercommunity.visualstudio.com/idea/414743/view-organization-settings-permission.html

**Comment by Jominana** [comment] 2020-05-19 04:56
Hi @JvanderStad 

Azure DevOps is a collaborative product and was designed for those within the Org to work together.  As such, identities are Org level objects and can be @mentioned and listed across all projects under the same Org. The guidance for the usage you outline above (Org members have no affinity) is to keep projects for each of your customers in separate organizations.

**Comment by JvanderStad** [comment] 2020-05-19 05:14
Exactly my point, it's **not** clear from the documentation. For example:

> **Reasons to add another project**
> **To prohibit or manage access to the information contained within a project to select groups**
> To support custom work tracking processes for specific business units within your organization
> **To support entirely separate business units that have their own administrative policies and administrators**
> To support testing customization activities or adding extensions prior to rolling out changes to the working project
> To support an Open Source Software (OSS) project

I made this mistake and apparently I'm not the only one. My assumption was wrong and the docs should be updated the prevent other customers to experience the same.

**Comment by croban** [comment] 2020-06-03 20:25
> Hi @JvanderStad, Unfortunately, there's no way to hide the pages/experiences you are concerned about. We're tracking this issue on the Developer Community (see here: https://developercommunity.visualstudio.com/content/problem/485973/userstakeholder-has-access-to-organization-setting.html), and it's currently under consideration.
> 
> The best practice we recommend for the time being is to either avoid inviting clients to the organization or use a separate organization for each client. Thank you.

Okay, this would work if there would be any possibility to search wit over the organisations (customers)? Means some persons are part of different organisations, and 90% of companies are just interested if everyone has somehing to do. If that would work, than the  problem with stakeholders would be solved for me. 
Something like this guy have made it here: [https://tobiasfenster.io/creating-a-combined-work-item-list-from-multiple-azure-devops-organizations-and-why-that-matters-for-gdpr](https://tobiasfenster.io/creating-a-combined-work-item-list-from-multiple-azure-devops-organizations-and-why-that-matters-for-gdpr)

**Comment by chcomley** [comment] 2020-06-03 20:29
@Jominana, can you please provide assistance, thank you.

**Comment by chcomley** [comment] 2020-06-16 17:36
Hi @JvanderStad, and @croban, There's now a feature request in the Developer Community for tracking this work. I highly encourage you to [visit this feature request ](https://developercommunity.visualstudio.com/content/idea/365834/better-permission-management-user-interface-identi.html) and provide any comments or input, as well as up vote it. Since this is being tracked in the Dev Community, I'll be closing this issue and tracking this feature request to address any potential updates to the article. If you have any further questions about the article, please don't hesitate to @mention me. Thank you so much!

**Closed** 2020-06-16 17:36 UTC
Labels: Pri1, devops-new-user/tech, devops/prod, doc-enhancement

**Comment by JvanderStad** [comment] 2020-06-18 10:27
@chcomley 

> Please update documentation to reflect Azure DevOps is **not GDPR compliant for the stakeholder role**.

> I made this mistake and apparently I'm not the only one. My assumption was wrong and the docs should be updated to prevent other customers to experience the same.

**Comment by jzabroski** [comment] 2020-07-21 18:48
@chcomley I don't think this issue should have been closed... it looks like @JvanderStad point of updating documentation is valid.  Saying that something is "Under Consideration" does not reflect the current state of the product.  Feature Requests don't get documentation, actual product behavior does.

**Comment by larshaupthansen** [comment] 2021-05-20 09:42
Solution is in preview - https://devblogs.microsoft.com/devops/limit-user-visibility-and-collaboration-to-specific-projects/
