### ISSUE TITLE
Update UI controls information in extension development documentation

### ISSUE THREAD

**Issue by patrickeibl** [MicrosoftDocs/azure-devops-docs#5699] opened 2019-09-22 21:04 UTC
Develop extensions / Reference / UI controls
The documentation in the above section is very thin and also out of date as it does not reference the newer azure-devops-ui controls. The whole section should just be replaced with a short description and pointer to the azure-devops-ui page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97777da6-f32b-a0f2-733f-91304a3ef163
* Version Independent ID: 70bf2041-914b-3f7a-3c05-f026b9c91b5f
* Content: [Combo Control](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/controls/combo?view=azure-devops#feedback)
* Content Source: [docs/extend/reference/client/controls/combo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/controls/combo.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by wavemotionio** [comment] 2020-02-13 14:39
Yes, this page is out of date as well: https://docs.microsoft.com/en-us/azure/devops/extend/develop/ui-controls/comboo?view=azure-devops.  The 'tree combo' example does not appear to have an equivalent in azure-devops-ui.

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri2, devops-ecosystem/tech, devops/prod
