### ISSUE TITLE
Non-editable Application Package

### ISSUE THREAD

**Issue by stofte** [MicrosoftDocs/azure-devops-docs#3278] opened 2019-02-07 15:37 UTC
In case others are confused, this task can also be used to deploy SF packages from a build pipeline that creates multiple artifacts (or SF packages). One just needs to go the "Stage 1" step and unlink the "Application Package" field, this makes it editable for all tasks in the pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7068e469-201e-c820-4d27-b798ea799b70
* Version Independent ID: d6bb717a-1c44-43a1-c7a5-9616b257c0e0
* Content: [Service Fabric Application Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/service-fabric-deploy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/service-fabric-deploy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/service-fabric-deploy.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by RoopeshNair** [comment] 2019-02-11 15:30
@pulkitaggarwl  for SF issues

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
