### ISSUE TITLE
Missing documentation of upgrading Docker@1 to Docker@2

### ISSUE THREAD

**Issue by estensen** [MicrosoftDocs/azure-devops-docs#7424] opened 2020-02-27 12:19 UTC
Upgrading v1 tasks to v2 is hard because the documentation of v1 is missing so it's hard to know what the differences are.

E.g. for login going from v1 to v2 you have to remove `azureSubscriptionEndpoint` and `azureContainerRegistry` and add `containerRegistry`, but it's not clear if you have to change parameters. Anyway, the upgrade seems to create a new service connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by shridharjjoshi** [comment] 2020-02-29 12:45
I am facing the same issue. Please make documentation for each version of each task available easily

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:31 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, doc-bug

**Comment by mm-gmbd** [comment] 2021-08-31 18:47
Still an issue here.

**Comment by Guillaume-R-FLOSS** [comment] 2023-01-31 14:54
As a work around at least we can target the previous specific version like this `AzureContainerAppsRC@0.1.7`
