### ISSUE TITLE
Associate with vs2019

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/azure-devops-docs#4715] opened 2019-07-02 18:33 UTC
Documentation stated "A test plan containing your automated tests, which you have associated with automated test methods using Visual Studio 2017, or Visual Studio 2015 or earlier."
Can we use VS2019 to do that or not easier than 2017 must be used? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6c92a2-2f5c-e34e-f285-3e1a2a02604b
* Version Independent ID: 6f31f4c2-94ac-20eb-da01-e1d47f041945
* Content: [Run automated tests from test plans - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/run-automated-tests-from-test-hub?view=azure-devops)
* Content Source: [docs/test/run-automated-tests-from-test-hub.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/run-automated-tests-from-test-hub.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by SychevIgor** [comment] 2019-08-31 05:28
It will be nice to have answer after 2 months.

**Comment by Additi** [comment] 2019-12-20 09:12
Hi @Sychevlgor, Apologies for late reply. It works fine with VS2019. We recommend you to have the latest version for the best experience.

**Comment by 2020-abhilash** [comment] 2020-01-29 05:16
Hello, I wanted to use the Test Plans for Automated Test Cases that we have in our project within Azure DevOps but the association with Visual Studio makes this confusing for us. How to we associate a project (and automated tests for that project) that is written in Java / Go with Visual Studio?

**Comment by jimicze** [comment] 2020-02-25 01:43
> Hello, I wanted to use the Test Plans for Automated Test Cases that we have in our project within Azure DevOps but the association with Visual Studio makes this confusing for us. How to we associate a project (and automated tests for that project) that is written in Java / Go with Visual Studio?

Not possible right now.

**Comment by SychevIgor** [comment] 2020-02-26 10:52
will be nice to finally update an article. 6+ months sounds like reasonable timeframe

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri1, devops-test/tech, devops/prod, doc-bug
