### ISSUE TITLE
Explain limitations of SQL Azure Dacpac Deployment

### ISSUE THREAD

**Issue by phatcher** [MicrosoftDocs/azure-devops-docs#7353] opened 2020-02-20 13:10 UTC
"SQL Azure Dacpac Deployment may not support all SQL server actions that you want to perform." 

Can we have some examples of when you would want to use SQLPackage vs Dacpac deployment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f4ee44-6500-b0e6-62d8-7a23e5b461fa
* Version Independent ID: 75bd021b-fed5-f258-315d-0ef8628fb887
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/azure-sqldb.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by cxwtool** [comment] 2020-11-24 23:31
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:31 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
