### ISSUE TITLE
Document GitHub source options (particularly reporting build/commit status)

### ISSUE THREAD

**Issue by dahlbyk** [MicrosoftDocs/azure-devops-docs#2474] opened 2018-11-17 20:00 UTC
I spent more time than I care to admit trying to get commit status reported to GitHub (https://stackoverflow.com/a/53354948/54249). The GitHub source was created automatically through Deployment Center, and I don't recall seeing any of the GitHub configuration options that I eventually found under the GitHub build source.

It seems like this is the correct documentation location to describe the options available, if only by duplicating the ⓘ tooltip content for SEO purposes. This is probably true of the other source options, though I have not used them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=vsts)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
