### ISSUE TITLE
Variable access to user home directory

### ISSUE THREAD

**Issue by ThadHouse** [MicrosoftDocs/azure-devops-docs#4337] opened 2019-05-24 22:51 UTC
I have a build that publishes artifacts to `~/releases`, however I cannot find any variable that would allow me to reliably get access to this directory. I can't change the publish directory in my build, so is there any variable, or a variable that can be added that might give access to `~/`? Just using `~/` in a task like PublishPipelineArtifact does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by chasewilson** [comment] 2019-11-05 22:57
Hi @ThadHouse thanks for the question. Is there a reason you can't [define a variable yourself](https://docs.microsoft.com/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch) and use it in your pipeline?

**Comment by ThadHouse** [comment] 2019-11-05 23:21
Defining a variable doesn't expand the path, so the PublishPipelineArtifact  still fails because it doesn't support ~/ as part of its path, and the defined variable isn't expanded.

**Comment by chasewilson** [comment] 2019-11-06 19:21
What are you trying to accomplish after the artifact has been published to `~/releases` ? Have you thought of using one of the [script tasks]()? That should be able to interpret the `~/` file path.

**Comment by ThadHouse** [comment] 2019-11-06 19:22
I'm just trying to publish that entire directory to the azure build artifacts. I guess I could copy all the files to a build relative folder, but that seems to just be adding complication for something that the PublishPipelineArtifact task should support directly.

**Comment by chasewilson** [comment] 2019-11-07 18:00
I understand why you wouldn't want to, normal process would be to use the staging dir or working dir, but if you can't do that, that might be the best option. You can reach out to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) for a feature request if you would like to see that added as well.

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
