### ISSUE TITLE
Allow scripts to access the OAuth token is missing

### ISSUE THREAD

**Issue by brandonmcclure** [MicrosoftDocs/azure-devops-docs#4521] opened 2019-06-14 16:01 UTC
I want to use the the [OAuth token in a PS script](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/powershell?view=azure-devops#use-the-oauth-token-to-access-the-rest-api) in my build, which led me to this page. Using the classic editor, our builds do not have a checkbox with any reference to OAuth. How can I set this without recreating the build to use YAML?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa5a83c-70fd-6925-a8c8-256b21c21a2e
* Version Independent ID: 75f4a136-7245-7878-2953-6b68272fe4ec
* Content: [Build options - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops)
* Content Source: [docs/pipelines/build/options.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/options.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by brandonmcclure** [comment] 2019-06-14 17:06
It is set for each phase now, not at the Build level:
https://developercommunity.visualstudio.com/solutions/214483/view.html

**Comment by thomps23** [comment] 2019-06-14 22:25
@steved0x Can you take a look at the community post and see if the doc needs updating?

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
