### ISSUE TITLE
Outdated and confusing

### ISSUE THREAD

**Issue by bdway** [MicrosoftDocs/azure-devops-docs#7854] opened 2020-04-07 13:06 UTC
I'm new to Azure DevOps and Pipelines. Got to this page by clicking a link automatically generated by a test pipeline I created. The steps no longer seem to match the actual process/screens and made things more confusing. I will go looking for other documentation as this doesn't really help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5da86a5-9d8d-4926-6384-be9216e7e029
* Version Independent ID: 53ab1193-2a58-9879-3bdd-af2439eae2ca
* Content: [Build your .NET desktop app for Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/windows/dot-net?view=azure-devops&tabs=vsts#feedback)
* Content Source: [docs/pipelines/apps/windows/dot-net.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/windows/dot-net.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by cxwtool** [comment] 2020-11-24 23:28
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:28 UTC
Labels: Pri2, devops-cicd-apps/tech, devops/prod, doc-bug
