### ISSUE TITLE
Need documentation on returning task status from gradle tasks

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [MicrosoftDocs/azure-devops-docs#3798] opened 2019-03-27 21:09 UTC
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops

There's no documentation on how you can return the status of a gradle task.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml says that you can make a step do something if the `Agent.JobStatus` is `SucceededWithIssues`. How do I make a gradle build task return `SucceededWithIssues`? I want to create a task that either returns `Succeeded` in most cases but if there are some issues we want to warn about but not break the build return `SucceededWithIssues`.

**Comment by AlberTajuelo** [comment] 2019-08-22 13:52
@vijayma How can this be accomplished?

We have a Azure DevOps pipeline that has a stage failed but pipeline is "SuccededWithIssues". Any idea about this too?

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri3
