### ISSUE TITLE
It's not clear from documentation how to use the rerun settings

### ISSUE THREAD

**Issue by jimmylewis** [MicrosoftDocs/azure-devops-docs#3950] opened 2019-04-12 17:33 UTC
Apparently the `rerunFailedTestCasesMaxLimit` value is only respected if `rerunType` is set to `basedOnTestFailureCount`.  This isn't the default, and this interaction is not called out anywhere.  It would be great if the descriptions for these properties called out the relation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by PBoraMSFT** [comment] 2019-12-06 08:48
@steved0x - sent you a mail with details on the fix required. Can you please help with updating the doc?

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
