### ISSUE TITLE
Classic Editor

### ISSUE THREAD

**Issue by wagnerbsouza** [MicrosoftDocs/azure-devops-docs#8078] opened 2020-04-24 09:17 UTC
Hello there. It would be very helpful some examples using the Classic Editor version of the task.
Spent almost 2 days having trouble with Kustomize output variable "manifestsBundle".
Finally figured out (pure lucky) that the Output Variables dropdown must have a name, otherwise it would be only ".manifestsBundle". I named it "bake", so it became "bake.manifestsBundle", which only then worked in the Manifests of the next task (deploy). I believe that would be extremely helpful. Also, a clear note that those using yaml must be aware that the "name" in the bake-action task is the one used to reference the manifests in the deploy-action task. And it can be any name, not necessarily "bake", as what matters is {name}.manifestsBundle for the manifests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d0eccc-f436-7367-cb24-b6da66b3a049
* Version Independent ID: 9bc5ee0d-3f00-dc10-ad69-77effc928290
* Content: [Bake manifests - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/bake?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/kubernetes/bake.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/kubernetes/bake.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri2, devops-cicd-ecosystems/tech, devops/prod, doc-enhancement
