### ISSUE TITLE
PublishPipelineArtifact Upload fails, error message very unspecific

### ISSUE THREAD

**Issue by ThKaufmann-PG** [MicrosoftDocs/azure-devops-docs#7324] opened 2020-02-18 10:05 UTC
I was directed here from this page: https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact, hope this is the corect community for this question, otherwise please indicate, where to address this question.

I run a pipeline on a self hosted linux agent and the publish pipeline artifact step fails. I enabled the debug option, but still I cannot figure out the reason.

It says that one or more errors occured, How do I find out which ones?
This agent runs on debian linux (Version I have to find out). The same pipeline worked on a ubuntu hosted agent.
I also checked the log of the agent, but cannot find any error indication.

This is the printout I get:

2020-02-17T14:56:43.1399813Z ==============================================================================
2020-02-17T14:56:43.1399905Z Task         : Publish Pipeline Artifacts
2020-02-17T14:56:43.1399940Z Description  : Publish (upload) a file or directory as a named artifact for the current run
2020-02-17T14:56:43.1399975Z Version      : 1.2.2
2020-02-17T14:56:43.1400026Z Author       : Microsoft Corporation
2020-02-17T14:56:43.1400061Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact
2020-02-17T14:56:43.1400095Z ==============================================================================
2020-02-17T14:56:43.5591369Z Artifact name input: demo-image-complete
2020-02-17T14:56:43.5744669Z Uploading pipeline artifact from /< path to artifact cut>/dummyartifact for build #6646
2020-02-17T14:56:47.8642101Z ##[debug]Dedup parallelism: 192
2020-02-17T14:58:27.8868579Z ##[error]One or more errors occurred. (A task was canceled.)
2020-02-17T14:58:27.8878690Z ##[debug]Processed: ##vso[task.logissue type=error;]One or more errors occurred. (A task was canceled.)
2020-02-17T14:58:27.8879432Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2020-02-17T14:58:27.8979006Z ##[debug]   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.VisualStudio.Services.BlobStore.Common.Telemetry.BlobStoreApplicationInsightsTelemetrySender..ctor(IAppTraceSource tracer, Uri baseAddress)
   at Agent.Plugins.PipelineArtifact.DedupManifestArtifactClientFactory.CreateDedupManifestClient(AgentTaskPluginExecutionContext context, VssConnection connection, CancellationToken cancellationToken, BlobStoreClientTelemetry& telemetry)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.UploadAsync(AgentTaskPluginExecutionContext context, Guid projectId, Int32 pipelineId, String name, String source, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.PublishPipelineArtifactTaskV1.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
2020-02-17T14:58:27.9051720Z ##[section]Finishing: PublishPipelineArtifact

**Comment by ThKaufmann-PG** [comment] 2020-02-18 12:48
I finally found something in the agent log:

[2020-02-18 12:35:05Z INFO JobDispatcher] Successfully renew job request 10840, job is valid till 18/02/2020 12:45:05
[2020-02-18 12:36:05Z INFO JobDispatcher] Successfully renew job request 10840, job is valid till 18/02/2020 12:46:05
[2020-02-18 12:37:05Z INFO JobDispatcher] Successfully renew job request 10840, job is valid till 18/02/2020 12:47:05
[2020-02-18 12:38:05Z INFO JobDispatcher] Successfully renew job request 10840, job is valid till 18/02/2020 12:48:05
[2020-02-18 12:39:05Z INFO JobDispatcher] Successfully renew job request 10840, job is valid till 18/02/2020 12:49:05
[2020-02-18 12:39:35Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2020-02-18 12:39:35Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2020-02-18 12:39:35Z INFO ProcessInvokerWrapper] Exited process 9447 with exit code 102
[2020-02-18 12:39:35Z INFO ProcessInvokerWrapper] Finished process 9447 with exit code 102, and elapsed time 00:05:30.4293881.
[2020-02-18 12:39:35Z INFO JobDispatcher] Worker finished for job 60dfd29e-1890-5ba0-75a9-043684c54d27. Code: 102
[2020-02-18 12:39:35Z INFO JobDispatcher] finish job request for job 60dfd29e-1890-5ba0-75a9-043684c54d27 with result: Failed
[2020-02-18 12:39:35Z INFO Terminal] WRITE LINE: 2020-02-18 12:39:35Z: Job Init and sync repositories completed with result: Failed

Is there a list of exit codes around? In the Worker log I cannot find anything about failed processes.

**Comment by romil07** [comment] 2020-02-27 11:02
@jtpetty You were probably looking at a related issue
https://github.com/microsoft/azure-pipelines-agent/issues/2750

**Comment by cxwtool** [comment] 2020-11-24 23:31
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:31 UTC
Labels: Pri3, doc-enhancement
