### ISSUE TITLE
Should SymbolsVersion be the same as AssemblyVersion?

### ISSUE THREAD

**Issue by NightOwl888** [MicrosoftDocs/azure-devops-docs#4554] opened 2019-06-19 01:35 UTC
Must SymbolsVersion be the same as the AssemblyVersionAttribute? Or can it contain a pre-release tag (1.2.3-beta002)?

On a side note, the casing of the YAML generated by Azure DevOps portal is Pascal case, the documentation shows camel case (SymbolsVersion vs symbolsVersion). Also, the names in the documentation don't match the parameter names (symbolsVersion vs Version). Confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946d67f6-9bb7-481f-f32f-59b5965f9590
* Version Independent ID: 8865f1e2-15b3-8cdb-1d8c-939c665e9bdc
* Content: [Index Sources & Publish Symbols build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/index-sources-publish-symbols?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/index-sources-publish-symbols.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/index-sources-publish-symbols.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by PBoraMSFT** [comment] 2019-07-03 13:38
@andyjlewis - can you please help route this appropriately? 
For some odd reason, random task docs that I don't own seem to have gotten associated with my GH id and I am getting assigned to them. Request help in investigating that and fixing it, please.

**Comment by PBoraMSFT** [comment] 2019-08-07 10:47
@chasewilson - Please see my previous comment. I do not own this doc and have been tagged incorrectly.

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
