### ISSUE TITLE
description doesn't match azure-pipelines 

### ISSUE THREAD

**Issue by bospoort** [MicrosoftDocs/azure-devops-docs#4526] opened 2019-06-14 22:35 UTC
[Enter feedback here]
The pipeline that is imported from the GitHub repo needs more work than what is described here. The Readme on the GitHub repo mentions it. Please update. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa0194a9-ffa7-fa79-e6c7-8ecb5e8c93ec
* Version Independent ID: 4f5a9f04-b629-b8b1-1332-9260c95d13b7
* Content: [Azure Machine Learning service training and deployment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-machine-learning?view=azure-devops#feedback)
* Content Source: [docs/pipelines/targets/azure-machine-learning.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/azure-machine-learning.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @jpe316
* Microsoft Alias: **jordane**

**Comment by bospoort** [comment] 2019-06-14 23:12
Looking at the history of the pipeline.yml file, it looks like there was an update that changed the resource group and name of the service connection for ScottGu build session. You might want to revert that back.

**Comment by WilliamAntonRohm** [comment] 2019-06-17 22:08
@bospoort -- thank you for bringing this to our attention.  I have asked our expert to review your request.

@jpe316 -- please look into this information.

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
