### ISSUE TITLE
Arguments for updateType:'Docker Image settings' are not documents

### ISSUE THREAD

**Issue by Ivers07** [MicrosoftDocs/azure-devops-docs#4663] opened 2019-06-27 08:28 UTC
If the Update Type is selected as Docker Image settings the required arguments list changes but there is no documentation about what values to pass for Image Names Path or Image Digests Path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b41ba27-633a-37d4-ce78-a1444a99b5b1
* Version Independent ID: 387739fb-276b-d0c9-4848-45426b6e2319
* Content: [Update Service Fabric App Versions task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/service-fabric-versioning?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/service-fabric-versioning.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/service-fabric-versioning.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment] 2019-06-28 05:38
@pulkitaggarwl

**Comment by shelleylessing** [comment] 2019-08-01 12:18
Hi, I am also busy trying to use this task to update the Docker image settings and am struggling to figure out what the Image Names Path and Image Digests Path are used for. Any help on this would be appreciated.

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
