### ISSUE TITLE
Update debugging section

### ISSUE THREAD

**Issue by annaisalwaysawesome** [MicrosoftDocs/azure-devops-docs#9853] opened 2020-12-18 05:15 UTC
Please update the debugging section with more information on how/where to debug. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment] 2021-05-03 20:23
This issue hasn't been updated in over 130 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by chcomley** 2021-05-03 20:23 UTC
Labels: Extensions, Pri1, devops-ecosystem/tech, devops/prod, doc-enhancement
