### ISSUE TITLE
ACR based triggers on yaml pipeline do not work as per the release document

### ISSUE THREAD

**Issue by binitku** [MicrosoftDocs/azure-devops-docs#8414] opened 2020-05-21 11:31 UTC
There is a conflict in the documentation related to ACR based yaml pipeline trigger.
As per the github documentation  https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-triggers.md#containers "However, triggers are not enabled on container resource today. So, we will keep the current behavior. In the next version of YAML we will enable the triggers by default."

As per the release document https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-160-update#acr-as-a-first-class-pipeline-resource it should work

Few more links:
https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-resources.md#schema-6
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-pipelines

All the links have different schema. Tried it out and found it to be not working.

**Comment by PaulCharlton** [comment] 2020-05-24 06:40
+1
I got the same issue with ACR triggers

**Comment by PaulCharlton** [comment] 2020-05-24 06:43
we need some server side logs for triage of resource based triggers

**Comment by PaulCharlton** [comment] 2020-05-24 14:27
first priority for me is a working example anywhere public ...I have not yet found the "happy path" after testing over 20 permutations of schema variables and syntax.
also see here: https://developercommunity.visualstudio.com/content/problem/920292/azure-pipeline-resource-triggers-not-working.html

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri3, doc-bug
