### ISSUE TITLE
Document the task and output vars

### ISSUE THREAD

**Issue by giantslogik** [MicrosoftDocs/azure-devops-docs#7230] opened 2020-02-11 13:30 UTC
Documentation  does not mention:
APPLE_PROV_PROFILE_UUID
provisioningProfileUuid
provisioningProfileName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5891d09-bbcf-012e-483d-795eb4b469e5
* Version Independent ID: be1f16ef-ea88-ee8e-fa90-61b5228dc454
* Content: [Install Apple Provisioning Profile task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-provisioning-profile?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/install-apple-provisioning-profile.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-apple-provisioning-profile.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by erjohnms** [comment] 2020-02-27 19:39
Docs should mention that if you name the provisioning task eg 'ProvisioningProfileTask' that the variables can be consumed later in the yaml as $(ProvisioningProfileTask.provisioningProfileUuid)

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
