### ISSUE TITLE
Improve doc for 'submodules' flag for checkout step

### ISSUE THREAD

**Issue by mahilleb-msft** [MicrosoftDocs/azure-devops-docs#3450] opened 2019-02-22 10:43 UTC
It seems to suppress checkout out submodules and empty (or unspecified) submodules key needs to be given, for example:

```
  - checkout: self
    clean: true
    fetchDepth: 3
    lfs: false
    submodules: ''
    persistCredentials: false
```

This also corresponds to https://github.com/Microsoft/azure-pipelines-agent/blob/master/src/Agent.Plugins/GitSourceProvider.cs#L213-L223.

Would be nice to clarify this. Also, https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-travis?view=azure-devops claims that "submodules: false" should work, which doesn't, would be nice to fix that as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **macoope**

**Comment by mahilleb-msft** [comment] 2019-02-22 12:52
(addendum: if `submodules` is missing, seems to inherit the setting from the Pipeline definition in the Web UI?)

**Comment by jonstelly** [comment] 2019-02-28 18:33
Also, are submodules from a different Azure Devops Project supported for YAML builds?  I submitted a separate issue: https://github.com/MicrosoftDocs/vsts-docs/issues/3520.

I don't see anywhere in the YAML schema/documentation talking about agent scope, but I'm not 100% sure that's exactly what my problem is.  I can't seem to work out the security hoops to jump through so my pipelines from project B can reference a submodule repository in project A.

**Comment by sschuberth** [comment] 2019-03-28 13:09
On a related note, I just realized `fetchDepth` applies to submodules, too. That should be documented more clearly. Ideally, there would be a way to specify the fetch depth for `self` and contained submodules separately. That way one could use a low fetch depth for `self` for performance reasons, but a high or unlimited fetch depth for submodules, as submodules often point to an arbitrary commit in the submodule repository that might be way behind their current HEAD, which with a low fetch depth results in something like

```
Fetched in submodule path 'analyzer/src/funTest/assets/projects/external/jgnash', but it did not contain 2aa4cce7d7fd46164030f2b4d244c4b89e77f722. Direct fetching of that commit failed.
##[error]Git submodule update failed with exit code: 1
##[section]Finishing: Checkout
```

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
