### ISSUE TITLE
Error in the examples for `tf branch`? reference to `C:\314.cs` instead of `C:\projects\314.cs` ?

### ISSUE THREAD

**Issue by per-ok** [MicrosoftDocs/azure-devops-docs#13413] opened 2023-06-17 12:11 UTC
In the [Examples](https://learn.microsoft.com/en-us/azure/devops/repos/tfvc/branch-command?view=azure-devops#examples) for the `tf branch` command the path `C:\314.cs` is mentioned and I suspect that this should be `C:\projects\314.cs` instead.  Otherwise, if it is referring to a file outside the workspace root folder, maybe a path like `C:\not-in-workspace\314.cs` could be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 761dc0a7-a74a-5e1b-1f38-d3f5a9238844
* Version Independent ID: eea02d4b-a9d1-f5fb-aa60-ced3c3274991
* Content: [Branch TFVC command - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/tfvc/branch-command?view=azure-devops)
* Content Source: [docs/repos/tfvc/branch-command.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/tfvc/branch-command.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-tfvc**
* GitHub Login: @MaximMalygin
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment] 2023-06-19 06:45
Duplicate of #13414

**Closed by WilliamAntonRohm** 2023-06-19 06:45 UTC
Labels: duplicate, cba, Pri2, azure-devops-repos/svc, azure-devops-repos-tfvc/subsvc
