### ISSUE TITLE
The documentation does not mention that .NET Core 2 is required

### ISSUE THREAD

**Issue by bialpio** [MicrosoftDocs/azure-devops-docs#4108] opened 2019-05-01 06:12 UTC
The documentation does not mention that .NET Core 2 is required. The task will fail when running on .NET Core 3. This is due to a requirement of reportgenerator that is used by this task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by nigurr** [comment] 2019-05-02 11:54
@bialpio I tried with Net Core 3 and it's working fine for me.
Can you please share your setup/pipeline debug logs to further investigate

**Comment by jayaranigarg** [comment] 2019-05-17 06:32
@bialpio : We haven't heard back from you on this. Let us know if this is still a concern!

**Comment by AArnott** [comment] 2019-06-12 05:00
It also fails when .NET Core 1 is used, as tracked by https://github.com/tonerdo/coverlet/issues/466

**Comment by ShreyasRmsft** [comment] 2019-06-18 06:43
@AArnott .NET Core 1 and 1.1 are nearing the end of the support cycle.

https://dotnet.microsoft.com/platform/support/policy/dotnet-core

If it however does not work with dotnetcore 2 or 3 please do provide the logs as requested.

**Comment by bialpio** [comment] 2019-06-26 05:39
I have an agent configured on a VM, the output of `dotnet --list-sdks` contains only `3.0.100-preview3-010431 [<path>]`. `dotnet --list-runtimes` lists Microsoft.AspNetCore.App (3.0.0-preview3-19153-02) and Microsoft.NETCore.App (3.0.0-preview3-27503-5). The pipeline is configured with a task `PublishCodeCoverageResults@1` that was not working until I've added an additional task `DotNetCoreInstaller@0` with inputs set to `packageType: 'runtime'`, `version: '2.2.3'`. Unfortunately, I currently don't have the access to old pipeline logs.

As far as I can tell, the `PublishCodeCoverageResults` task internally uses ReportGenerator (see github: danielpalme/reportgenerator) that currently does not support running on .NET Core 3 - this is not mentioned anywhere in the documentation of `PublishCodeCoverageResults`.

**Comment by kaadhina** [comment] 2019-07-05 11:17
Hi, looks like @nigurr has already checked that net core 3 is working, can you please share the requested logs

**Comment by ahaleiii** [comment] 2020-02-28 18:33
The version of ReportGenerator is definitely still using a version of .NET Core which reached [EOL almost a year and a half ago](https://dotnet.microsoft.com/platform/support/policy/dotnet-core).

> Executable: C:\vsts\my-agent\_work\_tasks\PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97\1.160.1\\**netcoreapp2.0**\\ReportGenerator.Core.dll

Whatever version of .NET Core is on the agent executing this task needs to support .NET Core 2.0, and it should be called out as a requirement.

Full logs:
```
Starting: Publish code coverage
==============================================================================
Task         : Publish code coverage results
Description  : Publish Cobertura or JaCoCo code coverage results from a build
Version      : 1.160.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results
==============================================================================
##[warning]Multiple file or directory matches were found. Using the first match: C:\vsts\my-agent\_work\1767\s\tests\MyApp.Data.Tests\test-results\coverage.xml
"C:\Program Files\dotnet\dotnet.exe" C:\vsts\my-agent\_work\_tasks\PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97\1.160.1\netcoreapp2.0\ReportGenerator.dll -reports:C:\vsts\my-agent\_work\1767\s/tests/**/test-results/coverage.* -targetdir:C:\vsts\my-agent\_work\_temp\cchtml -reporttypes:HtmlInline_AzurePipelines
2020-02-28T13:15:31: Arguments
2020-02-28T13:15:31:  -reports:C:\vsts\my-agent\_work\1767\s/tests/**/test-results/coverage.*
2020-02-28T13:15:31:  -targetdir:C:\vsts\my-agent\_work\_temp\cchtml
2020-02-28T13:15:31:  -reporttypes:HtmlInline_AzurePipelines
2020-02-28T13:15:31: Executable: C:\vsts\my-agent\_work\_tasks\PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97\1.160.1\netcoreapp2.0\ReportGenerator.Core.dll
2020-02-28T13:15:31: Working directory: C:\vsts\my-agent\_work\1767\s
2020-02-28T13:15:31: Loading report 'C:\vsts\my-agent\_work\1767\s\tests\MyApp.Data.Tests\test-results\coverage.xml' 1/2 in memory
2020-02-28T13:15:31: Finished parsing C:\vsts\my-agent\_work\1767\s\tests\MyApp.Data.Tests\test-results\coverage.xml...
2020-02-28T13:15:31: Loading report 'C:\vsts\my-agent\_work\1767\s\tests\MyApp.Tests\test-results\coverage.xml' 2/2 in memory
2020-02-28T13:15:31: Start merge result 1
2020-02-28T13:15:31: Finished merge result 1
2020-02-28T13:15:31: Finished parsing C:\vsts\my-agent\_work\1767\s\tests\MyApp.Tests\test-results\coverage.xml...
2020-02-28T13:15:31: Parsing of 2 files completed.
2020-02-28T13:15:31: Start merge result 2
2020-02-28T13:15:31: Finished merge result 2
2020-02-28T13:15:31: Initializing report builders for report types: HtmlInline_AzurePipelines
2020-02-28T13:15:31: Analyzing 610 classes
2020-02-28T13:15:34:   Writing report file 'C:\vsts\my-agent\_work\_temp\cchtml\index.htm'
2020-02-28T13:15:34: Report generation took 2.9 seconds
Generated code coverage html report: C:\vsts\my-agent\_work\_temp\cchtml
Reading code coverage summary from 'C:\vsts\my-agent\_work\1767\s\tests\MyApp.Data.Tests\test-results\coverage.xml'
Async Command Start: Publish code coverage
Publishing coverage summary data to TFS server.
 Lines- 5081 of 10674 covered.
 Branches- 321 of 321 covered.
Modifying Cobertura Index file
Publishing code coverage files to TFS server.
Uploading 613 files
Total file: 613 ---- Processed file: 44 (7%)
Total file: 613 ---- Processed file: 135 (22%)
Total file: 613 ---- Processed file: 243 (39%)
Total file: 613 ---- Processed file: 348 (56%)
Total file: 613 ---- Processed file: 456 (74%)
Total file: 613 ---- Processed file: 564 (92%)
File upload succeed.
Published 'C:\vsts\my-agent\_work\_temp\cchtml' as artifact 'Code Coverage Report_164146'
Async Command End: Publish code coverage
Finishing: Publish code coverage
```

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
