### ISSUE TITLE
Variable format described inconsistently between this page and the variable groups page.

### ISSUE THREAD

**Issue by jjpepper** [MicrosoftDocs/azure-devops-docs#3626] opened 2019-03-13 01:51 UTC
This page says:

"In this topic, we discuss user-defined variables. Names of these variables consist of letters, numbers, ., and _ characters."

However at point 6 of [this page](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=designer#create-a-variable-group) there is an image of a variable group with variables called "app-location", "app-name", "requires-login" and "user-name".

Are these talking about the same kinds of variable?  What _is_ allowed in a variable name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
