### ISSUE TITLE
Azure DevOps SERVICES only? Or, also DevOps SERVER

### ISSUE THREAD

**Issue by Loves2Code** [MicrosoftDocs/azure-devops-docs#3948] opened 2019-04-12 14:10 UTC
My client is considering Azure DevOps Server as an on-premise solution.
The client also runs Jenkins.
Thus, is it only Azure DevOps SERVICES that allow interaction with Jenkins, for example?
Or, is it possible to integrate with Jenkins via the on-premise Azure DevOps Server 2019?
The article appears to only target Azure DevOps Services, and doesn't clarify whether, based on the 3rd party tools, this functionality is available on Azure DevOps Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634d1b6c-a9ca-6188-a262-2fd23ea8df8f
* Version Independent ID: ded5ff86-199d-1251-5b51-5c52af444447
* Content: [Integrate Azure DevOps Services with third party apps using service hooks](https://docs.microsoft.com/en-us/azure/devops/service-hooks/index?view=azure-devops)
* Content Source: [docs/service-hooks/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/index.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment] 2019-04-12 17:55
Adding @roofers to help answer this one.

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri2, devops-collab/tech, devops/prod, doc-bug
