### ISSUE TITLE
VSO refered me wrongly to this page, should be to a subpage 

### ISSUE THREAD

**Issue by dannyvv** [MicrosoftDocs/azure-devops-docs#3453] opened 2019-02-22 19:05 UTC
Hi,

My build: (id:8525995, account:mseng) failed which a promise of documentation on why shallow-cone might fail:
```
##[warning]Git checkout failed on shallow repository, this might because of git fetch with depth '1' doesn't include the checkout commit &lt;anonymized&gt;'. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=829603) 
4121
```
But this page doesn't seem to have this information. It seems the content moved to a sub-page (Pipeline options for git). It would be nice if either the parent doc can mention that the shallow-clone docs are in the sub-page or ideally the fwlink would be updated to [shallow-fetch section in 'Pipeline options for Git' page](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#shallow-fetch)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59bebc3-fe8a-ad9e-7c55-884a8c7b4bac
* Version Independent ID: 7db3d604-b118-2f7b-85f4-1bd52244b279
* Content: [Build source repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/?view=azure-devops)
* Content Source: [docs/pipelines/repos/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/index.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by seangwright** [comment] 2019-04-06 18:40
I was also linked here from the DevOps pipelines Build edit screen for the "Get Sources" task.

![azure-devops-pipelines-build-edit-get-sources](https://user-images.githubusercontent.com/1382768/55673735-c7ed1000-5879-11e9-9ae4-1607d791ef84.jpg)

The link should provide more information whether or not you want to "tag sources" but there is nothing on this page about "tagging".

**Comment by JeffBor** [comment] 2020-01-06 18:45
> I was also linked here from the DevOps pipelines Build edit screen for the "Get Sources" task.
> 
> ![azure-devops-pipelines-build-edit-get-sources](https://user-images.githubusercontent.com/1382768/55673735-c7ed1000-5879-11e9-9ae4-1607d791ef84.jpg)
> 
> The link should provide more information whether or not you want to "tag sources" but there is nothing on this page about "tagging".

Azure Devops link is https://aka.ms/ci-tagsources but redirects to this page currently titled "Build source repositories"

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
