### ISSUE TITLE
Build.RequestedFor and Build.RequestedForId not matching docs

### ISSUE THREAD

**Issue by samiyaakhtar** [MicrosoftDocs/azure-devops-docs#3923] opened 2019-04-10 23:08 UTC
According to docs [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#identity_values), when the build is triggered by a branch policy build, then the `Build.RequestedFor` and `Build.RequestedForId` values are based on "The person who checked in the changes". I'm not seeing this to be the case, for `Build.RequestedFor` I get `GitHub` and for `Build.RequestedForId` I get a GUID `0aae581f-2f5f-48c4-afa9-ce854c8324c6`. When I try `Build.RequestedForEmail`, it's blank. 

For reference, I've tried testing all of these as author names in commits here: [See last three commits](https://github.com/samiyaakhtar/aks-deploy-destination/commits/master). 

![Screen Shot 2019-04-10 at 4 07 06 PM](https://user-images.githubusercontent.com/1795990/55919420-d05f8680-5baa-11e9-806f-065423018782.png)

Is there any way I can get the name of the user who committed from the build variables, rather than guids? I'm trying to avoid having to make an API call to GitHub/Azure DevOps to get this author name.

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri3, doc-bug
