### ISSUE TITLE
Strong collective ownership

### ISSUE THREAD

**Issue by jessehouwing** [MicrosoftDocs/azure-devops-docs#2254] opened 2018-10-28 10:29 UTC
The study leaves out strong collective ownership through promiscuous pair programming and mob programming. These are hard to measure through commit history... Any thoughts? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba3f89f-a30e-37a1-a66a-c6728089ce60
* Version Independent ID: f16921aa-af53-ee3f-0534-6ce7a4a10ca2
* Content: [Code ownership and software quality - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/code-ownership-software-quality)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fcode-ownership-software-quality.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fcode-ownership-software-quality.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **mgreiler**

**Comment by steved0x** [comment] 2018-10-31 14:52
@jessehouwing I have forwarded your feedback to the author and I'll update this issue when I get a response.

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri2, devops-learn/tech, devops/prod, doc-bug
