### ISSUE TITLE
Missing Required App Fields when Uploading

### ISSUE THREAD

**Issue by aaronjedwards** [MicrosoftDocs/azure-devops-docs#7217] opened 2020-02-10 22:36 UTC
I was able to successfully use this task to upload and distribute an internal line of business app to my company Intune store. I soon noticed that after this process, I was unable to view or edit the "Properties" of my Intune app in the Intune portal (preventing editing of user assignments, app description, info url, etc.). I was able, however, to upload the .ipa file manually to Intune and access the "Properties" tab just fine. I noticed that during the manual upload of the app to Intune that there were certain required fields (the app's description) that I could not specify in App Center or in using the AppCenterDistribute task.

In the end, I was able to get everything working by manually patching the app through the Intune Graph API (https://docs.microsoft.com/en-us/graph/api/intune-apps-ioslobapp-update?view=graph-rest-1.0) to add the required description field, although it was a pain to figure out that even needed to be done. The docs should be expanded to point to an explanation of how to properly use this task with Intune or they should include a note indicating that specific fields are required when uploading to Intune (and how to specify them in App Center).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da6643ac-ea32-1761-a7e9-0f17a3c0b8ee
* Version Independent ID: 2442af0f-3f01-a91c-a98a-29c2f32d35b9
* Content: [App Center Distribute task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/app-center-distribute.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/app-center-distribute.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
