### ISSUE TITLE
For k8s service connection: please provide a clear description of difference between "Azure subscription option" and "service account option"

### ISSUE THREAD

**Issue by bitsofinfo** [MicrosoftDocs/azure-devops-docs#6177] opened 2019-10-29 16:05 UTC
You present 2 options for AKS service connections:

"Azure subscription option" and "service account option"

But there is no explanation on what is the clear difference between these two options. They both produce service accounts? What is the diff? The auth mechanism? What is the auth mechanism?

Please provide more info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-kuber)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
