### ISSUE TITLE
Power BI Content packs are no longer available

### ISSUE THREAD

**Issue by pschaeflein** [MicrosoftDocs/azure-devops-docs#8981] opened 2020-08-03 13:41 UTC
Following the steps on this page, the content pack cannot be found. PowerBI has transitioned to Template Apps, and content packs are no longer shown in the user interface.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0c4c36-bf68-3950-e6fa-d1f4ab728f8b
* Version Independent ID: 088e51cc-a926-ffb7-53b9-2f53fdc65d14
* Content: [Extension Statistics Power BI Content pack - Visual Studio Marketplace](https://docs.microsoft.com/en-us/azure/devops/marketplace/extension-statistics-powerbi-contentpack?view=azure-devops)
* Content Source: [docs/marketplace/extension-statistics-powerbi-contentpack.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/marketplace/extension-statistics-powerbi-contentpack.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by prashantvc** [comment] 2020-08-06 07:52
Duplicate of https://github.com/MicrosoftDocs/azure-devops-docs/issues/7604

**Comment by chcomley** [comment] 2020-08-06 15:30
Hi @pschaeflein, Thanks for your feedback. This is a duplicate issue, which is closed, as it isn't a documentation issue. Please refer to this[ GitHub issue](https://github.com/MicrosoftDocs/azure-devops-docs/issues/7604) for further information. Thank you.

**Closed by chcomley** 2020-08-06 15:30 UTC
Labels: Pri2, devops-marketplace/tech, devops/prod, doc-bug

**Comment by pschaeflein** [comment] 2020-08-06 20:19
@chcomley It is a documentation issue. Content Packs are no longer supported in PowerBI, so the documentation should not indicate that it is available. I am 100% certain that the ticket opened with the PowerBI team will result in a message that Content Packs are no longer supported. Unless the DevOps team will be updating the content pack to a PowerBI Template App, folks who read the documentation will never get PowerBI integration.
