### ISSUE TITLE
A way to clone the suite in the same plan

### ISSUE THREAD

**Issue by AgentMC** [MicrosoftDocs/azure-devops-docs#1040] opened 2018-06-13 09:31 UTC
The `tcm suites /clone` does not allow copying the suite within the same plan. This may sound weird as MTM does. And indeed this is a senseless limitation which you can easily overcome by creating a temporarily "proxy" plan, copying the `source` to `proxy` and then `proxy` to `target` within the same plan `source` is in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89c0b4f2-6754-f147-6681-759d06027c4f
* Version Independent ID: 981f81b2-3c4c-c26b-d36a-61cfe9594e0c
* Content: [Copying and cloning test suites and test cases](https://docs.microsoft.com/en-us/vsts/test/mtm/copying-and-cloning-test-suites-and-test-cases?view=vsts)
* Content Source: [docs/test/mtm/copying-and-cloning-test-suites-and-test-cases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/mtm/copying-and-cloning-test-suites-and-test-cases.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment] 2018-06-13 09:54
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by THEotterlover** [comment] 2019-07-18 14:45
I'm using Azure Test Plans since MS Test Manager is now obsolete. I saw the FAQ link at the beginning of this article (https://docs.microsoft.com/en-us/azure/devops/test/reference-qa?view=azure-devops#copyclonetce).

I'm very interested in copying test suites inside the same test plan as we are using static suites for testing activities and we want to easily re-use the test cases inside those test suites without having to manually add them using "Add existing" since there can be a lot to add (100+) and they have different area path/iteration path which is why we cannot use multi-selection in the "Add existing" query window.

I will try what is suggested in the FAQ but it doesn't look that straightforward; I'll update my comment if I succeed.

"Q: Can I copy or clone test plans and test suites?
A: Yes. For test plans, use this API. For test suites, use this API. We plan to expose these capabilities through the out-of-box UI in a future release."

**Comment by cxwtool** [comment] 2020-11-24 23:50
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:50 UTC
Labels: Pri2, devops-test/tech, devops/prod, doc-bug
