### ISSUE TITLE
Missing information about "Legacy Microsoft-hosted build option, charged per minute"

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/azure-devops-docs#1394] opened 2018-07-25 09:46 UTC
This is an option on the Azure portal - &gt; Team Services administration -&gt; [organisation] -&gt; Settings -&gt; CI/CD. Per minute billing sounds better/more SaaSy/cloudy than the current 'capacity' model. 

![image](https://user-images.githubusercontent.com/12844147/43193476-761d4384-9043-11e8-9e95-ac8a1c99f6ed.png)

I know it's legacy, but there should be docs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb26f633-6068-0e2a-0b8d-e97f8acdbb09
* Version Independent ID: 449ffa66-9707-c87a-6128-57beeb22f0fc
* Content: [CI/CD Concurrent Jobs in Team Services](https://docs.microsoft.com/en-us/vsts/pipelines/licensing/concurrent-jobs-vsts?view=vsts)
* Content Source: [docs/pipelines/licensing/concurrent-jobs-vsts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/licensing/concurrent-jobs-vsts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
