### ISSUE TITLE
`publishWebProjects` required for publish is wrong

### ISSUE THREAD

**Issue by Kissaki** [MicrosoftDocs/azure-devops-docs#4857] opened 2019-07-13 14:53 UTC
The YAML snipped/reference documents `publishWebProjects` as required when command is `publish`:

&gt; `#publishWebProjects: true # Required when command == Publish`

How I understand this is that it has to be true for publish, e.g. this task only supports publishing web projects.

However, this does not seem to be the case as setting it to false for a desktop app seems to run fine.

It could also mean that specifying it for publish is required, but then the default value would make no sense as well as the publish command trying to find web projects by default.

So I guess this is just outdated? And it is not actually required for the publish command?

Then the required note should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#open-source)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by BrianMinister** [comment] 2020-02-05 15:12
Not just messy, but wrong.
After "@PRMerger10 PRMerger10 added devops-cicd/tech devops/prod Pri2 labels on Jul 17, 2019" it looks like this has been forgotten.

**Comment by gojanpaolo** [comment] 2020-02-18 23:44
45a

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
