### ISSUE TITLE
.git and .artifactignore are not ignored by default

### ISSUE THREAD

**Issue by cotyhamilton** [MicrosoftDocs/azure-devops-docs#8292] opened 2020-05-12 16:21 UTC
The document says .git is ignored by default and to unignore it you need to add !.git

I have static html files checked in to source and just need to upload them

Using the publish pipeline artifact task and . (or $(build.sourcesdirectory) or $(pipeline.workspace)/s) as the path, the .git folder and .artifactignore file get published if not specified in the .artifactignore file, which conflicts with the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40b39086-3718-419d-d850-914422097cde
* Version Independent ID: 4f23e54f-f59b-85ab-2eb0-6a58eb0ad088
* Content: [Use the .artifactignore file - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/artifactignore?view=azure-devops)
* Content Source: [docs/artifacts/reference/artifactignore.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/reference/artifactignore.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri2, devops-artifacts/tech, devops/prod, doc-enhancement
