### ISSUE TITLE
Docs seem out of date with use of always_exclude and sparse-checkout

### ISSUE THREAD

**Issue by mwasplund** [MicrosoftDocs/azure-devops-docs#5977] opened 2019-10-14 15:22 UTC
It appears as if the documentation on this page is out of date:
https://docs.microsoft.com/en-us/azure/devops/learn/git/gvfs-architecture

It says that gvfs uses always_exclude and sparse-checkout, however when doing testing it was not doing what I expected. I also found a task that mentions that GVFS has transitioned over to using something called Modified paths:
https://github.com/microsoft/VFSForGit/pull/261

**Comment by msebolt** [comment] 2019-10-15 04:54
@mwasplund Thank you for the feedback, assigning this to an author for review.

@thomps23 The author's alias is missing, can you assign this accordingly?

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri3, doc-enhancement
