### ISSUE TITLE
Step 2 fails with "Downloading file: https://nodejs.org/dist/v10.15.1/win-x64/node.exe"

### ISSUE THREAD

**Issue by ChiefOfUnicornExtermination** [MicrosoftDocs/azure-devops-docs#8411] opened 2020-05-21 06:22 UTC
I just followed the sample lines, and failed. 
  Error
      at doRequest (node_modules\azure-pipelines-task-lib\node_modules\sync-request\index.js:27:11)
      at MockTestRunner.downloadFile (node_modules\azure-pipelines-task-lib\mock-test.js:230:22)
      at MockTestRunner.downloadNode (node_modules\azure-pipelines-task-lib\mock-test.js:210:22)
      at MockTestRunner.getNodePath (node_modules\azure-pipelines-task-lib\mock-test.js:147:25)
      at new MockTestRunner (node_modules\azure-pipelines-task-lib\mock-test.js:28:30)
      at Context.&lt;anonymous&gt; (tests\_suite.js:33:18)
      at processImmediate (internal/timers.js:456:21)

Seemed like attempting to download non existing path. I can't believe everyone else could do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment] 2020-06-02 19:46
Hi @ChiefOfUnicornExtermination, Please accept my apology for the delayed response. I'm adding @jtpetty for further guidance. Thank you.

**Comment by jtpetty** [comment] 2020-06-02 20:02
@damccorm - Do you know what the issue is here? Is this something wrong in our example or just flakiness from nodejs.org?

**Comment by krumelist** [comment] 2020-06-03 12:10
Hey @jtpetty was just going through your tutorial as well and I am facing the same issue right now.
Trying to download the file via the link out of the console output works at least. So I don't think its a flakiness from nodejs.org.

`PS C:\Users\X\Desktop\azure-devops-extensions\home\buildAndReleaseTask> mocha tests/_suite.js

  Sample task tests
Downloading file: https://nodejs.org/dist/v10.15.1/win-x64/node.exe
    1) should succeed with simple inputs
Downloading file: https://nodejs.org/dist/v10.15.1/win-x64/node.exe
    2) it should fail if tool returns 1

  0 passing (8s)
  2 failing

  1) Sample task tests
       should succeed with simple inputs:
     
  Error
      at doRequest (node_modules\azure-pipelines-task-lib\node_modules\sync-request\index.js:27:11)
      at MockTestRunner.downloadFile (node_modules\azure-pipelines-task-lib\mock-test.js:230:22)
      at MockTestRunner.downloadNode (node_modules\azure-pipelines-task-lib\mock-test.js:210:22)
      at MockTestRunner.getNodePath (node_modules\azure-pipelines-task-lib\mock-test.js:147:25)
      at new MockTestRunner (node_modules\azure-pipelines-task-lib\mock-test.js:28:30)
      at Context.<anonymous> (tests\_suite.js:33:18)
      at processImmediate (internal/timers.js:439:21)

  2) Sample task tests
       it should fail if tool returns 1:
     
  Error
      at doRequest (node_modules\azure-pipelines-task-lib\node_modules\sync-request\index.js:27:11)
      at MockTestRunner.downloadFile (node_modules\azure-pipelines-task-lib\mock-test.js:230:22)
      at MockTestRunner.downloadNode (node_modules\azure-pipelines-task-lib\mock-test.js:210:22)
      at MockTestRunner.getNodePath (node_modules\azure-pipelines-task-lib\mock-test.js:147:25)
      at new MockTestRunner (node_modules\azure-pipelines-task-lib\mock-test.js:28:30)
      at Context.<anonymous> (tests\_suite.js:46:18)
      at processImmediate (internal/timers.js:439:21)`

**Comment by damccorm** [comment] 2020-06-03 12:19
I think this is the same issue as https://github.com/microsoft/azure-pipelines-task-lib/issues/630, looks like @stephenmichaelf and @alex-peck were looking into it

**Comment by dastewa** [comment] 2020-06-16 00:37
I just ran into this issue as well and thought it might be an issue with the sync-request version being used, or how it's being used by azure-pipelines-task-lib. I got around this problem by installing azure-pipelines-task-lib v3.0.0-preview (npm i azure-pipelines-task-lib@3.0.0-preview) and then installing the latest sync-request.

**Comment by stephenmichaelf** [comment] 2020-06-16 11:29
@ChiefOfUnicornExtermination @dastewa I was able to follow the docs and run the tests without issue. What version of node are you using? I ran with 10.18.0.

**Comment by ChiefOfUnicornExtermination** [comment] 2020-06-17 18:47
Hmm?? Is this version so old? If you meant node.exe's version, it said v10.15.1 according to the url it downloads as you can see on my comment above.
It's simply gotten from `npm install azure-pipelines-task-lib --save` and `npm install mocha --save-dev -g` just following the tutorial. There are no version specified for them. Why this happens? I haven't tried yet but you mean if I download each items with specific version I manually type, it'll work??

![image](https://user-images.githubusercontent.com/65433846/84937115-21f98000-b090-11ea-9e0c-1ea39ab828c9.png)


```
Downloading file: https://nodejs.org/dist/v10.15.1/win-x64/node.exe
    2) it should fail if tool returns 1


  0 passing (10m)
  2 failing

  1) Sample task tests
       should succeed with simple inputs:

  Error
      at doRequest (node_modules\azure-pipelines-task-lib\node_modules\sync-request\index.js:27:11)
      at MockTestRunner.downloadFile (node_modules\azure-pipelines-task-lib\mock-test.js:230:22)
      at MockTestRunner.downloadNode (node_modules\azure-pipelines-task-lib\mock-test.js:210:22)
      at MockTestRunner.getNodePath (node_modules\azure-pipelines-task-lib\mock-test.js:147:25)
      at new MockTestRunner (node_modules\azure-pipelines-task-lib\mock-test.js:28:30)
      at Context.<anonymous> (tests\_suite.js:33:18)
      at processImmediate (internal/timers.js:456:21)

  2) Sample task tests
       it should fail if tool returns 1:

  Error
      at doRequest (node_modules\azure-pipelines-task-lib\node_modules\sync-request\index.js:27:11)
      at MockTestRunner.downloadFile (node_modules\azure-pipelines-task-lib\mock-test.js:230:22)
      at MockTestRunner.downloadNode (node_modules\azure-pipelines-task-lib\mock-test.js:210:22)
      at MockTestRunner.getNodePath (node_modules\azure-pipelines-task-lib\mock-test.js:147:25)
      at new MockTestRunner (node_modules\azure-pipelines-task-lib\mock-test.js:28:30)
      at Context.<anonymous> (tests\_suite.js:46:18)
      at processImmediate (internal/timers.js:456:21)
```

**Comment by stephenmichaelf** [comment] 2020-06-18 11:56
@ChiefOfUnicornExtermination  Sorry, not the node version that is being downloaded, the version you are using on your computer. You can type `node -v` to get it.

**Comment by ChiefOfUnicornExtermination** [comment] 2020-06-19 01:22
Okay. It's v14.2.0
Maybe too new? Or new update has this issue?
I'm using Windows 10. Maybe this also relates it?

**Comment by chcomley** [comment] 2020-06-26 17:53
Hi @stephenmichaelf, Did you get all of your questions answered? Please let us and @stephenmichaelf  know if you need further guidance, thank you!

**Comment by JFolberth** [comment] 2020-06-26 18:58
I am having the same issue with following the sample. My node version is v12.18.1

**Comment by stephenmichaelf** [comment] 2020-06-26 19:12
@JFolberth Did you try 10.18.0? This has worked for others too.

**Comment by chcomley** [comment] 2020-07-02 16:09
Hi all, I want to make sure 10.18.0 is working for everyone? I'll be closing this issue, as there's been no further discussion. Please @mention me if you need me to reopen this and I'll be happy to! Thanks so much for your feedback!

**Comment by ganesh-kashid** [comment] 2020-12-09 17:46
Installing 10.18.0 did not solve my issue. 
Finally solved by following below steps to bypass the node.exe downloading
1. Downloaded node.exe from https://nodejs.org/dist/v10.21.0/win-x64/node.exe and saved it in home folder i.e. 
"C:\Users\<UserName>\azure-pipelines-task-lib\_download\node10\node.exe"
2. Updated "\<TaskName>\node_modules\azure-pipelines-task-lib\mock-test.js" and replaced function that trying to download node.exe with the path in step 1. 
 **Updated Line**: _28_
 **Line updated:** _this.nodePath = getNodePath()_
 **Line updated with**: _this.nodePath = 'C:\\Users\\<UserName>\\azure-pipelines-task-lib\\_download\\node10\\node.exe';_
3. Referred below MS Doc to install latest node and npm packages. Here I installed latest version v14.15.1, however in step1 downloaded v10.21.0 as its hardcoded in azure-pipelines-task-lib. May be azure-pipelines-task-lib is compliant with v10.21.0.
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task

**Comment by tukaya** [comment] 2020-12-15 21:32
Uninstalling nodejs and then installing v10.21.0 (choco install nodejs --version 10.21.0) solved the issue for me.

**Comment by bennett-elder** [comment] 2021-02-15 07:21
Nodejs 10 is EOL in a few months so similar to above I'm using Nodejs 14.15.5.

After installing azure-pipelines-task-lib 2.12 I experienced the same issue where it tried to download Nodejs 10. That led me to this issue.

Installing 3.0.6-preview-2 resolved it:

`npm install azure-pipelines-task-lib@3.0.6-preview.2 --save`

**Comment by bennett-elder** [comment] 2021-02-15 09:04
Hi @chcomley, I think we should reopen this zombie thread. 🧟 😄 

I dug a bit and discovered why Node v14 isn't supported yet:
The Node14 changes have been rolled back in both the [azure-pipelines-task-lib docs](https://github.com/microsoft/azure-pipelines-task-lib/pull/693/files) and the [azure-pipelines-agent](https://github.com/microsoft/azure-pipelines-agent/pull/3151) due to [issues during the migration](https://github.com/microsoft/azure-pipelines-agent/issues/3195#issuecomment-749438520). It looks like [it could be quite a while before Node14 support in the agent ships](https://github.com/microsoft/azure-pipelines-agent/pull/3151#issuecomment-719596228).

**Why I think we should reopen the issue:**
The current version of the docs suggests that we should be able to walk through the tutorial with the latest version of Node (15 at the moment) and the latest version of azure-pipelines-task-lib (2.12). We've seen that leads to the "downloading file" error. To clear up any confusion, we can note in the tutorial that the dev machine _needs to run Node v10.21.0_ to ensure the code written is compatible with the production environment on the agent and the latest non-preview version of azure-pipelines-task-lib.

**Comment by chcomley** [comment] 2021-02-15 17:40
Hi @stephenmichaelf, We've reopened this issue! Could you please provide assistance? Thanks so much!

**Comment by chcomley** [comment] 2021-03-04 17:44
Hi @bennett-elder, I've added an IMPORTANT note, which should go live sometime today. This issue will automatically close when it's live. Thank you for reopening the zombie thread and for providing a helpful "fix".

**Closed** 2021-03-04 18:00 UTC
Labels: Extensions, Pri1, devops-ecosystem/tech, devops/prod, doc-bug
