### ISSUE TITLE
How to run UWP tests

### ISSUE THREAD

**Issue by vborovikov** [MicrosoftDocs/azure-devops-docs#5642] opened 2019-09-18 06:08 UTC
Not clear how to enable running tests from UWP test app project.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 5b846f94-2bb5-d5a8-63c8-8227ab1b613b
* Version Independent ID: 5ba1aaac-6076-c5e0-fec0-c2ac2405b138
* Content: [Build your Universal Windows Platform app - Azure Pipelines](https://docs.microsoft.com/ru-ru/azure/devops/pipelines/apps/windows/universal?view=azure-devops&viewFallbackFrom=vsts&tabs=vsts)
* Content Source: [docs/pipelines/apps/windows/universal.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/windows/universal.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
