### ISSUE TITLE
Clarify the use of deployment jobs to setup a multi-environment release.

### ISSUE THREAD

**Issue by empz** [MicrosoftDocs/azure-devops-docs#8348] opened 2020-05-15 14:19 UTC
Setting up a multi-environment release pipeline with Classic Releases is pretty straightforward. The ability to trigger Release pipelines after successful Builds, chaining, and promoting releases from one environment to the next one (DEV -&gt; QA -&gt; Staging -&gt; Production), approving, gates. It's all very straightforward to set up using Classic.
With the new pipelines is not easy. I couldn't find a proper example on setting up a deploy yaml pipeline on multiple environments, set the Dev one to be triggered once a build is successful, promote to QA and so on.

Please provide proper examples for this very standard use case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-cicd-process/tech, devops/prod, doc-enhancement
