### ISSUE TITLE
How to show Deployment control on hosted xml process work items

### ISSUE THREAD

**Issue by deadlydog** [MicrosoftDocs/azure-devops-docs#5980] opened 2019-10-14 18:13 UTC
If you're using an Inherited process model the Deployment control shows up on your work items by default, but not when using a Hosted XML process model. Some instructions on what XML needs to be modified to show the Deployment control on works items is currently missing from the docs and would be greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462be419-4cfd-4bfc-06cc-45800c0d888b
* Version Independent ID: 95cb8a7d-c61d-dfac-403f-12fe40ba1c49
* Content: [See release deployment information from the work item form - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-deployments-control?view=azure-devops)
* Content Source: [docs/boards/work-items/work-item-deployments-control.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/work-item-deployments-control.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @danhellem
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment] 2019-10-15 05:21
@deadlydog Thank you for the feedback, assigning this to the author for review.

**Comment by danhellem** [comment] 2019-10-15 16:21
@msebolt - I don't work at Microsoft anymore. Please reach out to Martina for this.

**Comment by msebolt** [comment] 2019-10-15 17:49
@danhellem  Thank you for the update.

@thomps23 Can you have this article re-assigned?

**Comment by danhellem** [comment] 2019-10-16 15:51
I assigned to @MartinaMS. She will be able to help

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri1, devops-agile/tech, devops/prod, doc-enhancement
