### ISSUE TITLE
Add more details on using an Azure Artifacts registry

### ISSUE THREAD

**Issue by dotnetcanuck** [MicrosoftDocs/azure-devops-docs#3531] opened 2019-03-01 15:11 UTC
The documentation on the npm task page talks about setting `customRegistry` to `useFeed`, if you want to install NPM packages from an Azure Artifacts feed. But it doesn't say anything about what the value of `customFeed` should be.

I eventually opened the visual pipeline designer and clicked the "View YAML" button to get the GUID that I eventually pasted into my project's YAML pipeline config. But if I hadn't known that you can get YAML examples from the visual designer, I doubt I would have ever figured that out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c00d3b8-64c1-9f1b-83f8-62d8cf07817b
* Version Independent ID: 5fcdebed-cfb8-c5a6-d807-1315b2db5e57
* Content: [npm task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/package/npm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/npm.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by lifesoccult** [comment] 2019-04-02 19:20
Just came across this issue myself. The documentation for the npm task is overwhelmingly sub-par.

**Comment by elbatk** [comment] 2019-04-04 00:07
Hey folks - so I took a a look at this. The value of `customFeed` should be the name of your feed:

steps:
```
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
    customRegistry: useFeed
    customFeed: feedName
```

If that doesn't work, then we need to file a bug. As far as the documentation goes, I believe the Pipelines team is working hard to help their users use YAML more efficiently/easily.

**Comment by ntherrien** [comment] 2019-07-25 22:12
How do we specify more than one feed? I have a product using packages from two feeds within the company.

**Comment by elbatk** [comment] 2019-07-25 23:03
I haven't tested out that capability yet @ntherrien , but a lot of Azure Pipelines let you put a list in as comma separated values: 'feed1,feed2'. However, you could always set up feed1 to upstream to feed2, and then when you ask feed1 for a package, it'll go get it from feed2, store it, and you can use it.

**Comment by ntherrien** [comment] 2019-07-26 15:26
Listing multiple feeds with commas does not seem to be working. I'm seeing errors accessing the registries related to badly parsed URLs.

Im going to fall back to using a .npmrc file, but I would have preferred not having to use personal access tokens. I wanted to use service principal connections instead via feed authentication.

**Comment by ntherrien** [comment] 2019-07-26 16:42
UPDATE:  I have found a way to make it work using the feed option.

1) Define a .npmrc file in the root of your project listing the URLs for the registries there. Make sure there are no authentication information in that file. It should look like:
@reponame:registry=https://msi-cie.pkgs.visualstudio.com/_packaging/registryname/npm/registry/
@reponame:registry https://msi-cie.pkgs.visualstudio.com/_packaging/registryname/npm/
@reponame:always-auth=true
@reponame2:registry=https://pkgs.dev.azure.com/msi-cie/_packaging/repo2/npm/registry/
@reponame2:always-auth=true

Note: since this file does not contain any authentication information, you will need to provide your personal tokens in the .npmrc file located in your home directory.

2) In the pipeline yaml, set customRegistry to useFeed 
3) Set customFeed to the comma separated list of feed NAMES. Not the URLs.   This is what i was doing wrong.   
Using the example above, this value would be: 'registryname,repo2'

4) that's it, with this set up, reading and publishing from the feeds will be authenticated automatically using the service principal connection.

NOTE: my project has service principal connections defined for both registries. I cannot know for certain if they are used. Just keep that in mind if you get authentication error using this little tutorial. To set up service connections, go to your project settings, under service connections and add service connections for your npm feeds.

Thanks @elbatk for your comment earlier. You were right and it was your comment that gave me the clue that perhaps the customFeed value would take a feed name and not the registry url.

**Comment by ntherrien** [comment] 2019-07-26 17:01
UPDATE: looks like im still missing something after all.  Publishing fails due to missing bearer token. Not sure what to do.  Will be reverting to another method which inserts secrets in the .npmrc file.

@elbatk,  do you have any idea what could be missing? I was expecting the npm task to authenticate with the feed for publishing.
PS: i have publishRegistry set to useFeed and publishFeed set to the feed name.
Also, the package.json file contains an entry to the publish registry with URL in it.

**Comment by elbatk** [comment] 2019-07-26 17:21
If you're targeting feeds within your organization, then the build access token should be sufficient for authentication. So when targeting multiple feeds, you'll want to use an .npmrc and rely on your build token for auth.

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
