### ISSUE TITLE
Yarn and Azure Artifacts

### ISSUE THREAD

**Issue by chriskuech** [MicrosoftDocs/azure-devops-docs#3977] opened 2019-04-16 04:34 UTC
I started using Azure Artifacts for my NPM packages and I also use `yarn`.  I am getting 401s when running `yarn install` inside my YAML pipeline.  It would be great to see an example using `yarn` with an Azure Artifacts feed inside a YAML pipeline, as it seems like a popular scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c99686eb-6c78-0336-1ec3-802a53c9868d
* Version Independent ID: 6eaf1acb-24d4-5bb7-3935-17abe7e59dd9
* Content: [Build, test, and deploy JavaScript and Node.js apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=azure-devops#feedback)
* Content Source: [docs/pipelines/languages/javascript.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/javascript.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by svanzoest** [comment] 2019-05-30 17:44
@chriskuech you can use [Yarn Build and Release Tasks](https://marketplace.visualstudio.com/items?itemName=geeklearningio.gl-vsts-tasks-yarn) from the Marketplace as it is more Azure DevOps aware and can handle this credentials bit for you.

**Comment by brettpostin** [comment] 2019-10-18 15:05
I have yarn working locally with authentication to an Azure Artifacts feed, but the Yarn pipeline tasks aren't working. Yarn install gets `Request failed \"401 Unauthorized\""` errors.

I have set the task up to use our private feed:

![image](https://user-images.githubusercontent.com/3657993/67105680-2304a580-f1c1-11e9-9873-3c6323c77c98.png)

Any ideas?

**Comment by brettpostin** [comment] 2019-10-18 15:30
I've added a `yarn config list` in the pipeline, this is the current config...

```
info yarn config
{ 'version-tag-prefix':
   'v',
  'version-git-tag':
   true,
  'version-commit-hooks':
   true,
  'version-git-sign':
   false,
  'version-git-message':
   'v%s',
  'init-version':
   '1.0.0',
  'init-license':
   'MIT',
  'save-prefix':
   '^',
  'bin-links':
   true,
  'ignore-scripts':
   false,
  'ignore-optional':
   false,
  registry:
   '[REMOVED]',
  'strict-ssl':
   true,
  'user-agent':
   'yarn/1.19.0 npm/? node/v10.16.3 win32 x64',
  'always-auth':
   true }
info npm config
{ registry:
   '[REMOVED]',
  'always-auth':
   true,
  '//[REMOVED]:_authToken':
   '***',
  cache:
   'C:\\npm\\cache',
  prefix:
   'C:\\npm\\prefix' }
```

Everything matches local config except the format of the auth token in npm config.

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug

**Comment by jstensved** [comment] 2021-01-30 11:58
Our team is experiencing the same issue. Using regular NPM commands and pushing from Nuget commands work fine.

**Comment by palumbo67** [comment] 2021-11-11 19:44
We are also experiencing this issue...
