### ISSUE TITLE
Which parameters are actually required?

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/azure-devops-docs#7534] opened 2020-03-08 10:36 UTC
A lot of the parameters have '(Required)' next to them and then go on to state a default value. These things can either be defaulted or required, both just sounds wrong.

Also virtually all the other pages for Pipeline tasks have a 'YAML Snippet' and 'Arguments' sections. I feel this article would be better if it was consistent with that format.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b648a9b-9a8d-423f-94c9-cb56ec458273
* Version Independent ID: efe57b89-fbac-8a5c-4607-102ebfd57b54
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, doc-enhancement
