### ISSUE TITLE
Deployment strategy

### ISSUE THREAD

**Issue by DrGrijando** [MicrosoftDocs/azure-devops-docs#6887] opened 2020-01-10 15:39 UTC
In the HockeyApp distribution task there was an option for stating if builds should replace the previous one with the same version number or not. Is this possible witht he App Center task?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da6643ac-ea32-1761-a7e9-0f17a3c0b8ee
* Version Independent ID: 2442af0f-3f01-a91c-a98a-29c2f32d35b9
* Content: [App Center Distribute task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/app-center-distribute.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/app-center-distribute.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment] 2020-01-13 16:49
@DrGrijando Thank you for the feedback, assigning this to the author for review.

The latest version [AppCenterDistributeV3](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AppCenterDistributeV3/task.json) now supports a `buildVersion` parameter.

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
