### ISSUE TITLE
How do you configure Record Project Details in YAML builds?

### ISSUE THREAD

**Issue by TabithaLarkin** [MicrosoftDocs/azure-devops-docs#5044] opened 2019-07-29 10:32 UTC
This section mentions a checkbox, but in YAML builds, I don't see the corresponding option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22342679-18af-7c79-f902-fe9c0bb55379
* Version Independent ID: a8e7c201-6593-458b-5a81-b54e93fde4b5
* Content: [MSBuild build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/msbuild?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/msbuild.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/msbuild.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment] 2019-07-30 15:16
The task docs can be improved as they still have some remnants of earlier version of the editor. Have you tried opening the task assistant in the YAML editor for your pipeline, and select the field that you need?

![image](https://user-images.githubusercontent.com/27018975/62141971-7dc1eb80-b2bb-11e9-961e-dfaf79c37d1c.png)

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
