### ISSUE TITLE
Linux agent assumes linux-x64

### ISSUE THREAD

**Issue by fernandreu** [MicrosoftDocs/azure-devops-docs#5777] opened 2019-09-29 14:15 UTC
I am doing some tests setting up a Raspberry Pi 4 as an agent through this page. The docker image builds fine, but the run command fails with the error message:

```
./config.sh: line 85: ./bin/Agent.Listener: cannot execute binary file: Exec format error
```

It turns out the start.sh script is assuming a `linux-x64` platform when downloading the agent:

```
AZP_AGENT_RESPONSE=$(curl -LsS \
  -u user:$(cat "$AZP_TOKEN_FILE") \
  -H 'Accept:application/json;api-version=3.0-preview' \
  "$AZP_URL/_apis/distributedtask/packages/agent?platform=linux-x64")
```

If I change the last part to `platform=linux-arm`, the error is gone.

I think it is worth at least adding a comment that you might need to change that line depending on your architecture. Either that, or having some logic in the start.sh script itself to detect the right URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
