### ISSUE TITLE
Configuring Task

### ISSUE THREAD

**Issue by jbburf** [MicrosoftDocs/azure-devops-docs#6620] opened 2019-12-09 19:13 UTC
I'm trying to move local Xcode builds to azure's cloud pipeline but I've found the documentation to be extremely shallow. I am specifically trying to build without signing but nothing in the above documentation explains how to configure this task. Multiple options above are not available in the actual task (using the latest @5 version in Azure Devops). Things in the documentation are extremely poorly described, for example the Configuration field. What is this configuring? I see that best practice is to use a variable, but what should it say? What are the options? What am I actually configuring here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff158626-303c-b9aa-0507-50f9b898e364
* Version Independent ID: cf4561a9-40fa-af57-0e29-75cd339d7b7b
* Content: [Xcode Build build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xcode-build?view=tfs-2018&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/pipelines/tasks/build/xcode-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/xcode-build.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment] 2019-12-10 03:42
@jbburf Thank you for the feedback, assigning this to the author for review.

Please see [Build, test, and deploy Xcode apps](https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode?view=azure-devops) for further guidance.

A similar concern was also posted with https://github.com/Microsoft/azure-pipelines-tasks/issues/8845.

**Comment by jbburf** [comment] 2019-12-10 18:26
I've already reviewed [that link](https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode?view=azure-devops) and it was not helpful either. Issue [#8845](https://github.com/microsoft/azure-pipelines-tasks/issues/8845) seems unrelated.

**Comment by MrDEV0** [comment] 2020-01-15 12:49
Hi, how can I can use Automatic Signing while building iOS project on Azure cloud? I believe it should be a place to add the Apple Developer account and define the team.

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
