### ISSUE TITLE
Adding tools and customizing the container -- expand please

### ISSUE THREAD

**Issue by ppumkin** [MicrosoftDocs/azure-devops-docs#5924] opened 2019-10-10 07:22 UTC
Hi - I am a newb and there are others that may need guidance on this page to prompt that we probably need to install tooling required as we need it before the agent becomes any use right?
We need to install like visual studio and or dot net core before the capabilities of the agent are of any use.
Can you please make a short paragraph explaining this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2019-10-10 17:39
@ppumkin Thank you for the feedback, assigning this to the author for review.

**Comment by hendriksteinhorst** [comment] 2020-04-01 19:03
I got it to install dotnet core just by adding the following lines (from [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#examples)) in start.ps1
`
  Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1';
  ./dotnet-install.ps1 -InstallDir '~/.dotnet' -Version '3.1.201';
`
Just after 
`Expand-Archive -Path "agent.zip" -DestinationPath "\azp\agent"` (line 42).
You maybe have to adjust the dotnet core version that is downloaded.

I think this way you can download and install any other tool.

Hope this helps,

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
