### ISSUE TITLE
DownloadPipelineArtifact@2 - YAML not consistent with parameter table

### ISSUE THREAD

**Issue by tillig** [MicrosoftDocs/azure-devops-docs#5505] opened 2019-09-05 22:27 UTC
The YAML snippet shows the following inputs for `DownloadPipelineArtifact@2`:

- `buildType`
- `project`
- `definition`
- `specificBuildWithTriggering`
- `buildVersionToDownload`
- `branchName`
- `pipelineId`
- `tags`
- `artifactName`
- `itemPattern`
- `targetPath`

However, the table below it lists:

- `source`
- `preferTriggeringPipeline`
- `artifact`
- `patterns`
- `path`
- `project`
- `pipeline`
- `runVersion`
- `runBranch`
- `runId`

It's like there was a copy/paste error or something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by tillig** [comment] 2019-09-05 22:28
`tags` is also described as "coma-delimited" which is either a typo or a really, really long time between tags. :)

**Comment by ShadowXVII** [comment] 2020-02-12 05:32
Looks like it's been updated now. The old terms have become aliases in the table.

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
