### ISSUE TITLE
Expand Parallel jobs section

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/azure-devops-docs#3315] opened 2019-02-11 09:02 UTC
The remark at https://docs.travis-ci.com/user/build-stages/#data-persistence-between-stages-and-jobs is very essential and without that it is very misleading/confusing on how such a simplified pipeline would really work in practice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035d0e47-a927-1e99-34a4-181e34578af3
* Version Independent ID: ab6853d8-98cf-dd68-7425-4644cc7e0492
* Content: [Migrate from Travis to Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-travis?view=azure-devops#git-submodules)
* Content Source: [docs/pipelines/migrate/from-travis.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/migrate/from-travis.md)
* Product: **devops**
* GitHub Login: @ethomson
* Microsoft Alias: **ethomson**

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
