### ISSUE TITLE
Single job syntax

### ISSUE THREAD

**Issue by fcooper8472** [MicrosoftDocs/azure-devops-docs#4149] opened 2019-05-06 12:37 UTC
I have attempted to use the single job syntax as specified:
```
job: myJob
timeoutInMinutes: 10
pool:
  vmImage: 'ubuntu-16.04'
steps:
- bash: echo "Hello world"
```
but get the following errors when running a build:
```
/azure-pipelines.yml (Line: 14, Col: 1): Unexpected value 'job'
/azure-pipelines.yml (Line: 15, Col: 1): Unexpected value 'timeoutInMinutes'
```
The syntax I have used appears to be identical to the instructions on this page.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54bf6c2f-95c1-943d-26ae-d7099143bccf
* Version Independent ID: 0833bb55-1e54-6953-ee69-de6d191d2ec1
* Content: [Jobs in Azure Pipelines, Azure DevOps Sever, and TFS - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
