### ISSUE TITLE
I have facing problem complete/K8sDeploy.yaml

### ISSUE THREAD

**Issue by BalajiAnand** [MicrosoftDocs/azure-devops-docs#1713] opened 2018-09-12 14:47 UTC
For Files to archive enter the relative path to the Kubernetes YAML deployment file: complete/K8sDeploy.yaml.
 While implementing this procedure it throws an error in  Files to archive (complete/K8sDeploy.yaml’ doesn’t match anything: ‘complete’ exists but not ‘complete/K8sDeploy.yaml’) because there is no YAML file in that path. But you give a procedure for in VSTS to create K8sDeploy.yaml. For Jenkins how can I get it into inside? that file. I am struggling for this couple of days. Kindly give solution for this issue. I am waiting for your reply.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae027d8-bc05-bb24-dcc8-f57a9b84410f
* Version Independent ID: 3a7c4e39-5807-db02-c0ad-356aab27fbfb
* Content: [Deploy to Kubernetes on Azure Container Service (AKS) with Jenkins CI and Azure Pipelines CD](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/integrate-jenkins-vsts-aks?view=vsts)
* Content Source: [docs/pipelines/release/integrate-jenkins-vsts-aks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/integrate-jenkins-vsts-aks.md)
* Product: **devops**
* GitHub Login: @nicolela
* Microsoft Alias: **nicolela**

**Comment by alexhomer1** [comment] 2018-09-13 13:47
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by azooinmyluggage** [comment] 2019-01-21 12:53
@BalajiAnand can you please add more details about the scenario. It will be great to know the folder structure and the logs of the release.

**Comment by srivatsamarichi** [comment] 2019-10-04 07:45
@BalajiAnand Can you please confirm if you have configured the sample app to include a YAML file for deploying to your AKS cluster? It seems you might have missed the step for which you're seeing the aforementioned error. If you have not, then would suggest you to please create one and then follow the rest of the article. You can find the link [here](https://github.com/spring-guides/gs-spring-boot-docker) to create one.

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
