### ISSUE TITLE
sudo docker is still the old docker

### ISSUE THREAD

**Issue by xmnlab** [MicrosoftDocs/azure-devops-docs#5479] opened 2019-09-04 14:40 UTC
I installed the docker as described in the documentation and it seems it worked very well.

but I need to run a command using sudo .. and that runs docker (maybe using also sudo docker) .. but the docker reached is the old docker ... is there any workaround for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e363794a-15bb-94f5-5a0f-021a5b068d2f
* Version Independent ID: 262421e1-9598-fa0c-74f3-ad8baf56374e
* Content: [Docker Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/docker-installer?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/docker-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/docker-installer.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment] 2019-09-04 19:01
@xmnlab  Thank you for the question.

Please try finding the location of the docker daemon and running it using the absolute path. 

The code uses `azure-pipelines-tool-lib/tool` but I'm not familiar with .ts files.

**Comment by xmnlab** [comment] 2019-09-04 20:55
hey @msebolt thanks for the feedback.

just to add more details: the command I am running is `minikube start --vm-driver=none` .. using `--vm-driver=none` needs `sudo` to run ... and internally it runs `sudo docker .. `

as it is a binary .. I cannot change this call .. as you can see in this example: https://github.com/kubernetes/minikube/blob/master/pkg/minikube/cruntime/docker.go#L87

**Comment by xmnlab** [comment] 2019-09-09 21:17
@shashankbarsin any idea about this?

**Comment by kcpevey** [comment] 2019-09-23 13:26
@shashankbarsin Any suggestions here?

**Comment by thiagopri** [comment] 2020-01-08 17:10
Hi @msebolt,

I'm just following up on this since I'm having the same issue. Did you have a chance to look into it? I'm wondering if the DockerInstaller task shouldn't replace the existing docker (default path) to avoid this issue. Thoughts? 

Thanks.

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
