### ISSUE TITLE
Argument "Working folder with package.json" is confusing

### ISSUE THREAD

**Issue by rguthriemsft** [MicrosoftDocs/azure-devops-docs#2361] opened 2018-11-06 21:45 UTC
The description is accurate "Path to the folder containing the target package.json and .npmrc files. Select the folder, not the file e.g. "/packages/mypackage"." but the Argument value is confusing as you are supposed to point to the folder and not the package.json file.  It would be good to clean up argument so its obvious you don't point to package.json but the folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c00d3b8-64c1-9f1b-83f8-62d8cf07817b
* Version Independent ID: 5fcdebed-cfb8-c5a6-d807-1315b2db5e57
* Content: [npm task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm?view=vsts)
* Content Source: [docs/pipelines/tasks/package/npm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/npm.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment] 2019-07-01 19:43
Apologies for the very delayed response. Heads up to @chasewilson

**Comment by Mexicoder** [comment] 2019-10-23 21:14
This would be nice if it was updated to be more clear. Also when I use this I get errors is I have a leading '/'.

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
