### ISSUE TITLE
LinuxFxVersion and DOCKER_CUSTOM_IMAGE_NAME

### ISSUE THREAD

**Issue by mslot** [MicrosoftDocs/azure-devops-docs#7391] opened 2020-02-25 16:18 UTC
I can see that both are set during deploy, but ehy both? I can easily deploy and get an image pulled with only one of them set, if I choose to set one of them through an ARM template. I can't find any info anywhere on these two entities. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:31
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:31 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug

**Comment by mslot** [comment] 2020-11-27 08:51
@cxwtool i have specifically requested info on the subject, because i cant find anything about it in the docs, so is there more info on this in the docs, or dont we want to include more info on the subject?

I cant see why we should close this, because i actually see it as relevant info to know when doing deployment through ARM.
