### ISSUE TITLE
Missing nuget example

### ISSUE THREAD

**Issue by miles1302** [MicrosoftDocs/azure-devops-docs#5003] opened 2019-07-25 07:48 UTC
would also be helpfull with a nuget example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/index?view=azure-devops#feedback)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by guillaume86** [comment] 2019-07-25 18:38
Not really practical without wildcard support in keys (need to list all packages.config / csproj files), I guess they are waiting for if before adding the Nuget example.

**Comment by dammejed** [comment] 2019-08-02 01:14
Presumably this will require https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-packages to be available, since there isn't currently in-box support for a single 'package.lock' analog, similar to yarn and npm.

However, one could probably come pretty close if relying on the [Microsoft.Build.CentralPackageVersions](https://github.com/Microsoft/MSBuildSdks/tree/master/src/CentralPackageVersions#microsoftbuildcentralpackageversions) nuget package. Once you set up a solution with a `Packages.props` file, that file could act as the key, with the version numbers centrally managed. It's not a perfect translation, since transitive dependency versions aren't required to be mentioned, but I _think_ it would get the job done in a CI scenario.

I sketched out what the tasks would presumably look like, but I haven't been able to test because this update isn't yet deployed on my tenant of choice.

```yaml
variables:
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget

steps:
- task: CacheBeta@0
  inputs:
    key: |
      nuget
      $(Build.SourcesDirectory)/Package.props
    path: $(NUGET_PACKAGES)
  displayName: Cache nuget packages

- task: NuGetCommand@2
  displayName: 'NuGet restore **/*.sln'
  inputs:
    restoreSolution: '**/*.sln'
```

Note that this requires usage of `<PackageReference>` in all projects, since this restores packages to the global cache at `$(NUGET_PACKAGES)`

**Comment by RehanSaeed** [comment] 2019-08-04 08:58
Why couldn't you cache the entire `C:\Users\[username]\.nuget\packages` directory?

**Comment by dammejed** [comment] 2019-08-04 13:13
The existing document's guidance recommends caching directories within the `$(Pipeline.Workspace)`, so I incorporated that into my example. If pipeline caching can work in any directory, I suppose caching a user directory would work, but some downsides that come to mind:
1. It's definitely not cross platform, so wouldn't work on a Linux agent (if you changed my example to restore using the dotnet cli, for instance)
2. It would require that you know the user principle that will be used to execute the jobs, and that this is the same for all agents, and won't change.

Given that, setting the directory using the already-available environment variable certainly seems more robust.

**Comment by richardgavel** [comment] 2019-08-05 21:24
@RehanSaeed. Because once created, cache contents are immutable (See above). You need a method to determine whether to rebuild the cache.

One option (short of using centralized versions), is to generate a string containing all the distinct PackageReference and/or packages.config entries in sorted order and use a hash as the cache key,

**Comment by dammejed** [comment] 2019-08-16 03:24
I see that a Nuget example has been added now, but I feel it's misleading. `packages.lock.json` is only available at the _project level_ right now. This might work for single-project solutions, but I doubt this is the norm for .Net applications.

**Comment by alanwales** [comment] 2019-08-16 11:37
To generate the key I wrote a powershell script to grab all of the NuGet package references from a solution (below) and run this powershell script in the pipeline before the cache task. It's working using the sample above with NUGET_PACKAGES variable set to $(Pipeline.Workspace)/.nuget/packages

==================== Yaml pipeline
    - task: CacheBeta@0
      displayName: 'Restore cache'
      inputs:
        key: 'scripts/packages.txt'
        path: '$(NUGET_PACKAGES)'

==================== Create-Solution-Nuget-Packages-Hash.ps1
param
(
    [string] $solutionPath=$(throw "The solution path is required"),
	[string] $outputFilePath="$PSScriptRoot/packages.txt"
)

if(!(Test-Path $solutionPath)) {
    Throw [System.IO.FileNotFoundException] "No solution file was found at $solutionPath"
}

Set-Location -Path (get-item $solutionPath).Directory
$projectList = Get-Content $solutionPath | where { $_ -Match  ".csproj" } | where { $_ -match "Project.+, ""(.+)""," } | foreach { $matches[1] } | % { Get-Content $_ }
$nugetPackageList = [System.Collections.Generic.List[string]]::new()

foreach($i in $($projectList -split "`r`n")){
    if($i -match "<PackageReference"){
        $nugetPackageList.Add($i)
    }    
}

$nugetPackageList = $nugetPackageList | Sort-Object -Unique

Write-Host "NuGet packages:"
Write-Host "=============="
Write-Host $nugetPackageList
Write-Host "=============="

Set-Content -Path "$outputFilePath" -Value $nugetPackageList -Force

Write-Host "Wrote list of NuGet packages to $outputFilePath"

**Comment by alanwales** [comment] 2019-08-16 11:39
In case it's not obvious the sample for powershell yaml is below but in reality I use the Agent.TempDirectory

    - task: PowerShell@2
      inputs:
        filePath: 'scripts/Create-Solution-Nuget-Packages-Hash.ps1'
        arguments: '-solutionPath "Test.sln" -outputFilePath "scripts/packages.txt"'
        failOnStderr: true
        pwsh: true

**Comment by MisinformedDNA** [comment] 2019-08-16 20:03
@dammejed @alanwales Comparing to the Maven example, would this not work?

```yaml
- task: CacheBeta@0
  inputs:
    key: nuget | **/packages.lock.json
    path: $(NUGET_PACKAGES)
  displayName: Cache NuGet packages
```

**Comment by alanwales** [comment] 2019-08-17 07:05
Thanks for the tip, was not aware of this, looks like an easy option to add to projects

https://devblogs.microsoft.com/nuget/enable-repeatable-package-restores-using-a-lock-file/

Would be great to have a version of the task that is package ecosystem aware eg a select box with ‘npm,nuget,yarn,custom’ with some logic in each option like ‘use lock file’ or ‘use package references in solution file’ etc?

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
