### ISSUE TITLE
More details about CI/CD setup

### ISSUE THREAD

**Issue by FixRM** [MicrosoftDocs/azure-devops-docs#5148] opened 2019-08-06 11:05 UTC
@ethomson, can you please provide more details on that? How and there do you do version bump, what automatons are done when you push PR's or do merges to different branches, etc.? What about the tags? The only environment mentioned here is the production. What about manual testing to make sure UI bug has gone of visuals are fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1235ec4-e7e9-b0c2-8f1f-ee9682175a05
* Version Independent ID: a473750a-fbb6-4eed-e0e6-34e8a5009507
* Content: [Release Flow - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2frelease-flow.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2frelease-flow.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **ethomson**

**Comment by WilliamAntonRohm** [comment] 2019-08-08 23:14
@FixRM -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by FixRM** [comment] 2019-08-09 04:36
There is no special topic here. This article is about DevOps at Microsoft but no details provided about actual CI/CD setup for this branching strategy

**Comment by WilliamAntonRohm** [comment] 2019-08-20 16:53
@FixRM -- Artem, thank you for your additional feedback.

**Comment by murraj** [comment] 2019-09-16 13:36
Is there an update to this topic? We are also curious as to how the CI/CD setup is.  In our case, we have three environments: DEV, QA, and PROD. Our first thought is that the master branch build gets deployed to DEV and that release branches get deployed to QA and then PROD if they pass testing. Hot fixes would get pushed to both DEV and QA via the merging of the pull requests / cherry picking. However, is there a way to do this with "static" definitions of build and release pipelines or will we have to create a new build / release pipeline for each release since the names change from release to release (releases/M129, releases/M130, etc).  Ideally, we would like one build definition and one release definition that would handle all of our branches (master or release).

**Comment by FixRM** [comment] 2019-09-16 15:06
@murraj, branch filters can include wildcards. For exp you can use `/releases/*` and it will trigger for any release branch.

What I didn't understand is how to release a hotfix v1.1 in case when there is buggy v2.0 in QA already. Do we need more QA's in this case or this situation is really so rare that I shouldn't care on that?

**Comment by murraj** [comment] 2019-09-16 16:23
In our case, we plan to only have on QA environment for now. If v2.0 is already in QA and we have to do a hotfix for v1.1, then the hotfix will get pushed to QA (overwriting v2.0).  Once v1.1 is tested and pushed to PROD, then we would revert QA to buggy v2.0.  We also have a "prod support" environment where we could put v1.1 if QA ended up not being an option.

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri1, devops-learn/tech, devops/prod, doc-bug
