### ISSUE TITLE
Azure Data Explorer service connection

### ISSUE THREAD

**Issue by pemj** [MicrosoftDocs/azure-devops-docs#6879] opened 2020-01-09 21:54 UTC
I'm currently trying to prototype some release gates in an Azure pipeline that make queries to Azure Data Explorer. To make use of an ADX Query Gate, I need to fill in a Service endpoint field. When I try to use the +New button to access the New service connection dialog (or when I go to the Create new service connection button in the Project Settings menu), I get a prompt that requests a lot of information, and a Learn More link that leads to this page. I don't see a link in the "Common service connection types" section that describes the process of making an ADX service connection. If the Learn More link is going to lead here, it seems like there should be something here that lets me learn more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
