### ISSUE TITLE
Add Version for Azure Devops Server 2019 for TFS Build agents and Controller.

### ISSUE THREAD

**Issue by mmj78** [MicrosoftDocs/azure-devops-docs#3781] opened 2019-03-26 18:02 UTC
Can this documentation add the section for Azure Devops Server 2019 in the "TFS Build agents and Controller" section. It is missing this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84ec61ca-02ef-740d-d9a3-98f088e3f27d
* Version Independent ID: d5ed9d97-9db5-9d9e-70ed-414093d79fa9
* Content: [Look up version compatibility for Azure DevOps clients - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/server/compatibility?view=azure-devops#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fcompatibility.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fcompatibility.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Git Login: **aaronhallberg**
* Microsoft Alias: **aaronha**

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri2, devops-server/prod
