### ISSUE TITLE
Microsoft Hosted agents do not seem to contain multiple node versions as advertised

### ISSUE THREAD

**Issue by bweggersen** [MicrosoftDocs/azure-devops-docs#6181] opened 2019-10-29 17:02 UTC
Under the section `Check for Latest Version` it seems to suggest that if we are using Microsoft-hosted agents we can leave this option blank, in combination with a wide version range, to re-use node versions already installed on the agent. [The documentation on software pre-installed on `macos-latest`](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md), for instance, includes node versions: v6.17.1 v8.16.2 v10.16.3 and v12.12.0. We are, however, not able to find any node versions on that agent, other than v6.17.0, even with a wide range such as "10.x":

```
      - task: NodeTool@0
        displayName: "Install Node"
        inputs:
          versionSpec: "10.x"
          checkLatest: false
```

If we run the above in debug mode, we get the following log. When I compare this with the code of the task, it looks like the first `evaluating 0 versions` is the return from the local query and the `evaluating 381 versions` is the result of an online query (from nodejs.org).

```
##[debug]versionSpec=10.x
##[debug]checkLatest=false
##[debug]isExplicit: null
##[debug]explicit? false
##[debug]isExplicit: null
##[debug]explicit? false
##[debug]Agent.Version=2.159.2
##[debug]Agent.ToolsDirectory=D:\a\_tool
##[debug]evaluating 0 versions
##[debug]match not found
##[debug]isExplicit: null
##[debug]explicit? false
##[debug]evaluating 381 versions
##[debug]matched: v10.17.0
##[debug]isExplicit: 10.17.0
##[debug]explicit? true
```

This is an issue for us as http://nodejs.org is sometimes down, and it's adding unnecessary build time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb95406-322e-11db-41e0-7b8064c8295c
* Version Independent ID: 57fb95a8-385d-7548-ee6a-9a3a875a150e
* Content: [Node.js Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/node-js.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/node-js.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
