### ISSUE TITLE
appSettings vs configurationStrings

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/azure-devops-docs#8098] opened 2020-04-27 12:49 UTC
What's the different between the two?
Where do slot specific settings come in?
Azure portal shows "connectionStrings" section as well - what does that correlate to?
Trying to correlate these different terms is currently a bit of a mess

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4756ed74-d7d5-d4db-6e72-71f2910f7e1f
* Version Independent ID: 2413f407-8624-7843-a910-c610bd317319
* Content: [Azure Web App for Container task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-containers?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-containers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-containers.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by msebolt** [comment] 2020-04-28 16:42
@dazinator Thank you for the question.

According to the [reference](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureWebAppContainerV1) `appSettings` are provided for your application on startup and `configurationSettings` are used for the task container.

I can assign this to the author for further confirmation and to clarify this information to the article.

**Comment by dazinator** [comment] 2020-04-28 17:51
@msebolt - thanks, that's confused me a little more - the ms docs page I created this issue form refers to `configurationStrings` as the argument, and you've now referenced a page that shows `configurationSettings` not `configurationStrings`..

Yes if this can be clarified that would be great, thank you.

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, doc-enhancement
