### ISSUE TITLE
Documentation for base URL

### ISSUE THREAD

**Issue by jrm346** [MicrosoftDocs/azure-devops-docs#5452] opened 2019-09-02 14:09 UTC
Hi,

Its not very clear to me how to set up a connection top the specific resource i'm testing. e.g. how do i set the connection so that it sends the request to a web app in the resource group. Also, how can i set the connection so that it sends the request to an API Management instance in a resource group?

thanks.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bc6da4-5a1e-5989-f4f0-27465953b5fd
* Version Independent ID: fd12f976-5d3b-3b1b-3d0a-a0bf2a60c961
* Content: [Invoke HTTP REST API task - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/http-rest-api.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by gotmike** [comment] 2019-09-18 18:20
i agree. the section that covers `arguments` should more clearly indicate that the user must set up a `generic service connection` and link to this page --> https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri2, devops-cicd/tech, devops/prod
