### ISSUE TITLE
Zipalign Options > Link settings > Parameters.zipalign

### ISSUE THREAD

**Issue by onemanarmy0182** [MicrosoftDocs/azure-devops-docs#1915] opened 2018-09-28 15:31 UTC
Can you provide documentation on how to use this setting? I'm looking for ways to modify the name of the output file of the zip aligned apk. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b1fbcd8-d799-879e-d672-9dee164401ef
* Version Independent ID: 7208d03d-9042-7753-ab4d-d1ad8e99ef1d
* Content: [Android signing build and release task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/android-signing?view=vsts#arguments)
* Content Source: [docs/pipelines/tasks/build/android-signing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/android-signing.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment] 2019-03-10 18:44
Keep-alive

**Comment by jvhgamer** [comment] 2019-06-27 23:56
@davidstaheli any news on this? Likewise- having issues booting Xamarin Android apps from Azure DevOps. Can build, sign, release, etc. fine from VS2019 but when building and signing through a hosted VS2019 the apk launches and reports "App keeps stopping". We have no idea how to debug this issue! Any ideas on this front either?

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
