### ISSUE TITLE
Initialize Job step doesn't list all current variables values anymore

### ISSUE THREAD

**Issue by Gismork** [MicrosoftDocs/azure-devops-docs#8331] opened 2020-05-14 17:30 UTC
Hello,

It's seems we can't see all variables value used by agent job when we click on a build step "Initialize Job step" in a classic build.
Tested today on a Azure DevOps online organisation with Self-hosted agent (agent version: '2.166.4') and Microsoft-hosted agent (agent version: '2.168.2').
system.debug flag is enabled.

Is this a bug that should be fixed to match the documentation or should the documentation be updated to match current behavior ?

Initialize Job step screenshot on Microsoft Hosted Agent:
![image](https://user-images.githubusercontent.com/2140163/81966256-8ea8d700-9619-11ea-8fe3-157e78ac76ab.png)

Initialize Job step screenshot on Self Hosted Agent:
![image](https://user-images.githubusercontent.com/2140163/81966394-ca43a100-9619-11ea-8043-07eb9aa6f7cb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#view-vars)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-cicd-release/tech, devops/prod, doc-bug
