### ISSUE TITLE
Normalize nomenclature

### ISSUE THREAD

**Issue by thecoolestname36** [MicrosoftDocs/azure-devops-docs#8239] opened 2020-05-07 14:44 UTC
The wording "select the version at the time of release creation" is slightly different when creating a build artifact in ADO, it is worded as "specify at the time of release creation" and should be updated for SEO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598465e1-85d4-4961-b8b6-902d6026c5e3
* Version Independent ID: 5ef1308a-3aeb-fcc4-dec7-6f10785612a3
* Content: [Release artifacts and artifact sources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri1, devops-cicd-release/tech, devops/prod, doc-enhancement
