### ISSUE TITLE
rootDirectory input parameter default?

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/azure-devops-docs#7373] opened 2020-02-22 18:55 UTC
Please document the default value for the rootDirectory input parameter 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ea8b7b-44cb-e315-b086-c4e3361bf59a
* Version Independent ID: 5fcdaa72-ca89-2139-a8c9-2eb263b4824e
* Content: [FTP Upload task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/ftp-upload?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/ftp-upload.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/ftp-upload.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by cxwtool** [comment] 2020-11-24 23:31
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:31 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug

**Comment by HughDevlin** [comment] 2020-12-02 21:05
Please re-open this issue.

Please document the default value for the rootDirectory argument.
