### ISSUE TITLE
Does not work on Mac?

### ISSUE THREAD

**Issue by janpio** [MicrosoftDocs/azure-devops-docs#2441] opened 2018-11-14 14:10 UTC
Is it correct that this task does not work on `vmImage: 'macOS-10.13'` and you can only use the [already installed ruby version](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-Readme.md#language-and-runtime) there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02568f8b-6928-c8f1-178a-79e4cb0d93e2
* Version Independent ID: 1107622c-4165-dcff-741a-279757b35323
* Content: [Use Ruby Version task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-ruby-version?view=vsts)
* Content Source: [docs/pipelines/tasks/tool/use-ruby-version.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/use-ruby-version.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by janpio** [comment] 2019-03-01 09:52
Assigned, but no progress or response yet.

**Comment by janpio** [comment] 2019-07-18 18:41
Hello? Still getting errors here:

```
[command]/usr/bin/sudo ln -sf /Users/vsts/hostedtoolcache/Ruby/2.6.2/x64/bin/ruby /usr/bin/ruby
ln: /usr/bin/ruby: Operation not permitted
Prepending PATH environment variable with directory: /Users/vsts/hostedtoolcache/Ruby/2.6.2/x64/bin
```

Pool: Hosted macOS High Sierra

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
