### ISSUE TITLE
The steps to "Add State Sort Order" are out of date/incorrect

### ISSUE THREAD

**Issue by jonathanpmast** [MicrosoftDocs/azure-devops-docs#7289] opened 2020-02-14 14:44 UTC
This document assume the "State Category" field is available in all default shared views in Azure Devops.  In order to follow this tutorial we had to go and create a Shared View with the State Category field added.  Otherwise it does not show up in PowerBI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71c046b7-9bc7-2b63-9401-72af0e1a577e
* Version Independent ID: d9d85ca9-74ba-63bd-0edf-8f95754d4991
* Content: [Add a time-in-state measure to a Power BI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/create-timeinstate-report?view=azure-devops#feedback)
* Content Source: [docs/report/powerbi/create-timeinstate-report.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/create-timeinstate-report.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @thomps23
* Microsoft Alias: **kaelli**

**Comment by cxwtool** [comment] 2020-11-24 23:31
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri2, devops-analytics/tech, devops/prod, doc-bug
