### ISSUE TITLE
Python builds don't work and there is no anonymous access to badges.

### ISSUE THREAD

**Issue by rscottwatson** [MicrosoftDocs/azure-devops-docs#8243] opened 2020-05-07 21:34 UTC
Following your example for python produced a pipeline that fails in the pytest step in all versions.  I believe there is also a problem with the wheel package missing from the requirements.  The last issue I found was that there doesn't seem to be any option for anonymous access to badges in the setting under pipelines.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=python%2Cyaml%2Cbrowser%2Ctfs-2018-2)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by rscottwatson** [comment] 2020-05-07 22:12
I am not sure if this is the right solution but I added wheel==0.34.2 as the first line of the requirements.txt and I also changed the test_test1.py to be 
`def test_printmessage():
    print('Hello World')`

now my builds are working.

**Comment by rscottwatson** [comment] 2020-05-08 17:00
I forgot I also had to create a file called pytest.ini with the following

[pytest]
junit_family=xunit1

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
