### ISSUE TITLE
Windowss Docker Agent start.ps1 is incorrect

### ISSUE THREAD

**Issue by adminnz** [MicrosoftDocs/azure-devops-docs#6882] opened 2020-01-10 03:49 UTC
When running the windows docker container it fails with lots of errors from the start.ps1 script.

2. Downloading and installing Azure Pipelines agent...
Exception calling "DownloadFile" with "2" argument(s): "Value cannot be null.
Parameter name: address"
At C:\azp\start.ps1:45 char:34
+ $wc.DownloadFile($packageUrl, "$(Get-Location)\agent.zip")
+                                  ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

Expand-Archive : The path 'agent.zip' either does not exist or is not a valid
file system path.
At C:\azp\start.ps1:47 char:1
+ Expand-Archive -Path "agent.zip" -DestinationPath "\azp\agent"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (agent.zip:String) [Expand-Arch
   ive], InvalidOperationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive

3. Configuring Azure Pipelines agent...
Cleanup. Removing Azure Pipelines agent...
.\config.cmd : The term '.\config.cmd' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\azp\start.ps1:73 char:3
+   .\config.cmd remove --unattended `
+   ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\config.cmd:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

.\config.cmd : The term '.\config.cmd' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\azp\start.ps1:53 char:3
+   .\config.cmd --unattended `
+   ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\config.cmd:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2020-01-10 18:23
@adminnz Thank you for the feedback, assigning this to the author for review.

**Comment by bernieatwar** [comment] 2020-02-20 14:15
I'd love this use this dockerfile, any updates on fixes or work around those issues?

**Comment by jacksonstaub16** [comment] 2020-03-09 22:43
Hi any luck with an update to the ps1 file? This issue is still occurs for me

**Comment by sudmis** [comment] 2020-04-17 15:02
any update, i am also facing similar issue

**Comment by atedsimple** [comment] 2020-05-16 08:57
You need to enable TLS 1.2 by adding the following line to the top of your Start.ps1 script
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug

**Comment by Mr-Silv** [comment] 2021-11-30 13:59
For those encountering this issue, can you try with a Base64 encoded PAT
https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#use-a-pat
