### ISSUE TITLE
dependencies statement seems to pull value from first stage only if there are multiple stages in a deployment.

### ISSUE THREAD

**Issue by ossentoo** [MicrosoftDocs/azure-devops-docs#5786] opened 2019-09-30 12:57 UTC
We have a yaml deployment that uses multiple stages and the dependencies statement within a job (that is a child of the stage).

It seems to me that if the **dependencies** statement is used in this scenario, then the statement doesn't appear to be scoped to only pull values from the current stage.  It seems to also pull values from the previous stages too.

This means, that if we have stages DEV, UAT and PRD, when a task is run in the UAT stage to pull dependencies.A.task.name value from a previous job, it may reference values from DEV.dependencies.A.task.name, rather than from UAT.dependencies.A.task.name

Please clarify whether this is expected behaviour and document as such.

This documentation isn't clear. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
