### ISSUE TITLE
Documented API version is out of date

### ISSUE THREAD

**Issue by sobjornstad** [MicrosoftDocs/azure-devops-docs#3091] opened 2019-01-22 17:37 UTC
The 2.0 version of the API documented here is not the newest available in TFS 2018 R3. The schema is very different in this undocumented $nextversion -- build steps are now under `process` rather than `build` for instance. Moreover, several things available in my web interface are missing entirely from the 2.0 API, like phases, conditions on build steps, and the "Allow scripts to access OAuth token" option on phases.

When I tried inspecting the request sent by the TFS web interface, the web interface does not appear to use an API version number in its requests, so I don't know how far out of date the documentation is and I can't determine what version I should use to switch over to the new schema.

Not having the most recent version available is causing a bug in my PowerShell script: when I retrieve some build definitions, update them, and PUT them back on the server, fields that are not part of the new schema are reset to their defaults even though I didn't change them (since I didn't *have* them). Please locate the appropriate documentation and update when possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f529434d-92f5-9208-8c7c-9d4a75039e32
* Version Independent ID: 4f1c55c4-094c-b43c-40b7-08a903cfeb71
* Content: [Build Definitions](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/build/definitions?view=tfs-2018)
* Content Source: [docs/integrate/previous-apis/build/definitions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/build/definitions.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment] 2019-02-07 15:36
Hi @sobjornstad , if you're using TFS, you should be able to use 4.1, which has auto generated docs here:
https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-4.1#api-and-tfs-version-mapping

Is that not applicable to you?

**Comment by sobjornstad** [comment] 2019-02-08 21:41
I haven't gotten a chance to try upgrading my code yet, but I expect this will work.

I'm still frustrated that the old documentation says it's applicable to TFS 2018 but is actually much older than that, though. I understand you probably don't want to put a lot of effort into fixing up documentation for an old version of TFS, but maybe you could add a banner pointing this out or something?

I know there's this note, which is good:

![image](https://user-images.githubusercontent.com/2313414/52507570-87458300-2bb7-11e9-8ef9-5c5350fd00e0.png)

But the content in these old docs doesn't align at all with the table in the link you just gave me:

![image](https://user-images.githubusercontent.com/2313414/52507605-9f1d0700-2bb7-11e9-8da4-b8a0ed1b4ca1.png)

For instance, say I were still using TFS 2018 R1, which is the last version that the "Note" says is covered under the old APIs. I would thus select "Team Foundation Server 2018" from the drop-down on the old docs. In the Git section, I would still be getting the 2.0 APIs, which properly belong to TFS *2015* according to the table. That's very misleading, so at least a warning to users seems appropriate.

**Comment by sobjornstad** [comment] 2019-02-08 21:44
This is closely related to #1870.

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-ecosystem/tech, devops/prod
