### ISSUE TITLE
Task groups extracted parameters from Tasks

### ISSUE THREAD

**Issue by dipti927** [MicrosoftDocs/azure-devops-docs#1593] opened 2018-08-24 09:25 UTC
As per the article, When creating task group from tasks so it automatically extracts variables from tasks and converted into parameters, and variables values will be the parameters default value.. 

But it is not working in my case, when i am trying to create it using variables $(MyVariable),variables values do not extract and become a default value for task group parameters.

In fact, i have to add the default value for the parameters, which will pass to task arguments where actually defined variables.

Any help would be appreciated.

Thanks,
Dipti Mamidala

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6b773c-dfb0-5c58-1463-e9b865d73af6
* Version Independent ID: 83f332ed-719a-5347-acd8-bfe3bdb397b4
* Content: [Task Groups in VSTS and Team Foundation Server](https://docs.microsoft.com/en-us/vsts/pipelines/library/task-groups?view=vsts)
* Content Source: [docs/pipelines/library/task-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/task-groups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment] 2018-08-24 11:05
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by romantitov** [comment] 2019-03-06 15:14
I have the same issue.

**Comment by joshuadavidson** [comment] 2019-04-02 20:10
I have the same issue when using a task group in Deployment group job. When I use the same task group in an Agent job the parameters come through correctly. This is a major bug and makes task groups within Deployment group jobs unusable.

**Comment by AaronDWong** [comment] 2019-04-03 15:03
I have the same issue when deploying an Azure Stream Analytics task, I use a Powershell script to retrieve a policy key as first step and use it on the ASA deployment, tried:
- Giving it a default falue.
- Modifying the json script of the task group to make the the parameter optional.
- Take out the variable from the json script of the task group.

Neither work, when giving it a default/optional value it just hardcode the default/blank values and do not accept the new value from the powershell script. Taking out the variable doesn't work either, it fails as if a parameter is not sent.

Agreeing with Joshua Devidson, this issue makes Task Groups unusable. 

Hope you have a solution soon.

**Comment by hakeberplus4** [comment] 2019-04-04 13:23
I too am experiencing the issues listed above.  In addition, if I import a Task Group and then edit and Save my changes thru the UI, then several of my parameters disappear from the Task Group Parameters list (it appears to only keep 2 parameters).

**Comment by joshuadavidson** [comment] 2019-04-04 14:20
I have submitted this as an issue on the [Azure DevOps community portal](site.https://developercommunity.visualstudio.com/content/problem/518375/task-group-parameters-do-not-show-in-deployment-gr.html).

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
