### ISSUE TITLE
[Git-Documentation]Manually Importing a repo into Azure DevOps should not use Clone/Push git CLI

### ISSUE THREAD

**Issue by DigiThax** [MicrosoftDocs/azure-devops-docs#7417] opened 2020-02-27 02:27 UTC
[https://docs.microsoft.com/en-us/azure/devops/repos/git/import-git-repository?view=azure-devops]
Not sure if this applies to TFVC but none the less, if a commit message has a work item ID or just a Pound Sign placed before a natural number, **pushing** that new repository into a project in Azure DevOps instead of **importing** it will result in the commit link showing up in a work item. Provided there exists a work item that has an ID which matches the number in the commit message. This can even affect work items in other projects under the same project collection.

**Comment by WilliamAntonRohm** [comment] 2020-02-27 21:37
@DigiThax -- Kevin, thank you for your feedback regarding [this article](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-git-repository?view=azure-devops).  

@apawast -- Apeksha, please look into this issue.

**Comment by cxwtool** [comment] 2020-11-24 23:31
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:31 UTC
Labels: Pri3, doc-bug
