### ISSUE TITLE
Default repo fails to build.

### ISSUE THREAD

**Issue by VeryKross** [MicrosoftDocs/azure-devops-docs#4078] opened 2019-04-26 20:45 UTC
Following the doc for creating my first pipeline and selecting a Forked copy of the "ASP.Net Core Application for Azure Pipelines Doc" repo on GitHub, the build fails with:

##[section]Starting: VSBuild
==============================================================================
Task         : Visual Studio Build
Description  : Build with MSBuild and set the Visual Studio version property.
Version      : 1.148.1
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613727)
==============================================================================
##[error]Solution not found using search pattern 'D:\a\1\s\**\*.sln'.
##[section]Finishing: VSBuild

No edits were performed to the repo after it was Forked.

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri3, doc-bug
