### ISSUE TITLE
Restart agents after each Job (Akin to the vsts-docker lifecycle)

### ISSUE THREAD

**Issue by w3s7y** [MicrosoftDocs/azure-devops-docs#2207] opened 2018-10-24 13:38 UTC
Hi, 

We are currently trying to implement behavior the same as the 'vsts-docker' image in native self-hosted windows agents. 

We run the vsts-docker image and after each job it completes the pod is stopped and the agent restarted.  We would like to emulate that behavior on a Windows agent installed as a service.  However can't see a method in which we can mark it as unavailable or stop it entirely while within the pipeline executing on the agent itself.  (Our requirement is that only one build is sent to an agent, then we revert it to a snapshot before it takes another release). 

We have achieved this in K8s land due to the fact the agent restarts itself after every job, however the windows agent (installed as a service) seems to run 24/7 and does not restart itself after a job has completed.  Therefore we cannot update the agent capabilities during execution and other queued builds end up on agents which are not in the desired state to start a new release. 

However, we can't find anything concrete in the docs, did see the `--noRestart` flag which we have experimented with however this only negates the restart of the agent during configuration time, not after each job. 

Does such a function/capability exist in the hosted VSTS agent?

**Comment by w3s7y** [comment] 2018-10-24 13:38
Apologies if this is the wrong audience for such questions, I'm hoping it's documented and I just can't find it!

**Comment by steved0x** [comment] 2018-10-31 18:36
@w3s7y I will find out if this is documented. @alexhomer1 Can you take a look, or reassign to someone that knows about agents to see if this is possible?

**Comment by shashban** [comment] 2018-11-09 06:10
@w3s7y If you are using the Microsoft hosted agents, then recycling of the agents is taken care of by the hosted pools. For self hosted agents, there isn't a functionality to signal restart of the agent.

Adding @chrisrpatterson for more details

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri3, devops-cicd/tech, devops/prod, doc-bug
