### ISSUE TITLE
Variable names are gone

### ISSUE THREAD

**Issue by vw-bnauta** [MicrosoftDocs/azure-devops-docs#12928] opened 2022-11-28 15:16 UTC
I think this page used to have a table with variable names and descriptions. It seems only the descriptions are left.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/build/variables.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment] 2022-11-28 17:10
@vw-bnauta -- thank you for your feedback.  On my screen, all the variable tables are in the article.  Please clarify where the table is missing in your view.

**Comment by WilliamAntonRohm** [comment] 2022-11-28 17:17
Closing as a duplicate of #12925

**Closed by WilliamAntonRohm** 2022-11-28 17:17 UTC
Labels: duplicate, needs-more-info, cba, Pri1, azure-devops-pipelines/svc, azure-devops-pipelines-build/subsvc
