### ISSUE TITLE
Task input (`aliases`) incorrectly lists `azureSubscription` as primary input

### ISSUE THREAD

**Issue by nis-spiir** [MicrosoftDocs/azure-devops-docs#13281] opened 2023-05-02 09:31 UTC
Mosts ADO tasks that needs a Service Connection contains this documentation:

![Confusing auto-generated documentation for input name](https://user-images.githubusercontent.com/55689628/235629459-b47a3ab0-ceba-4a07-9bc5-f7ec2393ec4b.png)

This is very confusing because it _should not_ contain the name of an Azure Subscription.
Lots of issues has been opened about this:
 * https://github.com/MicrosoftDocs/azure-devops-docs/issues/6400
 * https://github.com/MicrosoftDocs/azure-devops-docs/issues/10561
 * https://github.com/MicrosoftDocs/azure-devops-docs/issues/10397
 * https://github.com/MicrosoftDocs/azure-devops-docs/issues/4900
 * https://github.com/MicrosoftDocs/azure-devops-docs/issues/6578
 * https://github.com/MicrosoftDocs/azure-devops-docs/issues/11312

Looking at the code for e.g. `AzureCLI@2` (screenshotted above), we clearly see that `azureSubscription` is the alias and `connectedServiceName` is the _real_ parameter name:

![Source code for AzureCLI showing connectedServiceName is the real parameter name](https://user-images.githubusercontent.com/55689628/235630183-04fcaee3-b6d6-424d-b34b-860d6b1225d9.png)

Suggestion for solving this issue:
 * Is the script for generating the docs public? I'd love to make a PR making sure the actual input name is shown in big and aliases are shown as aliases
 * Update all tasks so they contains two aliases: `"aliases": ["connectedServiceName", "azureSubscription"]` - I guess the script will then pick the first alias?

**Comment by WilliamAntonRohm** [comment] 2023-05-03 22:33
@nis-spiir -- Nicolai, thank you for your well-researched feedback, and for your PR.

@ramiMSFT -- Rami, please look into this issue.

**Comment by nis-spiir** [comment] 2023-05-15 08:36
@ramiMSFT any feedback? Can you point me towards the script that generates the public docs? I would love to make sure the 'real' variable name is actually shown on the docs page.

**Comment by ramiMSFT** [comment] 2023-05-23 15:37
@nis-spiir Thank you for the detailed feedback! We discussed this internally, please stay tuned!

+ @steved0x 
+ @geekzter

**Comment by steved0x** [comment] 2023-05-23 16:40
@nis-spiir The tooling that autogenerates the task reference is not public, but I can answer some of the questions about how it determines which YAML task input name is displays as the "primary" name.

Some background, before YAML Pipelines were introduced in 2019, customers had no visibility to the name of a task input; they would only see the label that was displayed in the classic pipeline designer, and the task input name was used only internally in the task implementation. When YAML pipelines were introduced, many of these task input names were not descriptive, and the concept of aliases was created, to allow a task author to provide a task input YAML name that was more descriptive than the original name, while keeping the original name to preserve compatibility with folks that had YAML pipelines using the original task input name.

https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users

Starting with Azure DevOps Server 2019, a YAML Pipeline editor was introduced, that provided an intellisense type functionality. The schema used to validate a YAML Pipeline in the pipeline editor is available using this API (for example Visual Studio Code uses this when a pipeline is being edited in VS Code, and the Pipeline extension is installed.)

https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/yamlschema/get?view=azure-devops-rest-7.0

If a task input has an alias, the YAML schema suggests the alias in its intellisense instead of the original parameter name. I can't confirm, but I believe it is because the intent of an alias was to provide a more descriptive name to a parameter. In the example of the AzureCLI@2 task, here is the list of inputs displayed by the intellisense functionality; note that it uses the alias (if the input has an alias, for example the azureSubscription task input name)

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/1580889/832446ac-21bc-455d-a5a1-f5da6154cef9)

In the schema downloaded using the REST API, that input it looks like this:
```
"task": {
  "description": "Azure CLI\n\nRun Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.",
  "ignoreCase": "value",
  "pattern": "^AzureCLI@2$"
},
"inputs": {
  "description": "Azure CLI inputs",
  "properties": {
    "azureSubscription": {
      "type": "string",
      "description": "Azure Resource Manager connection",
      "ignoreCase": "key",
      "aliases": [
        "connectedServiceNameARM"
      ]
    },
```

If a task input has more than one alias, which one does it display as the primary name in the task reference? 

It uses the first alias in the list, in order to match the intellisense in the YAML Pipeline editor. One example of this is the XamarinIOS@2 task:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/XamariniOSV2/task.json#L111

```
            "name": "buildToolLocation",
            "aliases": [
                "mdtoolFile",
                "mdtoolLocation"
            ],
```

From the YAML Schema, using the first alias name as the primary name.
```
                "mdtoolFile": {
                  "type": "string",
                  "description": "Build tool path",
                  "ignoreCase": "key",
                  "aliases": [
                    "buildToolLocation",
                    "mdtoolLocation"
                  ]
                },
```

I think that adding some new aliases to the tasks is a good idea, and if they are added so that they are the first in the list, they will be used as the primary name in the task reference.

While many portions of the task reference are automated, some parts are user editable, like task description, and task input descriptions. Part of the task input content is generated, but part of it is manually authored and can accept PRs.

https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/README.md

For this particular task input (from your example above), the description is accurate, but I agree that the task input naming could be improved (and the alias doesn't really provide any clarity)

I don't work with this particular task, so someone else will reply to this specific issue about task input names, but I wanted to provide some information about the task reference article generation. If you have a PR to any of the "editable content" in the task reference, please submit it with our gratitude.

Thank you for your feedback on this task (and others using a similar task input),
Steve

**Comment by nis-spiir** [comment] 2023-06-01 14:58
Hey, thanks for the in depth reply, makes a lot of sense!

It seems like people are mostly creating "proper named" primary variable names today (see: https://github.com/microsoft/azure-pipelines-tasks/pull/18229#issuecomment-1547425059) and then adding `azureSubscription` as an alias to be backwards compatible, so it might make sense to flip the logic of the internal script? I.e. pick primary variable name instead of first alias

Or would it be valid to change e.g. this:

```json
    …,
    "inputs": [
        {
            "name": "connectedServiceNameARM",
            "aliases": [
                "azureSubscription"
            ],
        }
    ]
```

to this:

```json
    …,
    "inputs": [
        {
            "name": "connectedServiceNameARM",
            "aliases": [
                "connectedServiceNameARM",
                "azureSubscription"
            ],
        }
    ]
```

This would be a fairly small PR on a handful of tasks and then the logic about picking first alias would now produce the "correct" variable name in docs (without having to change code)

**Comment by steved0x** [comment] 2023-06-08 13:53
Good points, I would have to review to see what happens in the doc generation process when an alias is a duplicate of the input name, I think it just get screened out (as I think there were 1-2 that had an alias that was a duplicate of the name).

**Comment by steved0x** [comment] 2023-06-21 21:44
Closing since we are tracking this in https://github.com/microsoft/azure-pipelines-tasks/pull/18522

**Closed by steved0x** 2023-06-21 21:44 UTC
Labels: doc-bug, Pri3
