### ISSUE TITLE
Missing documentation of output variable

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#5446] opened 2019-09-01 21:47 UTC
The task returns an "output variable", but this is missing from the docs.

It seems to be a general issue (for all tasks). Let's get those output variables added (for all tasks). :)

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d955bb83-fa46-22e0-de73-7700ae214af8
* Version Independent ID: 1f55672f-711e-24fa-e6bc-edc0ca723eba
* Content: [Azure Web App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
