### ISSUE TITLE
Explicitly state this is a one way conversion.

### ISSUE THREAD

**Issue by luckielordie** [MicrosoftDocs/azure-devops-docs#5132] opened 2019-08-05 15:19 UTC
Performing git svn clone with the --no-metadata flag is a one-way operation that severs the link between svn and the new git repository.
Would it be possible to state the reasoning for such a choice? Or maybe show how a repo could be cloned then kept up to date with an svn repo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Migrate from Subversion (SVN) to Git](https://docs.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops#feedback)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/perform-migration-from-svn-to-git.md)
* Product: **devops**
* Technology: **devops-whitepapers**
* GitHub Login: @hkamel
* Microsoft Alias: **hkamel**

**Comment by rihei** [comment] 2019-08-21 13:59
Especially when this article mentions a step "(Optional) Synchronize the local Git repository with any changes from SVN repository while developers continue using SVN" without specifying how this is to be done. Is it even possible when the --no-metadata flag is used? I just migrated an old repository and it took ~6 hours to complete, so I'm not keen to redo it. Hope I find some way to get the latest SVN commits migrated to the Git repository.

**Comment by luckielordie** [comment] 2019-08-21 20:47
Unfortunately, you do need to run again without that flag. If it's any consolation my repo was from 2006 and took another 5 days.

Also, if you want to use the Atlassian conversion tool you will need to run with an empty prefix like so `--prefix=''` for the tool to work.

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri1, devops-whitepapers/tech, devops/prod, doc-bug
