### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by saraswat40** [MicrosoftDocs/azure-devops-docs#7648] opened 2020-03-19 19:14 UTC
Hello,

This document is outdated and incomplete. The Azure pipeline screens have changed and I couldn't find any working yaml samples to build or deploy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a95fd0f-578f-308a-489d-b90c9163530b
* Version Independent ID: 4958a19d-78f0-750e-3750-3297989f451a
* Content: [Deploy an ASP.NET Cloud Service app - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-cloudservice-cloudservice?view=azure-devops#feedback)
* Content Source: [docs/pipelines/apps/cd/deploy-cloudservice-cloudservice.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-cloudservice-cloudservice.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:29
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:29 UTC
Labels: Pri2, devops-cicd-apps/tech, devops/prod, doc-bug
