### ISSUE TITLE
Argument name in the Arguments table doesn't match yaml name

### ISSUE THREAD

**Issue by heskew** [MicrosoftDocs/azure-devops-docs#3290] opened 2019-02-08 00:24 UTC
It takes some guessing to do the mental map from the YAML name to the Argument description. Would it make sense to make that relation more explicit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by t-eckert** [comment] 2019-02-10 23:19
Seconded. I've been working at this for awhile and it's pretty confusing.

**Comment by RoopeshNair** [comment] 2019-02-11 17:12
@DavidStaheli - is there a way we can autogenerate the docs to include yaml property name for the task arguments in the Docs? I can raise a PR for this specific issue, however it would be appropriate if we can automate.

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
