### ISSUE TITLE
How to define output

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/azure-devops-docs#3939] opened 2019-04-12 07:32 UTC
The build task has Output Variables, that should be used (see https://docs.microsoft.com/en-us/azure/iot-edge/how-to-ci-cd#configure-continuous-integration step 6 and 8) to get the deployment json. 
![grafik](https://user-images.githubusercontent.com/4662023/56019649-7f17da00-5d05-11e9-893d-ee86493792e1.png)

This documentation should explain how to get this variable in the yaml Schema.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d93a0bac-faf1-3c5d-d358-487d3d0d4f9e
* Version Independent ID: 06d36475-d60d-067d-0c12-d5af0ff1d85c
* Content: [Azure IoTEdge task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/azure-iot-edge.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/azure-iot-edge.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by 4or5trees** [comment] 2019-06-28 09:51
The default output path for the _Generate deployment manifest_ IoT Edge task is **$(System.DefaultWorkingDirectory)/config/deployment.json** 

So right now I'm just publishing the **$(System.DefaultWorkingDirectory)/config** folder as artifact, which works (artifact contains my deployment.json). That workaround seems fine, but proper integration like in the Visual Designer is preferable.

One strange thing I've noticed is that the _Push module images_ IoT Edge action logs state that the file should be directly in (what I assume is) **$(System.DefaultWorkingDirectory)**:
```
Expanding 'deployment.template.json' to 'config/deployment.amd64.json'
The generated deployment file located in the path: /home/vsts/work/1/a/deployment.amd64.json
```
But that deployment.amd64.json does **not** show up in the output of the following task that ran after the _Push module images_ task:
```
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls $(System.DefaultWorkingDirectory)'
```
So maybe the log output from the _Push module images_ IoT Edge task that states the generated deployment file is located in $(System.DefaultWorkingDirectory) is bugged?

**Comment by michaeljqzq** [comment] 2019-07-08 06:27
@blackchoey Could you take a look at this?

**Comment by blackchoey** [comment] 2019-07-12 06:55
Hi @StefanSchoof we now have the `Generate deployment manifest` task to generate deployment manifest. This is the recommended way to generate deployment.json now. Could you try to use this new task when authoring your build definition via yaml file? The usage is more straightforward and you can generate yaml code from Azure Pipelines portal as well. We're working to update the documents now.

**Comment by blackchoey** [comment] 2019-07-12 08:26
@4or5trees In original flow, the build task generates file to **$(Build.ArtifactStagingDirectory)** and push task adds credentials to the deployment file under **$(Build.ArtifactStagingDirectory)**. No files will be generated under $(System.DefaultWorkingDirectory).
Now we suggest using `Generate deployment manifest` task to generate deployment.json and expand credentials configured as variables, which provides better security control for the generated deployment manifest. The previous behavior is only kept for backward compatibility.

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
