### ISSUE TITLE
Is possible use "Scope" field to feed different variable values for substitution in different deployment environments?

### ISSUE THREAD

**Issue by jairov4** [MicrosoftDocs/azure-devops-docs#1431] opened 2018-07-30 06:58 UTC
It is not clear for me whats the behavior on different variables having same name but different scope during variable substitution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/transforms-variable-substitution?view=vsts#xmlvarsubs)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment] 2018-07-30 11:24
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by pemj** [comment] 2019-05-13 22:17
Hi, I have the same question, and it looks like the issue has been here for about a year. Any movement on that? If I have one pipeline variable set to Release-wide scope, and another set to a regional or per-stage scope, which one do I get when I'm at that stage?

**Comment by pemj** [comment] 2019-05-13 22:21
I'm also curious about this. I was looking at the Azure DevOps [documentation ](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch), and I couldn't find any answers there either. I don't suppose anyone has any more illuminating knowledge on the subject?

**Comment by N-Usha** [comment] 2019-07-02 09:41
If a variable is defined with 'Release' scope then it will be considered during substitution, if variable with same name is scoped to a specific 'stage' and that stage contains the file transform task, it will be considered during substitution. 
![image](https://user-images.githubusercontent.com/25389593/60502485-8da9d800-9cdb-11e9-9af2-99e3c42e5a62.png)

**Comment by pemj** [comment] 2019-07-02 21:03
How about with variable groups and predefined variables? I've observed that pipeline variable substitution occurs before evaluation of a task, which means that bash for instance evaluates a variable differently depending on whether it's a pipeline variable, a member of a variable group, or a predefined variable. Is that distinction covered anywhere in more depth in the docs?

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
