### ISSUE TITLE
Firewall settings missing for retrieving artifacts when deploying

### ISSUE THREAD

**Issue by bremnes** [MicrosoftDocs/azure-devops-docs#5674] opened 2019-09-19 19:24 UTC
The IP address ranges mentioned in the article are
>13.107.6.0/24
13.107.9.0/24
13.107.42.0/24
13.107.43.0/24

We are allowing outgoing connections in the firewall to the mentioned addresses, and the agent connects and can run agent jobs:
>Scanning for tool capabilities.
Connecting to the server.
2019-09-19 18:49:37Z: Listening for Jobs

However, when downloading artifact it first tries to connect to a storage account that is within the ip range (https://vsblobprodeus21.vsblob.visualstudio.com/ - 13.107.42.18), but is then redirected to another storage account that is not in the range (wx3vsblobprodeus218.blob.core.windows.net - 52.239.156.138) and then proceeds to retry until failure.

AzDO log:
```
...
2019-09-19T19:03:36.8064770Z Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodeus21.vsblob.visualstudio.com/A77773e24-3f8c-47f1-&lt;REDACTED&gt;/_apis/dedup/chunks/D785F6F1D130E1E073DFF15686566DA52A10A4213618&lt;REDACTED&gt;A01 attempt 1/6 failed with StatusCode RedirectMethod, IsRetryableResponse False
2019-09-19T19:04:36.8548928Z Warning, [https://wx3vsblobprodeus218.blob.core.windows.net/db77773e243f8c47f1937f6e6a0f73e56d/D785F6F1D130E1E073DFF15686566DA52A10A&lt;REDACTED&gt;] Try 1/5, non-retryable exception caught. Throwing. Details:
2019-09-19T19:04:36.8550016Z Task was requested to be canceled. System.Threading.Tasks.TaskCanceledException: A task was canceled.
2019-09-19T19:04:36.8550473Z    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-09-19T19:04:36.8550928Z    at Microsoft.VisualStudio.Services.Common.TaskCancellationExtensions.EnforceCancellation[TResult](Task`1 task, CancellationToken cancellationToken, Func`1 makeMessage, String file, String member, Int32 line)
2019-09-19T19:04:36.8551465Z    at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.&lt;&gt;c__DisplayClass56_0.&lt;&lt;GetRedirectResponseAsync&gt;b__0&gt;d.MoveNext()
2019-09-19T19:04:36.8552169Z --- End of stack trace from previous location where exception was thrown ---
2019-09-19T19:04:36.8552615Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
2019-09-19T19:04:36.8581454Z Warning, [hhttps://wx3vsblobprodeus218.blob.core.windows.net/db77773e243f8c47f1937f6e6a0f73e56d/D785F6F1D130E1E073DFF15686566DA52A10A&lt;REDACTED&gt;] Try 1/5, retryable exception caught. Retrying in 00:00:01. Details:
2019-09-19T19:04:36.8582179Z No LastRequestResponse on exception TaskCanceledException: A task was canceled. System.Threading.Tasks.TaskCanceledException: A task was canceled.
2019-09-19T19:04:36.8582581Z    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-09-19T19:04:36.8582923Z    at Microsoft.VisualStudio.Services.Common.TaskCancellationExtensions.EnforceCancellation[TResult](Task`1 task, CancellationToken cancellationToken, Func`1 makeMessage, String file, String member, Int32 line)
2019-09-19T19:04:36.8583315Z    at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.&lt;&gt;c__DisplayClass56_0.&lt;&lt;GetRedirectResponseAsync&gt;b__0&gt;d.MoveNext()
2019-09-19T19:04:36.8584276Z --- End of stack trace from previous location where exception was thrown ---
2019-09-19T19:04:36.8585160Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
2019-09-19T19:04:36.8585885Z    at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.&lt;&gt;c__DisplayClass59_0.&lt;&lt;HandleRedirectAsync&gt;b__0&gt;d.MoveNext()
2019-09-19T19:04:36.8588067Z --- End of stack trace from previous location where exception was thrown ---
2019-09-19T19:04:36.8588397Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
...
(5 more retries)
```

Agent log:
```
2019-09-19 19:03:20Z: Running job: Agent job
2019-09-19 19:10:04Z: Job Agent job completed with result: Failed
```

So, can you tell us what additional outgoing firewall openings are required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a Azure Pipelines agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
