### ISSUE TITLE
"Allow scripts to access OAuth token" option is in a different place

### ISSUE THREAD

**Issue by htxryan** [MicrosoftDocs/azure-devops-docs#4493] opened 2019-06-12 19:37 UTC
The "Allow scripts to access OAuth token" option is now on the phase page under "Additional Options" rather than on the "Options" tab of the pipeline definition, as stated in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 024e4ed9-cf8d-155f-5e4a-73c2effaaed8
* Version Independent ID: f19c0538-4aae-b3b4-82b9-422e76723b01
* Content: [Run Git commands in a script - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/scripts/git-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/git-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by chasewilson** [comment] 2019-09-24 17:21
@htxryan Thanks for the input! This whole page will be revamped next month and this will be addressed.

**Comment by wcornfredrik** [comment] 2019-10-04 07:32
Can you please show me where this setting is? I cannot find it.

**Comment by amang2205** [comment] 2019-10-21 13:22
You'll find it in if you select the agent job group (by default it's called Agent job 1), towards the lower section of the right-hand pane, under the section called 'Additional options'

**Comment by f1ben** [comment] 2020-01-27 17:50
@chasewilson, It's 2020 now, and this issue has not been addressed as you had expected.

@iamalexmang, Thanks for pointing us to the new location of this setting.

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
