### ISSUE TITLE
Bindings parameter needs sample format

### ISSUE THREAD

**Issue by charlie-retzler** [MicrosoftDocs/azure-devops-docs#5338] opened 2019-08-22 20:38 UTC
Please add documentation with a sample for the Bindings parameter. It looks like this must be json data. I was able to get this to work by adding the following to my yaml file.

Bindings: '{"bindings": [ {"protocol": "http", "port": "8081"}, {"protocol": "http", "port": "8082"}]}'

I don't know if there is a simpler yaml format to set each individual field without using json. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 244121ae-5de4-14cd-a9c3-d9cda5ad0a3b
* Version Independent ID: 313238b7-d67b-bc60-1188-cbe305179600
* Content: [IIS Web App Manage task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/iis-web-app-management-on-machine-group?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
