### ISSUE TITLE
Trello Service Hook appears to be broken for 2017 and below now

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/azure-devops-docs#1574] opened 2018-08-21 17:43 UTC
Although it ships with the product, it doesn't appear possible to configure the hook anymore. This is kind of a product bug, but reporting it here since the documentation should probably be updated to reflect the support doesn't exist anymore.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1402b59d-915f-2457-e198-60898fd66191
* Version Independent ID: af8951ef-3bc1-8748-81a5-03696c6f5e85
* Content: [Trello with VSTS](https://docs.microsoft.com/en-ca/vsts/service-hooks/services/trello?view=vsts)
* Content Source: [docs/service-hooks/services/trello.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/trello.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment] 2018-09-21 15:30
Thanks @nschonni , @willsmythe is this the case?

**Comment by nschonni** [comment] 2018-11-19 18:43
@willsmythe can you confirm that the API changed on the Trello side and it isn't supported on the older versions so the docs can be updated

**Comment by nschonni** [comment] 2018-12-17 21:58
@elbatk @willsmythe this is still an issue

**Comment by elbatk** [comment] 2019-01-29 16:50
Hey @nschonni , going to try to bring in @roofers to help here as he looks over the Service Hooks now!

**Comment by roofers** [comment] 2019-01-29 17:03
@nschonni - There was an issue with Trello in TFS 2017. It was around supported SSL versions. Can you open a [customer support ticket](https://azure.microsoft.com/en-us/support/devops/) and we'll be able to help get you unblocked.

**Comment by elbatk** [comment] 2019-01-29 17:22
@roofers is there anything I should add to the docs or are we okay?

**Comment by nschonni** [comment] 2019-01-29 19:13
Thanks @roofers we're trying to just get our folks to use TFS right now, but if there is a documentation update (even if it is "open a support ticket if it isnt' working") that would be good to add here. I think there are a bunch of social.msdn & SO threads with people hitting this and giving up :wink:

**Comment by roofers** [comment] 2019-01-29 22:57
@nschonni - Yep. I'm going to work with @elbatk to get that added.

**Comment by jean** [comment] 2019-06-27 09:32
Anything happened? Was that "customer support ticket" created?

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri2, devops-collab/tech, devops/prod, doc-bug, help wanted
