### ISSUE TITLE
The "Install SSH Key task" link is broken

### ISSUE THREAD

**Issue by wichert** [MicrosoftDocs/azure-devops-docs#4968] opened 2019-07-23 08:29 UTC
Under "See Also" there is a link to https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/InstallSSHKey which should not work. The correct link is https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/InstallSSHKeyV0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89132320-da86-8a4e-4468-cf651561892c
* Version Independent ID: 4946284d-9666-4a15-9e03-72377693ecb0
* Content: [Copy Files Over SSH task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/copy-files-over-ssh?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/copy-files-over-ssh.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/copy-files-over-ssh.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by wichert** [comment] 2019-07-23 08:30
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-ssh-key would probably be a more useful link for people as well.

**Comment by jaypharis** [comment] 2019-07-23 19:55
I have an open PR to fix the docs, https://github.com/MicrosoftDocs/vsts-docs/pull/4647

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri2, devops-cicd/tech, devops/prod
