### ISSUE TITLE
Not able to prevent Release transforms from running during build

### ISSUE THREAD

**Issue by PilotBob** [MicrosoftDocs/azure-devops-docs#3678] opened 2019-03-18 20:58 UTC
I tried to follow the instructions here. No matter what I did, the Release transform was run during the msbuild task in my build pipline. 

1. Removed the dependant on tag for the transform files.
2. Added /p:TransformWebConfigEnabled=false to my msbuild command line
3. Added /p:ProfileTransformWebConfigEnabled=false to msbuild command line

After all these steps, it was still performing the transform during the build. I worked around it, but this topic content should be checked, perhaps things have changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment] 2019-03-19 13:44
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by pauska** [comment] 2019-08-17 12:52
@PilotBob how did you work around this issue? I'm in the same boat - want the build to run without any transform, and perform transforms in deployment instead.

**Comment by PilotBob** [comment] 2019-08-18 15:38
> @PilotBob how did you work around this issue? I'm in the same boat - want the build to run without any transform, and perform transforms in deployment instead.

I created a web.stagename.config files that are transformed in the release pipeline during the web deploy task. So my web.release.config only now turns off debug and other things common to all the release environments.

**Comment by uniquelau** [comment] 2020-01-09 17:22
Any update on this?
I am seeing the same behavior locally in Visual Studio 2019.

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
