### ISSUE TITLE
Show worked example for PyPI

### ISSUE THREAD

**Issue by jbarlow83** [MicrosoftDocs/azure-devops-docs#4875] opened 2019-07-16 08:46 UTC
The most basic usage of this feature is uploading to pypi.org, but as written this is baffling.

What is a valid artifact feed name? How is set? How do I specify the files that should be uploaded? What is the format for externalFeeds - URIs or something else? I have multiplatform builds and only want to upload wheels if all builds succeed. How to gather the built wheels from each platform, and transfer them to a final job that uploads?

The comment: Add '-r FeedName/EndpointName --config-file $(PYPIRC_PATH)' to your twine upload command. For feeds present in this organization, use the feed name as the repository (-r). Otherwise, use the endpoint name defined in the service connection.

Where does twine upload command go? Before the TwineAuthenticate task or after? What's EndpointName?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 726683ec-c811-46b7-17d6-527fbafaf8d0
* Version Independent ID: 6d964146-88fb-1975-1263-4d4f6584a03a
* Content: [Python Twine Upload Authenticate - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/twine-authenticate?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/package/twine-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/twine-authenticate.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
