### ISSUE TITLE
Is there a way to access the Response Body

### ISSUE THREAD

**Issue by verbedr** [MicrosoftDocs/azure-devops-docs#7581] opened 2020-03-11 16:12 UTC
It is nice to call REST API's but I need the result of that call in order to perform a second call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bc6da4-5a1e-5989-f4f0-27465953b5fd
* Version Independent ID: fd12f976-5d3b-3b1b-3d0a-a0bf2a60c961
* Content: [Invoke HTTP REST API task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/http-rest-api.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by verbedr** [comment] 2020-03-11 16:14
Never mind I read in the closed issues that it is not possible. It would be nice to have something that can provide the results as an output for other tasks

**Comment by verbedr** [comment] 2020-03-11 16:15
An it would be nice to include this as part of the documentation.

**Comment by WilliamAntonRohm** [comment] 2020-03-12 01:06
@verbedr -- Dries, thank you for your question and followup.  You are welcome to [add your product suggestion here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

@RoopeshNair -- Roopesh, please look into this potential documentation issue.

**Comment by verbedr** [comment] 2020-03-12 01:23
@WilliamAntonRohm Thx for your quick reply. I do realize I was a bit to quick to post the question/remark. If I would have taken more time I should have realize that the Task used the HttpRequest feature from tfs which is limiting the options that are available. And it's not that easy to fix/solve.

My appoligies if I sounded aggravated.

@RoopeshNair you could add an additional question in the Q/A

Can I use the response boby as the input for a nother task?

No, as this taks is an agent less task and thus is using TFS internal HttpRequest it can't return the content of the http request

**Comment by WilliamAntonRohm** [comment] 2020-05-06 22:14
@verbedr -- Dries, thank you for clarifying.  Your first comment is fine -- it's what we do!

@shashban -- Shashank, please review [private PR 1382](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1382).

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, doc-bug
