### ISSUE TITLE
.artifactignore does not work consistently

### ISSUE THREAD

**Issue by liusu119** [MicrosoftDocs/azure-devops-docs#6285] opened 2019-11-06 20:36 UTC
Some of the path in .artifactignore doesn't work.
Example:
Directory tree before using .artifactignore
root
-StoreRelease
--Bin
--BundleArtifacts
--GeneratedFiles
--Obj
--Pkg

.artifactignore's content:
StoreRelease/Bin/**.*
StoreRelease/BundleArtifacts/**.*
StoreRelease/GeneratedFiles/**.*
StoreRelease/Obj/**.*

Expected artifact directory tree:
root
-StoreRelease
--Pkg

Actual artifact directory tree:
-StoreRelease
--bin
--pkg

So basically the bin directory is uploaded even though it's included in the .artifactignore file. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40b39086-3718-419d-d850-914422097cde
* Version Independent ID: 4f23e54f-f59b-85ab-2eb0-6a58eb0ad088
* Content: [Use the .artifactignore file](https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/artifactignore?view=azure-devops)
* Content Source: [docs/artifacts/reference/artifactignore.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/reference/artifactignore.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by liusu119** [comment] 2019-11-06 20:44
In this case, what I really want to use is
**/*
!StoreRelease/Pkg/**.*

But this completely blocks any upload.

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri2, devops-artifacts/tech, devops/prod, doc-bug
