### ISSUE TITLE
Documentation, Examples

### ISSUE THREAD

**Issue by MouthOfMadness** [MicrosoftDocs/azure-devops-docs#4436] opened 2019-06-05 15:52 UTC
Does this task even work?  The error message isn't that useful, as this is the value recommended by the documentation.

##[error]"&lt;!DOCTYPE html&gt;\n&lt;html lang=\"en\"&gt;\n&lt;head&gt;\n&lt;meta charset=\"utf-8\"&gt;\n&lt;title&gt;Error&lt;/title&gt;\n&lt;/head&gt;\n&lt;body&gt;\n&lt;pre&gt;Cannot POST /v0.1/apps/https://appcenter.ms/orgs/mycompany/apps/test/distribute/distribution-groups/release_uploads&lt;/pre&gt;\n&lt;/body&gt;\n&lt;/html&gt;\n"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da6643ac-ea32-1761-a7e9-0f17a3c0b8ee
* Version Independent ID: 2442af0f-3f01-a91c-a98a-29c2f32d35b9
* Content: [App Center Distribute task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/app-center-distribute.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/app-center-distribute.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
