### ISSUE TITLE
AzTable module

### ISSUE THREAD

**Issue by hannwang1** [MicrosoftDocs/azure-devops-docs#8094] opened 2020-04-27 08:13 UTC
I need to manage storage table entities using AzTable module.  Does this task support AzTable module?  I got error "The term 'Add-AzTableRow' is not recognized as the name of a cmdlet, function, script file".  It will be difficult to manage storage table entities without this module. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cconrado** [comment] 2020-05-16 05:55
I couldnt install the module either

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, doc-enhancement
