### ISSUE TITLE
Misleading: "perhaps by entering the values for custom variables used by the tasks in the release." not actually allowed

### ISSUE THREAD

**Issue by Pxtl** [MicrosoftDocs/azure-devops-docs#7804] opened 2020-04-02 16:09 UTC
The variables for the environment are greyed out and not editable once the release to this environment has begun, so telling the user to "enter the values for custom variables" is actually impossible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c633b9-c8b2-e05d-de2c-7754894d28fd
* Version Independent ID: df031b76-0fe7-e138-dd36-2736757a97fd
* Content: [Manual Intervention task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-intervention?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/manual-intervention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/manual-intervention.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by Sidewinder53** [comment] 2020-04-23 06:59
This is not entirely true. While you are are not able to edit variables scoped to the stage in which the Manual Intervention task is in, you can edit variables that are scoped to "Release" or to any other stage.

**Comment by cxwtool** [comment] 2020-11-24 23:28
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:28 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod
