### ISSUE TITLE
What is the encoding of the messageBody

### ISSUE THREAD

**Issue by evancarey** [MicrosoftDocs/azure-devops-docs#8406] opened 2020-05-20 22:14 UTC
I get more than just the string I provide in the messageBody argument. Can you provide an example of how to extract just the string I entered. I'm using the examples found at https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/servicebus/service-bus/samples/javascript as guide but when I console.log the message.body I get something like the following:

@strin3http://schemas.microsoft.com/2003/10/Serialization/�string i entered in pipelines

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1c2ed83-c2e6-ebca-cd70-8d9561880ab3
* Version Independent ID: 0376e36f-a56a-2844-d853-7772737ac899
* Content: [Publish To Azure Service Bus task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-to-azure-service-bus?view=azure-devops#q--a)
* Content Source: [docs/pipelines/tasks/utility/publish-to-azure-service-bus.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/publish-to-azure-service-bus.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, doc-enhancement
