### ISSUE TITLE
Multiple reports

### ISSUE THREAD

**Issue by jrutroff** [MicrosoftDocs/azure-devops-docs#4799] opened 2019-07-09 19:20 UTC
When running 2 tasks to generate both a drift report and a deploy report, it seems that the second report will overwrite the first  in the build pipeline.  Only the second report artifact will get published.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f07c04-6b05-0de0-9b74-e032226528a4
* Version Independent ID: f0363446-1415-4e48-4c40-9b56906654f2
* Content: [Azure SQL Database Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/sql-azure-dacpac-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/sql-azure-dacpac-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
