### ISSUE TITLE
Bad twine command

### ISSUE THREAD

**Issue by syonekura** [MicrosoftDocs/azure-devops-docs#3500] opened 2019-02-27 18:39 UTC
It should be:

- script: 'twine upload -r {feedName/EndpointName} --config-file $(PYPIRC_PATH) {package path to publish}'

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 638243e7-cdd6-7573-aa6a-87c39da1bb3d
* Version Independent ID: d0046f56-ed26-7af2-3b8f-3dd5ab6ab892
* Content: [Publish packages to PyPI - Azure Pipelines](https://docs.microsoft.com/es-es/azure/devops/pipelines/artifacts/pypi?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pypi.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pypi.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **elbatk**

**Comment by chrahunt** [comment] 2019-06-26 00:59
Fixed in #2863.

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed** 2023-03-08 19:16 UTC
Labels: devops/prod, devops-cicd/tech, doc-bug, Pri2
