### ISSUE TITLE
Incomplete command in SVN to Git migration

### ISSUE THREAD

**Issue by ShaneZhengNZ** [MicrosoftDocs/azure-devops-docs#3756] opened 2019-03-25 01:49 UTC
In the svn to Git migration documentation, it is missing '>> authors-transform.txt', therefore the command is not complete.

Also good to point out the encoding of the file to avoid the issue that git-svn aborts because username cannot be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Migrate from Subversion (SVN) to Git](https://docs.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/perform-migration-from-svn-to-git.md)
* Product: **devops**
* GitHub Login: @hkamel
* Microsoft Alias: **hkamel**

**Comment by ShaneZhengNZ** [comment] 2019-03-25 01:50
#3757

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri1, devops/prod
