### ISSUE TITLE
Not relevant sentence

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/azure-devops-docs#1259] opened 2018-07-10 11:45 UTC
This is not relevant : Server URL	http://10.0.0.4:8080

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b55e0120-df94-9e7a-5439-7d7c45841deb
* Version Independent ID: 92c4e1a2-b161-796f-7053-d5a68373a0f3
* Content: [Build Docker images for your Java project with VSTS](https://docs.microsoft.com/en-us/vsts/java/labs/builddocker/?view=vsts)
* Content Source: [docs/java/labs/builddocker/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/labs/builddocker/index.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by mlearned** [comment] 2018-07-11 11:33
@SamirFarhat we are looking at this one.  When you say "not relevant" you mean the private IP for pom.xml correct?  any other details you can share?

**Comment by SamirFarhat** [comment] 2018-07-11 17:02
Yes, it's possible that we get a different IP address.

**Comment by cxwtool** [comment] 2020-11-24 23:50
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:50 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
