### ISSUE TITLE
Wrong Jenkins plugin?

### ISSUE THREAD

**Issue by Axman111** [MicrosoftDocs/azure-devops-docs#3308] opened 2019-02-10 19:23 UTC
In the section: Configure a Jenkins CI build with Azure Pipelines integration, in step 11, it states to add "Trigger release in TFS/Team Services", however the steps below it correspond to "VS Team Services Continuous Deployment" action.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31c95c7b-388a-7b39-5283-43193bb643df
* Version Independent ID: 943fc46d-a114-5555-d6e0-6ad2400d1ad0
* Content: [Deploy to Kubernetes on AKS with Jenkins - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/integrate-jenkins-pipelines-aks?view=azure-devops)
* Content Source: [docs/pipelines/release/integrate-jenkins-pipelines-aks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/integrate-jenkins-pipelines-aks.md)
* Product: **devops**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
