### ISSUE TITLE
How can I consume secure files

### ISSUE THREAD

**Issue by FixRM** [MicrosoftDocs/azure-devops-docs#3809] opened 2019-03-29 06:56 UTC
The ability to download secure file is very intriguing :) but how can we really consume signing certificate for giving assembly a strong name, for example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140dcb9a-2ed0-11d5-064b-068f863ed97f
* Version Independent ID: 672d2aa3-cf0d-9207-c97c-e2eba14506b7
* Content: [Secure files for Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops)
* Content Source: [docs/pipelines/library/secure-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/secure-files.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **madhurig**

**Comment by timheuer** [comment] 2019-04-03 20:48
@FixRM -- use the Download Secure File task in your pipeline and then you can reference it using $(Agent.WorkFolder)\_temp\<yourfile> in your task definition inputs.

**Comment by FixRM** [comment] 2019-04-04 05:05
@timheuer, thanks for you answer. The question was: What's next?

**Comment by timheuer** [comment] 2019-04-04 17:58
Sorry @FixRM I'm not sure I understand.  Here would be the flow:
- use Download Secure File task in your pipeline
- The task has an output variable you can specify (secureFilePath) or also just use $(Agent.TempDirectory)\yourfilename
- use either of those variables in a later task to use the file value.

**Comment by FixRM** [comment] 2019-04-05 04:39
@timheuer, thanks again. Let me explain question in other way: Why we don't have any out of box tasks that can deal with secure files? Microsoft didn't provide any sensible materials on that.

**Comment by timheuer** [comment] 2019-04-05 05:42
Not that I'm aware of...just the Download Secure File task...here's how I used mine: https://timheuer.com/blog/archive/2019/04/04/signing-nuget-package-using-azure-devops-pipelines.aspx

**Comment by FixRM** [comment] 2019-04-05 07:15
@timheuer, signing is ok, no problem with it as we are covered by OOB NuGet task and good third party alternatives. The problem is Strong name signing. Delay signing is a nightmare! sn.exe and other tools are not accessible on MS hasted agents. MS provide us a lot of scattered information but there is no official step-by-step article saying "we design this to work in flowing way"

Any way, I finally find the source of my problem. Password protected key files are not an option for remote build. I will use Download Secure File task to put unprotected cert to solution folder :) Thank you!

link: https://www.karpach.com/visual-studio-team-services-assembly-signing.htm

**Comment by polamarasetti** [comment] 2019-10-08 13:27
hi, I am trying to store my SSH keys in secured files of Library. Then how to consume this file in following two tasks CI/CD pipeline Azure Devops 2019.
1.Run Shell commands on remote machine ?
2.Securely copy files to the remote machine?
Both of these tasks need SSH service connection. when I create SSH connection, keys are showing as plain text, so I want to avoid this security breach.
Bottom line is I want to create SSH connection without exposing keys in plain text.

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri1, devops/prod
