### ISSUE TITLE
Add Note on VS Version Compatability

### ISSUE THREAD

**Issue by SamGrantham** [MicrosoftDocs/azure-devops-docs#6343] opened 2019-11-12 16:27 UTC
This would be a good place to call out that this depreciation also means that XAML Builds can only be modified in Visual Studio 2015 and below.   VS 2017 and above are not compatible and there are no plans to fix.

The only public facing documentation I can find for this is here: https://developercommunity.visualstudio.com/content/problem/377375/serialization-error-for-adalsilenttokenacquisition.html
in the comment by Yaswanth Anantharaju [MSFT]
"Thank you for the feedback, but our team was unable to prioritize it at this time. XAML is deprecated, we recommend VS 2015 for XAML based scenarios. We stopped investing in XAML for later versions of visual studio. We strongly recommend migrating to our pipelines https://devblogs.microsoft.com/devops/whats-new-with-azure-pipelines/"

It would be nice if there was a simple, succinct note at the beginning of this article that told people, Due to the deprecation of XAML you can only edit XAML builds in Visual Studio 2015 and lower.  This makes sense in the migration article since you will want to see your XAML Build to make the changes and you may require an older version of VS to do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8c7b10c-fb6e-c491-bc0c-71c6af9a4766
* Version Independent ID: 2ae046aa-31c2-6409-fc80-796d54692450
* Content: [Migrate from XAML builds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/migrate-from-xaml-builds?view=azure-devops#overview-of-the-migration-effort)
* Content Source: [docs/pipelines/build/migrate-from-xaml-builds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/migrate-from-xaml-builds.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
