### ISSUE TITLE
Are there existing Docker Images provided as with https://mcr.microsoft.com/v2/azure-pipelines/vsts-agent/tags/list

### ISSUE THREAD

**Issue by cicorias** [MicrosoftDocs/azure-devops-docs#7085] opened 2020-01-28 17:07 UTC
Are the Docker Hub images still managed maintained and up to date?  

https://hub.docker.com/_/microsoft-azure-pipelines-vsts-agent  

Is there another location where the Agent is pushed to a pre-built container image?

The syndication points to https://mcr.microsoft.com/v2/azure-pipelines/vsts-agent/tags/list  -- but is this updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by qtzar** [comment] 2020-01-29 02:39
I would also like to see some pre-built images that I can pull down from Docker Hub, it would make spinning up an agent so much easier, especially if it had all the base tools needed like JDK and Maven etc.

**Comment by kvaes** [comment] 2020-02-02 10:24
+1

**Comment by rwaal** [comment] 2020-02-24 12:14
+1 for pre-built images.

**Comment by logiclabs** [comment] 2020-02-26 13:16
There are scripts for Windows dev environment images in: https://github.com/actions/virtual-environments  - these look like the base for the hosted pipeline agents.

There are also packer images here: https://github.com/Microsoft/azure-pipelines-image-generation.

**Comment by pprivately** [comment] 2020-04-19 16:04
+1

**Comment by znatan** [comment] 2020-05-03 13:48
+1. any answers from MSFT?

**Comment by bbarman4u** [comment] 2020-05-06 11:25
+1. I guess this method outlined is only useful if we have any specific needs for having a custom image that needs tools that MSFT don't have in their base image and not easy to maintain on the hosted platform. It does not look like they are keen on allowing users to extend their base agent for pipeline for this.

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
