### ISSUE TITLE
page outdated

### ISSUE THREAD

**Issue by tiagoroxo** [MicrosoftDocs/azure-devops-docs#7462] opened 2020-03-02 09:59 UTC
Please update the TFS name to Azure DevOps Server
"What is Azure DevOps Server?
Collaborative software development tools for the entire team
Previously known as Team Foundation Server (TFS), Azure DevOps Server is a set of collaborative software development tools, hosted on-premises. Azure DevOps Server integrates with your existing IDE or editor, enabling your cross-functional team to work effectively on projects of all sizes."
More Details: https://azure.microsoft.com/en-gb/services/devops/server/

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* Content: [Create a service hook Microsoft Teams - Azure DevOps Services, TFS 2017](https://docs.microsoft.com/en-gb/azure/devops/service-hooks/services/teams?view=azure-devops#configuring-a-new-connector-for-tfs)
* Content Source: [docs/service-hooks/services/teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri1, devops-collab/tech, devops/prod, doc-bug
