### ISSUE TITLE
Both the parameters are not optional, description needs to be better

### ISSUE THREAD

**Issue by atrauzzi** [MicrosoftDocs/azure-devops-docs#3148] opened 2019-01-27 05:44 UTC
If you add this task without providing a parameter, it errors out.  I'm not sure I understand what this task does either, it's not clear whether this will provide authentication details for my Azure Devops private repositories or if it is used for something else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd3386c8-fd1f-903d-605b-725c60157f9e
* Version Independent ID: e5c90de9-eab7-6aef-d89e-edf3e5d6010e
* Content: [npm Authenticate task (for task runners) - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm-authenticate?view=azdevops)
* Content Source: [docs/pipelines/tasks/package/npm-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/npm-authenticate.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by elbatk** [comment] 2019-02-07 17:58
Hi @atrauzzi , I'm going to add @mitchdenny here for some help. Mitch, how is it that both of these properties are optional? As far as what this task does, it's specifically for authenticating npm with task runners like gulp or Grunt within an Azure DevOps Pipeline. If you're using the actual npm task to do your work in a pipeline, you won't need to use this authenticate task.

**Comment by mitchdenny** [comment] 2019-02-11 06:32
@steved0x can you provide an example of the error you are seeing? It might just be some assumptions we have baked into the task.

**Comment by elbatk** [comment] 2019-02-11 14:23
I think @mitchdenny meant to tag the issue author, @atrauzzi :)

**Comment by mitchdenny** [comment] 2019-02-11 14:56
Ah yes! Sorry.

**Comment by atrauzzi** [comment] 2019-02-19 13:48
@mitchdenny 

>If you add this task without providing a parameter

**Comment by mitchdenny** [comment] 2019-02-20 06:10
Adding @elbatk this is probably something you want to consider around auth :)

**Comment by jotaylo** [comment] 2019-03-08 19:51
The first one is indeed required, but the second is optional (custom endpoints only need to be specified for feeds in a different organization or third party feeds, not feeds in the current organization)

**Comment by atrauzzi** [comment] 2019-03-10 18:23
Yeah, but it shouldn't be.  Most people just want to add authentication to the current series of tasks.

It *should support* having no parameters so that the file can be created automatically.  This alleviates the burden of having to explicitly manage the file.

**Comment by petong** [comment] 2019-04-12 23:35
Any update to this? I am seeing an error trying to use this:

##[error]Error: The file you selected to authenticate (/home/vsts/work/1/s) is not a valid .npmrc file.

The documentation states that workingFile is optional. I am trying to use this task to use a Service Connection to publish to npmjs.

**Comment by awentzel** [comment] 2019-06-20 21:42
Additionally, if you follow the instructions, and leave the optional credential field empty, to leverage the use of the project .npmrc file, it will not authenticate for private registries even if they are both in the same account/collection.

**Comment by awentzel** [comment] 2019-06-20 21:42
I recommend further clarifying the use case for accessing private and public feeds.

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug

**Comment by atrauzzi** [comment] 2020-11-26 02:03
Yikes, that's a bad automation.
