### ISSUE TITLE
Document how to pass arguments to script

### ISSUE THREAD

**Issue by tkawchak** [MicrosoftDocs/azure-devops-docs#7521] opened 2020-03-06 18:11 UTC
There is no clear demonstration on how to pass arguments to a script.  Should multiple variables all be specified on one line?  Should all of the arguments be contained in quotes?  

This page should provide an example of how to pass arguments to a script file just like this section does for the AzurePowershell@4 Task: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops#samples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47d0c973-d722-9ae3-10a7-adfe396fc223
* Version Independent ID: 42661879-914d-c775-21ac-0526aa79bd75
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, doc-bug
