### ISSUE TITLE
Argument names

### ISSUE THREAD

**Issue by cptnalf** [MicrosoftDocs/azure-devops-docs#6133] opened 2019-10-24 19:22 UTC
The argument names don't match any of the yaml-syntax names.  While one can infer the parameters, it would be nice if the parameter names were explicitly called out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add63018-4f2c-f258-76ea-9f76aa43ff09
* Version Independent ID: c71f17c9-9a78-396e-7a0f-ad8b52b01724
* Content: [Archive Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/archive-files?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/archive-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/archive-files.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment] 2019-10-24 19:58
@steved0x are we going to do any updates to the task docs to map friendly names and YAML names?

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
