### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by jcace** [MicrosoftDocs/azure-devops-docs#7803] opened 2020-04-02 15:56 UTC
Followed this article exactly, multiple times (re-starting from scratch each time). It will not work. The deployment always runs OK, but in the container logs, the following error message shows up:

`ERROR - DockerApiException: Docker API responded with status code=NotFound, `
and 
`ERROR - Image pull failed: Verify docker image configuration and credentials (if using private repository)`

ACR credentials are correct in the Container configuration. And interestingly, it deploys just fine using the built-in "Continuous Deployment" feature (ie https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-ci-cd). It just doesn't seem to deploy from the DevOps Release pipeline. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593c3abc-7b38-6673-62b6-7787d0dda4dd
* Version Independent ID: cbb2b875-b220-596c-7b4d-c2cf6c644335
* Content: [Deploy a Docker container app - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-docker-webapp?view=azure-devops&tabs=java)
* Content Source: [docs/pipelines/apps/cd/deploy-docker-webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-docker-webapp.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by jcace** [comment] 2020-04-02 15:58
Here is the log message when it deploys **successfully** via "Continuous Deployment
`2020-04-02 15:12:07.267 INFO  - Pulling image: xxcontainerregistry.azurecr.io/dev-image:71`

Here is the log message right before it fails, with Release pipeline
`2020-04-02 15:40:55.205 INFO  - Pulling image: xxcontainerregistry.azurecr.io/dev-image`

**Comment by jcace** [comment] 2020-04-02 22:26
Finally found the problem. The Build artifact was not specified for the pipeline, so it could not access the tag "$(Build.BuildId)" - tag was set to empty when it tried to pull the docker image. Curious as to why it didn't work, my understanding is it would default to ":latest" and pull the latest one.

**Comment by cxwtool** [comment] 2020-11-24 23:28
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:28 UTC
Labels: Pri1, devops-cicd-apps/tech, devops/prod
