### ISSUE TITLE
Mono version selection on Mac may require to update symlink

### ISSUE THREAD

**Issue by pleonex** [MicrosoftDocs/azure-devops-docs#4138] opened 2019-05-03 21:54 UTC
Right now the way to select which Mono version to use on Mac is based on updating some environment variables. However, some tools like [Cake look into a hard-coded path](https://github.com/cake-build/cake/blob/f48c6a9a253e62334474f5053cd6a23b8b520c23/src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs#L17) for the version with name `Current`. This is a symlink to the expected "current" version installed on the machine.

To make work these tools, there is an extra-step apart from update the environment variables which is to update the `Current` symlink as follow:

```bash
sudo rm /Library/Frameworks/Mono.framework/Versions/Current
sudo ln -s $MONOPREFIX /Library/Frameworks/Mono.framework/Versions/Current
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
