### ISSUE TITLE
Add information about when the system evaluates the input parameters of the task

### ISSUE THREAD

**Issue by Danchoys** [MicrosoftDocs/azure-devops-docs#7340] opened 2020-02-19 14:10 UTC
From my experience the system checks the secure file existence and permissions at compile time of the pipeline before the job containing this step is run. Therefore you can't use runtime expressions (`$[ ... ])` or macros (`$(...)`) for the secureFile input parameter. Furthermore if you are using a template expression (`${{ }}`) and it resolves to something that doesn't exist, the pipeline will crash at compile time before the actual job even starts. This can be problematic in case the job is not even supposed to be run, but that step inside of it will prevent the whole pipeline from running.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* Content: [Download Secure File task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-secure-file.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by GooDVim** [comment] 2020-02-21 13:05
I agree - it's not possible to parametrise this task.

**Comment by cxwtool** [comment] 2020-11-24 23:31
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:31 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
