### ISSUE TITLE
NodeTool@1 in sample code should be UseNode@1 instead

### ISSUE THREAD

**Issue by cremor** [MicrosoftDocs/azure-devops-docs#13800] opened 2023-11-17 12:37 UTC
As far as I can tell there is no `NodeTool@1` task. It is called `UseNode@1`.
See also https://github.com/MicrosoftDocs/azure-devops-docs/issues/13748#issuecomment-1805656807

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f617d-59c1-f3d4-d322-88ae5301d9b2
* Version Independent ID: df0db0d1-21da-ce6f-1f74-34b4be1d9ff3
* Content: [Quickstart - Use Azure Pipelines to build and publish a Node.js package - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/javascript?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/javascript.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/javascript.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment] 2023-11-20 06:40
Duplicate of #13748.

**Closed by WilliamAntonRohm** 2023-11-20 06:40 UTC
Labels: duplicate, cba, Pri1, azure-devops/svc, azure-devops-ecosystem/subsvc

**Comment by cremor** [comment] 2023-11-20 06:55
@WilliamAntonRohm #13748 is closed and I didn't get any response on my comment after it was closed. That's the only reason why I created this new issue.
Could you please reopen #13748?
