### ISSUE TITLE
Give Example on Multiline Patterns

### ISSUE THREAD

**Issue by sensslen** [MicrosoftDocs/azure-devops-docs#8237] opened 2020-05-07 14:11 UTC
When trying to match Files I came accross the question whether a file must match all given patterns or just one.
Is it possible to control this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd54e81-9a0c-c5e5-fb89-9534372805ff
* Version Independent ID: f3d49618-32d7-0abc-1c33-8211eb7dd073
* Content: [File matching patterns reference - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/file-matching-patterns.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/file-matching-patterns.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, doc-enhancement
