### ISSUE TITLE
How to define triggers when multiple jobs

### ISSUE THREAD

**Issue by Gimly** [MicrosoftDocs/azure-devops-docs#3254] opened 2019-02-06 15:54 UTC
From the documentation it's quite unclear where the `trigger` and `pr` option go if you have multiple jobs. 

Can it be added globally? In that case, should it go at the same level of `jobs`? Can it be added on a per-job basis, in which case would it go at the same level as `variables` and `steps`?

Both the online editor and the VSCode extension seem to complain wherever you put it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment] 2019-02-15 20:57
`trigger` and `pr` are both pipeline-level. You cannot trigger at the job level. Each of these are valid (and we'll get the schema parser fixed to reflect this):

```yaml
# Implicit single job
trigger:
  branches:
  - master
steps:
- script: echo foo

# Explicit single job
trigger:
  branches:
  - master
jobs:
- job: A
  steps:
  - script: echo foo

# Multi job
trigger:
  branches:
  - master
jobs:
- job: A
  steps:
  - script: echo foo
- job: B
  steps:
  - script: echo bar
```

**Comment by ryanfitzer** [comment] 2019-04-08 21:52
It seems like this means all jobs will run run on push to `master` in your examples. Is there a way to have multiple jobs, with each having their own trigger? I'd like `job1` to be triggered on push to `branch1` and have `job2` to be triggered on push to `branch2`.

Not able to find this in the docs.

**Comment by vtbassmatt** [comment] 2019-04-09 12:13
@ryanfitzer sorry, that's not something we support. You could conditionalize your jobs to only run when branches they care about are responsible for the push.

**Comment by andyjlewis** [comment] 2019-05-30 17:13
@vtbassmatt did the parser fix you mentioned above happen? is there a doc fix we still need to make?

**Comment by bender2k14** [comment] 2019-06-03 10:58
> Is there a way to have multiple jobs, with each having their own trigger? I'd like `job1` to be triggered on push to `branch1` and have `job2` be triggered on push to `branch2`.
> ~ @ryanfitzer

You could do this if you put these jobs in different pipelines.

Is there a reason you want these jobs in the same pipeline?

**Comment by vtbassmatt** [comment] 2019-06-03 11:53
@andyjlewis I believe the syntax highlighter parser has been fixed. I'm slightly negative on a doc fix, unless we want to explicitly say "triggers apply to the entire pipeline" somehow. And that doesn't feel like it belongs in the schema doc.

**Comment by ryanfitzer** [comment] 2019-06-03 17:04
@bender2k14 

> Is there a reason you want these jobs in the same pipeline?

I want to run different tasks based on the branch. Right now, we run the full build on commit to `master`, which publishes the `dist` assets. My goal is to at least cut out the asset task when the branch is not `master`. I'm new CI/CD (and Azure) and I've found the docs very helpful, except on this aspect.

**Comment by bender2k14** [comment] 2019-06-04 11:36
As the [documentation shows](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pipeline-structure), each pipeline contains some number of stages, each stage contains some number of jobs, and each job contains some number of steps.

What you want to use is included and excluded [branch triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#triggers).  In the pipeline that publishes your assets, add
```
trigger:
- master
```

and in the pipeline that doesn't publish your assets, add
```
trigger:
  branches:
    exclude:
    - master
```

**Comment by henryhwang** [comment] 2019-07-11 05:25
One way to do this is to use different versions of pipeline (azure-pipeline.yml file) for different branch in your project.

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
