### ISSUE TITLE
Unclear role of "mavenOptions" and "goals" fields

### ISSUE THREAD

**Issue by algattik** [MicrosoftDocs/azure-devops-docs#3845] opened 2019-04-03 11:39 UTC
I was trying to run "mvn package -DskipTests -Pspark-2.4".

Therefore I tried the following:

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m -DskipTests -Pspark-2.4'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
which failed with:

Unrecognized option: -P
Error: Could not create the Java Virtual Machine.
After some trial and error, I changed to the following, which succeeded.

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package -DskipTests'

This is pretty confusing, as apparently the "mavenOptions" field is not actually for Maven options, but for JVM options. Also apparently any extra maven options need to be put into the goals field, although they are not goals! I wonder if the field names could be made clearer, and the documentation could be expanded to make this easier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e076c-9f67-77df-3204-4f549566f21b
* Version Independent ID: 2e51ef13-8fd3-1397-82f0-27c92f1ccee5
* Content: [Maven build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by titimoby** [comment] 2020-03-13 10:36
Any news on progress on this issue?
What's the best workaround advised?

**Comment by algattik** [comment] 2020-03-13 14:55
@titimoby the workaround I explain works well. It's more that the field names are confusing.

**Comment by titimoby** [comment] 2020-03-13 15:05
Oh, thanks @algattik  , it actually works well.
I just wanted to be sure that there were no other options or drawback to the goal solution.
It is fine for me now.
But it will be great to have some estimate on a proper solution

**Comment by haokanga** [comment] 2020-03-13 18:44
I agree with @algattik "mavenOptions" and "goals" fields are confusing. 

I would say one way to address the confusion is that the Azure Doc should include worked examples on **how to translate worked mvn CLI commands into Maven tasks**.

For example, the Azure doc of Maven task should include: if the mvn commands is

```
export MAVEN_OPTS="-Xmx3072m"
mvn clean package -Dmaven.test.skip=true
```

**what should be the Maven Task equivalent**.

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri2, devops-cicd/tech, devops/prod

**Comment by anbuanand** [comment] 2021-06-17 21:18
-P option is not working, should be supported.
Or what is the workaround, I am stuck, have to use "script" instead of the maven task ??
