### ISSUE TITLE
Please provide example with yaml based pipeline..

### ISSUE THREAD

**Issue by rajdhandus** [MicrosoftDocs/azure-devops-docs#7668] opened 2020-03-22 02:54 UTC
This page talks about creating a UI based Release pipeline... the new pipelines are now being created are yaml based format. please update this  example accordingly..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 079492cb-bdc3-7ba6-8581-dd76391cda4f
* Version Independent ID: 81e719d4-b127-fa41-4cf2-421e91b9d4be
* Content: [Canary deployment strategy for Kubernetes deployments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/canary-demo?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/kubernetes/canary-demo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/kubernetes/canary-demo.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by cxwtool** [comment] 2020-11-24 23:29
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:29 UTC
Labels: Pri2, devops-cicd-ecosystems/tech, devops/prod, doc-bug
