### ISSUE TITLE
XML variable substitution

### ISSUE THREAD

**Issue by Bazul99** [MicrosoftDocs/azure-devops-docs#7040] opened 2020-01-23 16:29 UTC
Is it true that variable substitution on XML .config files limited *only* to appSettings, applicationSettings, and connectionStrings?

There's no way for example to substitute machine keys in a config file's system.web section if you didn't want to keep the keys in source control?

  &lt;system.web&gt;
    &lt;machineKey decryptionKey="{hex-key value}" validationKey="{hex-key value}" /&gt;
  &lt;/system.web&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 064f48ba-1c34-6422-5fe3-c3e88d2803c4
* Version Independent ID: c38f5761-4718-9aae-bc83-063257a78eb3
* Content: [File Transform task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/file-transform?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/file-transform.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/file-transform.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by pozy** [comment] 2020-04-21 08:03
Looks like it is true unfortunately:/. Only *.config files and only "applicationSettings", "appSettings", "connectionStrings", "configSections" nodes are taken into account during variables substitution in XML files.
Source code:
https://github.com/microsoft/azure-pipelines-tasks/blob/241a7bc367f3355fa364c2ba8dea42627b7d806a/Tasks/Common/webdeployment-common-v2/xmlvariablesubstitutionutility.ts#L84

**Comment by cameronsibbald** [comment] 2020-05-07 17:29
There is a community contributed task (thanks to Guillaume Rouchon)that you can use for variable substitution in other file types that contain tokens that is not restricted to "applicationSettings", "appSettings", "connectionStrings", and "configSections" nodes.

https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
