### ISSUE TITLE
Build.Clean alternative is unclear

### ISSUE THREAD

**Issue by Seikilos** [MicrosoftDocs/azure-devops-docs#4297] opened 2019-05-22 10:28 UTC
While looking for a way of periodically clean the working directory of a build I reached this site. It contains a hint to the deprecated `Build.Clean` variable and links to a page, that does not explain how to actually clean sources occasionally without some external tool or extra jobs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment] 2019-05-22 15:42
Thanks for the feedback. We need links to topics like this: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#clean-build. Heads up to @steved0x

**Comment by Seikilos** [comment] 2019-05-22 16:18
@andyjlewis correct. Although the referenced docs point to persistent settings for cleaning. AFAIK it does not cover the scenario where sometimes residual files have to be cleaned by an user that starts a build. The pipeline settings mentioned in the link above would require elevated permissions and a manual reset of the clean setting after it has cleaned the workspace once.

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
