### ISSUE TITLE
Conditional logging is not addressed

### ISSUE THREAD

**Issue by Falven** [MicrosoftDocs/azure-devops-docs#7888] opened 2020-04-09 23:32 UTC
This document does not mention any of these other logging methods...
# Write your powershell commands here.

Write-Host "##[section] This is colored green!"
Write-Host "##[command] This is colored blue!"
Write-Host "##[debug] This is colored gray!"
Write-Host "##[warning] This is a warning!"
Write-Host "##vso[task.logissue type=warning;]This is another warning" 
Write-Host "##[error] This is an error!"
Write-Host "##vso[task.logissue type=error;]This is another error"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#feedback)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by cxwtool** [comment] 2020-11-24 23:28
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:28 UTC
Labels: Pri1, devops-cicd-scripts/tech, devops/prod, doc-enhancement
