### ISSUE TITLE
Notification of changes in firewall requirements

### ISSUE THREAD

**Issue by bjowes** [MicrosoftDocs/azure-devops-docs#5928] opened 2019-10-10 13:08 UTC
Our organization is actively using Azure DevOps behind a corporate firewall. In the spring of 2019 we made an effort to become compliant with all the firewall white-list rules recommended on this page. 

As we are experiencing intermittent issues since some months back we started investigating this again. And it appears that the white-list rules were changed. 

1) Is there any way to receive notifications of such changes that impact our infrastructure? It would be most helpful, I don't see "checking in on this page occasionally" as a solution.

2) I would also like to see a compliance testing page. We found [this page from the Azure DevOps blog](https://status.dev.azure.com/_ipcheck) but it is unclear which rules it validates, I presume it only checks for the new IP ranges mentioned in the related blog post. A complete compliance testing page would be awesome to be able rule out firewall issues when troubleshooting.

3) Our firewall does not support wildcard FQDNs in the white-list. We are just hoping that addresses used by https://*.dev.azure.com are already included in the IP ranges, but this is not clearly stated in the text. In any case, please strive to provide non-wildcard FQDNs or IP ranges only, since some firewalls cannot handle wildcard FQDNs.

4) The FQDN list mentioned on this page is not complete. We are using the npm repository in Azure DevOps, and we needed to open up additional FQDNs to make that work, for instance *.blob.core.windows.net. The page where we found the requirements for Azure DevOps packaging service was [this one](https://docs.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server). I think it would help out if your page referenced that one (and possibly others?) when detailing the required firewall rules. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by bjowes** [comment] 2019-10-10 21:59
Thanks @msebolt - I've set up a subscription on the agent docs. This will probably be ok for Item 1 as long as the documentation structure won't change.

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
