### ISSUE TITLE
Only master branch migrate to remote 

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/azure-devops-docs#954] opened 2018-06-01 01:27 UTC
When I do mirror push on TFS2015 update 4, I can see something like 
root@redmine:/tmp/myproject# git push --mirror http://mytfs.com.tw:8080/tfs/SDD/DevOpsinfra/_git/myproject
Counting objects: 1005, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (448/448), done.
Writing objects: 100% (1005/1005), 147.85 KiB | 0 bytes/s, done.
Total 1005 (delta 527), reused 1005 (delta 527)
remote: Analyzing objects... (1005/1005) (58 ms)
remote: Storing packfile... done (338 ms)
remote: Storing index... done (69 ms)
To http://mytfs.com.tw:8080/tfs/SDD/DevOpsinfra/_git/myproject
 * [new branch]      master -> master
 * [new branch]      origin/HEAD -> origin/HEAD
 * [new branch]      origin/feature-DIR-424 -> origin/feature-DIR-424
 * [new branch]      origin/master -> origin/master
But I can only see master branch on TFS WebUI
What I have done is:
git clone \<old project url\>
cd \<old project\>
git clone --mirror \<new empty repo url\>
git push --mirror  \<new empty repo url\>
Any thing I did wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b779541e-e77e-38e7-7134-fa1f4c698899
* Version Independent ID: fe82ec27-4640-d0f2-3978-01400e2b719b
* Content: [Move Git repositories between Team Projects](https://docs.microsoft.com/en-us/vsts/articles/move-git-repos-between-team-projects?view=vsts)
* Content Source: [docs/articles/move-git-repos-between-team-projects.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/articles/move-git-repos-between-team-projects.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @wpschaub
* Microsoft Alias: **willys**

**Comment by johnsivertsen** [comment] 2019-01-08 11:14
I had the same problem. This guide is missing some step. Following https://docs.microsoft.com/en-us/azure/devops/repos/git/import-git-repository?view=vsts&tabs=new-nav#manually-import-a-repo I was able to perform the migration

**Comment by cxwtool** [comment] 2020-11-24 23:50
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:50 UTC
Labels: Pri2, devops-whitepapers/tech, devops/prod, doc-bug, unspecified/svc
