### ISSUE TITLE
Required and optional arguments

### ISSUE THREAD

**Issue by tmahncke-lhind** [MicrosoftDocs/azure-devops-docs#8131] opened 2020-04-29 07:47 UTC
From the documentation above I find it very hard to understand which arguments must be provided and which don't. Do I have to give a value in my pipeline that is required but has a default value? If not, what is the difference between a required value with default false and an optional value with default false?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e076c-9f67-77df-3204-4f549566f21b
* Version Independent ID: 2e51ef13-8fd3-1397-82f0-27c92f1ccee5
* Content: [Maven build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, doc-bug
