### ISSUE TITLE
You will see this parameter 

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/azure-devops-docs#6741] opened 2019-12-19 22:27 UTC
In the Arguments section, under runtimeStack, awkward unclear wording "You will see this parameter only when..." seems to be a cut&paste from a GUI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d955bb83-fa46-22e0-de73-7700ae214af8
* Version Independent ID: 1f55672f-711e-24fa-e6bc-edc0ca723eba
* Content: [Azure Web App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug

**Comment by HughDevlin** [comment] 2020-12-02 21:15
Please re-open this issue.

Please clarify the description of the runtimeStack argument.
