### ISSUE TITLE
Documentation on flag CompressSymbols is ambiguous

### ISSUE THREAD

**Issue by FrankHeimes** [MicrosoftDocs/azure-devops-docs#6992] opened 2020-01-19 08:54 UTC
The YAML snippet says:
"#compressSymbols: false # Required when symbolServerType == FileShare"
I interpret this so that PDB compression must be disabled when using a file share.
This would comply to the fact that Task 'Index Sources & publish Symbols' (2.*) does not provide a checkbox for enabling compression.
But at the bottom, the page says:
"CompressSymbols  (Required) Only available when File share is selected as the Symbol server type."
implying that the flag is only usable if a file share is used.
The latter actually makes more sense.
So which one is correct and why can't I enable compression in the TFS task?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946d67f6-9bb7-481f-f32f-59b5965f9590
* Version Independent ID: 8865f1e2-15b3-8cdb-1d8c-939c665e9bdc
* Content: [Index Sources & Publish Symbols - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/index-sources-publish-symbols?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/index-sources-publish-symbols.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/index-sources-publish-symbols.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by FrankHeimes** [comment] 2020-01-19 09:00
... if "Required" referred to the parameter and not its value, then the documentation should read:
"CompressSymbols   Only required when File share is selected as the Symbol server type. ..."

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
