### ISSUE TITLE
Missing vcpkg example

### ISSUE THREAD

**Issue by jwillemsen** [MicrosoftDocs/azure-devops-docs#4988] opened 2019-07-24 14:47 UTC
Would be helpful when there is also an example using vcpkg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops&lc=1033#feedback)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by N-Dekker** [comment] 2019-08-14 14:23
Thanks @jwillemsen It would also be very helpful to me, to see an example of how to specify by `CacheBeta` in an Azure Pipelines yml file, to reuse a previously installed "C:\vcpkg\installed" directory, including previously built third party binaries.

**Comment by N-Dekker** [comment] 2019-08-16 18:11
Related blog post by  @tara-raj: https://devblogs.microsoft.com/cppblog/vcpkg-2019-07-update

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
