### ISSUE TITLE
Provide cache example for Go

### ISSUE THREAD

**Issue by qmuntal** [MicrosoftDocs/azure-devops-docs#8917] opened 2020-07-23 03:04 UTC
Please provide an example on how to use pipeline caching with Go.

How to invoke go to use the cache?
How to store the cache?
How to restore the cache?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by cxwtool** [comment] 2020-11-24 23:14
This issue hasn't been updated in more than 120 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:14 UTC
Labels: Pri2, devops-cicd-release/tech, devops/prod, doc-enhancement
