### ISSUE TITLE
Automated Test and Test Cases

### ISSUE THREAD

**Issue by emendezsg** [MicrosoftDocs/azure-devops-docs#3746] opened 2019-03-22 17:06 UTC
I want to associate Test Case to an automated test using Selenium. It's that possible? I have been associating test to the test cases using VS 2017 Pro, but when the automated test is executed in a release pipeline, seems like the result report doesn't show anything related to the test cases.

https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=azure-devops

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri3, devops-cicd/tech, devops/prod, doc-bug
