### ISSUE TITLE
Query agent online/offline status

### ISSUE THREAD

**Issue by sgh-msft** [MicrosoftDocs/azure-devops-docs#3163] opened 2019-01-28 22:44 UTC
Is there a convenient way to query the status of an agent in a demand or a conditional on a job? I find myself running into the message "All eligible agents are disabled or offline" a lot which causes my build pipeline to wait forever to queue when I would rather have it fail and let the pipeline finish

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54bf6c2f-95c1-943d-26ae-d7099143bccf
* Version Independent ID: 0833bb55-1e54-6953-ee69-de6d191d2ec1
* Content: [Build and release jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azdevops&tabs=yaml)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment] 2019-02-05 15:19
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by chrisrpatterson** [comment] 2019-02-06 14:02
I am not sure I understand this question or the scenario.

**Comment by sgh-msft** [comment] 2019-02-06 16:13
Let me try rephrasing, is there a way to stipulate that a job is queued only if a certain agent is online? We keep running into an issue where the only eligible agent for a job goes offline and the build waits forever

**Comment by subudear** [comment] 2019-09-18 09:25
Any solution for this problem raised in this????

**Comment by sgh-msft** [comment] 2019-09-18 17:57
@subudear I never got any resolution on this, it's particularly a problem when our builds get backed up over a weekend 🙁

**Comment by subudear** [comment] 2019-09-19 06:09
I think I have a solution. Let me explain my issue which I was working on. Probably the solution will work for you as well. I have Win and Linux based private build agents. I delete these VMs daily and recreate them every morning and configure the build agents (to save cost). Now this all works fine using scripts. I needed to monitor these VMs status (up or down) and whether build agent is offline or online after creation of VM and configuration. I am using azure automation runbook and using the below WebRequest to get build agent status (online or offline).

Use this request to get pool details (get the poolid from the output (id in the output will be poolid)) 
- https://dev.azure.com/{replace with organization}/_apis/distributedtask/pools?api-version=5.1

Now run this request to get all agents in the pool and there details (get the agentid from the output) -
https://dev.azure.com/{replace with organization}/_apis/distributedtask/pools/{replacepoolid}/agents?api-version=5.1

Run this request to get the details of specific build agent (it will have Status in the output)-

https://dev.azure.com/{replace with organization}/_apis/distributedtask/pools/{replacepoolid}/agents?agentid={replace agentid}&api-version=5.1

Feel free to ask if you have any queries. to my knowledge, pipeline doesn't have any way right now to find whether build agent is offline or not. But monitoring them can help avoid such situation.

**Comment by spitfire184** [comment] 2020-02-27 16:53
Please can we have this as a feature, perhaps exposed through the demands?

**Comment by WilliamAntonRohm** [comment] 2020-03-29 00:16
@subudear -- thank you for contributing.

@spitfire184 -- thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here. 

@vijayma -- please look into this issue.

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
