### ISSUE TITLE
failed to create pipeline agent in docker for DevOps Server 2019 Update 1

### ISSUE THREAD

**Issue by cyrilzh** [MicrosoftDocs/azure-devops-docs#6153] opened 2019-10-28 01:18 UTC
I am following https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops to create a pipeline agent in Linux docker.

It works fine in Azure DevOps Server 2019 but not in Azure DevOps Server 2019 update 1. The PAT authentication in start.sh script failed. The issue can be reproduced by running the following script against a DevOps 2019 server.  It will return empty result and logged 401 in IIS log.

curl -LsS -u user:[PATToken] -H 'Accept:application/json;api-version=3.0-preview' "https://[servername]/_apis/distributedtask/packages/agent?platform=linux-x64"

I cannot believe this is caused by some product bug since this is a such essential function. If this is not the case, could you please update the document for Azure DevOps Server 2019 update 1?

**Comment by msebolt** [comment] 2019-10-28 19:06
@cyrilzh  Thank you for the feedback, assigning this to the author for review.

Please also consider involving the product team by using the **Report a problem** feature in [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and linking back to this issue.

**Comment by cyrilzh** [comment] 2019-10-29 02:28
Thanks @msebolt. Here is the link in Azure DevOps Community. 

https://developercommunity.visualstudio.com/content/problem/795513/azure-devops-server-2019-update-1-pat-authenticati.html

Please feel free to let me know if any more information is needed. BTW, the problem can be reproduced by authenticating with PAT in Postman as well.

**Comment by cyrilzh** [comment] 2019-10-31 09:19
I found the answer. In  DevOps 2019 server, the following script works fine. 
curl -LsS -u user:[PATToken] -H 'Accept:application/json;api-version=3.0-preview' "https://[servername]/_apis/distributedtask/packages/agent?platform=linux-x64"

In  DevOps 2019 server Update 1, the above script doesn't work. Organization name is required in URL. So the script for DevOps 2019 update 1 is:

curl -LsS -u user:[PATToken] -H 'Accept:application/json;api-version=3.0-preview' "https://[servername]/[**organizationname**]_apis/distributedtask/packages/agent?platform=linux-x64"

I think this should be updated to document since the script in the current document doesn't work in update 1 version.

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri3, doc-enhancement
