### ISSUE TITLE
The Graphics are out-of-date on this page about running automated tests.

### ISSUE THREAD

**Issue by sulu99** [MicrosoftDocs/azure-devops-docs#6663] opened 2019-12-12 21:22 UTC
The graphics need an update for Azure-related automated tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6c92a2-2f5c-e34e-f285-3e1a2a02604b
* Version Independent ID: 6f31f4c2-94ac-20eb-da01-e1d47f041945
* Content: [Run automated tests from test plans - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/run-automated-tests-from-test-hub?view=azure-devops&source=docs#feedback)
* Content Source: [docs/test/run-automated-tests-from-test-hub.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/run-automated-tests-from-test-hub.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2019-12-13 06:14
@sulu99 Thank you for the feedback, assigning this to the author for review.

**Comment by Additi** [comment] 2019-12-20 09:07
Hi,
Can you help me understand what exactly do you refer to when you say "Azure-related automated tests"?

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri1, devops-test/tech, devops/prod, doc-enhancement
