### ISSUE TITLE
What are the valid options?

### ISSUE THREAD

**Issue by noelbundick** [MicrosoftDocs/azure-devops-docs#5105] opened 2019-08-01 23:59 UTC
For some properties, it's not clear what the valid or available options are without going to GitHub and reading the Task source.

Ex: `appType` looks like it could possibly be `functionApp`, `functionAppLinux`. There's also a `webAppLinux` option mentioned in the text, which isn't present in the source code task.json - though it notably is used in the `AzureWebApp@1` task

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82ad1fa-cee5-c5c6-7050-21aaec6b714a
* Version Independent ID: 617316ff-2dab-d021-880f-c1c79313c320
* Content: [Azure Function App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-function-app.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-function-app.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment] 2019-08-06 20:24
@noelbundick Thank you for the feedback.

This sort of documentation should first be available via the **README** at  [azure-pipelines-tasks repo](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFunctionAppV1), since this article is more of an example to get started.

Please consider transferring the issue there.

Re-assigning to the author.

**Comment by M0ns1gn0r** [comment] 2019-11-15 13:19
This seems to be a general problem with Pipelines tasks documentation. The arguments are not properly documented.

**Comment by SikoSoft** [comment] 2020-03-02 08:11
"Silly person looking at Azure DevOps pipeline documentation for information related to running the pipelines. You should have gone to the source code for this repo and looked there instead!"

Alrighty. Yeah, that README that doesn't even contain the formatted strings you were looking for... Nah, better dig deeper in the code, cause this here "article" is only intended on covering whatever it managed to cover for whoever it covered it for. Why would putting the relevant values possible provide any value when that's precisely the sort of thing these documentation pages are used for?

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
