### ISSUE TITLE
How do pools load-balance?

### ISSUE THREAD

**Issue by DaveWhite** [MicrosoftDocs/azure-devops-docs#7008] opened 2020-01-21 15:10 UTC
If I have a pool with 4 agents on one VM, where agents 1 and 3 are on C: and agents 2 and 4 are on D:
I would expect that the order would be 1-&gt;2 when 2 simultaneous builds are triggered. However it seems that the order is actually 1-&gt;3, which means I have more activity on one disk.
Can the load-balancing be explained?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser#feedback)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
