### ISSUE TITLE
##[error]Error: Preparing the test sources file failed. Error : Error: No test sources found matching the given filter '**\release\*test*.dll,!**\obj\**'

### ISSUE THREAD

**Issue by mallikarjun364** [MicrosoftDocs/azure-devops-docs#6542] opened 2019-12-03 14:23 UTC
Hi,

i'm getting this error in CICD pipeline log

##[error]Error: Preparing the test sources file failed. Error : Error: No test sources found matching the given filter '**\release\*test*.dll,!**\obj\**'

earlier message was showing as warning but now its an error and i'm not doing any test.

thank you

**Comment by WilliamAntonRohm** [comment] 2019-12-04 00:20
@mallikarjun364 -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by mallikarjun364** [comment] 2019-12-04 04:40
@WilliamAntonRohm the topic is CICD pipeline integration in VSTS

**Comment by WilliamAntonRohm** [comment] 2019-12-04 18:04
@mallikarjun364 -- thank you for clarifying.  Please provide the topic URL.

**Comment by mallikarjun364** [comment] 2019-12-05 05:16
@WilliamAntonRohm  the topic url is https://docs.microsoft.com/en-us/azure/devops/pipelines/overview?view=azure-devops-2019

**Comment by D4rkiii** [comment] 2019-12-05 10:11
We are getting the same error.
We queued a build today (last build was on friday and worked fine) and the build fails in the "Visual Studio Test" step.

**Friday build log from the test step:**
##[section]Starting: VsTest - testAssemblies
==============================================================================
Task         : Visual Studio Test
Description  : Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test (VsTest) runner. Test frameworks that have a Visual Studio test adapter such as MsTest, xUnit, NUnit, Chutzpah (for JavaScript tests using QUnit, Mocha and Jasmine), etc. can be run. Tests can be distributed on multiple agents using this task (version 2).
Version      : 2.160.4
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest
==============================================================================
SystemVssConnection exists true
SystemVssConnection exists true
SystemVssConnection exists true
Running tests using vstest.console.exe runner.
======================================================
Test selector : Test assemblies
Test filter criteria : null
Search folder : D:\a\1\s
VisualStudio version selected for test execution : latest
Attempting to find vstest.console from a visual studio installation with version [16.0,17.0).
Attempting to find vstest.console from a visual studio build tools installation with version [16.0,17.0).
Attempting to find vstest.console from a visual studio installation with version [15.0,16.0).
Run in parallel : false
Run in isolation : false
Path to custom adapters : null
Other console options : null
Code coverage enabled : false
Diagnostics enabled : true
SystemVssConnection exists true
Run the tests locally using vstest.console.exe
========================================================
##[warning]No test assemblies found matching the pattern: **\release\*test*.dll,!**\obj\**.
======================================================
##[section]Finishing: VsTest - testAssemblies


**Today build log from the test step:**
##[section]Starting: VsTest - testAssemblies
==============================================================================
Task         : Visual Studio Test
Description  : Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test (VsTest) runner. Test frameworks that have a Visual Studio test adapter such as MsTest, xUnit, NUnit, Chutzpah (for JavaScript tests using QUnit, Mocha and Jasmine), etc. can be run. Tests can be distributed on multiple agents using this task (version 2).
Version      : 2.161.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest
==============================================================================
SystemVssConnection exists true
SystemVssConnection exists true
SystemVssConnection exists true
Running tests using vstest.console.exe runner.
======================================================
Test selector : Test assemblies
Test filter criteria : null
Search folder : D:\a\1\s
VisualStudio version selected for test execution : latest
Attempting to find vstest.console from a visual studio installation with version [16.0,17.0).
Attempting to find vstest.console from a visual studio build tools installation with version [16.0,17.0).
Attempting to find vstest.console from a visual studio installation with version [15.0,16.0).
Run in parallel : false
Run in isolation : false
Path to custom adapters : null
Other console options : null
Code coverage enabled : false
Diagnostics enabled : true
SystemVssConnection exists true
Run the tests locally using vstest.console.exe
========================================================
Source filter: **\release\*test*.dll,!**\obj\**
======================================================
##[error]Error: Preparing the test sources file failed. Error : Error: No test sources found matching the given filter '**\release\*test*.dll,!**\obj\**'
##[error]VsTest task failed.
##[section]Finishing: VsTest - testAssemblies



**yml definition from the test step:**
steps:
- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*test*.dll
     !**\obj\**
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    diagnosticsEnabled: True
  enabled: true

**Comment by shawnpaige** [comment] 2019-12-06 16:04
We are also receiving the same error as outlined by D4rkiii.

**Comment by WilliamAntonRohm** [comment] 2020-01-08 17:46
@steved0x -- please look into this issue.

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri3, doc-bug
