### ISSUE TITLE
Doesn't work with Visual studio subscriptions

### ISSUE THREAD

**Issue by Ayanmullick** [MicrosoftDocs/azure-devops-docs#7032] opened 2020-01-23 02:15 UTC
Step 5 doesn't work with Visual studio subscriptions. How can one use one's Visual studio subscriptions for Azure Devops billing? I'm currently getting the below error.

![image](https://user-images.githubusercontent.com/17693249/72951441-f9c15b80-3d53-11ea-85b5-97c70166ffef.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f717dae-91b5-276f-2f87-4b98331fb303
* Version Independent ID: e6e9d3b1-c00d-24d2-5667-58b4822df718
* Content: [Change Azure subscription used for billing - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/change-azure-subscription?view=azure-devops)
* Content Source: [docs/organizations/billing/change-azure-subscription.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/change-azure-subscription.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment] 2020-01-23 21:56
@Ayanmullick -- Ayan, it looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few support options that might help you with the issue that you're experiencing:​ 

If you have a subscription, contact [Visual Studio Subscriptions Support](https://visualstudio.microsoft.com/subscriptions/support/).​ 

 

If you are not sure if you have a subscription, sign in to [https://my.visualstudio.com/subscriptions](https://my.visualstudio.com/subscriptions) to see all the subscriptions assigned to your email address.​ 

 

If you do not have a subscription, consider using either our [Live Chat]( https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues, or reaching out to us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by Ayanmullick** [comment] 2020-01-24 03:53
@WilliamAntonRohm , This is an issue with all subscriptions with a spending limit. The Product group needs to document separate steps for changing the billing to subscriptions with spending limits or document that limitation of the product in this page.

**Comment by WilliamAntonRohm** [comment] 2021-07-14 23:26
@Ayanmullick -- Ayan, thank you your follow-up, and my apologies for the immense delay in responding.

@chcomley -- Chrystal, please look into this issue.

**Comment by chcomley** [comment] 2021-07-16 20:04
@parsamzand can you please help us with this issue? Thanks so much.

**Comment by chcomley** [comment] 2021-07-16 20:05
@parsamzand can you please assist with this issue? Thank you!

**Comment by chcomley** [comment] 2021-07-17 15:30
Hi @Ayanmullick, I've confirmed with our PM that you can't use Azure Credits from VS subscriptions to pay for Azure DevOps. We have it documented in our [Billing FAQ ](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=azure-devops#can-i-use-the-monthly-azure-credits-from-my-visual-studio-subscription-to-buy-azure-devops-)for reference. Thank you for posting your question. Have a great day!

**Closed** 2021-07-17 15:30 UTC
Labels: Pri1, devops-billing/tech, devops/prod, doc-enhancement

**Comment by Ayanmullick** [comment] 2021-07-17 16:11
> Hi @Ayanmullick, I've confirmed with our PM that you can't use Azure Credits from VS subscriptions to pay for Azure DevOps. We have it documented in our [Billing FAQ ](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=azure-devops#can-i-use-the-monthly-azure-credits-from-my-visual-studio-subscription-to-buy-azure-devops-)for reference. Thank you for posting your question. Have a great day!

I understand that @chcomley . However, I'm not trying to pay for licenses using Visual studio Credits. I just want for the org to show up in that subscription for ease in Azure management and visibility with other related resources for an ADO org.
