### ISSUE TITLE
Build or release pipeline variables

### ISSUE THREAD

**Issue by soerennielsen** [MicrosoftDocs/azure-devops-docs#3907] opened 2019-04-09 08:13 UTC
This page really seem to only talk about variables in the build pipeline. 

In the release pipeline you CAN set variables in the same way, but they will only be available locally. So: What is the syntax for setting a variable (e.g. using powershell) and it's scope? It MUST be doable somehow.

The use case is to have a number of variables set at the beginning of a release pipeline and then make the values usable for the subsequent stages. For now it seems I have to call REST API end points to accomplish this (if doable). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by kmkive** [comment] 2019-04-26 10:13
You can change a release variable using REST API :-)
There is a sample on stackoverflow that show how to change the release definition variable value, but you can also change a variable inside a release to be used by another stage:

Sample of powershell script to modify release variable to be used by another release stage:
$url = "$($env:SYSTEM_TEAMFOUNDATIONSERVERURI)$env:SYSTEM_TEAMPROJECTID/_apis/Release/releases/$($env:RELEASE_RELEASEID)?api-version=5.0"
Write-Host "URL: $url"
$pipeline = Invoke-RestMethod -Uri $url -Headers @{
    Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
}
# Write-Host "Pipeline = $($pipeline | ConvertTo-Json -Depth 100)"

# Update an existing variable named MyReleaseVariable
$pipeline.variables.MyReleaseVariable.value = "NewVariableValue"

####****************** update the modified object **************************
$json = @($pipeline) | ConvertTo-Json -Depth 99


$updatedef = Invoke-RestMethod -Uri $url -Method Put -Body $json -ContentType "application/json" -Headers @{Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"}

write-host "==========================================================" 
Write-host "The value of Variable 'MyReleaseVariable' is updated to" $updatedef.variables.MyReleaseVariable.value
write-host "==========================================================" 

Original stackoverflow link: https://stackoverflow.com/questions/53042605/how-to-modify-azure-devops-release-definition-variable-from-a-release-task

**Comment by soerennielsen** [comment] 2019-04-28 13:36
Well I did try that. 

It gave me errors about some of the other release properties being readonly and unsettable. Even when set to the same value. 

It's been a few days, but as I recall it, the error was alon the lines of cannot change status from active to active.

Did you test the snippet above? I'll be happy to spend and hour again on my end if you did. Using online version of Azure DevOps.

**Comment by kmkive** [comment] 2019-04-30 14:19
I made some minor changes to the original powershell script. Remember to grant required access to build agent. 

This inline powershell script are verified in a release pipeline in Azure Devops:
```
#Script based on https://stackoverflow.com/questions/53042605/how-to-modify-azure-devops-release-definition-variable-from-a-release-task

$url = $env:SYSTEM_TEAMFOUNDATIONSERVERURI + $env:SYSTEM_TEAMPROJECTID + "/_apis/Release/releases/" + $env:RELEASE_RELEASEID + "?api-version=5.0"
Write-Host "URL: $url"
$pipeline = Invoke-RestMethod -Uri $url -Headers @{
    Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
}

# Update an existing variable named MyReleaseVariable
$pipeline.variables.MyReleaseVariable.value = "NewValue"

####****************** update the modified object **************************
$json = @($pipeline) | ConvertTo-Json -Depth 100

#The string in PowerShell is Unicode, need UTF8 encoding
#https://stackoverflow.com/questions/15290185/invoke-webrequest-issue-with-special-characters-in-json

$updatedef = Invoke-RestMethod -Uri $url -Method Put -Body ([System.Text.Encoding]::UTF8.GetBytes($json)) -ContentType "application/json" -Headers @{Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"}

write-host "==========================================================" 
Write-host "The value of Variable 'MyReleaseVariable' is updated to" $updatedef.variables.MyReleaseVariable.value
write-host "=========================================================="
```

**Comment by hh23485** [comment] 2019-05-09 13:19
Yes, That's great, But one question about the Security, I didn't found the switch of `Edit release definition`, so I can't make it `allow`. Why?

**Comment by kmkive** [comment] 2019-05-13 14:58
> Yes, That's great, But one question about the Security, I didn't found the switch of `Edit release definition`, so I can't make it `allow`. Why?

See screenshot for details:
![2019-05-13 16 55 22](https://user-images.githubusercontent.com/6023541/57631538-f3ad9500-759f-11e9-9553-06a8c3278e1e.png)

**Comment by hh23485** [comment] 2019-05-13 15:10
> > Yes, That's great, But one question about the Security, I didn't found the switch of `Edit release definition`, so I can't make it `allow`. Why?
> 
> See screenshot for details:
> ![2019-05-13 16 55 22](https://user-images.githubusercontent.com/6023541/57631538-f3ad9500-759f-11e9-9553-06a8c3278e1e.png)

Yes, I know this. and finally, I found the `Edit release definition` has gone, while allow access `Manger releases` will work.

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
