### ISSUE TITLE
unauthorized: authentication required

### ISSUE THREAD

**Issue by wrkettlitz** [MicrosoftDocs/azure-devops-docs#6327] opened 2019-11-11 13:16 UTC
Followed these intructions but i get this error "unauthorized: authentication required"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cfc7aa5-d9ff-ad64-d26e-d2bd10470025
* Version Independent ID: 9b4f02ea-dab9-f613-5345-496435ab2408
* Content: [Deploy a Docker container app - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-docker-webapp?view=azure-devops&tabs=dotnet-core)
* Content Source: [docs/pipelines/apps/cd/deploy-docker-webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-docker-webapp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by shashban** [comment] 2019-11-11 14:59
@wrkettlitz can you point us to the failed release where you got this error to check backend long? Share of downloaded logs for the failed release would be super helpful.

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, needs-more-info
