### ISSUE TITLE
"Configuration failed" guidance doesnt work

### ISSUE THREAD

**Issue by Ads5555** [MicrosoftDocs/azure-devops-docs#7139] opened 2020-02-03 02:33 UTC
When following the guidance for the error in the troubleshooting section, I am unable to successfully add the required permission to the correct directory. The wrong directory is used still when reaching the approve/deny page. There is no ability to change it.

Navigating back to [https://aex.dev.azure.com/me](https://aex.dev.azure.com/me) shows the correct directory selected though.

Browsers attempted: 
- Firefox (72.0.2 (32-bit), 
- Chrome (79.0.3945.130 (Official Build) (64-bit)), 
- IE (11.592.18362.0).

To get past this issue, I perform the following steps in Internet Explorer (it lets me edit the urls in popup):
- Navigate to [https://aex.dev.azure.com/me](https://aex.dev.azure.com/me) and set a **different** directory to the one I want. 
- In the same browser, log in to teams.microsoft.com and then attempt the sign in to the azure plugin (repos/boards/etc).
- Pick the account I want to use as required.
- Once on the approve/deny popup page, copy the url for later use.
- Manually navigate to [https://aex.dev.azure.com/me](https://aex.dev.azure.com/me) in the same browser window.
- Change to the correct directory you want to set permission in.
- In the same browser window, navigate to the approve/deny url that was copied earlier.
- Permissions will now be applied automatically and the window will be closed.

Side note: You don't get shown the approve/deny page at the end. The permission is simply automatically applied. Separate issue?

Article: https://docs.microsoft.com/en-us/azure/devops/repos/integrations/repos-teams?view=azure-devops#configuration-failed-please-make-sure-that-the-organization-organization-name-exists-and-that-you-have-sufficient-permissions

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri3, doc-bug
