### ISSUE TITLE
ResourceNotFound: The Resource 'Microsoft.Web/sites/xxxx' under resource group 'xxxx' was not found

### ISSUE THREAD

**Issue by wouterroos** [MicrosoftDocs/azure-devops-docs#8206] opened 2020-05-06 07:07 UTC
Hi,

Please see my comment https://github.com/MicrosoftDocs/azure-docs/issues/43203#issuecomment-621734170 on a similar issue. In short: A few weeks ago deployments of web apps with managed identity enabled started failing with the error message mentioned in the title. We've been deploying these ARM templates successfully for over 2 years without issues and they've started failing only recently. We didn't make any changes to the templates. I can reproduce this issue over multiple project spanning multiple resource groups in multiple subscriptions. 

If this isn't the correct place to submit this issue, please let me know where I should submit it.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment] 2020-05-07 05:52
@wouterroos Thank you for the feedback.

Please see if [this post](https://stackoverflow.com/questions/60954793/the-resource-microsoft-web-sites-abc-rg-under-resource-group-null-was-not-f) addresses the issue and report the problem [here](https://developercommunity.visualstudio.com/content/problem/post.html?space=21) to get feedback from the product team.

**Comment by msebolt** [comment] 2020-05-11 21:37
Closing this now, please comment below if there are further issues.

**Comment by wouterroos** [comment] 2020-05-14 08:16
@msebolt Product team isn't responding to my post. Is there any way to get this on their radar?

**Comment by msebolt** [comment] 2020-05-18 05:44
@wouterroos Please post a link to the thread and I will up-vote and add comments to the issue.

**Comment by wouterroos** [comment] 2020-05-18 12:21
@msebolt here's the link: https://developercommunity.visualstudio.com/content/problem/1021144/resourcenotfound-the-resource-microsoftwebsitesxxx.html.

**Comment by royastro-upstream** [comment] 2020-05-24 02:54
I am getting the same issue. Any update?

**Comment by mariussm** [comment] 2020-10-20 10:11
Same issue, for both logicapps and webapps

**Comment by msebolt** [comment] 2020-11-03 20:27
Re-opening until the product team can respond.

**Comment by msebolt** [comment] 2020-11-17 17:20
Posted question to Azure's forum, see https://docs.microsoft.com/en-us/answers/questions/165924/resourcenotfound-the-resource-39microsoftwebsitesx.html.

**Comment by wouterroos** [comment] 2020-11-18 07:56
Turns out that the issue is related to adding ApplicationInsights to a Web App. The syntax previously used has been deprecated and stopped working from one day to another. The issue can be fixed by altering the template as shown below:

Modify the node "type": "config" dependsOn

- remove [resourceId('microsoft.insights/components/', ...
- remove "Microsoft.ApplicationInsights.AzureWebSites"
- add "[resourceId('microsoft.insights/components/', variables('[AppInsightsResourceNameHere'))]"

**Comment by msebolt** [comment] 2020-11-18 16:59
The question was addressed, cited from the [post](https://docs.microsoft.com/en-us/answers/questions/165924/resourcenotfound-the-resource-39microsoftwebsitesx.html) above:

**Turns out that the issue is related to adding Application Insights to a Web App. The syntax previously used has been deprecated and stopped working from one day to another. The issue can be fixed by altering the template as shown below:**

-  Modify the node `"type": "config" dependsOn`

    - remove `[resourceId('microsoft.insights/components/', ...`
    -  remove `"Microsoft.ApplicationInsights.AzureWebSites"`
    -  add `[resourceId('microsoft.insights/components/', variables('[AppInsightsResourceNameHere'))]`'"

For additional questions, please refer to [post](https://docs.microsoft.com/en-us/answers/questions/165924/resourcenotfound-the-resource-39microsoftwebsitesx.html) or start an additional issue [here](https://docs.microsoft.com/en-us/answers/topics/azure-virtual-machines.html).

**Closed** 2020-11-20 18:17 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, product-feedback
