### ISSUE TITLE
unlink current Azure Boards

### ISSUE THREAD

**Issue by Philipid3s** [MicrosoftDocs/azure-devops-docs#8392] opened 2020-05-20 09:41 UTC
Based on your article (https://docs.microsoft.com/en-us/azure/devops/boards/integrations/boards-teams?view=azure-devops), we can unlink the current board simply with this comment 
`@azure boards unlink`
But it doesnt work... 
And I cant even link another Board of my Organization from the Settings panel - Is there an issue ?

**Comment by msebolt** [comment] 2020-05-21 05:28
@Philipid3s Thank you for the feedback and apologies for the issues.

Assigning this to the author for review.

Please note for issues based on specific user scenario (i.e. that cannot be reproduced) we recommend using the following support options:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri3, doc-bug
