### ISSUE TITLE
Checkout clean doesn't match my TFS Yaml

### ISSUE THREAD

**Issue by spankr** [MicrosoftDocs/azure-devops-docs#6145] opened 2019-10-25 20:56 UTC
The example for 'clean on checkout' on this page is a boolean (with 'true' as the value).
The yaml in my pipeline expects a string of "all", "outputs" or "resources".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 024e4ed9-cf8d-155f-5e4a-73c2effaaed8
* Version Independent ID: f19c0538-4aae-b3b4-82b9-422e76723b01
* Content: [Run Git commands in a script - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/scripts/git-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/git-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
