### ISSUE TITLE
Incorrect docs for default value for Azure Devops Docker Compose containerregistrytype

### ISSUE THREAD

**Issue by RothNRK** [MicrosoftDocs/azure-devops-docs#6759] opened 2019-12-22 15:15 UTC
If you do not provide: `containerregistrytype: Azure Container Registry` the pipeline will default to 
` [docker.io/azureContainerRegistry/projectName]` and not `[azureContainerRegistry.azurecr.io/projectName]` as the documentation suggests.

In the docs:
containerregistrytype(Container registry type) | (Optional) Azure Container Registry if using ACR or Container Registry if using any other container registry. Default value: Azure Container Registry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d767aebb-620e-9ad3-e906-3e2bafa02ee9
* Version Independent ID: c8cb5a48-ccdf-778c-1547-a10db74cb56c
* Content: [Docker Compose task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/docker-compose.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker-compose.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
