### ISSUE TITLE
Accessing output variables within Deployment Jobs from earlier lifecycle hooks

### ISSUE THREAD

**Issue by akokskis** [MicrosoftDocs/azure-devops-docs#7933] opened 2020-04-14 18:26 UTC
As mentioned in #7294 (which refers to the documentation on the deployment jobs page), the documentation regarding output variables being accessed within deployment jobs from previous lifecycle hooks is totally lacking.

It would be good to understand the details and syntax of how to access these variables. 

```
strategy:
  runOnce:
    preDeploy:
      steps:
      - bash: |
          echo "##vso[task.setvariable variable=myLocalVar;isOutput=false]local variable"
        name: setvarStep
      - bash: |
          echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]output variable"
        name: outvarStep
      - bash: |
          echo 'Both $(myLocalVar) and $(outvarStep.myOutputVar) are available here'
    deploy:
      steps:
      - bash: |
          echo 'Neither $(myLocalVar) nor $(outvarStep.myOutputVar) are available here'
```
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by waltervos** [comment] 2020-04-16 07:06
I agree, this is lacking from documentation and/or not supported. Even if it's not supported then that should be mentioned in documentation.

**Comment by akokskis** [comment] 2020-04-17 11:51
To follow up on this, I received notification that this is in fact not a supported use case, however a work around involving artifacts is possible. [Reference1](https://developercommunity.visualstudio.com/content/problem/990148/unable-to-share-deployment-job-variables-between-l.html#), [reference2](https://stackoverflow.com/questions/61216069/sharing-variables-between-deployment-job-lifecycle-hooks-in-azure-devops-pipelin).

It would be ideal to update the docs to reflect that this is not a supported case.

Thanks!

**Comment by csabagal** [comment] 2020-05-04 12:39
We came across the same issue. The documentation says it works! But id does not. Please update your documentation! Not to cause more headaches to others!

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri2, devops-cicd-process/tech, devops/prod, doc-enhancement
