### ISSUE TITLE
Virtual Machine environment shared across projects.

### ISSUE THREAD

**Issue by socrplaycj** [MicrosoftDocs/azure-devops-docs#7069] opened 2020-01-27 15:41 UTC
Looking for this answer - doesn't appear to say what Scope VM Environments have. Or in my case - can they be referenced by a pipeline in another project. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d0d31f-81ee-c024-db7e-daddbf525f71
* Version Independent ID: 330f1649-386c-d0aa-5f96-b8343a1480d3
* Content: [Environment - Virtual machine resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-virtual-machines?view=azure-devops)
* Content Source: [docs/pipelines/process/environments-virtual-machines.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments-virtual-machines.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment] 2020-01-28 20:42
@socrplaycj Thank you for the question.

Since this is a new product-related feature it needs to be directed to **Azure DevOps community**.

Please add comments [here](https://developercommunity.visualstudio.com/idea/889113/shared-pipeline-environments-within-projects.html) and/or vote to give it higher priority within the product team.

@juliakm

**Comment by juliakm** [comment] 2020-01-29 15:15
@N-Usha Can you look at this?

**Comment by yangguang-hs** [comment] 2020-03-25 10:14
is there any updates?

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
