### ISSUE TITLE
Specify that you can provide multiple image names for multi-container scenarios

### ISSUE THREAD

**Issue by berberich** [MicrosoftDocs/azure-devops-docs#7607] opened 2020-03-13 19:21 UTC
The information button for Image name within this task includes the following details:

"Specify the fully qualified container image name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided."

I think it would be helpful to include that detail within this documentation. I was working with a customer under the impression you could not use this task for a multi-container deployment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4756ed74-d7d5-d4db-6e72-71f2910f7e1f
* Version Independent ID: 2413f407-8624-7843-a910-c610bd317319
* Content: [Azure Web App for Container task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-containers?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-containers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-containers.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by cxwtool** [comment] 2020-11-24 23:29
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:29 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, doc-bug
