### ISSUE TITLE
example?

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/azure-devops-docs#7704] opened 2020-03-25 17:32 UTC
please add a working example, thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf2fff2-d778-760c-d1a0-428a07d3590e
* Version Independent ID: f00e3009-1c3b-dd16-e9fc-50d1e58c83a8
* Content: [PowerShell on Target Machines task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/powershell-on-target-machines?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/powershell-on-target-machines.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/powershell-on-target-machines.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by SAPHemlock** [comment] 2020-04-23 16:18
It would be great if some examples of basic  tasks are provided like copy files/directory, delete files, creating file with some basic text. Thanks.

**Comment by cxwtool** [comment] 2020-11-24 23:29
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:29 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, doc-enhancement

**Comment by HughDevlin** [comment] 2020-12-02 20:59
Please re-open this issue.

Please add a simple working example.
