### ISSUE TITLE
Azure Dev Ops version control

### ISSUE THREAD

**Issue by r3plica** [MicrosoftDocs/azure-devops-docs#3645] opened 2019-03-14 14:04 UTC
This article seems really out of date. I am using Azure Dev Ops and for the life of me, I cannot find version control.
It might be nice if there were tabs for the different platforms (azure dev ops, tfs, etc)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 024e4ed9-cf8d-155f-5e4a-73c2effaaed8
* Version Independent ID: f19c0538-4aae-b3b4-82b9-422e76723b01
* Content: [Run Git commands in a script - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/scripts/git-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/git-commands.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by sobjornstad** [comment] 2019-07-31 13:34
Second this, the screenshots on the "Azure DevOps Services" tab look to be from TFS 2015!

**Comment by sobjornstad** [comment] 2019-07-31 13:34
Second this, the screenshots on the "Azure DevOps Services" tab look to be from TFS 2015!

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
