### ISSUE TITLE
Update Work Items Step 4 wording incorrect

### ISSUE THREAD

**Issue by ariso353** [MicrosoftDocs/azure-devops-docs#7887] opened 2020-04-09 21:58 UTC
Step 4 in the Update Work Items section says "Highlight all User Stories, choose the   actions icon, select Change type, and change the type to Product Backlog Item." but from Scrum to Agile it is the opposite.  Looks like a copy and paste from Agile to Scrum.  The picture is correct, however.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f73858a-31dd-e0fa-cb7f-53dd42192791
* Version Independent ID: f61f9f02-8fbc-4511-e655-3087834302bd
* Content: [Change process from Scrum to Agile - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/change-process-scrum-to-agile?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/change-process-scrum-to-agile.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/change-process-scrum-to-agile.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @kaelli
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment] 2020-04-13 20:38
@ariso353 -- Amanda, thank you for catching that.  I have updated the document.

@mijacobs -- Mike, please review [private PR 1235](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1235).

**Comment by ariso353** [comment] 2020-04-13 22:12
Thank you for your quick response!

**Comment by cxwtool** [comment] 2020-11-24 23:28
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:28 UTC
Labels: Pri2, devops-agile/tech, devops/prod, doc-bug
