### ISSUE TITLE
Missing instructions how to label (git tag) using pipeline scripts

### ISSUE THREAD

**Issue by Ozzian** [MicrosoftDocs/azure-devops-docs#2451] opened 2018-11-15 11:27 UTC
It took a long time to find out that there is a way to "manually" label the repository using the pipeline script. Nearly gave up using the Azure Devops pipelines. 

Please add the instructions somewhere for these "hidden features". Example

```
- powershell: Write-Host '##vso[build.addbuildtag]$(GitVersion.SemVer)'
  displayName: 'Git tag'

- powershell: Write-Host '##vso[build.updatebuildnumber]$(GitVersion.SemVer)'
  displayName: 'Set the build number'

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Pipeline options for Git repositories - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=vsts)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Ozzian** [comment] 2018-11-15 11:40
https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md

**Comment by celamb4** [comment] 2019-02-26 20:56
+1

**Comment by SychevIgor** [comment] 2019-05-29 05:46
Based on this table, it's impossible for yaml builds 
![image](https://user-images.githubusercontent.com/578954/58532434-343b1e80-81ee-11e9-9710-26a081bd7de4.png)

**Comment by Ozzian** [comment] 2019-05-29 07:48
> Based on this table, it's impossible for yaml builds

But still there is a way. (Hack)
1) Open up the _triggers_ of your azure pipeline (the three dots on the upper-right-hand-corner when you edit the pipeline). Note that the "settings" doesn't help you here.
2) Go to the first tab (YAML)
3) Pick task "Get Sources"
4) Select your preferred option from "Tag sources" and there you can use the $(build.buildNumber) that you have overwritten.

I hope that helps

**Comment by LordObsidian01** [comment] 2019-10-22 14:50
This, very much! Thanks @Ozzian for finding a way to do it with the yaml. Yaml support to tag repos needs to be added to yaml pipelines

**Comment by Ozzian** [comment] 2019-10-22 16:24
> This, very much! Thanks @Ozzian for finding a way to do it with the yaml. Yaml support to tag repos needs to be added to yaml pipelines

I have noticed an "easier" way to tag too; found in https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout

```
- checkout: self
  submodules: true
  persistCredentials: true

# later on in tasks

- script: |
     git tag $(GitVersion.SemVer)
     git push $(GitVersion.SemVer)
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
```

**Comment by garylogin** [comment] 2019-12-20 11:30
> > Based on this table, it's impossible for yaml builds
> 
> But still there is a way. (Hack)
> 
> 1. Open up the _triggers_ of your azure pipeline (the three dots on the upper-right-hand-corner when you edit the pipeline). Note that the "settings" doesn't help you here.
> 2. Go to the first tab (YAML)
> 3. Pick task "Get Sources"
> 4. Select your preferred option from "Tag sources" and there you can use the $(build.buildNumber) that you have overwritten.
> 
> I hope that helps

Thanks Ozzian thats great...but when i do that i cannot put a description, there is no date or user assigned to the tag
![image](https://user-images.githubusercontent.com/4747269/71252114-04836d80-231c-11ea-8133-d4d1edcf04ef.png)
1.0.25 was done using your method 1.0.25-beta was manual
thanks again

**Comment by phatcher** [comment] 2020-03-21 12:55
I had to make some slight changes to @Ozzian's script to make it work for me...
```
- checkout: self
  persistCredentials: true

- script: |
     git tag $(GitVersion.NugetVersionV2)
     git push origin $(GitVersion.NugetVersionV2)
  workingDirectory: $(Build.SourcesDirectory)
```
Note the assignment of the workingDirectory, otherwise I had an error that the location was not a git repository. Also I think there's a syntax error in Ossian's script in that it has to be `git push orgin <tag>`

@garylogin For your use case, you would need to create an [annotated tag](https://stackoverflow.com/questions/11514075/what-is-the-difference-between-an-annotated-and-unannotated-tag) rather than lightweight tag, so the syntax would look like this...
```
- script: |
     git tag -a <tagname> -m <message>
```
To get a user against it you might need to [set the user name/description](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-names?view=azure-devops) as well e.g.
```
- script: |
    git config --global user.name "BuildService"
    git config --global user.email "autobuild@fabrikam.com"
    git tag -a <tagname> -m <message>
```

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
