### ISSUE TITLE
Add the --collection option to the documentation under the Deployment Group Only section of the unattend scripts.

### ISSUE THREAD

**Issue by RyanWeishalla** [MicrosoftDocs/azure-devops-docs#6656] opened 2019-12-12 14:09 UTC
The --collection parameter is not included in the documentation for creating the deployment group only under the unattend section.  This is needed otherwise it cannot find the correct location to be able to install the agent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops-2019#feedback)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment] 2019-12-13 14:31
@RyanWeishalla Thank you for letting us know, I am taking a look at this one.

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
