### ISSUE TITLE
Requesting Documentation for deploying container images via azure pipeline releases

### ISSUE THREAD

**Issue by jeanpoelie** [MicrosoftDocs/azure-devops-docs#6691] opened 2019-12-16 18:20 UTC
I am trying to find documentation on deploying a Container image to kubernetes services.
I hope to be able to use Deploy to Kubernetes but this tells me that the artifact should be a .yml and not a container repository.

**Comment by msebolt** [comment] 2019-12-17 17:44
@jeanpoelie Thank you for the feedback.

Please refer to the [kubectl](https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/kubernetes) task.  

This should allow you to run something like the Kubernetes [run](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#run) command directly against an Azure Container repository.

**Comment by jeanpoelie** [comment] 2019-12-18 08:34
We currently use Octopus deploy to deploy our new images to our cluster, but since we have the option of going to Azure DevOps we are exploring it at the moment.

Octopus deploy provides us with a large set of settable configurations which make deploying an image a breeze for everyone in the team, only few know all the needed commands.
Is there a plan to implement this in azure pipelining at some point?

**Comment by msebolt** [comment] 2020-01-10 05:32
@jeanpoelie Thank you for the update and apologies for the delay.

Please refer to [Deploy to Kubernetes](https://docs.microsoft.com/azure/devops/pipelines/ecosystems/kubernetes/deploy) for current deployment capabilities and see [this post](https://devblogs.microsoft.com/devops/announcing-kubernetes-integration-for-azure-pipelines/) with the latest updates from the [Azure DevOps timeline](https://docs.microsoft.com/azure/devops/release-notes/features-timeline).

Assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri3, doc-enhancement
