### ISSUE TITLE
Availability of python developer packages

### ISSUE THREAD

**Issue by kenr** [MicrosoftDocs/azure-devops-docs#3851] opened 2019-04-03 17:58 UTC
A use case we have for changing python versions is to compile Python extension modules (C). This requires header files, etc. Will this be supported anytime soon? If not, do you have a suggestion on how to do compilation of Python extension modules in Azure Devops?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e765cfad-8ab9-443a-1171-5af81a31252f
* Version Independent ID: 8ff69d93-0128-dbeb-9d63-45266ed73020
* Content: [Use Python Version task - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/use-python-version.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/use-python-version.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **brcrista**

**Comment by brcrista** [comment] 2019-06-21 15:01
Which image?  For Hosted Ubuntu, the header files are there, under the `include` directory where Python is installed.

You can set `name: xxx` on the task and then use `$(xxx.pythonLocation)` in later scripts to get the Python install directory.

If you run this YAML, you should see `include` there:

```yml
pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3
  name: python3

- script: |
    echo $(python3.pythonLocation)
    ls $(python3.pythonLocation)
  displayName: Test output variable
```

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri2, devops-cicd/tech, devops/prod
