### ISSUE TITLE
Example Test Cases not working

### ISSUE THREAD

**Issue by RSweet24** [MicrosoftDocs/azure-devops-docs#7523] opened 2020-03-06 19:30 UTC
The primary example for performing UI tests with Selenium fails when running the tests.

https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=azure-devops

This is fixed by changing these two lines:

driver.FindElement(By.Id("sb_form_go")).Click();
driver.FindElement(By.XPath("//ol[@id='b_results']/li/h2/a/strong[3]")).Click();

to:

driver.FindElement(By.Id("sb_form_q")).Submit();
driver.FindElement(By.XPath("//ol[@id='b_results']/li/h2/a")).Click();

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri3, doc-bug
