### ISSUE TITLE
Some explanation about what the service connection is intended for?

### ISSUE THREAD

**Issue by evmimagina** [MicrosoftDocs/azure-devops-docs#8404] opened 2020-05-20 18:44 UTC
Hi,

There's not even a brief explanation about what those service connections are intended or capable of and how to use them…
e.g. I'm trying to use the "Azure Repos/Team Foundation Server", somehow it feels as it would allow to connect to another Azure Git Repo so I can see that repo as a local one... and in that way not missing info about who did a "commit" when using a CI/CD pipeline...

It feels incredible that to connect to Azure Devops from different organitzations is not properly solved 100%.

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-in/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-tfsts)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-cicd-library/tech, devops/prod, doc-enhancement
