### ISSUE TITLE
Does not answer actually how to use azure agent on windows without SSL....

### ISSUE THREAD

**Issue by kkarakk** [MicrosoftDocs/azure-devops-docs#4388] opened 2019-05-30 06:38 UTC
I have a deployed Azure devops on premise -am failing at the step of running .\config.cmd  with 

Enter server URL > http://120.168.120.153:2019/mobile-lab/
Enter authentication type (press enter for Integrated) > pat
Enter personal access token > ****************************************************
Basic authentication requires a secure connection to the server.
Failed to connect.  Try again or ctrl-c to quit

why is --sslskipcertvalidation only available on linux and mac? i cannot add a self signed cert to the server myself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8554882-68f4-d60b-fe3f-ba4ca00bfdff
* Version Independent ID: 87839017-b47c-4bc2-1bba-e20bef0c3025
* Content: [Run the agent with a self-signed certificate - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/certificate?view=azure-devops-2019)
* Content Source: [docs/pipelines/agents/certificate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/certificate.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by yvemuru** [comment] 2020-02-20 04:30
Even with a Mac, when I try to run with '--sslskipcertvalidation', I get the following errors on my diag logs:
[2020-02-20 04:21:11Z ERR  Terminal] System.InvalidOperationException: Basic authentication requires a secure connection to the server.
[Agent_20200220-042012-utc.log](https://github.com/MicrosoftDocs/vsts-docs/files/4228782/Agent_20200220-042012-utc.log)

Any resolution to this ? Why does it keep looking for a secure connection even when I send in the flag ?

**Comment by yvemuru** [comment] 2020-02-22 11:19
Even when I continue with the --sslskipcertvalidation, when the agent tries to get the source code from the local TFS repository it errors out when trying to fetch the sources. Created a question in developer community too for reference, please do have a look.

https://developercommunity.visualstudio.com/content/problem/926864/errors-with-getting-sources-when-trying-to-run-age.html

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri2, devops-cicd/tech, devops/prod
