### ISSUE TITLE
Manual intervention sections 5 and 7 refs nonexistent percentage section

### ISSUE THREAD

**Issue by horros** [MicrosoftDocs/azure-devops-docs#6640] opened 2019-12-11 07:57 UTC
Sections 5 and 7 of the section "Manual intervention for promoting or rejecting canary" says to set percentage to 25, but there is no such input field when promoting or rejecting a canary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 079492cb-bdc3-7ba6-8581-dd76391cda4f
* Version Independent ID: 81e719d4-b127-fa41-4cf2-421e91b9d4be
* Content: [Canary deployment strategy for Kubernetes deployments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/canary-demo?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/kubernetes/canary-demo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/kubernetes/canary-demo.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment] 2019-12-12 02:25
@horros  Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
