### ISSUE TITLE
YAML for publishing artifacts says `publish:` but it seems to be `upload:`?

### ISSUE THREAD

**Issue by dscho** [MicrosoftDocs/azure-devops-docs#4622] opened 2019-06-25 08:07 UTC
The schema and the example both insist on the term `publish`, but the Pipeline [fails](https://dev.azure.com/dscho/git/_build/results?buildId=196&view=results) to execute with:

```
/azure-pipelines.yml (Line: 20, Col: 5): Unexpected value 'publish'
```

When I replace it with the term `upload`, it [works](https://dev.azure.com/dscho/git/_build/results?buildId=198&view=results).

So the documentation is incorrect...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment] 2019-06-25 11:14
@willsmythe should `publish` be everywhere by now?

**Comment by SamirFarhat** [comment] 2019-08-23 08:10
Hi,

Any comment ?

**Comment by willsmythe** [comment] 2019-08-23 16:09
`upload` has been deprecated for a few months now. `publish' is the right way to "upload" (err, publish artifacts).

What happens when you try to use `publish`? Does it fail? If so, what is the error?

**Comment by dscho** [comment] 2019-08-26 14:11
@willsmythe see [my original report](https://github.com/MicrosoftDocs/vsts-docs/issues/4622#issue-460274223) for the error message...

**Comment by dscho** [comment] 2019-08-28 12:33
> if you run a pipeline that uses `publish` today, does it still fail?

I don't use the keyword in my Pipelines, neither `publish` nor `upload`, because of this here issue. I always use the full [`PublishBuildArtifacts@1` task](https://github.com/git/git/blob/v2.23.0/azure-pipelines.yml#L127-L132) or the full [`PublishPipelineArtifact@0` task](https://github.com/git/git/blob/v2.23.0/azure-pipelines.yml#L42-L46), which is a bit awkward, granted, but at the time when I was working on this, I was really unsure which keyword to use: the one that is suggested now did definitely not work back then.

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
