### ISSUE TITLE
NPM Publish with --tag

### ISSUE THREAD

**Issue by danielgary** [MicrosoftDocs/azure-devops-docs#3970] opened 2019-04-15 20:14 UTC
We need to be able to publish with a --tag on some builds for pre-release versions.    

Here is our build command:
        command: Custom
        customCommand: publish --tag next
        publishRegistry: useExternalRegistry
        publishEndpoint: npmjs

We are getting the following error:
39 error code ENEEDAUTH
40 error need auth auth required for publishing
41 error need auth You need to authorize this machine using `npm adduser`

It seems like a custom command doesn't use the npmjs connection we created?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c00d3b8-64c1-9f1b-83f8-62d8cf07817b
* Version Independent ID: 5fcdebed-cfb8-c5a6-d807-1315b2db5e57
* Content: [npm task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/package/npm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/npm.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by petong** [comment] 2019-04-17 21:00
I was banging my head against this very issue last week, what I ended up doing was adding a .npmrc file with 

registry=https://registry.npmjs.com

despite already defining the registry in my service connection with my authentication details. my task then looks like this:

      - task: Npm@1
        inputs:
          command: 'custom' # Options: install, publish, custom
          verbose: true
          customCommand: publish --tag $(npm_tag)
          customRegistry: 'useNpmrc'
          customEndpoint: <service connection>

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
