### ISSUE TITLE
New Navigation Changes

### ISSUE THREAD

**Issue by Cyanhyde-M** [MicrosoftDocs/azure-devops-docs#3187] opened 2019-01-30 21:26 UTC
This page should be updated with the new navigation to make its instructions clearer
- All images at top of page should have 'Old Navigation/New Navigation' pane toggles
- No 'Build' tab in new navigation -&gt; it's a 'Tasks' tab
- No 'Arguments' tab/option for Command Line task

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 024e4ed9-cf8d-155f-5e4a-73c2effaaed8
* Version Independent ID: f19c0538-4aae-b3b4-82b9-422e76723b01
* Content: [Run Git commands in a script - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azdevops&tabs=designer)
* Content Source: [docs/pipelines/scripts/git-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/git-commands.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by TomasHubelbauer** [comment] 2019-01-31 20:38
Yes please, I would live for it to have up to date Azure DevOps screenshots.

**Comment by andyjlewis** [comment] 2019-07-01 18:46
Thank you for reporting this issue. I'm sorry for the long delay in response. I was out of the office for a long period of time earlier this year.

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
