### ISSUE TITLE
Document missing information

### ISSUE THREAD

**Issue by doramalita** [MicrosoftDocs/azure-devops-docs#7422] opened 2020-02-27 08:36 UTC
It is worth to mention that Deploy: Azure PowerShell task will only run successfully if the VMSS was created with unmanaged OS disk created from generalized VHD. Only in this case can image.uri be changed to a new path of VHD. If the VMSS was created from an image in your resource group (or shared image gallery), imageReference exists under storageProfile, and it expects fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'. In this case another set commands are needed to create an image from the VHD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061aa8bc-6c7f-82f6-e4c8-ed9370596daf
* Version Independent ID: 775c82ad-6f92-1b0f-ee84-59e01a33d78d
* Content: [Deploy apps to an Azure VM Scale Set - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/azure/deploy-azure-scaleset?view=azure-devops#feedback)
* Content Source: [docs/pipelines/apps/cd/azure/deploy-azure-scaleset.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/azure/deploy-azure-scaleset.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by cxwtool** [comment] 2020-11-24 23:31
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:31 UTC
Labels: Pri2, devops-cicd-apps/tech, devops/prod, doc-bug
