### ISSUE TITLE
Will Microsoft fix or improve errors with this task?

### ISSUE THREAD

**Issue by jrybacek** [MicrosoftDocs/azure-devops-docs#8029] opened 2020-04-21 18:54 UTC
Many people are trying to fix bugs with this Extract Files task.  Clearly none of us can figure out how to actually get Microsoft to except the communities bug fixes.  Can you help me figure out how to contribute and/or could you fix the bugs that stop us from leveraging this task?  https://github.com/microsoft/azure-pipelines-tasks/issues/11593

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05de2755-a21b-91b8-46b3-05bcb55a1eb6
* Version Independent ID: ababbcfb-e7d4-68f7-423f-1e68201247f4
* Content: [Extract Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/extract-files?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/extract-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/extract-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by WilliamAntonRohm** [comment] 2020-04-22 22:12
Thank you for continuing to bring this to our attention and sorry that you ran into trouble – we see that there is an active issue and a pull request with a potential fix for this in the azure-pipelines-tasks repo. We’re sending a link to our engineering team to have them take a fresh look. Please follow the progress of this issue [here]( https://github.com/microsoft/azure-pipelines-tasks/issues/11593) and the PR [here]( https://github.com/microsoft/azure-pipelines-tasks/pull/11594).

cc @stephenmichaelf

**Comment by jrybacek** [comment] 2020-04-24 15:53
@WilliamAntonRohm Thank you very much, I am eager to use this new feature.  It will allow our entire team to consolidate our code deployment process in Azure DevOps.

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, product-feedback
