### ISSUE TITLE
Support for output variables does not work as documented for runOnce deployment

### ISSUE THREAD

**Issue by buyckkdelaware** [MicrosoftDocs/azure-devops-docs#8368] opened 2020-05-18 12:54 UTC
The documentation states:
"For a runOnce job, specify the name of the job instead of the lifecycle hook:"

But this does not seem to work if the runOnce deployment, has some other lifecycle hooks, e.g. the routeTraffic one. Please clarify how to access the output variable for a runOnce deployment, or a link to some source code I can check/read.

Example would be:

# Set an output variable in a lifecycle hook of a deployment job executing runOnce strategy
- deployment: A
  pool:
    vmImage: 'ubuntu-16.04'
  environment: staging
  strategy:                  
    runOnce:
      deploy:
        steps:
        - script: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the deployment variable value"
          name: setvarStep
        - script: echo $(setvarStep.myOutputVar)
          name: echovar
      routeTraffic:
        steps:
        - script: echo I'm not doing anything with variables, just routing traffic.

# Map the variable from the job
- job: B
  dependsOn: A
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    myVarFromDeploymentJob: $[ dependencies.A.outputs['A.setvarStep.myOutputVar'] ]
  steps:
  - script: "echo $(myVarFromDeploymentJob)"
    name: echovar

Previous issues:
https://github.com/MicrosoftDocs/azure-devops-docs/issues/4946
https://github.com/MicrosoftDocs/azure-devops-docs/issues/8163

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-cicd-process/tech, devops/prod, doc-enhancement
