### ISSUE TITLE
Page Out of Date

### ISSUE THREAD

**Issue by JustaSimpleUser** [MicrosoftDocs/azure-devops-docs#7952] opened 2020-04-15 19:02 UTC
The contents of this page are out of date with the latest Azure product release.  The steps described no long conform to the Azure DevOps UI.  For example, there is no "Set up Build" button on the Repos > Files page for the project.  Pipelines must be build from the Pipelines hub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f80d77-da2a-3c8d-efcf-3095bf293f69
* Version Independent ID: 36dcf393-e28a-2bc4-61e6-5c93cdacb625
* Content: [Build your .NET desktop app for Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/windows/dot-net?view=azure-devops&tabs=github#feedback)
* Content Source: [docs/pipelines/apps/windows/dot-net.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/apps/windows/dot-net.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri2, devops-cicd-apps/tech, devops/prod, doc-bug
