### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by gravity00** [MicrosoftDocs/azure-devops-docs#5301] opened 2019-08-20 13:11 UTC
I think it would be a nice improvement to the NodeTool documentation if there was some text (or link) explaining how to setup the proxy when using an internal agent.
It took me about 2 hours until I found a solution, but not from an official source.

For those interested, just add an environment variable HTTP_PROXY and HTTPS_PROXY to your machine and restart the agent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb95406-322e-11db-41e0-7b8064c8295c
* Version Independent ID: 57fb95a8-385d-7548-ee6a-9a3a875a150e
* Content: [Node.js Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/tool/node-js.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/node-js.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by brianveltman** [comment] 2019-08-21 11:02
This does not work on our Linux agents.
We've set proxy variables and noproxy variables as environment variables, also set the variables using the npmrc file and we've set the variables using the .proxy and .proxybypass files within the agent directory.
Node tools installer still throws 403 errors.
When running npm install using a bash task, it works fine.

**Comment by brianveltman** [comment] 2019-08-27 08:22
> This does not work on our Linux agents.
> We've set proxy variables and noproxy variables as environment variables, also set the variables using the npmrc file and we've set the variables using the .proxy and .proxybypass files within the agent directory.
> Node tools installer still throws 403 errors.
> When running npm install using a bash task, it works fine.

Turned out to be a malformed proxy uri inside .proxy file. It got encapsulated between quotes by Ansible.

**Comment by Luminaii** [comment] 2020-05-06 15:18
I have added the HTTP_PROXY and HTTPS_PROXY variables to my system but I'm getting "error]tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 8080 8080:80".

Is there any know solution for this?

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
