### ISSUE TITLE
Explain purpose of pushing to bare git repository

### ISSUE THREAD

**Issue by mloskot** [MicrosoftDocs/azure-devops-docs#2365] opened 2018-11-07 01:15 UTC
From https://stackoverflow.com/a/49623979/151641

&gt; It’s usually unnecessary to push local git repo to a local bare repo
&gt; unless you want to treat the local bare repo as your remote git server.

`git svn clone`-ed repository can be pushed to remote repository directly.

With the advent of Azure DevOps, GitHub, suggestion of pushing to *bare* repo seems obsolete and possibly confusing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Migrate from Subversion (SVN) to Git](https://docs.microsoft.com/en-us/azure/devops/articles/perform-migration-from-svn-to-git?view=vsts)
* Content Source: [docs/articles/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/articles/perform-migration-from-svn-to-git.md)
* Product: **devops**
* GitHub Login: @hkamel
* Microsoft Alias: **hkamel**

**Comment by steved0x** [comment] 2018-11-07 19:20
@mloskot Thanks for your feedback, I am checking with the author to see if we need to make an update. Thank you.

**Comment by ianwilliams1** [comment] 2019-07-15 19:25
@steved0x, any update from you or the author to this issue; stale(bot) closed it.

**Comment by mloskot** [comment] 2019-07-15 20:14
@ianwilliams1 
> stale(bot) closed it.

Luckily, stale bot just warned it is going to close it soon, but you're comment postponed the actual closing.

However, I'm also interested in a feedback

**Comment by ianwilliams1** [comment] 2019-07-15 20:30
I can understand stale(bot) closing when lack of submitter response, but when it's in MSFT's (owner) queue, that's not good. Maybe give stale(bot) some AI - or better logic?

**Comment by skylee91** [comment] 2019-10-25 08:21
OMG there is no follow up since July. Nobody working in this Docs Microsoft?

**Comment by mloskot** [comment] 2019-10-25 08:43
@skylee91 Yes, unfortunately, this issue is not an exception. Microsoft asks the community for help in proof-reading the docs but looking at the number of open issues, well, it's very de-motivating...

**Comment by ianwilliams1** [comment] 2019-10-25 08:56
Unfair to single out the Docs ppl; the last real update to the [Jenkins tfs-plugin](https://github.com/jenkinsci/tfs-plugin/releases) was 2018-08-13, over a year ago. There was a minor update to the documentation there recently in which they basically forgot about their product Azure DevOps Server in their re-branding exercise, so not counting it. [83 outstanding issues](https://issues.jenkins-ci.org/browse/JENKINS-59716?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20tfs-plugin), including [27/28 failed PRs](https://issues.jenkins-ci.org/browse/JENKINS-59716?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20tfs-plugin)

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri1, devops-whitepapers/tech, devops/prod, doc-bug
