### ISSUE TITLE
MultiStageYaml correction suggestion

### ISSUE THREAD

**Issue by tiagoags** [MicrosoftDocs/azure-devops-docs#13854] opened 2023-12-07 13:08 UTC
on ['Add stage to pipeline'](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/create-multistage-pipeline?view=azure-devops#add-new-stage-to-pipeline)  
on task: AzureWebApp@1 / inputs / appName   it is referencing $(WebAppNameDev)   

should be $(WebAppNameStaging) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0851ffe4-d380-6ff4-a4c7-0557fa5ef84e
* Version Independent ID: 0851ffe4-d380-6ff4-a4c7-0557fa5ef84e
* Content: [Tutorial: Create a multistage pipeline with Azure DevOps - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/create-multistage-pipeline?view=azure-devops#add-new-stage-to-pipeline)
* Content Source: [docs/pipelines/process/create-multistage-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/create-multistage-pipeline.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment] 2023-12-08 13:47
Duplicate of #13782.

**Closed by WilliamAntonRohm** 2023-12-08 13:47 UTC
Labels: duplicate, doc-bug, cba, Pri1, azure-devops-pipelines/svc, azure-devops-pipelines-process/subsvc
