### ISSUE TITLE
Build Retention Policies for Azure Pipelines

### ISSUE THREAD

**Issue by joeltimothyoh** [MicrosoftDocs/azure-devops-docs#3822] opened 2019-03-31 16:44 UTC
For Azure Pipelines, under 'Organization Settings' &gt; 'Retention and parallel jobs', I see the following:

Maximum retention policy
Days to keep: 	30
Minimum to keep: 	10
...

Default retention policy
Days to keep: 	10
Minimum to keep: 	1
...

Would it be right to say that the maximum days to retain builds for Azure Pipelines builds is limited to only 30 days, and that there is no way to increase that number? 

Also, it's unclear from the documentation which of the two build retention policies the organization's projects inherit from. I have done some earlier builds more than 10 days ago with the builds still retained, and can only guess 10 days not being the limit.

That said, I'd like to know if there's any way to preserve the build logs indefinitely without having to retain each build by hand? I ask this having observed open source projects like VSCode preserve a long history of their builds and have been expecting the same until stumbling upon this section of the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a285f9-738d-9f76-4de0-a4c4ecf6f5f5
* Version Independent ID: 9581a043-4873-bf0a-138f-85f6a61ae950
* Content: [Build and release retention policies - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops#global-build-retention-policy)
* Content Source: [docs/pipelines/policies/retention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/retention.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri2, devops-cicd/tech, devops/prod

**Comment by maxbog** [comment] 2021-01-19 12:41
Hi this issue did not get an answer and I'm also very interested. Is there any way to automatically preserve a build indefinitely?
