### ISSUE TITLE
Example setting up yarn cache task in classic (non-yaml) pipeline

### ISSUE THREAD

**Issue by 200even** [MicrosoftDocs/azure-devops-docs#6635] opened 2019-12-11 02:05 UTC
I'm having trouble setting this up for our pipeline to cache yarn packages. The YAML mentions a 'script' step, but I don't see that on the GUI task? I'm running yarn install as a separate task just after the cache task but getting a post-job cache error with a cache miss. Any help is appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#nodejsyarn)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment] 2019-12-11 19:24
@200even Thank you for the feedback, assigning this to the author for review of the steps.

Note this is a documentation forum and support options are limited to what's outlined in the general steps.

Please direct requests involving specific settings, environments, etc. to either:

- [Azure DevOps Support](https://azure.microsoft.com/en-us/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by 200even** [comment] 2019-12-11 19:47
Thanks @msebolt. In this case, I'm specifically requesting an example to be included in the documentation alongside the existing YAML example.

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
