### ISSUE TITLE
Save PDF is missing on left bottom.

### ISSUE THREAD

**Issue by pavankumar0425** [MicrosoftDocs/azure-devops-docs#3089] opened 2019-01-22 15:53 UTC
Save PDF is missing on left bottom.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0095da6-647f-6586-dbd8-4d220bd92272
* Version Independent ID: 54db56ed-2e60-f01a-05d8-775f34171e98
* Content: [Understand Git history - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/understand-git-history)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2funderstand-git-history.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2funderstand-git-history.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **routlaw**

**Comment by steved0x** [comment] 2019-01-24 17:44
@pavankumar0425 I'll check into that, my understanding is that it should be turned on, in the meantime, do you want me to see if I can get a PDF generated and send it to you?

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-learn/tech, devops/prod, doc-bug
