### ISSUE TITLE
Great Job

### ISSUE THREAD

**Issue by dirksteele** [MicrosoftDocs/azure-devops-docs#6035] opened 2019-10-17 15:58 UTC
Perfect.  I wish all documentation were this well and simply written.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebb7276b-e7ab-8d3f-f89c-4f5130808f61
* Version Independent ID: f11655e2-14f9-7755-dffa-61b21db1be67
* Content: [Add users to Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/set-permissions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/policies/set-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/set-permissions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment] 2019-10-17 18:15
@dirksteele -- Dirk, thank you!

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, docs-experience
