### ISSUE TITLE
Use Helm task with Azure Pipelines Environment Kubernetes resource

### ISSUE THREAD

**Issue by kyschouv** [MicrosoftDocs/azure-devops-docs#7548] opened 2020-03-10 00:34 UTC
It's not clear to me whether or not I should expect the Helm task to work like the Kubernetes task works. With the Kubernetes task, the service connection is loaded from the environment automatically. I'd expect that with the helm task as well, but it doesn't seem to work that way. Am I just missing something?

**Comment by WilliamAntonRohm** [comment] 2020-03-11 00:20
@kyschouv -- Kyle, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by kyschouv** [comment] 2020-03-11 00:25
The general documentation around Environments isn't very helpful. I had to do a lot of iteration to discover that I could reference environment information using built-in variables, e.g. $(Environment.ResourceName). I had expected the HelmDeploy task to work with the Environment automatically, like the KubernetesManifest task reference in the Environments documentation, but it doesn't.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops
https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/aks-template?view=azure-devops

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri3, doc-bug
