### ISSUE TITLE
Provide a customized app_offline.htm which will be used by TakeAppOfflineFlag?

### ISSUE THREAD

**Issue by iwhp** [MicrosoftDocs/azure-devops-docs#8356] opened 2020-05-16 07:21 UTC
Is it possible to provide a customized app_offline.htm file which will be used by TakeAppOfflineFlag?

If not, it should be possible. By example one should be able to put a app_offline_off.htm file into the root. If this file is present, it should be renamed to app_offline.htm during deploy and after it it should be renamed back to app_offline_off.htm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment] 2020-05-18 19:47
@iwhp  Thank you for the question, assigning this to the author for review.

If this feature is unsupported, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) for feedback from the product team.

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, product-question
