### ISSUE TITLE
Sentence correction

### ISSUE THREAD

**Issue by waqasm** [MicrosoftDocs/azure-devops-docs#4621] opened 2019-06-25 07:43 UTC
Hi,
There is a sentence require a little fix in document.

The sentence currently says "Select customers have opted into our second stage of feature flags."

I think "ed" is missing with "Select". 
I think, the sentence needs to be "Selected customers have opted into our second stage of feature flags."

Link to document: https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/progressive-experimentation-feature-flags

**Comment by waqasthetechguy** [comment] 2019-06-28 06:09
Is there any possibility that I can fix this?

**Comment by thomps23** [comment] 2019-06-28 15:28
This particular content set is a private one. II'll run this change by one of our editors to confirm and then make the change if needed.

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by msebolt** [comment] 2020-12-02 20:27
Change has been made, PR pending review.

**Closed** 2021-01-07 22:16 UTC
Labels: Pri3, devops-learn/tech, devops/prod, doc-bug, help wanted
