### ISSUE TITLE
Doc out of date for multi stage pipelines

### ISSUE THREAD

**Issue by drueckert** [MicrosoftDocs/azure-devops-docs#8418] opened 2020-05-21 16:10 UTC
This doc is out of date. Multi-Stage Pipelines code coverage reporting has been changed and this doc is no longer accurate for Azure Pipelines. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabbd5e2-993f-89da-665f-f39ab63d7c42
* Version Independent ID: 493c2582-69a4-1bbe-03b5-0bb5f1d41aed
* Content: [Review code coverage - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops#feedback)
* Content Source: [docs/pipelines/test/review-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/test/review-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-test**
* GitHub Login: @vinodjo
* Microsoft Alias: **vinojos**

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-cicd-test/tech, devops/prod, doc-bug
