### ISSUE TITLE
"Allow scripts to access OAuth" instructions out of date.

### ISSUE THREAD

**Issue by Gary-Peluso** [MicrosoftDocs/azure-devops-docs#7349] opened 2020-02-19 20:11 UTC
The instructions for how to find the "Allow scripts to access OAuth" is not updated.   That option is now specific to each build phase.  To find the option: Select a build phase, stay on Tasks tab, Scroll to bottom or right pane.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acfc2d3a-e665-f90d-bf3c-c2e81f0e72aa
* Version Independent ID: ea7dcfb7-cc63-43d6-939e-62b657b567d8
* Content: [Use PowerShell scripts to customize pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/powershell?view=azure-devops#feedback)
* Content Source: [docs/pipelines/scripts/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by rhughesjr** [comment] 2020-02-20 13:55
Also, there need to be instructions for how to set this in YAML

**Comment by cxwtool** [comment] 2020-11-24 23:31
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:31 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
