### ISSUE TITLE
No documentation for pool owner concept ?

### ISSUE THREAD

**Issue by spashx** [MicrosoftDocs/azure-devops-docs#5887] opened 2019-10-08 12:34 UTC
In Azure Devops Server, when a pool is selected at the collection level, there is a  "Detail for pool" tab , where it is possible to define a pool *owner* by clicking on the label "Search users and groups". 
I was not able to get any information about this.
What is the pool owner ? does this provide permissions/rights on the pool ? The documentation should explain it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops-2019&tabs=yaml)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2019-10-08 17:39
@spashx  Thank you for the feedback, assigning this to the author for review.

**Comment by japj** [comment] 2019-10-21 14:10
Also related to pool owner: is there a way to change it? (if someone leaves the organisation)

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
