### ISSUE TITLE
Outdated Windows Image

### ISSUE THREAD

**Issue by DamianMehers** [MicrosoftDocs/azure-devops-docs#4675] opened 2019-06-28 09:25 UTC
The documentation says to use 'vs2017-win2016' whereas it should likely say 'windows-2019' 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c45a95ce-73c8-861e-f92d-a26f1667aa60
* Version Independent ID: ecb82128-cdf4-3834-62c1-2cf61989ab5e
* Content: [Build Xamarin apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/xamarin?view=azure-devops)
* Content Source: [docs/pipelines/languages/xamarin.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/xamarin.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
