### ISSUE TITLE
Ambiguity if you can build a single .proj file or not

### ISSUE THREAD

**Issue by MrEmanuel** [MicrosoftDocs/azure-devops-docs#4042] opened 2019-04-23 13:27 UTC
This document clearly says it's not possible, but the opposite is true here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build?view=azure-devops 
There it says: "You can also build MSBuild project (.*proj) files." 

Also the link "XAML builds" is outdated and doesn't link to what it should I think. Since XAML builds seem depreciated it might be good to remove the link?

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22342679-18af-7c79-f902-fe9c0bb55379
* Version Independent ID: a8e7c201-6593-458b-5a81-b54e93fde4b5
* Content: [MSBuild build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/msbuild?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/msbuild.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/msbuild.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by jim-liu** [comment] 2019-06-05 13:18
I was able to build a single project within a solution by specifying the .*proj in the solution argument.

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
