### ISSUE TITLE
A full example for Angular should be on here as well as React and Vue

### ISSUE THREAD

**Issue by jjgriff93** [MicrosoftDocs/azure-devops-docs#8335] opened 2020-05-15 01:16 UTC
Key steps like the Copy Task to copy Angular build outputs from 'dist' or 'www' to the ArtifactsStagingDirectory are missing from the docs for Angular and should be added like they are in the Vie and React section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b2fdca-9125-9720-3d03-3c6dd336f100
* Version Independent ID: b2a24e28-9858-fe1c-4527-745f1f387e4e
* Content: [Build and deploy JavaScript and Node.js apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/javascript?view=azure-devops&tabs=code#feedback)
* Content Source: [docs/pipelines/ecosystems/javascript.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/javascript.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-cicd-ecosystems/tech, devops/prod, doc-enhancement
