### ISSUE TITLE
How to properly use secrets?

### ISSUE THREAD

**Issue by joseharriaga** [MicrosoftDocs/azure-devops-docs#6251] opened 2019-11-05 02:38 UTC
This document says the following:
"Secret variables are not passed into tasks as environment variables and must instead be passed as inputs."

However, the docs on [Variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables) say:
"It is recommended that you use the script's environment in order to pass secrets to the script. Operating systems often log commands for the processes that they run, and you would not want the log to include a secret that you passed in as an input."

So I'm a little bit confused about the proper way to use secrets. If I understand correctly, the former doc is saying: "You should pass secrets as inputs to your tasks", but then the latter doc is saying: "In the specific case of a PowerShell task, when you need to pass secrets to the scripts, do not pass them as parameters. You should map the secrets as environment variables and use these instead." Am I interpreting the docs correctly?

If so, what is then the appropriate way to pass secrets to the script that will be run by an AzurePowerShell task given that this task does not have an "env" parameter like the PowerShell task does?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#feedback)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment] 2019-11-05 19:10
@joseharriaga Thank you for the question, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
