### ISSUE TITLE
Suggestion: put task name at top of topic.

### ISSUE THREAD

**Issue by travelmarx** [MicrosoftDocs/azure-devops-docs#8436] opened 2020-05-24 10:27 UTC
I've run pipelines before but am not an expert. Now I want to do something new and build/deploy. I've seen a number of yml snippets here and there and I have a number of task names to check out (like "AzureRMWebAppDeployment" and "AzureWebApp") so I head to the docs. Instead of finding the task name front and center at the top of the topic, it's several page scrolls down in a snippet. To me, it seems like it would make more sense to have the task name at the top for all task pages. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:24
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, doc-enhancement
