### ISSUE TITLE
List of values for the XCode job actions parameter not complete

### ISSUE THREAD

**Issue by codedbypm** [MicrosoftDocs/azure-devops-docs#4768] opened 2019-07-07 19:17 UTC
[Enter feedback here]

The doc lists the possible values for the `actions` as 

- clean 
- build
- test
- analyze 
- archive

There are some more actions possible like `build-for-testing` and `test-without-building`. Perhaps more

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36460c87-c713-0930-461b-92da65e415e6
* Version Independent ID: 047d39f1-481b-c135-36e9-6cfc1cc92e99
* Content: [Xcode build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xcode?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/xcode.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/xcode.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
