### ISSUE TITLE
"Test on the Android emulator" section is outdated

### ISSUE THREAD

**Issue by sbolotovms** [MicrosoftDocs/azure-devops-docs#5723] opened 2019-09-24 21:55 UTC
Hi,

this section here: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops#test-on-the-android-emulator
is outdated and works for previous hosted VM generation - macOS 10.13. Since then, Azure provides VM macOS 10.14 definition, for which this no longer applies. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 454383d9-78ce-6203-2926-3449842d2f9f
* Version Independent ID: 947f872e-95b9-1691-acf0-e1a3f73b1e75
* Content: [Build, test, and deploy Android apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops#test-on-the-android-emulator)
* Content Source: [docs/pipelines/ecosystems/android.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/android.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **dastahel**

**Comment by sphanley** [comment] 2019-10-04 20:14
I'm part of a team who's trying to run Android tests on Azure DevOps - is there any info available as to what aspects of these instructions are no longer applicable for the 10.14 VM agents, and what the new recommended steps look like?

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
