### ISSUE TITLE
"Advanced | Output directory" does not exist in task version 5.*

### ISSUE THREAD

**Issue by vladfilyakov** [MicrosoftDocs/azure-devops-docs#3783] opened 2019-03-26 22:19 UTC
"Advanced | Output directory" does not exist in task version 5.*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36460c87-c713-0930-461b-92da65e415e6
* Version Independent ID: 047d39f1-481b-c135-36e9-6cfc1cc92e99
* Content: [Xcode build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xcode?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/xcode.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/xcode.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri2, devops/prod
