### ISSUE TITLE
Deploy canary stage, section 4 is maybe not quite clear

### ISSUE THREAD

**Issue by horros** [MicrosoftDocs/azure-devops-docs#6619] opened 2019-12-09 15:32 UTC
The step says to "Provide appropriate values for the input dropdowns to locate your container registry", and reading through the docs one would assume that this means one should use the service connection to ACR created in the "Create service connections" step. The docs do not mention that the service connection needs to be an Azure Resource Manager connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 079492cb-bdc3-7ba6-8581-dd76391cda4f
* Version Independent ID: 81e719d4-b127-fa41-4cf2-421e91b9d4be
* Content: [Canary deployment strategy for Kubernetes deployments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/canary-demo?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/kubernetes/canary-demo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/kubernetes/canary-demo.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment] 2019-12-10 03:34
@horros  Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
