### ISSUE TITLE
Update for Azure Pipelines

### ISSUE THREAD

**Issue by ruisilva450** [MicrosoftDocs/azure-devops-docs#3497] opened 2019-02-27 15:09 UTC
This documentation needs to be updated to use images from the updated Azure DevOps Pipeline.
I'm trying to generate a build for iOS (IPA file) from an Cordova Ionic 3 project.

On [Building iOS on macOS](https://docs.microsoft.com/en-us/azure/devops/pipelines/archive/apps/mobile/cordova-build?view=azure-devops#building-ios-on-macos) you start with:
"Now let's create a version of this same build pipeline to target iOS that will run on a configured agent on macOS."

And right after you state that we should "Right click on the Windows build pipeline and select "Clone." Once you save you should give this pipeline a name that indicates it's the iOS build."

Then you proceed to "Change the Platform value for the Cordova Build task to ios". 

What about saying that after the clone it is supposed to change the agent to macOS like is said above on the introdution?

This seems not suitable to the current UX of Azure DevOps Pipelines and should be updated to represent the updated organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f13eb3-d83b-f208-30df-77c261061b02
* Version Independent ID: 487dd1ee-b6df-4ba4-3fec-c6ba423185d3
* Content: [Build and Test Cordova Projects - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/archive/apps/mobile/cordova-build?view=azure-devops#installing-the-cordova-build-task)
* Content Source: [docs/pipelines/archive/apps/mobile/cordova-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/archive/apps/mobile/cordova-build.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by josersleal** [comment] 2019-07-04 17:25
I would suggest completing the information so that it includes the publishing or deploying to apple app store. To me that is not straight forward

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
