### ISSUE TITLE
Server URL for TFS 2018

### ISSUE THREAD

**Issue by vladek7** [MicrosoftDocs/azure-devops-docs#4066] opened 2019-04-25 10:25 UTC
Server URL for TFS 2018 is https://{your_server}/
Agent fails to connect on 
https://{your_server}/tfs 
but connects fine without 'tfs' bit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a build and release agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by NenoLoje** [comment] 2019-12-07 17:36
In the "Authenticate with a personal access token (PAT)" section, which gets included from "_shared/v2/prepare-permissions.md", we should:

- Say "Azure DevOps Server" instead of "Team Foundation Server" when moniker >= Server 2019.
- Update the URL to be: https://{your_server}/ (as mentioned in #4066 as well)

Thanks,
--Neno

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
