### ISSUE TITLE
Generic service connection Username/Password should be 'Optional'

### ISSUE THREAD

**Issue by ahaleiii** [MicrosoftDocs/azure-devops-docs#7640] opened 2020-03-18 15:14 UTC
The documentation says that the 'User name' and 'Password/Token Key' parameters are required. The 'Edit service connection' dialogue says that these are actually optional, and I was able to create a generic connection without adding these values.

![image](https://user-images.githubusercontent.com/7021001/76975973-a873b980-6909-11ea-8487-6126228e4bc0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-generic)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:29
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:29 UTC
Labels: Pri1, devops-cicd-library/tech, devops/prod, doc-bug
