### ISSUE TITLE
The arcticles are out-dated

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/azure-devops-docs#1269] opened 2018-07-11 11:49 UTC
Hi,
I need to raise an alert about all these how-to docs. There are out-dated:
1- Screenshots and steps are not always relevant with the current version of VSTS
2- MyShuttle2 does not exist anywhere. We are supposed to use MyShuttle
3- I was not able to successfully complete the steps, even if i took the time to guess the right steps

Please update and advise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b55e0120-df94-9e7a-5439-7d7c45841deb
* Version Independent ID: 92c4e1a2-b161-796f-7053-d5a68373a0f3
* Content: [Build Docker images for your Java project with VSTS](https://docs.microsoft.com/en-us/vsts/java/labs/builddocker/?view=vsts)
* Content Source: [docs/java/labs/builddocker/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/labs/builddocker/index.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by mlearned** [comment] 2018-07-11 16:01
@SamirFarhat  thank you, having a fresh look at things and will be back.

**Comment by mlearned** [comment] 2019-07-16 10:27
@erickson-doug  can we get someone to look at this one?

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:50 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
