### ISSUE TITLE
Clarify whether detected capabilities of an agent can be used as variables

### ISSUE THREAD

**Issue by Seikilos** [MicrosoftDocs/azure-devops-docs#7715] opened 2020-03-26 12:32 UTC
By reading the docs I cannot find information stating whether I can use the detected capabilities as variables in the build.

For instance I have an agent with this capability detected:
`MSBuild_16.0 C:\Program Files (x86)\Microsoft Visual Studio\2019\MSBuild\Current\Bin\`

I created a powershell script, that outputs this variable

```powershell
echo "$(Agent.Id) and $(Agent.Name)" # This works
echo "$(MSBuild_16.0)" # This fails, the name is not replaced
```

It is unclear whether this is possible or expansion must be done by other means etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:28
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:28 UTC
Labels: Pri1, devops-cicd-agents/tech, devops/prod, doc-bug

**Comment by xtu** [comment] 2021-08-02 10:28
@cxwtool can we reopen this issue? It is still valid.
