### ISSUE TITLE
Provide a method to release Desktop App

### ISSUE THREAD

**Issue by leus** [MicrosoftDocs/azure-devops-docs#4476] opened 2019-06-11 13:25 UTC
Please add a step with instructions on how to create relevant installers or packages for users to download. Something similar to "releases" in Github but for Azure Devops would be great.

**Comment by thomps23** [comment] 2019-06-14 17:10
@leus is there an existing topic you think this should be added to? Its possible the filing of this issue didnt capture the topic you were on.

**Comment by leus** [comment] 2019-06-27 19:09
@thomps23 currently there are no instructions nor any documentation on how to create a release for a desktop application. Everything in the docs point to either Azure VMs or ASP.NET applications. 

For examploe, this topic covers building an application but no information on how to deploy: [Build your .NET desktop app for Windows](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/windows/dot-net?view=azure-devops&tabs=vsts)

Documentation on how to create and how to get the relevant binary files after a build would be great. It's quite cumbersome to do so right now, not easily discoverable.

**Comment by thomps23** [comment] 2019-06-27 19:16
@leus Thanks for following up, i've completed the triage and assigned the issue.

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri3, doc-enhancement
