### ISSUE TITLE
Add sample with scripts arguments

### ISSUE THREAD

**Issue by Gismork** [MicrosoftDocs/azure-devops-docs#7236] opened 2020-02-11 16:08 UTC
Could you add some samples with scripts arguments passed to the az inline script ?
It's not always clear which syntax we need to use.
Thank you !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops#example)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**

**Comment by cconrado** [comment] 2020-04-29 02:50
any update on this?

**Comment by Romiko** [comment] 2020-04-30 23:47
Yes, please can we have some documenation using arguments a variety of ways

e.g. inlinde
xya $1 $2

also what about name arguments
xya $arg2 $arg1 etc

**Comment by wildky** [comment] 2020-05-06 20:41
Do we use arguments to pass pipeline variables to the CLI scripts? I am also requesting more info and examples around the arguments option

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
