### ISSUE TITLE
What about ##vso[task.debug]message?

### ISSUE THREAD

**Issue by Thilas** [MicrosoftDocs/azure-devops-docs#7839] opened 2020-04-06 07:54 UTC
I know from PowerShell module VstsTaskSdk that it exists but why not documenting it here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by Thilas** [comment] 2020-09-26 08:55
Any news about this?

**Comment by juliakm** [comment] 2020-11-25 17:54
Closing this ticket. We added task.debug recently. See [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#formatting-commands).

**Closed by juliakm** 2020-11-25 17:54 UTC
Labels: Pri1, devops-cicd-scripts/tech, devops/prod, doc-bug

**Comment by SimonAlling** [comment] 2021-08-09 09:29
> Closing this ticket. We added task.debug recently. See [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#formatting-commands).

I'm not quite following, @juliakm. The link refers to the _Formatting commands_ section of the _Logging commands_ page, which says:

> The formatting commands are:
> 
>     ##[group]Beginning of a group
>     ##[warning]Warning message
>     ##[error]Error message
>     ##[section]Start of a section
>     ##[debug]Debug text
>     ##[command]Command-line being run
>     ##[endgroup]

But the issue is about `##vso[task.debug]` – not `##[debug]` – which is not mentioned anywhere in that page. It is used not only by the `VstsTaskSdk` PowerShell module (as reported by @Thilas), but [also extensively by `azure-pipelines-task-lib`](https://github.com/microsoft/azure-pipelines-task-lib/blob/77c834ef3e62f9a43f28a2ef74bd517146a9da27/node/internal.ts#L294). So, indeed, shouldn't it be documented?

I'm particularly interested in this because [azure-pipelines-logging](https://github.com/SimonAlling/azure-pipelines-logging) is intended to support all commands understood by Azure Pipelines. At the time of writing, [it doesn't support `##vso[task.debug]` (`command("task", "debug")`)](https://github.com/SimonAlling/azure-pipelines-logging/blob/23dd3507e9e06f2e750d29584141bb5a11563dfc/src/internal/command.ts#L69) because I wrote it based on said documentation page and didn't even know about `##vso[task.debug]`; I just now stumbled over it by accident.
