### ISSUE TITLE
Azure Pipeline SCVMM Deployment References SCVMM 2012 R2

### ISSUE THREAD

**Issue by mletterle** [MicrosoftDocs/azure-devops-docs#3537] opened 2019-03-01 20:18 UTC
https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/scvmm?view=azure-devops#scvmm-connection

The first bullet point says

> Install the Virtual Machine Manager (VMM) console on the agent machine by following these instructions. Supported version: System Center 2012 R2 Virtual Machine Manager.

System Center 2012 R2 VMM has been [out of mainstream support since 2017](https://support.microsoft.com/en-us/lifecycle/search/17456).  

Looks like this cavet has been in there since the initial doc import, I would assume it should either be removed or updated to 2016.

**Comment by alexhomer1** [comment] 2019-03-04 17:13
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by ashokirla** [comment] 2019-12-17 12:33
Yes, now we support SCVMM 2016. We will update the documentation.

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri3, devops-cicd/tech, devops/prod, doc-bug
