### ISSUE TITLE
Change sample deployment script to PowerShell

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/azure-devops-docs#1681] opened 2018-09-11 14:28 UTC
Currently, this is a .bat script which looks quite dated. Should be changed to PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by MichaelStolpa** [comment] 2019-03-08 21:26
Is there a way to indicate that I'd like to use powershell? I get errors when trying to do so.

Standard error from script: 
2019-03-01T22:10:12.0726688Z ##[error]'Write-Host' is not recognized as an internal or external command,
operable program or batch file.

2019-03-01T22:10:12.9887638Z ##[error]Error: Unable to run the script on Kudu Service. Error: Error: Executed script returned '1' as return code. Error: 'Write-Host' is not recognized as an internal or external command,
operable program or batch file.

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
