### ISSUE TITLE
Documentation is missing around `containerRegistry`

### ISSUE THREAD

**Issue by booyaa** [MicrosoftDocs/azure-devops-docs#6465] opened 2019-11-25 10:52 UTC
This is the one task input that you can't use variable groups.  It must be the hardcoded service connection name.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/build/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment] 2019-11-26 06:40
@booyaa Thank you for the feedback, assigning this to the author for review.

**Comment by mithunshanbhag** [comment] 2020-01-28 16:36
Running into the same issue as @booyaa. Any resolution on this

**Comment by worldspawn** [comment] 2020-02-13 05:47
You can definitely use variables. eg `containerRegistry: drawboard-$something`.

This is determined at compile time. Which means you cannot use a runtime variable or rely on a value in the variable set at runtime. This whole compile time/runtime fiasco really ruins the yaml options utility.

A runtime reference (`containerRegistry: $[ variables.registry]`) never works.

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
