### ISSUE TITLE
The service connections section has been updated

### ISSUE THREAD

**Issue by oktotechnologies** [MicrosoftDocs/azure-devops-docs#7094] opened 2020-01-29 13:18 UTC
The service connections configuration is completely different than it used to be before so this page need a refresh.

Also, add a troubleshoot section, as mentioned below on what to do when a Azure Resource Manager is picked in combination with Service principal (automatic) and no subscription can be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26477658-d1ad-a4c9-0d9e-59aeead8a71e
* Version Independent ID: 45dfbd24-b9f4-fdf2-48a2-5648220204fe
* Content: [Connect to Microsoft Azure - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#feedback)
* Content Source: [docs/pipelines/library/connect-to-azure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/connect-to-azure.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment] 2020-01-29 14:59
@ashokirla

**Comment by beauof** [comment] 2020-03-25 08:11
I have the same problem.

"Switch from the simplified version of the dialog to the full version using the link in the dialog." --> this link does no longer exist.

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
