### ISSUE TITLE
Ubuntu 16.04 doesn't contain git version 2.9

### ISSUE THREAD

**Issue by jochenjonc** [MicrosoftDocs/azure-devops-docs#7843] opened 2020-04-06 09:35 UTC
When creating an image like in the documentation above and using it in combination with Azure DevOps Server, I get the following error:

##[section]Starting: Checkout
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Syncing repository: **** (Git)
##[command]git version
git version 2.7.4
To get a better Git experience, upgrade your Git to at least version '2.9'. Your current Git version is '2.7.4'.
##[error]Min required git version is '2.9', your git ('/usr/bin/git') version is '2.7.4'
##[section]Finishing: Checkout

To fix this you either have to use Ubuntu 18.04 or install git from another apt-get repository.

Maybe the documentation should be adjusted to include this?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:28
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:28 UTC
Labels: Pri1, devops-cicd-agents/tech, devops/prod, doc-bug
