### ISSUE TITLE
Need steps for pushing this to a remote

### ISSUE THREAD

**Issue by donzacharias** [MicrosoftDocs/azure-devops-docs#4496] opened 2019-06-12 23:05 UTC
These steps end with a local repository. I think it would be more helpful to complete the instructions on pushing this new local git repository to a shared location like Github.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Migrate from Subversion (SVN) to Git](https://docs.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops#feedback)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/perform-migration-from-svn-to-git.md)
* Product: **devops**
* Technology: **devops-whitepapers**
* GitHub Login: @hkamel
* Microsoft Alias: **hkamel**

**Comment by apawast** [comment] 2019-07-01 19:24
Hi @donzacharias, just to clarify are you asking for documentation on how to push specifically to Github or some general version control platforms like Github/Azure Repos?

**Comment by donzacharias** [comment] 2019-07-01 19:56
That was the idea - it doesn’t add much work, just adding a remote and
pushing.

**Comment by apawast** [comment] 2019-07-01 20:09
@donzacharias I understand. I will add instructions to the doc on how to push to an Azure Repo as an example. Thank you for the feedback!

**Comment by ataparia** [comment] 2019-08-22 15:07
Did you get a chance to write the steps to push the local GIT repo to Azure Repo? Are these steps under this section - "Push repository to a bare git repository". If yes, I have already created a repo on Azure and I have the URL for the same. How do I push the local GIT repo created following your steps to the azure repo?

**Comment by Vincentpapuchon** [comment] 2020-02-21 13:32
This works for me :
(Install Azure CLI if not done already)

Write-Host -nonewline "Create AZURE Project ? (y/n) : "; $reply = Ask
if($reply -eq 'y')
  {	
    # AZURE URL Config and Test
    Write-Host "==> Creating AZURE Project..."
    # add dev-ops extention (in case it's not already done)
    # az extension add --name azure-devops
    # create an AZURE project
    az devops project create --name "$azure_name"
    Write-Host ""
    Write-Host "==> AZURE URL : $azure_url"
    Write-Host "==> AZURE Project Created."
    Write-Host ""
  }
  
Start-Sleep -Seconds 1
Write-Host -nonewline "Puch project to AZURE ? (y/n) : "; $reply = Ask
if($reply -eq 'y')
	{
    Write-Host ""
    Write-Host "==> Push to Azure..."
    Set-Location -Path "$new_bare_git"
    git push --mirror "$azure_url"
    Write-Host "==> Git Puched."
    Write-Host ""
  }

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri1, devops-whitepapers/tech, devops/prod, doc-bug
