### ISSUE TITLE
MacOS support for Python Task

### ISSUE THREAD

**Issue by michaelmj** [MicrosoftDocs/azure-devops-docs#6409] opened 2019-11-19 16:25 UTC
The "Note" states Python task is not available on macOS, but 10.13 and 10.14 explicitly state that it's available in the Microsoft hosted agents : https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d52f9bd-a63c-d65f-ad92-7f245e4eb5c0
* Version Independent ID: 51ce0fb6-3195-6593-bd62-57c1c0157989
* Content: [Use Python Version task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/tool/use-python-version.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/use-python-version.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @brcrista
* Microsoft Alias: **brcrista**

**Comment by msebolt** [comment] 2019-11-19 21:20
@michaelmj  Thank you for the feedback.

The note should be updated to reflect that **both** 32-bit and 64-bit are supported on Windows (see [Readme.md](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md)), whereas Mac and Linux only offer 64-bit.

Assigning this to the author for review.

**Comment by msebolt** [comment] 2019-11-19 21:21
Including @brcrista

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
