### ISSUE TITLE
Linking to a build artefact from another project collection

### ISSUE THREAD

**Issue by TheBeardedLlama** [MicrosoftDocs/azure-devops-docs#1658] opened 2018-09-06 10:01 UTC
It would seem from reading the docs that it is possible to reference a build artefact across project collections.
If I haven't misunderstood, then I have tried and failed to do that in latest TFS2018.
If I have, it would be good to clarify the language in order to avoid such misunderstandings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598465e1-85d4-4961-b8b6-902d6026c5e3
* Version Independent ID: 5ef1308a-3aeb-fcc4-dec7-6f10785612a3
* Content: [Artifacts in Release Management](https://docs.microsoft.com/en-us/vsts/pipelines/release/artifacts?view=vsts)
* Content Source: [docs/pipelines/release/artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/artifacts.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment] 2018-09-11 08:13
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by TheBeardedLlama** [comment] 2019-02-11 11:14
I take it that this has not progressed?

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
