### ISSUE TITLE
 Typo in parameter "Cancelled" for Complete: Finish Timeline

### ISSUE THREAD

**Issue by brandonaut** [MicrosoftDocs/azure-devops-docs#5604] opened 2019-09-13 21:45 UTC
Using `result=Cancelled` doesn't work, but `result=Canceled` (single "l") does. According to the GitHub page for logging commands, "Canceled" is the correct spelling as well: https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md#task-logging-commands. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#complete-finish-timeline)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **phwilson**

**Comment by brandonaut** [comment] 2019-09-13 21:49
I think the description for "Canceled" is also incorrect, since it only marks the *task* as canceled. It does not actually fail the entire build.

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
