### ISSUE TITLE
Changing demands for a given build run

### ISSUE THREAD

**Issue by jeffyoungstrom** [MicrosoftDocs/azure-devops-docs#7215] opened 2020-02-10 19:19 UTC
There's a tip at the end of this page that says "When you manually queue a build you can change the demands for that run." I don't see any way to specify a demand at run time.  Can you be more specific or reference another page with the info about how this is done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7541ee6-d2bb-84c0-fead-1aa8ee7d2372
* Version Independent ID: 5cf7c51e-37e1-6c67-e6c6-80262c4eb662
* Content: [Demands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/demands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/demands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment] 2020-02-18 14:24
@jeffyoungstrom When you manually queue a classic pipeline from the portal, a dialog is displayed where you can specify options for this run, including demands:
![image](https://user-images.githubusercontent.com/1580889/74744187-caf1b480-522f-11ea-8c1b-3f35404332ea.png)

For YAML pipelines, I don't see that option (but that may be because demands are typically use for self-hosted agents and my YAML pipelines are using Microsoft-hosted agents.. Let me find out and I will report back with more information.

**Comment by jeffyoungstrom** [comment] 2020-02-18 19:25
Yeah, I'm looking at a YAML pipeline with a self-hosted agent and don't get the option to set Demands. May just not be supported. If so, it would be helpful if the note in the document specified as much. Thanks!

**Comment by steved0x** [comment] 2020-02-18 20:34
@jeffyoungstrom I have got an internal thread going and will get a definitive answer shortly, but because it uses "queue" and "build" terminology, I am guessing it is for classic editor pipelines. YAML pipelines use "Run". I will update that section with more detail either way and post back here once I find out for sure.

**Comment by bedej** [comment] 2020-04-03 01:14
What's the resolution here? I'm trying to run a self hosted agent, but it's never getting picked, even when my Microsoft hosted agents are all busy. I think this is because of unsatisfied demands, but I don't know how to see what the demands are for the pipeline, so it's difficult to say.

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
