### ISSUE TITLE
❯ az boards 'boards' is misspelled or not recognized by the system.

### ISSUE THREAD

**Issue by 1ak31sha** [MicrosoftDocs/azure-devops-docs#13169] opened 2023-03-06 16:04 UTC
❯ az boards
'boards' is misspelled or not recognized by the system.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8390e96-a029-2729-2f34-fc57f2f5e131
* Version Independent ID: 03e58d17-8cd0-0dd7-2a08-6f3e9ddc27ac
* Content: [View or run a query in Azure Boards and Azure DevOps - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/queries/view-run-query?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/queries/view-run-query.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/view-run-query.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment] 2023-03-06 19:26
Duplicate of https://github.com/MicrosoftDocs/azure-devops-docs/issues/13170

**Closed by chcomley** 2023-03-06 19:26 UTC
Labels: Pri2, azure-devops-boards/svc

**Comment by 1ak31sha** [comment] 2023-03-07 18:01
![Screenshot_20230307_125727_Chrome](https://user-images.githubusercontent.com/15619911/223509444-a2dc6be5-325a-4ab4-857f-146981a8e9d9.jpg)
