### ISSUE TITLE
Q&A Section implies this can be used on Linux and macOS

### ISSUE THREAD

**Issue by W0GER** [MicrosoftDocs/azure-devops-docs#5982] opened 2019-10-14 20:41 UTC
The Q&A Section contains the question "Do I need an agent?" with an answer "You need at least one agent to run your build or release. Get an agent for Linux, macOS, or Windows."

Expected: The answer implies that the task can be run on Linux and macOS.
Actual: When run on a macOS the task returns the error "The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell."

It would be good to know how to publish symbols for a Xamarin Forms/iOS project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946d67f6-9bb7-481f-f32f-59b5965f9590
* Version Independent ID: 8865f1e2-15b3-8cdb-1d8c-939c665e9bdc
* Content: [Index Sources & Publish Symbols build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/index-sources-publish-symbols?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/index-sources-publish-symbols.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/index-sources-publish-symbols.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment] 2019-10-15 05:32
@W0GER Thank you for the feedback, we're sorry you had to experience these issues.

Assigning this to the author now for review.

**Comment by PBoraMSFT** [comment] 2019-10-24 11:16
@msebolt - this is not my area of expertise and I don't own that task / doc. Please re-route.

**Comment by stefankip** [comment] 2020-01-03 12:00
I just got the same message on a Linux agent.
How do we publish symbols on these platforms?

**Comment by schmoli** [comment] 2020-05-15 19:17
Adding to this (months later) as I am also curious!

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
