### ISSUE TITLE
No Rest API Sample Code

### ISSUE THREAD

**Issue by jeffpatton1971** [MicrosoftDocs/azure-devops-docs#8102] opened 2020-04-27 16:13 UTC
The github link above only has code for the .net libraries, it would be very nice to have a repo with rest api samples in c#.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4abeff84-74e7-7fd3-db28-fa92683143c8
* Version Independent ID: 9d289096-4cf9-cb30-0893-e9ae5a72a34d
* Content: [REST API samples for Azure DevOps and TFS - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/rest/samples?view=azure-devops)
* Content Source: [docs/integrate/get-started/rest/samples.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/get-started/rest/samples.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment] 2020-04-28 15:33
@jeffpatton1971 Thank you for the feedback.

This is an issue for the samples repo, please move this [here](https://github.com/microsoft/azure-devops-dotnet-samples/issues) for further feedback.

@chcomley

**Comment by jeffpatton1971** [comment] 2020-04-28 16:00
Pretty sure it's an issue for you, that entire repository changed names, and it appears that the code there is ONLY for the public dotnet libraries.

https://github.com/Microsoft/vsts-restapi-samplecode

became

https://github.com/microsoft/azure-devops-dotnet-samples

**Comment by msebolt** [comment] 2020-04-28 16:29
I'll assign this to the author for further review.

In the meantime, please refer to the [REST API](https://docs.microsoft.com/rest/api/azure/devops) with corresponding [auth sample](https://github.com/microsoft/azure-devops-auth-samples/tree/master/ClientLibraryConsoleAppSample).

**Comment by jeffpatton1971** [comment] 2020-04-28 17:18
@msebolt thanks, was really looking for some samples of working with build definitions. But I'm not finding any C# samples for anything more than auth.

**Comment by chcomley** [comment] 2020-04-29 16:10
Hi @jeffpatton1971, I've followed up with the product group and will be in touch soon. Thanks and I hope you have a great day!

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri2, devops-ecosystem/tech, devops/prod, doc-bug
