### ISSUE TITLE
User settings independent date format

### ISSUE THREAD

**Issue by BogdanIoanF** [MicrosoftDocs/azure-devops-docs#6854] opened 2020-01-08 09:41 UTC
Information on date format is not complete. It seems universal independent format is also supported:
'yyyy-MM-ddTHH:mm:ss' e.g. 2019-12-29T17:05:45
or
'yyyy-MM-ddTHH:mm:ssZ' (UTC) e.g. 2019-12-29T17:05:45Z

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 710af5f2-8a31-e0d3-4f20-00c79dc54713
* Version Independent ID: 1d4d9580-984c-9fee-861a-a02ce828d3db
* Content: [WIQL reference syntax - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/wiql-syntax.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/wiql-syntax.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment] 2020-01-09 02:26
@BogdanIoanF Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri1, devops-agile/tech, devops/prod, doc-enhancement
