### ISSUE TITLE
Confused regarding PAT scope

### ISSUE THREAD

**Issue by iampeterdaniels** [MicrosoftDocs/azure-devops-docs#6380] opened 2019-11-14 22:55 UTC
Page says "For the scope select Agent Pools (read, manage) and make sure all the other boxes are cleared. If it's a deployment group agent, for the scope select Deployment group (read, manage) and make sure all the other boxes are cleared."  Not clear if a "Deployment group" needs both "Agent Pools (read, manage)" and "Deployment group (read manage)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 425b68d1-4ba0-5657-4e09-f3aac361ea09
* Version Independent ID: f8044e9d-98e2-6e00-b513-a91e772b2ef8
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
