### ISSUE TITLE
how to trigger the code pipeline in javascript

### ISSUE THREAD

**Issue by stevenruizhang** [MicrosoftDocs/azure-devops-docs#3758] opened 2019-03-25 06:19 UTC
Hi team,
  We have one code pipeline existed in one project , and in another nodeJS project we want to trigger this code pipeline in nodeJS code when meet conditions, any document can follow this case? If has sample code with Java script it is perfect.

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri3
