### ISSUE TITLE
YAML builds only work with latest (>2.158.0) agents

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/azure-devops-docs#6031] opened 2019-10-17 14:05 UTC
We noticed that YAML builds only work when you have the latest (2.158.0+) agent version.

&gt; We had an earlier version (2.155.0) running, and YAML builds where not picked up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#unattended-config)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Shortcheese** [comment] 2019-11-19 09:01
We have the same issue everytime the agent version upgrades (even prereleases).
And Azure it self doesn't prompts that we uses an old version of the agent.

**Comment by danielstefanescu** [comment] 2019-12-20 09:52
The issue is still valid: the yaml build doesn't start if the on-premise agent doesn't have the latest *pre-release* version; lost 3 hours on this.

**Comment by 4nandP** [comment] 2020-02-14 11:12
We have this issue too, the self-hosted agents don't update for some reason and every time a new version comes out the builds stop getting picked up.

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
