### ISSUE TITLE
No information on how buildContext works.

### ISSUE THREAD

**Issue by pawelpetruch** [MicrosoftDocs/azure-devops-docs#8042] opened 2020-04-22 11:16 UTC
Build context is not where a Dockerfile is (what is a case with docker commands) but where azure-pipelines.yml is. This is confusing and requires some comments.
For example this is valid:
```
  - task: Docker@2
    inputs:
      command: 'build'
      dockerfile: 'ProjectFolder/AnotherFolder/Dockerfile'
      context: 'ProjectFolder/AnotherFolder'
```
This way you can access files from AnotherFolder from Dockerfile:
```
COPY . .
```

This is an equivalent of: 
`docker build -t someImage ./ProjectFolder/AnotherFolder`

But if following the cmd logic then the azure docker task would give us the following command:  
 ```
docker build -f ./ProjectFolder/AnotherFolder/Dockerfile -t someImage ./ProjectFolder/AnotherFolder
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, doc-enhancement
