### ISSUE TITLE
Update for ARM storage?

### ISSUE THREAD

**Issue by somepunk** [MicrosoftDocs/azure-devops-docs#2866] opened 2018-12-25 05:18 UTC
The instructions are for the ASM storage version.  How about an updated version covering ARM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cd475cc-3510-5c4b-29e0-698eab618041
* Version Independent ID: bf3fff29-d364-b8ee-78ea-620363067c0e
* Content: [Azure Storage with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/azure-storage?view=vsts#feedback)
* Content Source: [docs/service-hooks/services/azure-storage.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/azure-storage.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment] 2019-02-06 18:47
Hi @somepunk , these docs are undergoing an overhaul right now and should get an update soon. We are actually going to dial down on some of the docs as they are expensive to maintain with other services. I'm going to keep this around and tag @roofers for awareness so that we can keep a log of requests for new docs in the service hooks area.

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-collab/tech, devops/prod, doc-enhancement
