### ISSUE TITLE
More explicit sample

### ISSUE THREAD

**Issue by acesyde** [MicrosoftDocs/azure-devops-docs#803] opened 2018-05-16 18:44 UTC
Please add a sample with import between go files and directory
Add go test support with junit report file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dde5d58-3741-98a2-1038-9afd7518a682
* Version Independent ID: 68416c13-04f0-ce83-69a5-733850412e44
* Content: [Build your Go app](https://docs.microsoft.com/en-us/vsts/build-release/apps/go/go?view=vsts&tabs=vsts)
* Content Source: [docs/build-release/apps/go/go.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/go/go.md)
* Service: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by elsesiy** [comment] 2019-02-08 10:04
I can second this, the current docs are not really helpful. Please also add an example usage for Go Modules where the env `GO111MODULE=on` is set or the source files are located outside of `GOPATH`. I couldn't make it work due to permission errors i.e.
`2019-02-08T09:55:26.6401916Z go build golang_org/x/net/http2/hpack: open /usr/local/go1.11/pkg/linux_amd64/vendor/golang_org/x/net/http2/hpack.a: permission denied`

Thanks!

**Comment by cxwtool** [comment] 2020-11-24 23:50
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:50 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, devops/svc, doc-bug
