### ISSUE TITLE
azureContainerRegistry Parameter Format

### ISSUE THREAD

**Issue by jlhjr** [MicrosoftDocs/azure-devops-docs#3638] opened 2019-03-13 23:59 UTC
These docs define the "azureContainerRegistry" parameter as "(Required) Name of the Azure Container Registry".  However, when I used just the name in my pipeline, I got an "unauthorized" exception when trying to push images.  After reviewing the YAML generated for this task (specifically, the "docker-compose push" task) by the visual designer, I saw that the visual designer uses the format:

azureContainerRegistry: '{"loginServer":"$(CONTAINER_REGISTRY_NAME).azurecr.io", "id": "/subscriptions/$(CONTAINER_REGISTRY_SUBSCRIPTION_ID)/resourceGroups/$(CONTAINER_REGISTRY_RESOURCE_GROUP)/providers/Microsoft.ContainerRegistry/registries/$(CONTAINER_REGISTRY_NAME)"}'

When I tried the above format, the docker-compose push command worked.  Are the docs wrong?  I am pretty sure we set up the service connection correctly.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d767aebb-620e-9ad3-e906-3e2bafa02ee9
* Version Independent ID: c8cb5a48-ccdf-778c-1547-a10db74cb56c
* Content: [Docker Compose task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops#push-service-images)
* Content Source: [docs/pipelines/tasks/build/docker-compose.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker-compose.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **shasb**

**Comment by nickrivas** [comment] 2019-08-09 13:47
You need to use `azureContainerRegistry: contoso.azurecr.io`

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
