### ISSUE TITLE
Missing details for inputs

### ISSUE THREAD

**Issue by noelbundick** [MicrosoftDocs/azure-devops-docs#4713] opened 2019-07-02 17:26 UTC
There are no details on what `addSpnToEnvironment` or `useGlobalConfig` do here in the docs

As an example for `addSpnToEnvironment`, the following is help text in the task repo: https://github.com/microsoft/azure-pipelines-tasks/blob/8d65f9c930fc6c88fe6eba4f3aa9bcdd3be8a78f/Tasks/AzureCLIV1/Strings/resources.resjson/en-US/resources.resjson#L19

"Adds service principal id and key of the Azure endpoint you chose to the script's execution environment. You can use these variables: `$servicePrincipalId` and `$servicePrincipalKey` in your script.\n\nThis is honored only when the Azure endpoint has Service Principal authentication scheme."

Can we get the missing properties added to docs so users don't have to read task source?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment] 2019-07-03 05:40
@pulkitaggarwl  for az cli

**Comment by StefanSchoof** [comment] 2019-07-22 04:07
A look into the source show there is also the `tenantId`: 

https://github.com/microsoft/azure-pipelines-tasks/blob/161f40de8cf062cb9c738d39f54237292e2b9255/Tasks/AzureCLIV1/azureclitask.ts#L70-L75

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
