### ISSUE TITLE
Add documentation about using go mod

### ISSUE THREAD

**Issue by tdi** [MicrosoftDocs/azure-devops-docs#4952] opened 2019-07-21 21:06 UTC
Modern go has go mod for dependency installing. It would be nice to document alternative way of getting dependencies instead of dep. For that you need to chnage the example yamls a bit so that you do not build in the GOPATH

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 1199cdec-3d76-5693-6295-6f36ce05f3bf
* Version Independent ID: 04ae7849-e91d-caf3-d48a-926473996248
* Content: [Build and test Go projects - Azure Pipelines](https://docs.microsoft.com/pl-pl/azure/devops/pipelines/languages/go?view=azure-devops)
* Content Source: [docs/pipelines/languages/go.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/go.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by zezha-msft** [comment] 2019-08-12 21:41
Agreed. 

Here is an example btw: https://github.com/Azure/azure-storage-azcopy/blob/dev/azure-pipelines.yml#L18

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
