### ISSUE TITLE
Example of path

### ISSUE THREAD

**Issue by KarsonAlford** [MicrosoftDocs/azure-devops-docs#11103] opened 2021-07-21 12:10 UTC
Please update documentation with an example of specifying the path for checkout.

https://github.com/MicrosoftDocs/azure-devops-docs/issues/7643

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment] 2021-07-21 15:14
@KarsonAlford - If I understand your comment, your issue is covered by the issue that you link to. It is labeled ready-to-doc, so that is in progress. I'm going to close this as duplicate of MicrosoftDocs/azure-devops-docs/issues/7643, but if those changes don't address your issue, we can reopen this one.

**Closed by TimShererWithAquent** 2021-07-21 15:14 UTC
Labels: devops-cicd-repos/tech, devops/prod
