### ISSUE TITLE
Note about Microsoft Edge browser support is missing link

### ISSUE THREAD

**Issue by raydixon** [MicrosoftDocs/azure-devops-docs#6961] opened 2020-01-16 16:24 UTC
The note near the top of the page that reads as follows is missing a hyperlink.

"Microsoft Edge browser currently cannot be run in the headless mode. To follow developments in this space, see this user voice item."

There is no link and it is unclear where I should go to find/follow developments on UI testing using a Microsoft Edge (old or the new Chromium-based version).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c96ae1b3-ab4c-540e-c4ca-79075f55f202
* Version Independent ID: c7b3e395-c55e-51a1-0f7e-8f5fb0430ee8
* Content: [Configure for UI testing - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops&tabs=mstest)
* Content Source: [docs/pipelines/test/ui-testing-considerations.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/ui-testing-considerations.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
