### ISSUE TITLE
Information missing from Invoke REST API task page

### ISSUE THREAD

**Issue by mehals** [MicrosoftDocs/azure-devops-docs#7166] opened 2020-02-05 20:29 UTC
There's some missing information on this documentation page about using this API

- The service called needs to return a 202 immediately, otherwise, the deploy step will still fail after 20 seconds
- The callback needs to include the bearer authtoken that the caller gives it with the first call, as `Bearer <authtoken>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb39c70-e320-3a02-fa5d-57e4f1849ebe
* Version Independent ID: 8237d198-1aa4-ccb7-53a3-7b9accd10e77
* Content: [Invoke HTTP REST API task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/http-rest-api.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
