### ISSUE TITLE
Provide more detail on cross-platform code coverage in .NET Core

### ISSUE THREAD

**Issue by scottaddie** [MicrosoftDocs/azure-devops-docs#2212] opened 2018-10-24 15:44 UTC
Coverlet is typically used with a solution like ReportGenerator to generate a human-readable code coverage report. This detail is missing. We should also provide a basic YAML snippet in this section to better guide customers using Linux or macOS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* Content: [Building .NET Core projects with Azure Pipelines and TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=vsts&tabs=yaml#feedback)
* Content Source: [docs/pipelines/languages/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/dotnet-core.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by scottaddie** [comment] 2018-12-19 15:49
@PBoraMSFT If it helps get this work done, I have a YAML file demonstrating how I accomplished this: https://github.com/scottaddie/ViewComponentsDemo/blob/master/azure-pipelines.build.yml

**Comment by andyjlewis** [comment] 2019-03-12 16:49
@PBoraMSFT can you look into this?

**Comment by thomps23** [comment] 2019-05-08 20:26
@PBoraMSFT  - it looks like we have the YAML snippets, but did we want to add the reference to known solutions for generating human readable reports with Coverlet?

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
