### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by echoesian** [MicrosoftDocs/azure-devops-docs#8111] opened 2020-04-28 02:29 UTC
source codes show Java but title says deploy nginx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf8bb33-e4cf-3dc5-5510-1111b8f1bdbf
* Version Independent ID: 3148d97d-2ff1-30f5-0487-dbfe93888a3f
* Content: [Deploy nginx to a Linux VM - Azure Pipelines](https://docs.microsoft.com/en-in/azure/devops/pipelines/apps/cd/deploy-linuxvm-deploygroups?view=azure-devops&tabs=java#feedback)
* Content Source: [docs/pipelines/apps/cd/deploy-linuxvm-deploygroups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/apps/cd/deploy-linuxvm-deploygroups.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri2, devops-cicd-apps/tech, devops/prod, doc-enhancement
