### ISSUE TITLE
DependsOn for steps

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/azure-devops-docs#8327] opened 2020-05-14 13:47 UTC
Is it possible to add dependencies to steps?
For example I want to run publish .pdb only if build step was succeeded. They both in same job. Or for example I want to publish .sql files only if any of them exists in specific folder.
All what I found now is "in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues')" that refer to whole JobStatus. And continueOnError: true - that warn me but not allow to refer to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment] 2020-05-15 06:11
@VerdonTrigance Thank you for the question.

By design `dependsOn` should be used between jobs.  Is there a particular reason the steps can't be broken down into separate jobs?

To submit this as a feature request, we recommend getting feedback from the product team using the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by VerdonTrigance** [comment] 2020-05-15 08:56
> @VerdonTrigance Thank you for the question.
> 
> By design `dependsOn` should be used between jobs. Is there a particular reason the steps can't be broken down into separate jobs?
> 
> To submit this as a feature request, we recommend getting feedback from the product team using the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Just because building and publishing should be in one job. Otherwise I'll lose build result between jobs.

**Comment by msebolt** [comment] 2020-05-18 21:37
I see, unfortunately then this will need to assessed by the product team for additional feedback.

Please use the link above and if you have issues with the current documentation please comment below.

**Comment by msebolt** [comment] 2020-06-01 16:39
Closing this issue now, for additional help please refer to [Azure DevOps support](https://azure.microsoft.com/support/devops/).

**Closed by msebolt** 2020-06-01 16:39 UTC
Labels: Pri1, devops-cicd-process/tech, devops/prod, product-question

**Comment by VerdonTrigance** [comment] 2020-06-01 17:17
Every time I dig yaml pipeline deeper and deeper I realize it's not so userfriendly and not so comfortable to use. It still have a lot problems inside invisible from the first sight. Hope it become better eventually.

**Comment by rafadess** [comment] 2021-07-03 23:43
I have the same concern of this issue: want to run the publishing step just if build step has succeeded. Looking at the documentation I found this:

> By default, steps, jobs, and stages run if all previous steps/jobs have succeeded. It's as if you specified "condition: succeeded()"

[Reference](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml`)

So if build and publish are in the same job, the publish step will run just if build had been succeeded. 
Am I right?

**Comment by foxmeyson** [comment] 2023-03-27 11:38
You can do this:
```
jobs:
  - job:
      - bash: |
           exampleshell.sh
        name: GetToken
      - bash: |
           anotherstep
        condition: succeeded('GetToken')
```
This work for me.
