### ISSUE TITLE
 Nunit now provides a formal definition for attachments in the results schema

### ISSUE THREAD

**Issue by taaariq** [MicrosoftDocs/azure-devops-docs#6937] opened 2020-01-14 21:03 UTC
https://docs.microsoft.com/en-us/azure/devops/pipelines/test/collect-screenshots-and-video?view=azure-devops

The above article mentions the following: 
> The NUnit and JUnit test result formats do not have a formal definition for attachments in the results schema, so the Publish Test Results task cannot publish attachments when these formats are used.

However Nunit now seems to have a formal definition for attachments in the results schema.
See:
https://github.com/nunit/docs/wiki/Test-Result-XML-Format#attachments
https://github.com/nunit/docs/wiki/Test-Result-XML-Format#attachment
https://github.com/nunit/docs/wiki/Test-Result-XML-Format#filepath
https://github.com/nunit/docs/wiki/Test-Result-XML-Format#description

It would be good if the article could be update to reflect this and possibly provide an example of how to collect attachments in Azure DevOps test results when using nunit.

**Comment by msebolt** [comment] 2020-01-15 21:19
@taaariq Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri3, doc-enhancement
