### ISSUE TITLE
Helm v3.0 in docs

### ISSUE THREAD

**Issue by rajarshi-singh** [MicrosoftDocs/azure-devops-docs#6661] opened 2019-12-12 19:25 UTC
Please update examples to mention Helm v3.0, it seems like this task supports it now. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6730d493-93eb-12c0-eae3-a60f9462ab18
* Version Independent ID: 5b6ce957-8fa9-43d5-dc1a-129ddd553910
* Content: [Helm installer task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/helm-installer?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/tool/helm-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/helm-installer.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment] 2019-12-13 06:12
@rajarshi-singh Thank you for the feedback, assigning this to the author for review.

**Comment by IvanKirianov** [comment] 2020-03-23 19:54
Starting from today, even if we define direct version of Helm 3 version, it's take Helm v2
Caching tool: helm 2.16.4 x64
Prepending PATH environment variable with directory: /opt/hostedtoolcache/helm/2.16.4/x64/linux-amd64

Looks that something changed on Agents. 
Please,  suggest how to work with Helm v3, we want to avoid install Tiller and etc...

**Comment by IvanKirianov** [comment] 2020-03-23 20:13
Updating as in article resolved issue:
          - task: HelmInstaller@1
            displayName: 'Install Helm 3.1.0'
            inputs:
              helmVersionToInstall: 3.1.0

**Comment by brent-robinson** [comment] 2020-03-27 08:36
Agreed. I previously used version 0 of the task, but now the inputs are ignored.

```
  - task: HelmInstaller@0
    displayName: 'Install Helm'
    inputs:
      helmVersion: 3.1.0
      kubectlVersion: 1.14.8
```

Updating to v1 of the task resolved the issue.

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
