### ISSUE TITLE
Registration process clarification

### ISSUE THREAD

**Issue by davidcorrigan714** [MicrosoftDocs/azure-devops-docs#6355] opened 2019-11-13 17:00 UTC
The "Communication with Azure Pipelines" section is a bit misleading on how registration happens. It reads as if you're exchanging the PAT for an OAuth refresh token when it's really creating an RSA key pair and sending the public key to DevOps to be used for OAuth later. A link to the GitHub docs with the full explanation would be nice too, the page here:
https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/auth.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2019-11-13 21:53
@davidcorrigan714  Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
