### ISSUE TITLE
Installing agent in path with spaces causes issues with msiexec

### ISSUE THREAD

**Issue by DonalLOConnor** [MicrosoftDocs/azure-devops-docs#5517] opened 2019-09-07 09:49 UTC
If the agent ZIP file is unzipped to a path containing spaces, such as the "Program Files" directory, then when the agent needs to install modules involving msiexec commands, attempting to compensate for the space in the path, the agent will improperly surround any entire msiexec parameter for public properties (PROPERTY=VALUE) with quotes ("PROPERTY=VALUE"), instead of surrounding just the value (PROPERTY="VALUE"). This will cause the related installation to fail. The solution is to unzip the agent to a path containing no spaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
