### ISSUE TITLE
Export URI as environment variable

### ISSUE THREAD

**Issue by casparjespersen** [MicrosoftDocs/azure-devops-docs#4695] opened 2019-07-01 10:24 UTC
I would like to be able to parse the returned URI from this plugin and use it as a build argument for a Docker image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77227c6d-c042-d4b9-9801-ecb3547e1c33
* Version Independent ID: af8571a9-604a-6cf7-43ea-a714c42b95e7
* Content: [Python Pip Authenticate - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/pip-authenticate?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/pip-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/pip-authenticate.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by WilliamAntonRohm** [comment] 2019-07-01 23:14
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by noelbundick** [comment] 2019-07-02 17:21
@casparjespersen this is possible today - the task sets the `PIP_EXTRA_INDEX_URL`, which you can use with Docker. I've got an example of this here: https://www.noelbundick.com/gists/consuming-packages-from-a-private-azure-pipelines-python-artifact-feed/

@WilliamAntonRohm I believe this is a docs issue rather than a product issue. Can we get it added/documented that `PIP_EXTRA_INDEX_URL` is set as a result of the `PipAuthenticate@0` task? If that's autogenerated via the tasks repo, I can open an issue/PR there

**Comment by casparjespersen** [comment] 2019-07-03 08:42
@WilliamAntonRohm Thank you for mentioning this workaround.

**Comment by WilliamAntonRohm** [comment] 2019-07-15 20:47
@davidstaheli -- please look into adding this information to the documentation.

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
