### ISSUE TITLE
How to copy without subdirectories

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/azure-devops-docs#3825] opened 2019-04-01 09:43 UTC
The Additional Arguments lets me filter by filename, however, this still copies the contents of all subdirectories.

Is there an option to exclude subdirectories?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e0ef2cf-ed52-6ded-bf14-4820d73b4ed0
* Version Independent ID: 7781e0f0-43aa-9008-abda-c03a37e2d7b4
* Content: [Windows Machine File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/windows-machine-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/windows-machine-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/windows-machine-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by Abdulsametileri** [comment] 2019-12-18 11:09
I think, No.

https://ss64.com/nt/robocopy.html

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri2, devops-cicd/tech, devops/prod
