### ISSUE TITLE
repository url in .pypirc doesn't include project name for a project-scoped feeds

### ISSUE THREAD

**Issue by kulmam92** [MicrosoftDocs/azure-devops-docs#7296] opened 2020-02-14 20:36 UTC
Thank you for your feedback!

The issues in this repo are for documentation feedback.
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/twine-authenticate?view=azure-devops

The sample code doesn't work when you are trying to upload a python distribution to a project-scoped feed. It's because the repository URL in .pypirc doesn't include the project name.

```
cat /home/vsts/work/_temp/twineAuthenticate/UfiUHn/.pypirc
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/1fd11bec-dd0f-4ca2-b2d1-b6f085831b8f.sh
[distutils]
index-servers=iics_python 
[iics_python]
repository=https://pkgs.dev.azure.com/myorgedw/_packaging/my_python/pypi/upload
```

Upload fails with below error
> HTTPError: 404 Client Error: Not Found - The feed with ID 'my_python' doesn't exist.

As a workaround, I added a step to do a simple string replace to put project name to the repository URL
`sed -i 's/\/_packaging/\/$(System.TeamProject)\/_packaging/g' $(PYPIRC_PATH)`

The upload succeeded after I added the project name. Please this bug as well.

**Comment by cxwtool** [comment] 2020-11-24 23:31
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:31 UTC
Labels: Pri3, doc-bug
