### ISSUE TITLE
How do we make Windows Containers run?

### ISSUE THREAD

**Issue by ctaggart** [MicrosoftDocs/azure-devops-docs#3815] opened 2019-03-29 19:59 UTC
What is meant by "The agent must have permission to access the Docker daemon". The message was added with feedback in https://github.com/Microsoft/azure-pipelines-agent/issues/2082, but I don't think it is enough. What permissions do we change to make it work?

This `azure-pipelines.yml`:
``` yaml
jobs:

- job: Windows
  pool:
    vmImage: win1803
  container: 'mcr.microsoft.com/dotnet/core/sdk:2.2.105-nanoserver-1803'
  steps:
  - script: |
      dotnet --info
```

Fails with:
```
Exit code 1 returned from process: file name 'C:\Program Files\Docker\docker.EXE', arguments 'version --format '{{.Server.APIVersion}}''.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#requirements)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **macoope**

**Comment by aelij** [comment] 2019-05-23 10:41
[This answer](https://developercommunity.visualstudio.com/solutions/580459/view.html) may be relevant

**Comment by jmlane** [comment] 2019-06-19 20:30
I occasionally get this error as well, as the docker service isn't always started in the hosted agent when the task gets to this point. This seems to be a rare error on the hosted Win1803 pool though.

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri1, devops-cicd/tech, devops/prod
