### ISSUE TITLE
Azure Pipelines Docker Agent downloads prerelease version of azure-pipelines-agent

### ISSUE THREAD

**Issue by egrubbs** [MicrosoftDocs/azure-devops-docs#8276] opened 2020-05-11 19:46 UTC
In step 5 of the Linux Dockerfile setup, the following code from the `start.sh`  script always grabs the most recent version of azure-pipelines-agent even if it is a prerelease. I have run into bugs with the prerelease version. It would be helpful if this script downloaded the "Latest Release" version as indicated on the github page, instead of downloading the "Prerelease" version.
https://github.com/Microsoft/azure-pipelines-agent/releases
```
  AZP_AGENTPACKAGE_URL=$(echo "$AZP_AGENT_RESPONSE" \
    | jq -r '.value | map([.version.major,.version.minor,.version.patch,.downloadUrl]) | sort | .[length-1] | .[3]')
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by ms-lolo** [comment] 2020-05-12 21:22
I don't know if this is similar enough but is it possible for the docker image to be built with a specific version of the agent instead of having it downloaded at runtime?

**Comment by egrubbs** [comment] 2020-05-14 20:20
@ms-lolo , if you want to specify the agent version in the docker image, you can set the `AZP_AGENTPACKAGE_URL` in the `start.sh` file. You just have to set the variable below where it is currently being set.

```
AZP_AGENTPACKAGE_URL="https://vstsagentpackage.azureedge.net/agent/2.166.4/vsts-agent-linux-x64-2.166.4.tar.gz"
```

**Comment by ms-lolo** [comment] 2020-05-14 20:23
@egrubbs so then if I do that I can move this download logic to my `docker build` step? And I would just need to keep checking back for new versions and any breaking changes and such?

**Comment by egrubbs** [comment] 2020-05-14 22:27
@ms-lolo That's correct.

**Comment by ms-lolo** [comment] 2020-05-15 15:35
Perfect thank you :) will give this a try as soon as possible!

**Comment by frankfuu** [comment] 2020-05-20 05:08
@egrubbs say today I bake my own local copy of vsts-agent-linux-x64-2.166.4.tar.gz into my docker image, start it up, on the day 2 my agent updates itself, then on the 3rd day the container restarts itself (from a reboot on the host side for instance), what would happen? would vsts-agent-linux-x64-2.166.4.tar.gz be loaded again or would it load the version I had on day 2?

**Comment by egrubbs** [comment] 2020-05-20 15:24
@frankfuu The `start.sh` script is specified as the `CMD` in the `Dockerfile`, so it runs every time the container starts. If you install the agent in the `start.sh`, it will go back to the version before the upgrade. If you use `RUN` or `COPY` in the `Dockerfile` to install the initial version, then the upgrade will remain after you restart the container.

**Comment by frankfuu** [comment] 2020-05-20 15:31
Thank you kindly @egrubbs. I wonder why Azure Pipelines team decided to go with the former approach? I've had issues with slow downloads of the vsts-agent-linux-x64-xxx.tar.gz files when I wanted to fire up temporary agents and the solution you provided might be a way forward for us.

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri1, devops-cicd-agents/tech, devops/prod, doc-enhancement
