### ISSUE TITLE
Section: Test on the Android Emulator

### ISSUE THREAD

**Issue by JohnH-FF** [MicrosoftDocs/azure-devops-docs#5384] opened 2019-08-27 13:27 UTC
This section describes how to install and run the android emulator, but it does not describe how to then run UITests from here.

Mac build hosts (which at time of writing is required to be able to run the android emulator) does not support the VSTest task, and the dotnet cli task running with test doesn't recognise UITest projects. So how should this work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955d694a-7285-45b6-56b9-3a86ddbb0820
* Version Independent ID: 0d226e23-1ddd-f6de-abf7-5b112533ec78
* Content: [Build, test, and deploy Android apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/android?view=azure-devops#feedback)
* Content Source: [docs/pipelines/languages/android.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/android.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **dastahel**

**Comment by JohnH-FF** [comment] 2019-12-16 08:28
No comments on this? The documentation says you can run UI tests, it doesn't say how. Can someone shed some light?

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
