### ISSUE TITLE
sqlcmd not included in PATH - full path required

### ISSUE THREAD

**Issue by sebader** [MicrosoftDocs/azure-devops-docs#5302] opened 2019-08-20 13:12 UTC
[Here ](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml#sql-scripts)you have an example using `sqlcmd`. However, it is not included in the PATH, hence the full path is required to run it. See here: https://github.com/microsoft/azure-pipelines-tasks/issues/5817#issuecomment-348014357

The documentation should state that. Also, it seems like VS2017-server2016 is the only hosted build agent that supports this (built-in). Is that correct? If so, please also state this here. https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd85890a-ccba-8697-b406-b662aabeb27f
* Version Independent ID: a1d371df-c0a0-1cd6-37f8-4b60913a2e97
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/azure-sqldb.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
