### ISSUE TITLE
XML Variable Substitution Mechanics of Locating Elements

### ISSUE THREAD

**Issue by AaronLS** [MicrosoftDocs/azure-devops-docs#1687] opened 2018-09-11 17:13 UTC
The example has 4 items in step 3 "Define the required values in release pipeline variables"

"DefaultConnection" is the value of the name attribute, and the variable value replaces the connectionString attribute's value.  This would be the equivilant of &lt;add name="DefaultConnection" connectionString="Data Source..." xdt:Transform="SetAttributes" xdt:Locator="Match(name)"/&gt;

"AdminUserName" is the value of the key attribute, and the variable value replaces the value attribute's value.

This would be the equivalent of &lt;add key="AdminUserName" value="ProdAdminName" xdt:Transform="SetAttributes" xdt:Locator="Match(key)"/&gt;

In each case there two attributes.  The key/name attribute used as the locator, and the second attribute which is having it's value set.  Looking at the example, I assume that you've added some behind the scenes niceties, such that you search all name/key attributes for the value in the variable Name column, and then depending on the type you're assuming we want to set the connecitonString attribute.

So variable name matches the value of a key/name attribute.  And variable value sets the value of a connectionString/value attribute.  So there's always two attributes, one being used as lookup, and we look at the value of the attribute for a match, and then the second attribute where we set the value of that attribute.

One attribute used for the lookup, the second attribute has it's value set.

Connection strings: The value of "name" attribute is used as the lookup, the second attribute "connectionString" has its value set.

App settings: The value of "key" attribute is used as the lookup, the second attribute "value" has its value set.

In all of the first three examples, the variable name and variable value map to the **values** of attributes.  The attribute names "key" and "name" don't appear in the example.  It's clear the transformation understands these configurations and infers this.  **However**, invariantName is not a attribute value, but an attribute name.

The last example in the table with a variable name "invariantName" and variable value "System.Data.SqlClientExtension" isn't consistent.  *Here's where things get really confusing*  

How does it do the lookup?

Let's say that there was consistency with the above.

Entity Framework providers: The value of "invariantName" attribute is used as the lookup, the second attribute "type" has its value set.

If this were true, then the example would instead show this for the fourth variable name/value example:
"System.Data.SqlClientExtension"    "System.Data.Entity.SqlServer"

It would lookup the provider with invariantType(inferred by the transformation the same way it infers name/key) matching value "System.Data.SqlClientExtension", and then set the second attribute "type" to "System.Data.Entity.SqlServer".

However, in this case "invariantName" is not the value of an attribute, it is the attribute name.  And the value is the value of the **same** attribute instead of a second attribute in the same element.  This is different from the preivous example where they inferred the two attributes, looked up the element on the attribute value, and then set a second attribute.

This further breaks down when you consider that the `providers` collection can have multiple providers.  And they will all have an attribute called invariantName.  So honestly I don't understand how the fourth example could possibly work.

This is not a problem for the connectionStrings/appSettings collections because the example makes it clear that they infer the variable name as being a value match against name/key attributes ensuring a unique element is obtained.  So again, any kind of consistent example would have the variable name as "System.Data.SqlClientExtension" and we assume that it uses this match against invariantName.

This is exactly why config transforms must include four pieces of information.  The name of the element to use for location, the value of that location element, the name of the attribute to set, the value of that attribute.  It's clear you've built something that infers two of those four pieces of information, the two attribute names, so we only provide a variable name/value for the remaining two.

&lt;add name="**DefaultConnection**" **connectionString**="**Data Source...**" xdt:Transform="SetAttributes" xdt:Locator="Match(**name**)"/&gt;

However this leaves us to guess for different collection types how you infer what the location attribute is, and which attribute will have its value set.

I understand you've tried to simplify the transformation, but then it makes everything else much more complicated because we have to guess which attribute is the locator attribute for the more complicated cases.

I might try to let us specify all four pieces of information, so the locator is explicit and clear.  I understand there's some learning curve with how transforms use locator attributes, so having all four pieces of information is more confusing.

To simplify the common case, prepopulate the table with information from the config file or provide preset options "subsitute app setting"/"substitute connection string" and a modal can show list of connection string names to choose from, which would generate the entry with all for pieces of information.

So for example, I click a "Subsitute Connection String" button, then I see the list of connection strings "DefaultDatabase" and "UserDatabase" (if I had two databases).  I click "UserDatabase" and it adds an entry to the table with all four pieces of information.  

Locator Attribute  |  Locator Value To Match    |   Attribute To Set    |  Value To Set
name | UserDatabase | connectionString | &lt;type/paste your connection string here&gt;

This is very intuitive, yet at the same time helps me learn and understand how the locators work.  You make the common case simple, but allow for more complex scenarios.  (Sorry I don't know how to format tables on github.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=vsts)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by AaronLS** [comment] 2018-09-11 18:44
Also consider what if a connecitonString name and an appSetting key have the same value.  The values table doesn't specify which section the variable is for.

I'll add the invariantType example is even more ambiguous when you consider there could be other XML paths that contain an attribute called invariantType.  Even my proposed design change would fall short, because it would match any element path in different configSections that happen to use the same attribute name.  This could result in some really unexpected transforms.

I imagine those who originally developed config transforms looked at ways to simplify transforms, and probably came to the same conclusion, that basically there's too many ambiguous cases to do anything simpler than fully specifying XML path, which in essence transforms do.

I think the only other option besides the existing transformations would be to use XPath expressions as the locator and provide some buttons as I mentioned to generate the most common cases for appSettings and Connection Strings.

I'd almost prefer to just upload a config transform specific to that build/release step and flag it as secured.  This way I can have production values secured and protected by the permissions access on the pipeline, and not have to include the transform in source control.

**Comment by AaronLS** [comment] 2019-03-21 03:08
Still relevant.  The mechanics of transformations in this section are still ambiguous: "Define the required values in release pipeline variables:"

**Comment by philchuang** [comment] 2019-03-22 05:24
Found the source code for the javascript that actually performs the xml variable substitution, guess we'll have to find out the hard way:

https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/Common/webdeployment-common/xmlvariablesubstitutionutility.ts

**Comment by RoopeshNair** [comment] 2019-06-19 10:23
@N-Usha

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
