### ISSUE TITLE
Document the Query Results grid API

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/azure-devops-docs#3262] opened 2019-02-06 19:30 UTC
Some extensions add custom actions to the Query Results window. Currently there is no documentation on how those extension points can update, refresh, or show errors as a result of the calls to the Query Result menu item calls.
There does appear to be an API, going by how the built-in "Bulk Update" work items behaves, but without randomly poking in the console to see what is going on we haven't found a way to behave the same as the built-ins.

**Comment by steved0x** [comment] 2019-02-14 19:59
@willsmythe @matthewisabel Here is some feedback on the documentation for (I believe) the Extend area.

**Comment by nschonni** [comment] 2019-02-14 20:15
Here is a more concrete example. How would an extension like https://github.com/konradsikorski/VSS.Extension.ChangeState update the grid to show that there were errors updating work items on the query result view.

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri3, devops-ecosystem/tech, devops/prod, doc-bug
