### ISSUE TITLE
The yaml snipplet's comments are wrong and misleading (at least in DownloadSecureFile@1)

### ISSUE THREAD

**Issue by biohazard999** [MicrosoftDocs/azure-devops-docs#6636] opened 2019-12-11 06:23 UTC
The sample should be:

```yml
# Download secure file
# Download a secure file to the agent machine
- task: DownloadSecureFile@1
  name: TheNameOfTheVariable #This is user defined and can be used like $(TheNameOfTheVariable.secureFilePath)
  inputs:
    secureFile: TheNameOfTheSecureFile # The name with which to reference the secure file. This is NOT the actual filename but the name you give it after uploading it.
```

That works fine. This is also the same code that the classic UI produces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36505533-7471-1f67-1a1d-4f3273bf4bf2
* Version Independent ID: abffb74f-97ab-c739-f39e-6138fdb5352b
* Content: [Download Secure File task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-secure-file.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment] 2019-12-11 19:42
@biohazard999 Thank you for the feedback, assigning this to the author for review.

**Comment by jimlamb** [comment] 2019-12-13 17:09
Taking a look at this one.

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
