### ISSUE TITLE
More detail

### ISSUE THREAD

**Issue by indyjason79** [MicrosoftDocs/azure-devops-docs#1656] opened 2018-09-05 21:14 UTC
You do not cover signing or any of the other tasks involved. I would strongly suggest covering every step/task needed, especially signing the APK since that's what I've been stuck on the most trying to set this up for our company. You should also cover setting up pre-reqs such as installing Android SDK Levels and setting the ANDROID_HOME environment. I've been working on this for 2 days and still can't produce an APK that works. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c45a95ce-73c8-861e-f92d-a26f1667aa60
* Version Independent ID: ecb82128-cdf4-3834-62c1-2cf61989ab5e
* Content: [Build your Xamarin app](https://docs.microsoft.com/en-us/vsts/pipelines/apps/mobile/xamarin?view=vsts&tabs=vsts)
* Content Source: [docs/pipelines/apps/mobile/xamarin.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/mobile/xamarin.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment] 2018-09-05 23:30
Thanks for creating this issue, Jason.  I'd like us to document what you suggested ASAP.  I'm sorry for the wasted time and frustration you went through.  If you haven't exhausted all of your available time, could you please email me at dastahel@microsoft.com?  We can help you get things working and then use our weak spots to improve the product and guide what we put in the documentation, including what you suggested above.

**Comment by maestrocoder** [comment] 2018-10-17 21:09
This is great for Xamain.ios and Xamarin.Android -  BUT, what about Xamarin.MAC?

**Comment by DavidStaheli** [comment] 2019-03-10 18:43
Keep-alive

**Comment by indyjason79** [comment] 2019-03-11 07:51
Sorry, I had forgot to reply to this. I'll email you this week to help with
the documentation.

Thanks,
Jason Willett

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug, doc-enhancement
