### ISSUE TITLE
cloning second repo step does not work

### ISSUE THREAD

**Issue by automagicallyio** [MicrosoftDocs/azure-devops-docs#3703] opened 2019-03-20 22:33 UTC
I have created a token with full access to everything, but cloning a second repo does not work when using private Linux agent with the following error:

error: cannot run /usr/libexec/git-core/git-gui--askpass: No such file or directory
fatal: could not read Password for 'https://ACCOUNTNAME@dev.azure.com': No such device or address

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#feedback)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by espoelstra** [comment] 2019-03-21 18:24
Have you tried using `https://ACCOUNTNAME:YOURTOKEN@dev.azure.com/PATH/TO/YOUR/REPO`?

**Comment by issamhouidi** [comment] 2019-05-24 11:47
is it possible to clone a second repository in a YAML Build ? 
We are migration from TFVC to Azure DevOps Git and I didn't find any replacement or equivalent to workspace mapping in TFVC !!!!

**Comment by dragon788** [comment] 2019-05-24 12:52
If you have a checkout step that persists the credentials you can use a shell step to perform a git clone if you use the syntax described in the other comment.

**Comment by issamhouidi** [comment] 2019-05-27 10:15
> If you have a checkout step that persists the credentials you can use a shell step to perform a git clone if you use the syntax described in the other comment.

Thanks for your reply. Indeed I am using a checkout step and after that I added a command line with git clone command to the other repo using http link but the folder is created however stays empty and nothing is cloned. 
How also I can link to that folder in future steps 
Thanks

**Comment by jbeesonnuva** [comment] 2020-04-22 15:55
Any updates on this issue? I'm also trying to use the method for cloning a second repo just to automate cloning repos in general and I always get "fatal: Authentication failed for 'https://dev.azure.com/xxxxxxxxx"

The PAT being used is confirmed to be working with REST API calls so it's not that.

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
