### ISSUE TITLE
"configuration" does not work

### ISSUE THREAD

**Issue by jeremy-jameson** [MicrosoftDocs/azure-devops-docs#6053] opened 2019-10-18 14:41 UTC
It appears the **configuration** key in the **inputs** list is obsolete.

For example, if you specify the following in azure-pipelines.yml, Azure DevOps will actually build the default configuration (i.e. **Debug**) for your projects (not the **Release** version):
```
variables:
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: build
      configuration: $(buildConfiguration)
```

To achieve the desired result, you must specify the following:
```
variables:
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: build
      arguments: "--configuration $(buildConfiguration)"
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by msebolt** [comment] 2019-10-18 20:56
@jeremy-jameson Thank you for the feedback, assigning this to the author for review.

**Comment by cpdohert** [comment] 2020-05-04 15:28
This doesn't work for dotnet pack.  Given this:

```
- task: DotNetCoreCLI@2
            displayName: "Build and Pack the Library"
            inputs:
              command: "pack"
              arguments: "--configuration Release -p:PackageVersion=$(GitVersion.NuGetVersion) -p:Version=$(GitVersion.AssemblySemVer)"
              versioningScheme: byEnvVar
              versionEnvVar: GitVersion.NuGetVersion
              packagesToPack: ${{ parameters.ProjectPath }}
```

The task completely ignores the `arguments:` option entirely and constructs the command line thusly:
```
##[debug]arguments:
##[debug]   pack
##[debug]   C:\agent\_work\1\s\src\MyProject.csproj
##[debug]   --output
##[debug]   C:\agent\_work\1\a
##[debug]   /p:PackageVersion=1.1.0-alpha0003
##[debug]   --verbosity
##[debug]   Detailed
```

One look at the number of posted issues indicates that the task and its documentation are in dire need of a quality review.

**Comment by cpdohert** [comment] 2020-05-04 15:31
Addenda: I just noticed that it *is* documented that `arguements:` is not supported for `dotnet pack`.  Because why would we be consistent, or anything.

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
