### ISSUE TITLE
Define azurepipelines.yml without triggering a build

### ISSUE THREAD

**Issue by KarlGW** [MicrosoftDocs/azure-devops-docs#2125] opened 2018-10-17 10:53 UTC
Following the steps in [Create your first pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts). Is there anyway to define an `azure-pipelines.yml` without triggering the build at initial creation? I can only see a "Save and Run", not any way of just doing a Save and configure the trigger later on. Or can this be worked around by setting `trigger: 'none'` in the definition file?

There are quite som scenarios where it's desired to define and create the build, configure variables and secrets in the UI (from outside the `azure-pipelines.yml` and then run the initial build.

**Comment by andyjlewis** [comment] 2019-07-01 20:03
Thank you for your question. Apologies for the very delayed response.

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri3, devops-cicd/tech, devops/prod, doc-bug
