### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by chiko123** [MicrosoftDocs/azure-devops-docs#5051] opened 2019-07-29 21:16 UTC
What is this code for? You are assigning browser "Chrome" and then you are switching over it. What does the TestCategory("Chrome") useful for.

As well, it seems all tests are running in parallel by default. What can I do to disable this nice un-needed feature (at least in my case).

    [TestInitialize()]
    public void SetupTest()
    {
      appURL = "http://www.bing.com/";

      string browser = "Chrome";
      switch(browser)
      {
        case "Chrome":
          driver = new ChromeDriver();
          break;
        case "Firefox":
          driver = new FirefoxDriver();
          break;
        case "IE":
          driver = new InternetExplorerDriver();
          break;
        default:
          driver = new ChromeDriver();
          break;
      }

    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e51d18-72ec-1ad4-9ae7-8185c8e1dcd6
* Version Independent ID: 9f2f0471-d123-8e95-1606-cd811d1ece9a
* Content: [Perform UI tests with Selenium - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=azure-devops#feedback)
* Content Source: [docs/pipelines/test/continuous-test-selenium.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/continuous-test-selenium.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ZLTM** [comment] 2019-09-16 13:47
Is's selecting the driver based on your browser, so the chrome browser will use a ChromeDriver, an IE browser would use an InternetExplorerDriver.
This lets you test your app on several browsers

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri1, devops-cicd/tech, devops/prod
