### ISSUE TITLE
No troubleshooting when no Azure subscriptions appear

### ISSUE THREAD

**Issue by yevster** [MicrosoftDocs/azure-devops-docs#4335] opened 2019-05-24 20:27 UTC
In step 3 of the Service Connection creation instructions, the following language appears: "If you don't see any Azure subscriptions or instances, see Troubleshoot Azure Resource Manager service connections."

However, the [Troubleshoot Azure Resource Manager](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-rm-endpoint?view=azure-devops) page only covers specific errors that arise on creation. It does not cover the scenario when no subscriptions appear, as was promised.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26477658-d1ad-a4c9-0d9e-59aeead8a71e
* Version Independent ID: 45dfbd24-b9f4-fdf2-48a2-5648220204fe
* Content: [Connect to Microsoft Azure - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops)
* Content Source: [docs/pipelines/library/connect-to-azure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/connect-to-azure.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment] 2019-06-18 11:49
The service connection screen has appropriate guidance. We need to update the docs. 

![image](https://user-images.githubusercontent.com/1370480/59679701-2e34ce00-91ed-11e9-800d-6613d1b87678.png)

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
