### ISSUE TITLE
We've TFS 2017.1 on-prem and secure files are not available

### ISSUE THREAD

**Issue by schmidtaa** [MicrosoftDocs/azure-devops-docs#3821] opened 2019-03-31 15:07 UTC
Which version or how to install them in TFS 2017?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140dcb9a-2ed0-11d5-064b-068f863ed97f
* Version Independent ID: 672d2aa3-cf0d-9207-c97c-e2eba14506b7
* Content: [Secure files for Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops#feedback)
* Content Source: [docs/pipelines/library/secure-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/secure-files.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **madhurig**

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri1, devops-cicd/tech, devops/prod
