### ISSUE TITLE
Difference between AzureResourceManagerTemplateDeployment and AzureResourceGroupDeployment

### ISSUE THREAD

**Issue by fgheysels** [MicrosoftDocs/azure-devops-docs#7122] opened 2020-01-31 10:34 UTC
There seem to be 2 similar tasks available for deploying Azure resources.

Unfortunately, I cannot find any documentation regarding the `AzureResourceManagerTemplateDeployment` although this `AzureResourceManagerTemplateDeployment` task can be choosen from the Yaml pipeline editor in Azure Devops:

```yaml
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'
```

On the other hand, I cannot find the `AzureResourceGroupDeployment` task in the Yaml pipelines editor in Azure Devops.  What are the differences between these 2 tasks ?  Where can I find the documentation regarding the `AzureResourceManagerTemplateDeployment` task and how come I cannot find the `AsureResourceGroupDeployment` task in the Yaml editor in Azure Devops ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by anderseide** [comment] 2020-02-13 00:36
Hi!

Documentation for the AzureResourceManagerTemplateDeployment can be found at https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceManagerTemplateDeploymentV3

Main difference is the deploymentScope part, where you can choose to target either on Management Group, Subscription or Resource Group level. Highly useful when you have service connections that span multiple subscriptions

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement

**Comment by lazarillo** [comment] 2021-04-23 11:33
Is anyone able to answer this question?  I am also confused.

@anderseide 's link is the *only* documentation I can find on `AzureResourceManagerTemplateDeployment`, and it is so poor that it does not even provide a single example of how to call it in a YAML pipeline, let alone provide any reference documentation for what each parameter means.  Eg, what is the difference between `templateLocation` and `csmFileLink`?

Also, which one has which scope?  Does `AzureResourceManagerTemplateDeployment` have the higher scope (Mgmt group or Subsc)?  Or `AzureResourceGroupDeployment`?  I presume the former, but that is purely just a guess with no documentation to support.  :(

**Comment by marc-gmail-towersap** [comment] 2023-02-10 00:33
Templatelocation is where ADO is going to access the json file (aka arm template).  it's either going to be locally somehow (linked artifact) on the agent, or, something outside the agent, be it a URL or a storage account.

If templatelocation is 'URL of the file', then you want to use csmFileLink to specify where the json file can be accessed at, which can be a real URL (assuming you have permissions to download it) or information to the storage account. if you google around, you can find examples. same for the parameterfilelink.

Otherwise, use csmFile.

As for the other, you cna find at https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-group-deployment-v2?view=azure-pipelines&viewFallbackFrom=azure-devops#troubleshooting

while it would be great to give examples, well, they don't.
