### ISSUE TITLE
Add a workaround example for non-commercial sonarqube 

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/azure-devops-docs#7207] opened 2020-02-09 14:09 UTC
Add an example like
```
sqAnalysisEnabled: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
```
for people who want to do PR builds but do not have Developer editions of SonarQube.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e076c-9f67-77df-3204-4f549566f21b
* Version Independent ID: 2e51ef13-8fd3-1397-82f0-27c92f1ccee5
* Content: [Maven build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by trajano** [comment] 2020-02-13 18:07
Correction from my OP
```
        sqAnalysisEnabled: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }}
```

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
