### ISSUE TITLE
How to manage permissions to run azure devops pipelines and permissions change variable groups pragmatically?

### ISSUE THREAD

**Issue by melezhik** [MicrosoftDocs/azure-devops-docs#5979] opened 2019-10-14 17:33 UTC
I am reading through this documentation - https://docs.microsoft.com/en-us/rest/api/azure/devops, I can't see a clear answer on how one can manage permissions to run pipelines and edit variable groups through the Rest API.

**Comment by msebolt** [comment] 2019-10-15 05:20
@melezhik  Thank you for the feedback.

Given the extent of available options in Azure DevOps it's hard to reference every scenario.  Perhaps try the API search feature?

![Untitled](https://user-images.githubusercontent.com/6675884/66802258-b3489f00-eed0-11e9-8b31-e2ceb9535de5.png)

For pipelines, please refer to [Build](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/?view=azure-devops-rest-5.1) or [Release](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/?view=azure-devops-rest-5.1) and for variable groups see [Variable groups](https://docs.microsoft.com/rest/api/azure/devops/distributedtask/variablegroups?view=azure-devops-rest-5.1).

**Comment by melezhik** [comment] 2019-10-15 17:59
Hi @msebolt , I refined the issue title I meant only permissions. I am already though https://docs.microsoft.com/en-us/rest/api/azure/devops/security , but IMHO the documentation is not that clear and does not cover many aspects of managing permissions through the RestAPI

**Comment by msebolt** [comment] 2019-10-16 06:17
@melezhik Thank you for the clarification, assigning this to the author for review.

For now, please refer to [Pipeline permissions](https://docs.microsoft.com/azure/devops/pipelines/policies/permissions?view=azure-devops#pipeline-permissions) and [Security roles](https://docs.microsoft.com/azure/devops/organizations/security/about-security-roles?view=azure-devops#library-asset-security-roles-variable-groups-and-secure-files) in determining which APIs are needed.

**Comment by melezhik** [comment] 2019-10-16 18:55
@msebolt  I've not found RestAPI to manage variable groups permissions, there is no even security-namespace for that, is it correct?

**Comment by melezhik** [comment] 2019-10-16 19:08
Ah, I found, it's called 'library'

**Comment by melezhik** [comment] 2019-10-17 20:41
@msebolt  how do I define token for git branch?

`az.cmd devops security permission list --id  2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87   --subject user@company.com` gives me a guess that it should be something:

`repoV2/$project_id/$repo_id/refs/heads/$unknown_chunk`

But I can't understand how to calculate the last bit of it  - `$unknown_chunk`, logically it should be something that define branch.

**Comment by melezhik** [comment] 2019-10-17 21:46
looks like it's 

for every letter of branch name:

`oct($i)00`

Why not document it?

**Comment by melezhik** [comment] 2019-11-04 15:48
@msebolt , any updates here? thanks

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri3, doc-enhancement
