### ISSUE TITLE
ONLY installs the CLI on macOS, while it appears to fetch other requirements to run Docker for Windows/Linux

### ISSUE THREAD

**Issue by espoelstra** [MicrosoftDocs/azure-devops-docs#3784] opened 2019-03-27 00:54 UTC
On macOS you actually need to install Docker for Mac in order to get the Docker daemon (or docker-machine via the Docker Toolbox, but that adds a dependency on Virtualbox too). After you've installed Docker for Mac you need to launch it with `sudo` to install the components that required elevated permissions (the `sudo` is to avoid a graphical elevation prompt you can't really interact with since you don't know the user's password) and also use `osascript` to poke the "Next" on a button in the GUI (even though you are starting it from the command line) and once you have launched it with `sudo` you need to run EVERY `docker` command with `sudo` thereafter, e.g. `sudo docker system info` `sudo docker-compose ps` etc.

My snippet to do this that is working on Hosted macOS nodes is below.

```
    brew cask install docker
    set -x
    echo "Running xattr"
    xattr -d -r com.apple.quarantine /Applications/Docker.app 
    echo "Running Docker as root to install helpers"
    sudo -b /Applications/Docker.app/Contents/MacOS/Docker
    echo "Taking a break to let Docker UI open"
    # an improvement over this blind sleep would be using osascript to wait until Docker is visible and then run the next step
    sleep 15
    echo "Hit next on startup wizard"
    osascript -s o -e 'tell application "Docker"' -e 'activate' -e 'tell application "System Events" to key code 36' -e 'end tell'
    echo "Waiting for docker system info to respond (which means the service is available)"
    set +x
    sleep 5
    # if the script appears to hang for more than 3 minutes comment above `set +x` or try to run the command inside the loop to see the output, like 'do sleep 1; sudo docker system info; done'
    while ! sudo /Applications/Docker.app/Contents/Resources/bin/docker system info &gt; /dev/null 2&gt;&1; do sleep 1; done;
    echo "Docker is ready and available"
    set -x
    sudo docker ps
    # note the permissions on the files and where the docker.sock is located
    ls -lA /usr/local/bin/docker* /var/run/docker*
    sleep 1
    sudo docker system info
    echo "Docker install complete"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e363794a-15bb-94f5-5a0f-021a5b068d2f
* Version Independent ID: 262421e1-9598-fa0c-74f3-ad8baf56374e
* Content: [Docker Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/docker-installer?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/tool/docker-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/docker-installer.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **shasb**

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri2, devops/prod
