### ISSUE TITLE
Missing parameter `ENV`

### ISSUE THREAD

**Issue by GenesisCoast** [MicrosoftDocs/azure-devops-docs#7852] opened 2020-04-07 10:19 UTC
This page is missing the fact that you can specify the parameter `env` for the task similar to the `PowerShell` task. The documentation should include this:

```
Environment variables	A list of additional items to map into the process's environment. For example, secret variables are not automatically mapped. If you have a secret variable called Foo, you can map it in like this:

YAML

- task: AzurePowerShell@4
  inputs:
    azurePowerShellVersion: LatestVersion
    azureSubscription: my-arm-service-connection
    inline: echo $env:MYSECRET
    scriptType: InlineScript
  env:
    MySecret: $(Foo)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcda4373-62ae-e1ae-c15d-63f441179b47
* Version Independent ID: 305f78c0-2e89-78f2-d2d1-89471602610c
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:28
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:28 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, doc-enhancement
