### ISSUE TITLE
MSBuild task - YAML snippet error

### ISSUE THREAD

**Issue by VianneyDoleans** [MicrosoftDocs/azure-devops-docs#5874] opened 2019-10-07 15:35 UTC
YAML snippet shows "#solution: '**/*.sln' " but the command is waiting for project argument, as specified below in Arguments part, not "solution" argument.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22342679-18af-7c79-f902-fe9c0bb55379
* Version Independent ID: a8e7c201-6593-458b-5a81-b54e93fde4b5
* Content: [MSBuild build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/msbuild?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/msbuild.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/msbuild.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by marcussonestedtbarium** [comment] 2019-10-23 12:15
Solution works for me, even for specifying projects.

**Comment by jpricket** [comment] 2019-12-13 19:19
I can see why this is confusing. The actual name of the input is "solution" which should work perfectly. However, in the docs just below the sample we use the alias of the input which is "project". Either should work, but we should probably be consistent. Especially, on a single page.

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
