### ISSUE TITLE
node CA hint is missing

### ISSUE THREAD

**Issue by robertmuehsig** [MicrosoftDocs/azure-devops-docs#8394] opened 2020-05-20 10:04 UTC
I had the following issue with the NuGet Restore task:

    ##[error]Error: Error: unable to verify the first certificate

(similar [Stackoverflow Question](https://stackoverflow.com/questions/56855546/azure-devops-server-pipeline-build-fails-when-using-self-signed-ssl-certificate))

I found many different solutions to this problem and I think this would deserve a small note on this site. I solved this adding a copy of the CA cert (as .pem) to the build agent and create the node ca enviroment like this:

    [Environment]::SetEnvironmentVariable("NODE_EXTRA_CA_CERTS", "C:\Path\To\Certificates\our_certificate.pem", "Machine")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35e47a40-a6dc-a672-e248-82560224e135
* Version Independent ID: 87d9bebf-2486-984f-1893-ff00f8696bbe
* Content: [Run the agent with a self-signed certificate - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/certificate?view=azure-devops-2019)
* Content Source: [docs/pipelines/agents/certificate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/certificate.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2020-05-21 05:52
@robertmuehsig Thank you for the feedback.

Is this after you tried upgrading to the latest version of nuget?  I only ask because it's what's recommended in the [forums](https://developercommunity.visualstudio.com/content/problem/437275/builds-failing-after-upgrade-to-azure-devops-serve.html).

I like the idea of adding a note, but would rather use the easier fix.

**Comment by robertmuehsig** [comment] 2020-05-25 22:11
The NuGet.exe was indeed not the most recent version, but the "unable to verify the first certificate" seems to be a node specific error message.
I removed the "NODE_EXTRA_CA_CERTS" from my build agent, rebooted it, did a "nuget.exe update -self" and run my build again:
![image](https://user-images.githubusercontent.com/756703/82845294-3a88d700-9ee4-11ea-9894-159955917623.png)

After I readded the "NODE_EXTRA_CA_CERTS" entry it worked again.

It seems that node is used to orchestrate the different AzureDevOps tasks and with a self signed certificate we need to tell node, that it is ok to use it. 
Our dev team uses the AzureDevOps NuGet Feed feature in combination with a self signed cert and I think that's why this error occurred.

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri2, devops-cicd-agents/tech, devops/prod, doc-enhancement
