### ISSUE TITLE
Secure files not found when authorized, "Authorize Resources" button returns an unhelpful error

### ISSUE THREAD

**Issue by pmullins-ewn** [MicrosoftDocs/azure-devops-docs#5119] opened 2019-08-02 14:37 UTC
I'm an administrator for my resources. I initially was attempting to access a keystore in order to sign an Android APK via the `DownloadSecureFiles` task. I verified that the keystore is authorized for access from all pipelines, but I keep getting the error listed in step #5 on this page. When I click the "Authorize Resources" button, I receive the following error: "An error occurred while auto-authorizing resources".

I've attempted to upload and authorize a plaintext file and access its filepath via an inlined bash script task, but I also receive the same error.

Additionally, is there anywhere where I can see what properties are available on downloaded secure files? the docs page on secure files only mentions `secureFilePath` as an example, I can't find a more extensive list anywhere.

My `azure-pipelines.yml` is set up as follows:
```trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

 - task: DownloadSecureFile@1
   name: keyStoreFile
   inputs:
     secureFile: TestKeystore.keystore

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*.Droid.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: AndroidSigning@2
  inputs:
    apkFiles: '**/*.apk'
    jarsign: true
    jarsignerKeystoreFile: '$(keyStoreFile.secureFilePath)'
    jarsignerKeystorePassword: '$(keystorePassword)'
    jarsignerKeystoreAlias: 'TestKeystore'
    jarsignerKeyPassword: '$(keystorePassword)'
    zipalign: true

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'testApp'```

TIA for the help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops#troubleshooting-authorization-for-a-yaml-pipeline)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by pmullins-ewn** [comment] 2019-08-02 14:39
Looks like my yml wasn't included in the initial report. Here's the contents:

`trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: DownloadSecureFile@1
  name: keyStoreFile
  inputs:
    secureFile: TestKeystore.keystore

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*.Droid.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: AndroidSigning@2
  inputs:
    apkFiles: '**/*.apk'
    jarsign: true
    jarsignerKeystoreFile: '$(keyStoreFile.secureFilePath)'
    jarsignerKeystorePassword: '$(keystorePassword)'
    jarsignerKeystoreAlias: 'TestKeystore'
    jarsignerKeyPassword: '$(keystorePassword)'
    zipalign: true

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'testApp'
`

**Comment by WilliamAntonRohm** [comment] 2019-08-07 15:58
@pmullins-ewn Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by pmullins-ewn** [comment] 2019-08-07 16:25
So my intent was to build an Android APK for use on development/testing devices for my organization, and to use Azure Pipelines to build and distribute a signed APK to my team. When walking through the documentation, my initial impression was that I needed to upload the Android keystore file to my Project's Secure Files, download it in the Pipeline via the `DownloadSecureFile` task, and sign it via the `AndroidSigning` task. I followed the documentation on the page referenced in the ticket under `Content` which pertains to troubleshooting access to secure files, but despite after authorizing the file for use in all pipelines, my build would still fail with the vague error message that I provided in the initial description.

I managed to find a workaround by referencing the secure file directly with help from the user in this ticket: https://github.com/MicrosoftDocs/vsts-docs/issues/4927, but I still feel like signing the APK in the method I attempted above either _should_ work or at least explain why the Secure File is not available.

**Comment by LanceMcCarthy** [comment] 2019-09-26 15:52
Agreed, this is a frustrating experience. There needs to be a good article on the difference between the variable names for SecureFiles as well as linked Group variables. The syntax of using the tag xxx.secureFile versus xxx in different places is frustrating. 

I ended up removing the linked Group because none of them would resolve (yes the variable group and secure files have allow multiple pipeline access, so access shouldnt be an issue).

My constructive feedback would be to have a way to test a variable's syntax while writing the YAML without having to submit another commit and triggering a build. I have 5-6 commits just trying different variants :)

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
