### ISSUE TITLE
Need more details on Checkout

### ISSUE THREAD

**Issue by dansiegel** [MicrosoftDocs/azure-devops-docs#6559] opened 2019-12-04 19:21 UTC
In general the checkout task needs support for SSH... but besides that... there is an option documented here that you can persist the token.. but you can only use the Task once, it's only good to checkout self / none... so what on earth do you do when you want to checkout a second repo because the task doesn't support SSH and I need my submodules? I'd love to continue using the OAuth token in a script to follow up but nowhere is it documented how to access the token that I've said yes please persist this so I can come back and use it later... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2019-12-05 17:49
@dansiegel Thank you for the feedback.

Since this is the documentation forum, please move the issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html) for feedback from the product team.

In the meantime, you'll need to use the [SSH task](https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/ssh?view=azure-devops) and provide the checkout as a script command.

**Comment by dansiegel** [comment] 2019-12-05 18:14
> Since this is the documentation forum...
> In the meantime, you'll need to use the SSH task

@msebolt you are correct this is the documentation forum... And while part of my gripe may have to do with some missing functionality in the product itself... the very fact that you're talking about the SSH Task here should already show by itself one of the ways that the documentation could be improved. Developers commonly use ssh for their repos so the mere fact that neither the checkout task or the docs address this is a major oversight.

I should also mention that I know that this is an issue that has affected some internal Microsoft teams as well and been the source of a lot of wasted man hours.

**Comment by msebolt** [comment] 2019-12-05 19:06
@dansiegel Thank you for the update.

I'll assign this to the author to update the documentation.

**Comment by steved0x** [comment] 2019-12-06 18:42
#assign:juliakm

**Comment by steved0x** [comment] 2019-12-06 18:42
#reassign:steved0x

**Comment by cxwtool** [comment] 2020-11-24 23:35
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:35 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
