### ISSUE TITLE
Is it possible to get the number of builds in queue for the agent pool?

### ISSUE THREAD

**Issue by blueelvis** [MicrosoftDocs/azure-devops-docs#4171] opened 2019-05-08 11:42 UTC
Hi!

I am trying to find information on how to find the number of builds which are awaiting allocation of an agent inside an agent pool. Is it possible to get the number at any given time for a particular agent pool?

I took a look at this REST API page - https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/pools/get?view=azure-devops-rest-5.1#propertiescollection

but, I am not able to see anything of that sort. Please do note that this data is visible in the UI -

![image](https://user-images.githubusercontent.com/6985763/57372714-0c8b0480-71b4-11e9-8315-71f3e3b190e6.png)

I have the following questions as of now regarding the above page -

1. Any idea how to get the current number of jobs which are being served by the agent pool?
2. Any idea how to get the current number of jobs which are running on the agent pool?
3. Could you please explain what the `autoSize` property does? It is written as `Whether or not the pool should autosize itself based on the Agent Cloud Provider settings.` but, it is not clear as to what that actually means (as in which context).

Thanks,
Pranav

**Comment by blueelvis** [comment] 2019-05-14 13:38
@andyjlewis - Any idea on this?

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri3, doc-bug

**Comment by blueelvis** [comment] 2020-11-25 10:10
Please reopen this.

**Comment by mijacobs** [comment] 2020-11-25 18:28
@blueelvis Issues aren't enabled for the REST API; this repo is for Azure DevOps conceptual docs.  Please check our conceptual docs for the info you're looking for:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser

For questions, you can also check with the  [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
