### ISSUE TITLE
Gradle cache setup problems

### ISSUE THREAD

**Issue by eric-labelle** [MicrosoftDocs/azure-devops-docs#5229] opened 2019-08-13 12:42 UTC
Using the documentation and setting cache to GRADLE_USER_HOME (.gradle)
 eventually ends up in error. In an Android pipeline, I wish to cache at least 3 things 

- .gradle/cache/build-cache-1 --> the buildCache would speed up build a lot
- .gradle/cache/modules-2/files-2.1 --> all dependencies downloaded
- .gradle/wrapper/ --> the gradle distribution jar

**My problems with current setup:**

- When I change a dependency from the Android project, the cache should be updated but isn't
- When I swap wrapper version the cache should be updated but isn't
- Caching the whole .gradle/ folder will eventually end up with an aapt2 error `Execution failed for task ':app:mergeDebugResources'.  > 8 exceptions were raised by workers:    com.android.builder.internal.aapt.v2.Aapt2InternalException: AAPT2 aapt2-3.4.2-5326820-osx Daemon #2: Daemon startup failed .This should not happen under normal circumstances, please file an issue if it does.`

I've seen there is lots of lock file in gradle repo and Gradle uses dependency locking so I was wondering.. Is there a lock file we can use for the Cache key in gradle similar to the example for yarn (_and/or gem.lock whereas everytime the dependencies changes, the file hash would be different_)

Either way, I'm glad you're working on this new task but I currently can't figure a way to make it work efficiently with Android / Gradle project.

Thanks for your time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#known-issues-and-feedback)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by msebolt** [comment] 2019-08-14 23:59
@Xexiz Thank you for providing the details.

These are excellent issues to address, however, this is more of a product issue then documentation and should be moved to [azure-pipeline-tasks](https://github.com/microsoft/azure-pipelines-tasks/labels/Area%3A%20PipelineCaching).  Please post the issue there for better traction.

Thank you again for your feedback.

**Comment by paulnuk** [comment] 2019-09-04 07:55
I do think the gradle documentation needs updating - there needs to be an example of how to use it in the real world. In the example given it appears to be the case that if you do a build it will cache the result but if you then change anything in your source branch it will use the cached build. It doesn't seem to fit in with Gradle's idea of a build cache (e.g. if I change one test case Gradle won't bother recompiling the main source folder, or if I add one dependency Gradle will just download that rather than downloading all dependencies every time),

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
