### ISSUE TITLE
Clarify Publishing .zip files

### ISSUE THREAD

**Issue by cawoodm** [MicrosoftDocs/azure-devops-docs#8207] opened 2020-05-06 10:50 UTC
It's not clear how we can publish .zip files directly. When we pass a folder or file, the task will zip it  - how can we specify that we have already zipped the artifact?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment] 2020-05-07 05:54
@cawoodm Thank you for the question, assigning this to the author for further review.

Please note if this is a feature not yet supported you should solicit further feedback from the product team [here](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri1, devops-cicd-artifacts/tech, devops/prod, doc-enhancement
