### ISSUE TITLE
Path to On-Premises Azure DevOps Server 2019 - 

### ISSUE THREAD

**Issue by Loves2Code** [MicrosoftDocs/azure-devops-docs#4040] opened 2019-04-23 11:10 UTC
At this location on the page:

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops-2019#authenticate-with-a-personal-access-token-pat

The path listed in "Step 1" for an on-premises path to create a Personal Access Token is listed as:

https://{your-server}:8080/tfs/

This URL will not work With Azure DevOps Server 2019 (I chose "Azure DevOps Server 2019" at the top left of the navigation menu to filter on this product).
It appears that almost any URL pointing to your on-premises Azure DevOps Server 2019 WILL work, but the path described in "Step 1" for on-premises (I'm assuming) is for older versions of TFS, not DevOps Server 2019. It seems one just needs to be able to access their "Profile" in the upper right-hand corner, which is easily accessible from many paths when on-premises, and would be available from the home page.

Could this URL for Azure DevOps Server 2019 be re-defined as:

https://{your-server}/DefaultHomePage

I am new to Azure DevOps Server 2019; I do not even know the default home page. I'm even new to the markdown procedures used in giving feedback on GitHub, so I ask for your patience in my description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by kkarakk** [comment] 2019-05-28 07:26
Currently facing the exact same issue, trying to self host agent on locally deployed azure devops...

**Comment by kkarakk** [comment] 2019-05-30 09:46
nvm, it wanted the complete url with the "collection" i create. once i put the collection in the path  as in 

> http://url:port/[collection-name]

 it worked just fine

**Comment by kyllian** [comment] 2019-09-10 15:48
I'm also facing the same issue as @kkarakk.

Enter server URL > http://localhost/Collection
Enter authentication type (press enter for Integrated) > PAT
Enter personal access token > ****************************************************
Basic authentication requires a secure connection to the server.
Failed to connect.  Try again or ctrl-c to quit

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
