### ISSUE TITLE
This works on TFS 2018.2

### ISSUE THREAD

**Issue by EklipZgit** [MicrosoftDocs/azure-devops-docs#4703] opened 2019-07-01 17:36 UTC
However the documentation incorrectly seems to indicate that this is only available on VSO by not having the page for TFS 2018. We have tested it working on TFS 2018.2 (16.131.27701.1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb95406-322e-11db-41e0-7b8064c8295c
* Version Independent ID: 57fb95a8-385d-7548-ee6a-9a3a875a150e
* Content: [Node.js Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops&viewFallbackFrom=tfs-2018#feedback)
* Content Source: [docs/pipelines/tasks/tool/node-js.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/node-js.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by gojanpaolo** [comment] 2020-03-13 03:51
Also works with Azure DevOps Server Version Dev17.M153.5

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
