### ISSUE TITLE
Missing test project

### ISSUE THREAD

**Issue by danielstefanescu** [MicrosoftDocs/azure-devops-docs#5377] opened 2019-08-27 06:30 UTC
The repository from https://github.com/MicrosoftDocs/pipelines-dotnet-core doesn't contain a test project so the page is out-of-sync with the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=azure-devops)
* Content Source: [docs/pipelines/languages/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by chasewilson** [comment] 2019-09-09 22:18
@vijayma, Do you have any direction on this?

**Comment by vijayma** [comment] 2019-09-10 00:44
@PBoraMSFT will help us add test assets into these repos.

**Comment by chasewilson** [comment] 2019-09-18 17:08
@PBoraMSFT, thanks for taking this on. Just wanted to give this a bump and see how this is going

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
