### ISSUE TITLE
Use Service Connection: Deauthorize Pipeline

### ISSUE THREAD

**Issue by syndicatedshannon** [MicrosoftDocs/azure-devops-docs#5963] opened 2019-10-13 02:37 UTC
The Use Service Connection topic ( https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#use-a-service-connection ) includes instructions on how to authorize a pipeline. As a security-minded consumer, I would also like instructions to Deauthorize a Pipeline, especially since it seems that the "Allow all pipelines" enumerates the currently existing pipelines into permanent security rules. If Deauthorizing a Pipeline is not possible, this documentation should (IMO) state that. The workaround I currently use is to delete the Service Connection, recreate it, and re-assign the rights in the connected Azure Subscription.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#use-a-service-connection)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment] 2019-10-14 18:23
@syndicatedshannon Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
