### ISSUE TITLE
Documentation and screen shots are outdated

### ISSUE THREAD

**Issue by SimonShor** [MicrosoftDocs/azure-devops-docs#8293] opened 2020-05-12 19:49 UTC
Given instructions, I have installed the demo into my organization but have no idea where to find it.

Seems issues are proactively closed before the documentation is actually fixed...guess there is a performance metrics incentive/motivation to close the feedback that actually fix the underlying concerns. 

This makes for a very challenging user experience to have paw though closed issues. Hows that for "Page feedback"!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri1, devops-ecosystem/tech, devops/prod, doc-enhancement
