### ISSUE TITLE
Retrieving certSecureFile value

### ISSUE THREAD

**Issue by TechWatching** [MicrosoftDocs/azure-devops-docs#3671] opened 2019-03-18 15:46 UTC
How can we find the value to set for `certSecureFile` once a file uploaded in Library / Secure Files of the Azure Devops project ?
On a build with view Designer, if we look at the generated yaml the value is an id that can't be find anywhere in the secure files section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e4f249c-c229-4a5c-7970-4e566026b560
* Version Independent ID: 7062bdf1-7b38-b42b-e117-c3041e09aae7
* Content: [Install Apple Certificate task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-certificate?view=azure-devops#)
* Content Source: [docs/pipelines/tasks/utility/install-apple-certificate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-apple-certificate.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by ravero** [comment] 2019-03-25 22:52
Got the same issue. There's a lack of documentation, just as of Xamarin.iOS Build task.
To get this value I needed to create this task using the visual designer and copy the YAML, which is incredibly dumb.

I found an alternative way to navigate to library, select the secure file and search for the `secureFileId` query string parameter, which is also a dumb solution.

**Comment by TechWatching** [comment] 2019-03-26 06:10
In fact, I discovered that the name of the file was also working. But I agree with you, some documentation and examples for yaml task are missing.

**Comment by VitorRigoni** [comment] 2019-04-14 16:26
+1 I had this issue as well and feels like a gap in the docs.

@TechWatching is correct: simply using the full file name works fine.
```yml
- task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'my-certificate.p12'
      certPwd: '$(my-cert-pw)'
```

**Comment by nk111** [comment] 2019-05-17 05:03
You can get the fileid of a secure file when you go to library / secure files and click on the secure file in question. Then you can see the SecureFileId parameter in the url. Not optimal but it works. But if the name is working too i'd prefer this.

**Comment by MouthOfMadness** [comment] 2019-12-13 20:26
This page needs a link on how to generate the apple certificates.

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
