### ISSUE TITLE
What are the required port openings

### ISSUE THREAD

**Issue by larserikfinholt** [MicrosoftDocs/azure-devops-docs#2592] opened 2018-11-28 12:18 UTC
The script stops executing (no error) after entering the PAT token. I suspect that we're missing some port openings. I suggest the docs list required openings. (We're using devops server, and first got problem downloading the package from the web)

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: 09fa0c14-9937-41bc-cc34-179edb379083
* Version Independent ID: 10fe3600-21a5-12db-5e21-5ade3a8fa484
* Content: [How to provision agents for deployment groups - Azure Pipelines & TFS](https://docs.microsoft.com/nb-no/azure/devops/pipelines/release/deployment-groups/howto-provision-deployment-group-agents?view=azdevserver-2019)
* Content Source: [docs/pipelines/release/deployment-groups/howto-provision-deployment-group-agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deployment-groups/howto-provision-deployment-group-agents.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment] 2018-12-06 11:36
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by florianeidner** [comment] 2019-01-18 09:36
+1 I also experience connection troubles even though the agent is trying on Port 80.

**Comment by RoshanKumarMicrosoft** [comment] 2019-01-18 12:57
@florianeidner Can you please share the exact warning or error message to RM_Customer_Queries@microsoft.com ? Is this transient ? Vm in which you want to configure agent is behind any proxy ?

**Comment by florianeidner** [comment] 2019-01-18 17:04
@RoshanKumarMicrosoft The zip folder is downloading correctly. It is happening druing the config - I think when trying to connect to Azure DevOps:
![image](https://user-images.githubusercontent.com/23451437/51401417-fac11b00-1b4a-11e9-9938-0a0d2f7cc8df.png)
There is no warning or error - it simply freezes. Capturing the traffic tells me that it repeatedly tries to connect.

**Comment by omarcarreon** [comment] 2019-10-09 20:32
@florianeidner did you find a solution for that?

**Comment by florianeidner** [comment] 2019-10-10 19:25
Actually the problem in the end was resolved by defining a proxy with the config command:
./config.cmd --proxyurl http://127.0.0.1:8888 --proxyusername "myuser" --proxypassword "mypass"

see here: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=azure-devops&tabs=windows

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
