### ISSUE TITLE
Docker instructions no longer valid

### ISSUE THREAD

**Issue by sahammer** [MicrosoftDocs/azure-devops-docs#5735] opened 2019-09-25 16:23 UTC
It appears that the project https://github.com/MicrosoftDocs/pipelines-dotnet-core no longer contains Docker files required for build.  There is a new repository specific to Docker located at https://github.com/MicrosoftDocs/pipelines-dotnet-core-docker

However, neither of these repos contain the required test files and as a result the instructions contained within this document are no longer valid. I was going to attempt to make updates - but it looks like there may need to be a longer discussion about how to handle the change in the project, or add the unit tests back in to the repository.

Additionally several files mentioned including `.vsts-ci.docker.yml` no longer exist in the project(s).

The above is specific to the docker section:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml#docker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Publish Test Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
