### ISSUE TITLE
Arguments list does not match YAML snippet

### ISSUE THREAD

**Issue by edwardaskew** [MicrosoftDocs/azure-devops-docs#5067] opened 2019-07-31 09:06 UTC
Values in Arguments list but not in YAML snippet:

- `selectOrConfig`
- `packagesDirectory`
- `searchPatternPush`
- `feedPublish`
- `externalEndpoint`
- `externalEndpoints`
- `searchPatternPack`
- `configurationToPack`
- `outputDir`
- `feedRestore`
- `requestedMajorVersion`
- `requestedMinorVersion`
- `requestedPatchVersion`

Values in YAML snipper but not Argument List:

- `feedsToUse`
- `vstsFeed`
- `externalFeedCredentials`
- `restoreDirectory`
- `packagesToPush`
- `publishVstsFeed`
- `publishFeedCredentials`
- `packagesToPack`
- `configuration`
- `packDirectory`
- `majorVersion`
- `minorVersion`
- `patchVersion`

This [doesn't seem to be](https://github.com/MicrosoftDocs/vsts-docs/issues/3290) [the only task documentation](https://github.com/MicrosoftDocs/vsts-docs/issues/4922) with this issue either which is a pretty poor showing given how vital accurate documentation is to be be able to actually use YAML task definitions...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by edwardaskew** [comment] 2019-07-31 10:39
Looking into how the YAML snippets seem to be generated from [the azure-pipelines-tasks repo](https://github.com/microsoft/azure-pipelines-tasks/blob/ec205fb641b01af7014cb90b9b1160eec638b914/make-util.js#L915) it looks like the YAML snippet is using the [first alias if one exists](https://github.com/microsoft/azure-pipelines-tasks/blob/master/make-util.js#L847) while as far as I can tell the argument list is manual but that's about as far as I can get as there seem to be some steps going on behind the scenes to get the generated md into the actual docs.

**Comment by ffloimair** [comment] 2020-02-21 08:50
Lots of progress on this one...
Almost 7 months and no change. Oh boy Microsoft. Same in https://github.com/MicrosoftDocs/vsts-docs/issues/4964

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
