### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/azure-devops-docs#7524] opened 2020-03-06 21:41 UTC
The example is less than enlightening since creating a database is a feature of the task itself, without inline sql. How about a simpler example of database creation and second example of inline sql?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edb0dd0e-99f2-2fc1-6e28-fc89ab457b5c
* Version Independent ID: f6cd5426-6258-9a75-dda7-81b377c29bed
* Content: [MySQL Database Deployment On Machine Group task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/mysqldb-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/mysqldb-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/mysqldb-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, doc-enhancement

**Comment by HughDevlin** [comment] 2020-12-02 20:50
Please re-open this issue.

Please add a simple example of database creation without inline SQL.
