### ISSUE TITLE
PublishTestResults does not specify how it operates with containers

### ISSUE THREAD

**Issue by Naatan** [MicrosoftDocs/azure-devops-docs#3918] opened 2019-04-10 15:01 UTC
I spend pretty much half a day yesterday going mad over why Azure Pipelines would not find my test results, before concluding (assuming) that it looks for them on the agent and not on the container. 

Imo this should work automatically, PublishTestResults is specified under the job level, and the job level has the container property, so it stands to reason that PublishTestResults would act on the container.

Regardless, the documentation should at least cover this topic. We live in a Docker world and it feels like a shortcoming that tasks like this cannot even consider Docker containers.

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri3, doc-bug
