### ISSUE TITLE
Missing policy to enforce branch up to date before merging

### ISSUE THREAD

**Issue by ivorb** [MicrosoftDocs/azure-devops-docs#8083] opened 2020-04-24 19:06 UTC
This is followup to #8064 however I was unable to open it. The issue isn't with my specific scenario, so the provided links don't apply here.

I'm looking for documentation of how to require branches to be up to date before merging a PR, within ADO. Github provides it in the link I gave in my first issue, and I assume parity was met for something as basic as this policy.

**Comment by msebolt** [comment] 2020-04-27 20:23
@ivorb  Thank you for the question, assigning this to the author for further review.

Please note if this is a missing feature it needs to be filed with the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri3, doc-enhancement

**Comment by DaveSkender** [comment] 2023-01-27 05:00
If you are interested in this feature, please upvote this UserVoice recommendation: [require branch to be up-to-date](https://developercommunity.visualstudio.com/t/azure-devops-support-the-feature-require-branches/1196970)
