### ISSUE TITLE
Custom conditions with dependencies on Release Pipelines

### ISSUE THREAD

**Issue by donatogr** [MicrosoftDocs/azure-devops-docs#8179] opened 2020-05-04 08:54 UTC
How can dependencies be specified in Release Pipelines, so to have a custom condition based on a specific job (e.g. run job C only if job A has failed and job B has succeeded)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment] 2020-05-05 08:59
@donatogr Thank you for the question.

Assigning this to the author for further review to see if the documentation can be updated.

If this feature is not yet available, please use Report a problem or Suggest a feature in the  [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback directly from the product team.

Or, for additional support options, see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri1, devops-cicd-process/tech, devops/prod, doc-enhancement
