### ISSUE TITLE
Ubuntu links broken

### ISSUE THREAD

**Issue by v-nalvarez** [MicrosoftDocs/azure-devops-docs#11778] opened 2021-12-24 14:40 UTC
Please check broken links below for Ubuntu's Include Software section

https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment] 2021-12-27 16:14
Duplicate of MicrosoftDocs/azure-devops-docs/issues/11771 - should be fixed in a minute.

**Closed by TimShererWithAquent** 2021-12-27 16:14 UTC
Labels: duplicate, devops/prod, cba, Pri2, devops-cicd-agents/tech
