### ISSUE TITLE
TFS GIT Pull Request - shortcuts

### ISSUE THREAD

**Issue by CJBS** [MicrosoftDocs/azure-devops-docs#6010] opened 2019-10-16 16:09 UTC
I don't see the shortcut for adding a comment to a file. There's an icon for doing so, and I know there's a shortcut because I've used it before, but I can't remember it. It seems this page is the place where it should be listed. Please add it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2fe0af-744d-e535-b300-8d1060945db6
* Version Independent ID: 10892c8d-ff0b-3072-46bd-cad31923c240
* Content: [Web portal Team Explorer keyboard shortcuts - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/navigation/keyboard-shortcuts?view=azure-devops#feedback)
* Content Source: [docs/project/navigation/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/navigation/keyboard-shortcuts.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment] 2019-10-17 00:15
@CJBS  Thank you for the feedback, assigning this to the author for review.

For now use the right-click context menu to show additional shortcuts, to add a comment is **F4**.

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri2, devops-collab/tech, devops/prod, doc-enhancement
