### ISSUE TITLE
Alternative to using the Checkout submodules option - not working

### ISSUE THREAD

**Issue by mmisztal1980** [MicrosoftDocs/azure-devops-docs#6292] opened 2019-11-07 10:50 UTC
I'm in a situation where I'm trying to consume 2 submodules hosted in 2 separate projects within a single AzD organization - therefore I'm not eligible for `submodules: true | recursive` (commented out) so I have to resort to the alternative solution.

I've followed the steps from the title paragraph and got an empty output. I'm trying to get this to work in a YAML pipeline, resulting in

```
steps:
      - checkout: self
        clean: true
        #submodules: recursive
        persistCredentials: true         
      - task: Bash@3
        displayName: "[bash] git submodule"
        inputs:
          targetType: "inline"
          script: |
            PAT="pat:${{ parameters['Git.PAT'] }}"
            PAT_BASE64=`echo -n $PAT | base64`
            git -c http.https://dev.azure.com/cloud-technologies/cloud-technologies.net/_git/core-build.extraheader="AUTHORIZATION: basic ${PAT_BASE64}" submodule update --init --recursive
            git -c http.https://dev.azure.com/cloud-technologies/realm/_git/realm-core-infrastructure.extraheader="AUTHORIZATION: basic ${PAT_BASE64}" submodule update --init --recursive            
```

I've verified that the `$PAT_BASE64` is encoded correctly. However when trying to repro this locally in the checked-out repo, the outputs of the git commands are blank.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#feedback)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2019-11-07 22:27
@mmisztal1980 Thank you for the question.

Unfortunately we are unable to handle support requests in this forum.

For further options, please start a issue in either:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

...and provide a link back to this one.

**Comment by mmisztal1980** [comment] 2019-11-07 23:07
This is not a support request. Based on the documentation you’ve provided, I’ve created a 1:1 solution that fails to work despite of what is being described in the docs. Either the docs are incomplete or wrong - unless you prove me to be wrong (which I won’t mind at all)

I am trying to solve a specific case described in the docs, according to the provided solution, and failing. 

Wysłane z iPhone'a

**Comment by msebolt** [comment] 2019-11-08 00:08
Sure, no problem.  I can assign this to the author, though this might be an issue with the DevOps bracketing syntax.

Does removing brackets work for the solution?

```
PAT_AUTHORIZATION="AUTHORIZATION: basic $PAT_BASE64"
git -c http.https://dev.azure.com/cloud-technologies/cloud-technologies.net/_git/core-build.extraheader=$PAT_AUTHORIZATION submodule update --init --recursive
```

**Comment by steved0x** [comment] 2019-12-13 22:22
@mmisztal1980 We just released a new multi-repo checkout functionality, so while it isn't specific to submodules, it may help you with checking out your code from multiple projects in the same organization? 

[Check out multiple repositories in your pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)

**Comment by mmisztal1980** [comment] 2019-12-13 22:56
@steved0x does this work across projects within the same Azure DevOps organization?

**Comment by basnijholt** [comment] 2020-03-06 13:10
I have just encountered this issue myself.

Still seems to be a problem.

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
