### ISSUE TITLE
System.PullRequest.TargetBranch is not formatted as the example given.

### ISSUE THREAD

**Issue by EraYaN** [MicrosoftDocs/azure-devops-docs#3654] opened 2019-03-14 21:45 UTC
This variable only contains for example `master` so for example using this as a value for the `DownloadBuildArtifacts@0` Task for the `branchName` value will not work, and you will have to append `refs/heads/`. Which might break if the target branch is ever not in heads (if that is even possible).

The best way is probably to just change the example in the documentation if it reflects intended behavior.

Some example builds (UI designer based) https://github.com/jellyfin/jellyfin/pull/1111#issuecomment-473073960 one with the default `refs/heads/master` value and one with the `master` value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
