### ISSUE TITLE
Doesn't really tell me how to deploy Cosmos

### ISSUE THREAD

**Issue by perfectphase** [MicrosoftDocs/azure-devops-docs#1984] opened 2018-10-05 14:10 UTC
From the title I was hoping this would cover how to deploy a comos DB via CI/CD!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8c39278-7b3f-11a9-f7d2-cb7dc854c812
* Version Independent ID: e1192149-53b5-c4ef-e0bf-2fa6d00fb79d
* Content: [CI/CD with Azure App Service and Azure Cosmos DB - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/cosmos-db?view=vsts)
* Content Source: [docs/pipelines/targets/cosmos-db.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/cosmos-db.md)
* Product: **devops**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
