### ISSUE TITLE
example build, run test, push Docker container for version 2.*

### ISSUE THREAD

**Issue by stharrold** [MicrosoftDocs/azure-devops-docs#5533] opened 2019-09-09 15:15 UTC
Please link this page to an example pipeline that follows best practices for building, running a test, and pushing a Docker container. The option to run a Docker container was removed in version 2.* of the Docker task (c.f. https://github.com/microsoft/azure-pipelines-tasks/issues/11118), and, from within "Docker" task page version 2.*, it's unclear how to implement the advice from @shashankbarsin to use `- script: docker run &lt;arguments&gt;` on the hosted agent. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by tashrifbillah** [comment] 2019-10-15 17:22
@WilliamAntonRohm , referencing my issue here since I am also looking for the best practice of building and running test of a Docker container.

https://github.com/MicrosoftDocs/vsts-docs/issues/5949

**Comment by WilliamAntonRohm** [comment] 2019-10-15 23:11
@stharrold, @tashrifbillah -- Samuel, Tashrif, thank you for your feedback and interest.

@shashankbarsin -- Shashank, please look into this issue 5533.

**Comment by simonjlawson** [comment] 2019-10-31 12:58
An example would be great, trying to use the Arguments input, it works in a Private agent but the Hosted Agent does not see them?

**Comment by tashrifbillah** [comment] 2019-11-05 14:38
Hi all,

I am putting in my environment file that can be a good practice of building, testing, and pushing docker containers. 

https://github.com/tashrifbillah/tbss_containers/blob/master/azure-pipelines.yml

I leveraged on `script` commands because of [not-yet-fixed](https://github.com/MicrosoftDocs/vsts-docs/issues/6067) `ContainerStructureTest@0` task. If I could use azure provided test tasks, the only gain I could have is, be able to publish tests results in the `Tests` tab. Otherwise, I am good for now.

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
