### ISSUE TITLE
Cross-platform scripting example for JavaScript does not work on Windows

### ISSUE THREAD

**Issue by DavidAnson** [MicrosoftDocs/azure-devops-docs#4412] opened 2019-06-01 22:06 UTC
The top example:

```yaml
steps:
- script: |
    npm install
    npm test
```

Attempts to run "npm install" followed by "npm test". And it does on Linux/macOS. However, it only runs the install on Windows. This is because "npm" is a CMD script on Windows and DevOps runs the commands above from another CMD script and doesn't add the "CALL" command that's necessary to avoid exiting the nested script on Windows.

Proof:

CI run that should fail on all platforms:
https://dev.azure.com/DavidAnson/markdownlint-ci/_build/results?buildId=9

But it passes on Windows. Looking at the "npm install and run ci" task log shows that only the install runs.

Relevant configuration:
https://github.com/DavidAnson/markdownlint/blob/662afeb2a8ef6a8ac260dda59609e29f02d70b41/azure-pipelines.yml#L44

The fix is to one-line the script so the Windows behavior is avoided:
https://github.com/DavidAnson/markdownlint/commit/2e761f8296c45f958a232c0b08b962352b74a8f7

Which results in the Windows run correctly executing everything and failing:
https://dev.azure.com/DavidAnson/markdownlint-ci/_build/results?buildId=10

There are many places throughout the documentation where this pattern is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 797838e7-f32b-868e-8766-8d96973bf18f
* Version Independent ID: 20c9e62d-56ec-f5a0-c3f9-6f72bf96252e
* Content: [Cross-platform scripting - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/scripts/cross-platform-scripting.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/cross-platform-scripting.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
