### ISSUE TITLE
The term "pull request" requires explanation

### ISSUE THREAD

**Issue by rrnielsen** [MicrosoftDocs/azure-devops-docs#5420] opened 2019-08-29 13:53 UTC
https://docs.microsoft.com/en-us/azure/devops/learn/git/git-pull-requests#learn-more

The name "pull request" in this context is really confusing and . A pull request in Git is a request to retrieve contents from a repository server. Azure DevOps seems to use the same term, but with a different meaning. The text explains well what an Azure "pull request" can be used for, but I miss an explanation of what it is (which hopefully would also explain why it is called a "pull request").

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri3, doc-enhancement
