### ISSUE TITLE
docker-compose is required in $PATH

### ISSUE THREAD

**Issue by heaths** [MicrosoftDocs/azure-devops-docs#3164] opened 2019-01-28 23:15 UTC
While some tasks download any tooling needed, this one (and perhaps Docker@ do not). It would be good if you mentioned this in the docs, or consider downloading the single-file docker-compose application as part of initialization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d767aebb-620e-9ad3-e906-3e2bafa02ee9
* Version Independent ID: c8cb5a48-ccdf-778c-1547-a10db74cb56c
* Content: [Docker Compose task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azdevops)
* Content Source: [docs/pipelines/tasks/build/docker-compose.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker-compose.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
