### ISSUE TITLE
Working Directory does not appear to be Required

### ISSUE THREAD

**Issue by KnicKnic** [MicrosoftDocs/azure-devops-docs#6852] opened 2020-01-08 08:13 UTC
It seems to be perfectly valid to leave working directory not specified, however it is listed as required.

Also custom command is not required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ed9a20-59d7-df2e-0bf2-12b6afbf2da6
* Version Independent ID: b59cad83-b113-9a3a-1278-4ee64f31395f
* Content: [Go task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/go?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/go.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/go.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment] 2020-01-09 02:24
@KnicKnic Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
