### ISSUE TITLE
Please can you clarify how I pass a variable between VSO tasks with on-prem tfs2015

### ISSUE THREAD

**Issue by queBurro** [MicrosoftDocs/azure-devops-docs#1077] opened 2018-06-18 13:21 UTC
the example's not that clear to me. Thanks, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Variables in Release Management](https://docs.microsoft.com/en-us/vsts/pipelines/release/variables?view=vsts&tabs=powershell)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment] 2018-06-18 15:08
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by cxwtool** [comment] 2020-11-24 23:50
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:50 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
