### ISSUE TITLE
Add pre-reqs for code coverage pipeline example

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/azure-devops-docs#7075] opened 2020-01-27 19:16 UTC
Using " Create your first pipeline" as a starting point per this article's pre-reqs, under https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops#add-steps, when adding the code coverage step to the pipeline, it fails to build because the code coverage step requires some other config. Please provide this as a pre-req or use a different example that doesn't cause the sample pipeline to fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521b594c-dbb9-54d5-f56f-00e2f5fa1d92
* Version Independent ID: 509d3e4e-23db-8493-e1a6-acb67ec47e81
* Content: [Customize your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops#add-steps)
* Content Source: [docs/pipelines/customize-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/customize-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment] 2020-01-29 00:54
@softwarecraft Thank you for the feedback.

Assigning this to the author for further review.

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
