### ISSUE TITLE
Helm chart creation not happening. No docs on creation. 

### ISSUE THREAD

**Issue by manuchandel** [MicrosoftDocs/azure-devops-docs#6000] opened 2019-10-15 23:02 UTC
This is in regard to this issue #2353. In the docs https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-aks?view=azure-devops&tabs=python  There is no such link in the current docs as mentioned in the original solution.  Following the documentation, I cannot create a release because it fails giving helms chart error. It cannot find gzip file in the path mentioned in the documents.

**Comment by msebolt** [comment] 2019-10-16 17:50
@manuchandel  Thank you for the feedback, assigning this to the author for review.

Some things to check in the meantime:

- Review the [Helm task](https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops) for missed settings and/or try working samples
- Run the [Helm Installer task](https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/helm-installer?view=azure-devops) for the latest version
- Review [Install applications with Helm](https://docs.microsoft.com/azure/aks/kubernetes-helm) to see if the cluster is configured correctly

Please comment any results below.

**Comment by manuchandel** [comment] 2019-10-17 18:38
Thank you @msebolt  for quick reply. I understood helm installer tasks. But the problem lies with one specific thing. "Helm Charts". I used this sample repo https://github.com/Microsoft/python-sample-vscode-flask-tutorial/  from the docs to deploy to kubernetes. This repo does not have any charts directory. I went through the docs and found this statement in particular  ```: This can be a path to a packaged chart or a path to an unpacked chart directory. In this example you are publishing the chart using a CI build, so select the file package using file picker or enter $(System.DefaultWorkingDirectory)/**/*.tgz```   It says, that I as a developer, am publishing the Chart using CI build. but there are no charts published. I get an error on AzureDevOps releases saying ```cannot resolve path```. I saw the closed issue and other developer seems to get resolved. but I cannot find posted screenshot links in current docs version.

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri3, doc-bug
