### ISSUE TITLE
Adding a string literal to an existing cache key does not avoid hits on existing caches

### ISSUE THREAD

**Issue by estensen** [MicrosoftDocs/azure-devops-docs#6997] opened 2020-01-20 10:40 UTC
Could you please update the example to correctly show how this is done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/index?view=azure-devops)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment] 2020-01-21 17:28
@estensen Thank you for the feedback, we apologize for any issues in the examples.

Please refer to the specific example, e.g. [Gradle](https://docs.microsoft.com/azure/devops/pipelines/caching/index#gradle) or [Maven](https://docs.microsoft.com/azure/devops/pipelines/caching/index#gradle), and we will assign this to the author for review.

**Comment by estensen** [comment] 2020-01-22 08:32
The hack to change the cache key to avoid a cache hit still returns a cache hit, not a miss, as explained in [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/index?view=azure-devops#can-i-clear-a-cache) example

**Comment by msebolt** [comment] 2020-01-22 16:25
Great, thank you for the update.  Assigning this to the author now.

**Comment by Slooz** [comment] 2020-04-05 19:52
@estensen you must have an existing cache that matches the new cache key that you're using. Can you try adding a random string literal to the cache key? Also, make sure that you aren't getting a cache hit from a key in `restoreKeys`.

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
