### ISSUE TITLE
Azure DevOps Pipeline Environment - Kubernetes resource API

### ISSUE THREAD

**Issue by skwasiborski** [MicrosoftDocs/azure-devops-docs#5573] opened 2019-09-11 14:20 UTC
Is there an API to create Azure DevOps Pipeline Environment - Kubernetes resource?

I have a CI/CD pipeline which automatically creates namespaces. It would be great if I could link these tasks to Kubernetes resource in appropriate environment. Unfortunately I did not find any way to automatically create the resource from CI/CD. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7730ae4d-4101-9c83-1823-4ff43ff161ce
* Version Independent ID: 20a7e263-4819-783e-c984-c4f3b459e22f
* Content: [Environment - Kubernetes resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/environments-kubernetes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments-kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment] 2019-09-11 15:09
@skwasiborski  Thank you for the question.

Can you try using the [Kubectl task](https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops)?  This should give you access to the `create` action.

**Comment by yelob** [comment] 2019-10-01 17:46
It would be extra cool, if when you specified the environment like
 environment: 'smarthotel-dev.bookings'
that it would not only create the environment 'smarthotel-dev' (if it didn't exist), but also create the namespace 'bookings' as a resource in the environment (if it didn't exist).

**Comment by shashankbarsin** [comment] 2019-10-04 16:55
@skwasiborski and @yelob we have a feature coming up really soon (around early November) called review apps which lets you create namespaces on the fly for each PR and register them as K8s resources under environments. We are doing this with the intention of allowing the user a way to assess the state of the application in this review environment before merging the PR.

About the request for documentation on APIs for creating K8s resource under environment, the REST APIs for creating environments are not publicly released yet. I'm closing this issue for now as this is not an issue with the documentation. Please open this as an issue on our [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) (which is where we take feature asks) and I'll make sure the PM owner and the team driving environments work are able to triage and act on this issue at the earliest.

**Comment by andrewsuiter** [comment] 2020-01-09 20:37
@shashankbarsin any update when any documentation will be available to environments/approval checks?

**Comment by syedhassaanahmed** [comment] 2020-01-16 13:21
+1
@shashankbarsin I'd suggest please reopen this issue until API documentation on environments/approval checks is available.

**Comment by daveneeley** [comment] 2020-02-10 22:23
Here's a feature request for this in developer community: https://developercommunity.visualstudio.com/idea/859033/rest-api-to-manage-environments-yaml-pipelines.html

**Comment by rajnemani** [comment] 2020-02-14 00:18
Any update on this issue?  I have a partner/customer who is being vocal about this

**Comment by JtMotoX** [comment] 2020-02-14 06:00
We automate everything using REST API, from creating project, repos, policies, pipelines (build/release), entitlements. We are in process of rolling out new version of multi-stage pipeline but we are not able to create Environments, Environment Resources, or Environment Approvals and Checks.  Please provide an API for these.  This is holding up a major milestone for us.

**Comment by jf781** [comment] 2020-06-03 21:12
I wanted to see if there were any updates to this.   It would be really helpful for us on a current project.

**Comment by IvanJosipovic** [comment] 2020-06-11 02:33
+1

**Comment by jf781** [comment] 2020-06-12 17:32
Figured out a way to do this and wanted to pass it along.   Please let me know if you have any issues/questions. 

[Creating an environment via API's in Azure DevOps](https://joefecht.com/posts/creating-an-azdo-environment-via-api/)

**Comment by f2calv** [comment] 2020-07-02 08:12
It's documented in the official docs;
- https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/kubernetes/add?view=azure-devops-rest-6.0

**Comment by JtMotoX** [comment] 2020-07-02 09:33
@f2calv Thanks for letting us know.  These Environments and Kubernetes docs must have been added recently because they were not present before.  I am listing below a sample workflow with what I have been able to confirm as working and what is still broken by following the new documentation.

1) List Environments (✔ supported/confirmed)
1) List Resources in a specified environment (✔ supported/confirmed)
1) Add Kubernetes Resource (❌ broken - see error below)
1) Delete Kubernetes Resource (✔ supported/confirmed)

The documentation you linked for adding a Kubernetes resource only supports 4 request parameters.  It seems to be missing parameters for the "Server URL", "Secret", and "Accept untrusted certificates".  When I try to create a Kubernetes using the 4 parameters documented, I get the error "_Failed to create resource. Please ensure that all mandatory fields are provided as input._"

https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/environments/get?view=azure-devops-rest-6.0#environmentexpands

Name | Type | Description
-- | -- | --
clusterName | string |  
name | string |  
namespace | string |  
tags | string[] | Tags of the kubernetes resource.
**serverUrl** ❌missing | string |
**secret** ❌missing | string |
**acceptUntrustedCertificates** ❌missing | string |

REQUEST:
```
POST https://dev.azure.com/{organization}/{project}/_apis/distributedtask/environments/{environmentId}/providers/kubernetes?api-version=6.0-preview.1
{
	"clusterName": "test",
	"name": "test name",
	"namespace": "test-namespace",
	"tags": "foo"
}
```
RESPONSE:
```
HTTP/1.1 500 Internal Server Error
{
  "$id": "1",
  "innerException": null,
  "message": "Failed to create resource. Please ensure that all mandatory fields are provided as input.",
  "typeName": "Microsoft.TeamFoundation.DistributedTask.WebApi.KubernetesResourceException, Microsoft.TeamFoundation.DistributedTask.WebApi",
  "typeKey": "KubernetesResourceException",
  "errorCode": 0,
  "eventId": 3000
}
```

**Comment by edjwhho** [comment] 2020-07-16 13:06
seeing exactly the same error when trying to create resource within a created environment:
rest api post to below url with body:
url =  https://XXX/xxxx/xxxx/_apis/distributedtask/environments/17/providers/kubernetes?api-version=6.0-preview.1 
```
JSON Payload: [
    {
        "clusterName":  "aks-sandbox",
        "tags":  "test",
        "name":  "pr-111",
        "namespace":  "pr-111",
        "serviceEndpointId":  "guid of service endpoint"
    }
]

`Invoke-RestMethod : {"$id":"1","innerException":null,"message":"Failed to create resource. Please ensure that all mandatory fields are provided as input.","typeName":"Microsoft.TeamFoundation.DistributedTask.WebApi.KubernetesResourceException, 
Microsoft.TeamFoundation.DistributedTask.WebApi","typeKey":"KubernetesResourceException","errorCode":0,"eventId":3000}`

**Comment by jf781** [comment] 2020-07-16 13:30
You can see the sample payloads in the link below.   The blog article above talks about how.  

https://github.com/jf781/AzureDevopsEnvironments/tree/master/payload-samples

Hope this helps!!

**Comment by edjwhho** [comment] 2020-07-16 14:54
thanks @jf781 , found the problem with the payload body im passing, it was due to my powershell passing through an array instead of just single json, got it sorted thanks.
 
you're example is very useful, thanks
> https://github.com/jf781/AzureDevopsEnvironments/tree/master/payload-samples

**Comment by CN-PierreNoel** [comment] 2020-08-25 21:14
I have the same issue using python.
no problem creating the service endpoint but can't create the kubernetes resource in the environment. Would be nice to have more information about what is missing

{'$id': '1', 'innerException': None, 'message': 'Failed to create resource. Please ensure that all mandatory fields are provided as input.', 'typeName': 'Microsoft.TeamFoundation.DistributedTask.WebApi.KubernetesResourceException, Microsoft.TeamFoundation.DistributedTask.WebApi', 'typeKey': 'KubernetesResourceException', 'errorCode': 0, 'eventId': 3000}

**Closed** 2021-03-31 16:24 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
