### ISSUE TITLE
Missing information about Environment installs

### ISSUE THREAD

**Issue by FISHMANPET** [MicrosoftDocs/azure-devops-docs#7044] opened 2020-01-23 18:29 UTC
Now that support has been added for "VM" as an Environment resource, config.cmd supports `--environment` and `--environmentname` flags (these are passed into the command line by the install string generated when adding a VM resource to an environment) but there's no information about them here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#download-configure)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2020-01-24 17:13
@FISHMANPET Thank you for the feedback.

Assigning this to the author for further review.

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
