### ISSUE TITLE
Test may always pass: Need "set -e"

### ISSUE THREAD

**Issue by mchirico** [MicrosoftDocs/azure-devops-docs#4744] opened 2019-07-04 17:30 UTC
Current example shows the following:
```bash
# THIS WILL ALWAYS PASS... INCORRECT
- script: go test -v ./...
  workingDirectory: '$(modulePath)'
  displayName: 'Run tests'

```

However, using _vmImage: 'ubuntu-16.04'_ it may be necessary to add **set -e** at the beginning of the script, as follows:

```bash
# CORRECT
- script: |
     set -e
     go test -v ./...
  workingDirectory: '$(modulePath)'
  displayName: 'Run tests'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1199cdec-3d76-5693-6295-6f36ce05f3bf
* Version Independent ID: 04ae7849-e91d-caf3-d48a-926473996248
* Content: [Build and test Go projects - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/go?view=azure-devops)
* Content Source: [docs/pipelines/languages/go.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/go.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by zezha-msft** [comment] 2019-08-12 23:31
That is super helpful, thanks!

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
