### ISSUE TITLE
Innaccurate

### ISSUE THREAD

**Issue by zarochi** [MicrosoftDocs/azure-devops-docs#4900] opened 2019-07-17 17:21 UTC
This is still the best doc I've found on getting your ARM template into CI/CD, but unfortunately it's not accurate. Some of the parameters listed as required aren't even included in the example. Further, azureSubscription isn't the azure subscription name or ID. This value expects the name of the service to service connection, so it's not intuitive. While I'd love for the yml to be updated to have this be serviceConnectionName or the like instead this doc needs to be updated as soon as possible to indicate that this doesn't accept the subscription information as input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment] 2019-07-19 05:53
@pulkitaggarwl  - fyi

**Comment by zarochi** [comment] 2019-07-22 18:40
Thanks for jumping on this one; I just wanted to add a note that the azureSubcription value mentioned works as the service to service connection in every place I've noticed it mentioned in docs like this; not just this one.

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
