### ISSUE TITLE
Add caching example for Python packaging via pip

### ISSUE THREAD

**Issue by ofek** [MicrosoftDocs/azure-devops-docs#6282] opened 2019-11-06 17:39 UTC

**Comment by WilliamAntonRohm** [comment] 2019-11-06 22:52
@ofek -- Ofek, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by ofek** [comment] 2019-11-07 17:44
Sorry about that! This is regarding https://aka.ms/pipeline-caching-docs

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri3, doc-enhancement
