### ISSUE TITLE
Details on setting test owner

### ISSUE THREAD

**Issue by kalkun** [MicrosoftDocs/azure-devops-docs#6360] opened 2019-11-13 21:23 UTC
How do I set the owner of a test or test file? It seems like it could be a very useful feature but on my own pipelines as well as on the screenshot in this article, the value is `not available`. How is this information controlled? This information seems like its within the scope of this article which does mention the _owner_ in various other instances.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94cca257-5f81-190e-b50c-7b7f69217234
* Version Independent ID: 1d84dc61-a8bb-b45a-6c93-5bec211c19a5
* Content: [Review test results - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops#tests-tab)
* Content Source: [docs/pipelines/test/review-continuous-test-results-after-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/review-continuous-test-results-after-build.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vinojos
* Microsoft Alias: **vinojos**

**Comment by msebolt** [comment] 2019-11-14 05:55
@vinojos  Thank you for the feedback, assigning this to the author for review.

Please note for product specific feedback, you'll need to direct this to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment] 2019-11-14 05:57
@thomps23 The author for this topics seems to be missing?

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
