### ISSUE TITLE
Azure Connection Type?

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/azure-devops-docs#7611] opened 2020-03-14 20:40 UTC
The descriptions of the Resource Group and Enable Copy Prerequisites arguments refer to an argument called Azure Connection Type, but no argument Azure Connection Type is documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:29
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:29 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod

**Comment by HughDevlin** [comment] 2020-12-02 20:46
Please re-open this issue.

An "Azure Connection Type" is referenced in several contexts on this page.

Please define "Azure Connection Type" on first reference.
