### ISSUE TITLE
Task should be marked deprecated

### ISSUE THREAD

**Issue by krizleebear** [MicrosoftDocs/azure-devops-docs#6238] opened 2019-11-03 23:14 UTC
IMHO the publish-build-artifacts should be marked deprecated in favor of PublishPipelineArtifact.
see also:
https://github.com/microsoft/azure-pipelines-agent/issues/1480#issuecomment-484199370

I'm new on Azure Pipelines and I really like the documentation, great work there. But having deprecated jobs not properly marked is an issue.

If the two tasks are actually intended for different scenarios, I'd like to have some description of these scenarios (when to use which of the two)

BR
Christian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by masterofimages** [comment] 2019-11-26 10:13
This task is not deprecated, since the new "Publish Pipeline Artifact" task doesn't yet work on the on-premise version of Azure DevOps. The documentation should be updated to reflect this, since at the moment there is no distinction made between on-premise and cloud, and the task is actually still available on-premise, it just doesn't work!

**Comment by krizleebear** [comment] 2019-12-02 22:15
Thanks for the explanation. A note like proposed would make things clearer. And if you're on cloud you could then choose the faster of the two.

**Comment by steved0x** [comment] 2019-12-13 22:28
The Publish Pipeline Artifact task is listed as being supported for Azure DevOps Services only at this time:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops

We can get that cleared up in the documentation. I'll get that updated.

![image](https://user-images.githubusercontent.com/1580889/70836298-bdeabc00-1dcd-11ea-9acd-7231b7bb7477.png)

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
