### ISSUE TITLE
Describe Build.SourceBranch[Name] value if triggered by git tag

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/azure-devops-docs#4258] opened 2019-05-19 11:34 UTC
Using https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops I inferred that for tag-triggered builds, `Build.SourceBranch` is something like `refs/tags/1.0` and (although not explicitly mentioned there) `Build.SourceBranchName` would then be `1.0`. Is this correct? Either way, it should be described in here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by RehanSaeed** [comment] 2019-05-26 11:47
How do you determine if there is a tag at all? Documentation needs a lot of work around git tags.

**Comment by RehanSaeed** [comment] 2019-06-02 16:53
How do we get the branch name if the build was started via a git tag.

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
