### ISSUE TITLE
Ability to set custom folder via ARM template?

### ISSUE THREAD

**Issue by gokusupa** [MicrosoftDocs/azure-devops-docs#3255] opened 2019-02-06 15:59 UTC
For two agents to be configured on one machine, the name of the agent and the folder name needs to be unique. 

Unfortunatly there is no documentation on setting a custom folder location when installing an agent via ARM template.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09fa0c14-9937-41bc-cc34-179edb379083
* Version Independent ID: 10fe3600-21a5-12db-5e21-5ade3a8fa484
* Content: [Provision agents for deployment groups - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/howto-provision-deployment-group-agents?view=azure-devops)
* Content Source: [docs/pipelines/release/deployment-groups/howto-provision-deployment-group-agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deployment-groups/howto-provision-deployment-group-agents.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment] 2019-02-21 09:14
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by t3mi** [comment] 2019-12-26 19:06
It would be great addition as well to have a possibility for setting a custom account for the agent.

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-cicd/tech, devops/prod
