### ISSUE TITLE
Artifact download for containers

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/azure-devops-docs#4475] opened 2019-06-11 05:41 UTC
"Azure Container Registry, Docker, Kubernetes" states "By default, builds are downloaded to the agent. You can configure an option in the stage to skip the download of artifacts." Does that mean that the agents will pull the container(s)? Besides, the linked page doesn't specify how to set that behaviour.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598465e1-85d4-4961-b8b6-902d6026c5e3
* Version Independent ID: 5ef1308a-3aeb-fcc4-dec7-6f10785612a3
* Content: [Release artifacts and artifact sources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=azure-devops#container)
* Content Source: [docs/pipelines/release/artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment] 2019-06-11 05:42
@azooinmyluggage  - can you please take a look?

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
