### ISSUE TITLE
exception creating 'All repositories': (No message available, see logs)---Facing this issue

### ISSUE THREAD

**Issue by Rajesh919** [MicrosoftDocs/azure-devops-docs#3754] opened 2019-03-24 21:29 UTC
Please see the below screenshot.
![image](https://user-images.githubusercontent.com/26745810/54886091-5913be00-4e5a-11e9-9a9f-9b8954c77ca5.png)

**Comment by Rajesh919** [comment] 2019-03-24 21:31
I was not able to view the repositories. Its throwing me an error "Exception creating: All Repositories".

Please post your suggestions or comments.

Thanks,
Raj

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri3
