### ISSUE TITLE
The sample script fails

### ISSUE THREAD

**Issue by tong-1324** [MicrosoftDocs/azure-devops-docs#4035] opened 2019-04-22 20:15 UTC
driver.FindElement(By.XPath("//ol[@id='b_results']/li/h2/a/strong[3]")).Click(); 

This line returns error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e51d18-72ec-1ad4-9ae7-8185c8e1dcd6
* Version Independent ID: 9f2f0471-d123-8e95-1606-cd811d1ece9a
* Content: [Perform UI tests with Selenium - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=azure-devops#feedback)
* Content Source: [docs/pipelines/test/continuous-test-selenium.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/continuous-test-selenium.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by Luukjn** [comment] 2019-06-26 11:35
It seems the bing website changed since this article is posted. The correct xpath is //*[@id='b_results']/li[2]/div[1]/h2/a

**Comment by adelisle** [comment] 2019-07-31 15:22
The correct xpath seems to now be `//*[@id='b_results']/li[1]/div[1]/h2/a`

**Comment by Luukjn** [comment] 2019-07-31 15:29
The xpath changes as soon as the 'azure pipelines' site moves up or down the bing search results. Maybe it is not a good idea to use a search engines search results page as an example here.

**Comment by adelisle** [comment] 2019-07-31 18:41
Then I suggest using this instead: `By.LinkText("Azure Pipelines | Microsoft Azure")`

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
