### ISSUE TITLE
The images should reflect better the flow in the documentation

### ISSUE THREAD

**Issue by bauca** [MicrosoftDocs/azure-devops-docs#5087] opened 2019-08-01 11:28 UTC
The arrows in the image are pointing from right to left, which does not correspond to the explanation in the text. Since A is parent of B the arrows should point from A to B and not otherwise.

[https://docs.microsoft.com/en-us/azure/devops/repos/git/history?view=azure-devops](https://docs.microsoft.com/en-us/azure/devops/repos/git/history?view=azure-devops)

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri3, doc-bug
