### ISSUE TITLE
Picture examples given in this page are very old

### ISSUE THREAD

**Issue by zl00p3r** [MicrosoftDocs/azure-devops-docs#6056] opened 2019-10-18 16:56 UTC
Picture examples given in this page are very old. This is up-to-date with current Azure DevOps portal experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2019-10-18 20:54
@zl00p3r Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
