### ISSUE TITLE
Incorrect guideline for "Authorize resources"

### ISSUE THREAD

**Issue by Sonesson** [MicrosoftDocs/azure-devops-docs#4642] opened 2019-06-26 10:59 UTC
Following your guide in the bullet under "Use a service connection"
I am trying to authorize a specific pipeline to my sonarqube service connection.
However there are no "Authorize resources" at the step you are mentioning. 
When queuing my build I get a red box with following text:
"Job Job1: Step  input connectedServiceName references service connection ETP-Shared which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

Nowhere on that dialog is it possible to perform authorization.

The only workaround I have found is to check the "Allow all pipelines" for the service connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment] 2019-06-26 11:22
@shashban

**Comment by shashban** [comment] 2019-07-30 06:56
@Sonesson We have made some changes to this space to bubble up the authorize resources call to action more reliably. Can you ensure you have permissions to use the resource? Authorize will fail if you do not have use permissions on the resource at all.
In case it still doesn't work, then can you point me to the pipeline yaml file and we can debug it further.

**Comment by ahaeber** [comment] 2019-09-02 18:38
For the Docker@2 task (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker) I need to specify a "Docker registry service connection" for the "Login" command. I have added a Azure Resource Manager (ARM) connection with a service principle because the container registry is in a different Azure subscription. Unfortunately, the subscription is not shown when I try to add a "Docker registry service connection". So how can I accomplish this when the Azure Container Registry is in a different subscription?

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri1, devops-cicd/tech, devops/prod
