### ISSUE TITLE
Example virtual machine scale set doesn't work

### ISSUE THREAD

**Issue by patrikn** [MicrosoftDocs/azure-devops-docs#9128] opened 2020-08-21 08:51 UTC
The example tries to use ephemeral storage with a Standard_D2_v3 VM, but you need an s-series VM to use ephemeral storage so the example command fails. Also requires Standard_LRS, not StandardSSD_LRS, for the storage account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2020-09-09 20:28
Possible duplicate of https://github.com/MicrosoftDocs/azure-devops-docs/issues/9180.

**Comment by lgmorand** [comment] 2020-09-09 20:45
@msebolt, yes all are duplicates but two of them were closed without being fixed. In the second one, Steve said he'll fix it and 12 days later it's not, but ticket has been closed.

Should we not fix the page before closing the ticket (at least this one, the last surviving :))

**Comment by msebolt** [comment] 2020-09-09 20:49
Yes, agreed, this issue should remain open until reviewed by the author.

**Comment by steved0x** [comment] 2020-11-30 21:59
@patrikn @lgmorand The article was updated August 28th and now has only 5 mentions of ephemeral storage, all within this updated section that explicitly calls out that your VM size must support it.  The rest of the article has also had some updates so I am going to run through the script and ensure that it is up to date (since the feature and the article have had several updates since then)

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#create-the-scale-set

![image](https://user-images.githubusercontent.com/1580889/100670546-0841b180-332d-11eb-9a50-b3d3d1049499.png)

**Comment by steved0x** [comment] 2020-11-30 22:06
I just ran the script in the article and verified it working. Please reopen this issue or post a new one if the latest version isn't working for you. Thank you.

**Closed by steved0x** 2020-11-30 22:06 UTC
Labels: Pri2, devops-cicd-agents/tech, devops/prod, doc-bug
