### ISSUE TITLE
Personal Access Token Information Misleading?

### ISSUE THREAD

**Issue by KaineVarley** [MicrosoftDocs/azure-devops-docs#4099] opened 2019-04-30 11:58 UTC
Hi,

I think that the information around the use of the [PAT (Personal Access Token)](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#personal-access-token-pat) may be misleading.

> Generate and use a PAT to connect an agent with Azure Pipelines or TFS 2017 and newer. PAT is the only scheme that works with Azure Pipelines. Also, as explained above, this _**PAT is used only at the time of registering the agent, and not for subsequent communication.**_

I have found that, when [removing an agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#remove-and-re-configure-an-agent) (`.\config.cmd remove`) to rename or change some configuration setting, that the PAT is also required.

![2019-04-30_1251](https://user-images.githubusercontent.com/1490082/56960100-a107be00-6b47-11e9-868d-b5775d71ed7c.png)

In fact, requiring the PAT for removing the agent seems wrong somehow since PAT's have expiry dates. So needing the original PAT to remove the agent may lead to issues if this is several months or years into the future or if the individual whose token it is has left the organisation. There again, perhaps I have misunderstood the role of the PAT and how Agents are supposed to operate.

Kind regards,

Kaine

**Comment by KaineVarley** [comment] 2019-05-28 09:55
Hi,

As an update to the issue I reported earlier, I now understand, when removing/changing the agent, that the PAT doesn't have to be the same token as the one used to configure the agent, but merely has to be valid. This wasn't clear to me from the documentation, but I have now tested this with a token from a colleague and it works. So, I am happy this to be closed down now, if it was open, but suggest that the documentation could be made clearer in this respect.

Thanks,

Kaine

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri3, doc-bug
