### ISSUE TITLE
Do not use md shorthand

### ISSUE THREAD

**Issue by stewartadam** [MicrosoftDocs/azure-devops-docs#6013] opened 2019-10-16 20:45 UTC
please use full `mkdir` which is compatible with all platforms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment] 2019-10-17 06:37
@stewartadam Thank you for the suggestion, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri1, devops-ecosystem/tech, devops/prod, doc-enhancement

**Comment by stewartadam** [comment] 2020-11-25 14:44
@apawast @msebolt Users don't have permissions to re-open issues on this repo, and you should probably configure the bot to not close issues when it's assigned to MSFT :)

**Comment by mijacobs** [comment] 2020-11-25 18:55
@stewartadam If you have the info you'd like to add to the article, can you open a PR? We have a team of folks standing by ready to review and approve contributions.

**Comment by stewartadam** [comment] 2020-11-25 22:32
https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/2468

Feedback around issue management still stands though, the bot is closing issues that haven't requested user input for inactivity and users cannot re-open them

**Comment by mijacobs** [comment] 2020-11-25 22:53
Thanks for the feedback, @stewartadam, we'll take it into account as we refine our process.
