### ISSUE TITLE
Incorrect information: How Do I Consume Artifacts?

### ISSUE THREAD

**Issue by jrtitus** [MicrosoftDocs/azure-devops-docs#7042] opened 2020-01-23 17:15 UTC
> "At present, you cannot download artifact produced by a YAML pipeline in another YAML pipeline." 

[Source](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml#how-do-i-consume-artifacts).

Elsewhere in the documentation, the exact thing this sentence says that one cannot do is defined in the [`DownloadPipelineArtifact` task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)

**Comment by msebolt** [comment] 2020-01-24 16:57
@jrtitus  Thank you for the feedback.

Assigning this to the author for further review.

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri3, doc-enhancement
