### ISSUE TITLE
Add a simple example for docker compose task

### ISSUE THREAD

**Issue by wlongxiang** [MicrosoftDocs/azure-devops-docs#6415] opened 2019-11-19 21:36 UTC
Can we add a simple runnable example for the docker compose task here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e2e5ad-709e-a751-8cd6-1e1b25147bd1
* Version Independent ID: 225d70c4-0591-5b9f-260a-7ae890903bde
* Content: [Docker Compose task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker-compose.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker-compose.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by msebolt** [comment] 2019-11-20 04:52
@wlongxiang Thank you for the suggestion, assigning this to the author for review.

**Comment by engineersamuel** [comment] 2020-03-06 22:51
Adding to this request, I setup a sample pipeline that builds a docker image and executes `DockerCompose@0` tasks.  From reading the docs [1] for the first time my first assumption was to `Run a Docker Compose command`.  I wanted to `up` and have it detached so I set `detached: true`.  However, that is a bit misleading since when running a command `detached: true` doesn't pass `-d` [2].  To get this proper behavior one has to `action: Run services` where `detached: true` does properly [3] add `-d` as an argument.

I think this could be largely resolved with a simple example for executing `docker-compose up`.

[1] https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops#run-a-docker-compose-command
[2] https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DockerComposeV0/dockercomposecommand.ts
[3] https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DockerComposeV0/dockercomposeup.ts

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
