### ISSUE TITLE
Max. simultaneous Hook triggers

### ISSUE THREAD

**Issue by nvondru** [MicrosoftDocs/azure-devops-docs#3662] opened 2019-03-15 16:07 UTC
If i set up a hook that triggers on workitem updated i have the following problem:
If i update more than 8 items at the same time (by moving them to another parent) the hook doesn't even trigger. At least i don't get any requests incomming on my endpoint. Is there a maximum amount of triggers at the same time? By moving 8 items i actually update 10 items am i right? 8 that get moved, 1 that gets new child-items and 1 that "looses" the child-items.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96287641-3e4f-b038-148f-08e8471bd573
* Version Independent ID: b0034cd1-4f29-2e2d-c2bb-49004552dae8
* Content: [Troubleshoot your service hooks integrations](https://docs.microsoft.com/en-us/azure/devops/service-hooks/troubleshoot?view=azure-devops#feedback)
* Content Source: [docs/service-hooks/troubleshoot.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/troubleshoot.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment] 2019-03-21 20:49
Hi @nvondru, I've created a user story to look into and follow up on this. Thanks for reaching out. I'll be in touch!

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri2, devops-collab/tech, devops/prod, doc-bug
