### ISSUE TITLE
Use docker hub

### ISSUE THREAD

**Issue by firestonem** [MicrosoftDocs/azure-devops-docs#4524] opened 2019-06-14 18:48 UTC
Right now these instructions are "paste these files onto your computer and build it yourself". MS has a public Dockerhub account https://hub.docker.com/u/microsoft/ where officially-built images can be hosted and distributed. Just a good-practice suggestion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliobbv
* Microsoft Alias: **juliobv**

**Comment by kwaazaar** [comment] 2019-06-19 14:16
Strange thing is there's this: https://hub.docker.com/_/microsoft-azure-pipelines-vsts-agent?tab=description

This seems to be deprecated, according to its docs. Why? Also those images are pretty old (22-1-2019).

**Comment by jboarman** [comment] 2019-06-22 22:44
This has recent releases posted in GitHub, but unfortunately does not seem to be for docker: https://github.com/Microsoft/azure-pipelines-image-generation

**Comment by fgervais** [comment] 2019-09-24 20:39
@kwaazaar yes I can't figure out why they would deprecate those images, makes no sens to me.

Copy and pasting scripts is error prone, inheriting from an image is not.

**Comment by ktchup** [comment] 2019-09-25 20:07
Hi everybody, I created a Docker image on the hub which contains .NET Core 3 SDK, Docker within Docker, SQL Server commands clients and more --> wizzapi/azpdockeragent

**Comment by PirateBread** [comment] 2019-11-21 16:41
Microsoft are incredibly confused about their build agent strategy. Deprecating the Docker agents in favour of Packer was a terrible idea considering how much more effort Packer builds in comparison.

The Dockerhub images and the Helm chart were perfect, easily integrated into things like Kubernetes or ACI. Literally took 5 minutes effort to deploy build agents across our clusters.

Now we have to deal with this rubbish.

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
