### ISSUE TITLE
Add multidimensional matrix example in step reuse section

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/azure-devops-docs#3316] opened 2019-02-11 09:09 UTC
Currently, all the matrix examples are not really a matrix but just a flat list of configurations. It would be good to include an example that compares how combinatorial products using multiple dimensions can be achieved both in Travis CI and here.
Some inspiration:
```
rvm:
  - 2.5
  - 2.2
env:
  - ISOLATED=true
  - ISOLATED=false
```
produces 4 jobs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035d0e47-a927-1e99-34a4-181e34578af3
* Version Independent ID: ab6853d8-98cf-dd68-7425-4644cc7e0492
* Content: [Migrate from Travis to Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-travis?view=azure-devops#git-submodules)
* Content Source: [docs/pipelines/migrate/from-travis.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/migrate/from-travis.md)
* Product: **devops**
* GitHub Login: @ethomson
* Microsoft Alias: **ethomson**

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
