### ISSUE TITLE
Should indicate what happens when publishing to the same artifact

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/azure-devops-docs#7281] opened 2020-02-14 04:40 UTC
This should describe the behaviour when publishing to an existing artifact.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by ScottLangham** [comment] 2020-03-10 16:04
I want to know if I can publish files to the same artifact from different jobs?

**Comment by xyz92** [comment] 2020-03-13 19:54
@ScottLangham Any updates on your question? please let me know. thank you.

**Comment by ScottLangham** [comment] 2020-03-13 21:18
I found through experimentation that it doesn't work.

**Comment by Smootium** [comment] 2020-04-22 18:17
Confirming @ScottLangham's experimentation, this is the error I get today (and the PublishPipeLineArtifact task fails):
No LastRequestResponse on exception ArtifactExistsException: Artifact packageNamesJsonFile already exists for build 151265.
...
##[error]Artifact packageNamesJsonFile already exists for build 151265.

One job creates and updates one property in a JSON file, which it then uploads.
A subsequent job downloads the artifact and updates another property in the file.
Another subsequent job needs the file with both properties filled out; I was attempting to simply have the one artifact instead of having to upload another artifact (basically, a copy of the first artifact).  
😕

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
