### ISSUE TITLE
Incorrect documentation note for the Jenkins Service Connection

### ISSUE THREAD

**Issue by bbarman4u** [MicrosoftDocs/azure-devops-docs#5845] opened 2019-10-04 01:22 UTC
The Jenkins service connection uses username and token (where the token is generated for the user used to connect to the Jenkins instance). Using the jenkins login password for the user would end in HTTP 403 error when Azure Pipelines connects to the Jenkins Instance.

![image](https://user-images.githubusercontent.com/20643454/66174633-9f24b800-e61b-11e9-8b70-9b9aed46b9aa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-in/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ashokirla** [comment] 2019-12-17 07:06
In Azure DevOps, Jenkins service connection takes username and password as input. You don't have to generate a token. Can you provide more details on where you are facing this issue.

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
