### ISSUE TITLE
.NET Core build

### ISSUE THREAD

**Issue by coffeymatt** [MicrosoftDocs/azure-devops-docs#5902] opened 2019-10-09 10:36 UTC
Would be useful if this included an example for .NET core builds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728b7c25-2ef7-3807-b898-b9024ba297e2
* Version Independent ID: 4b2eda64-1f32-fdf8-ee09-420dbb8b9f4d
* Content: [Setting up GitHub Source Linking with Azure DevOps Services Build & Azure DevOps Services Symbol Server](https://docs.microsoft.com/en-us/azure/devops/artifacts/symbols/setting-up-github-sourcelinking?view=azure-devops#feedback)
* Content Source: [docs/artifacts/symbols/setting-up-github-sourcelinking.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/symbols/setting-up-github-sourcelinking.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri2, devops-artifacts/tech, devops/prod, doc-enhancement
