### ISSUE TITLE
TFS_Core_Contracts.WebApiConnectedServiceRef link is not working 

### ISSUE THREAD

**Issue by ahmedspiir** [MicrosoftDocs/azure-devops-docs#4444] opened 2019-06-06 08:52 UTC
This link on this line is not working: connectedService: TFS_Core_Contracts.WebApiConnectedServiceRef. The connected service associated with the continuous deployment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 156add32-7c48-f47a-5737-fb76fd52cad9
* Version Independent ID: 0da5c87a-bcac-6930-a2e7-1e5856d63a49
* Content: [TFS/Build/Contracts ContinuousDeploymentDefinition API](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/tfs/build/contracts/continuousdeploymentdefinition?view=azure-devops#feedback)
* Content Source: [docs/extend/reference/client/api/TFS/Build/Contracts/ContinuousDeploymentDefinition.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/api/TFS/Build/Contracts/ContinuousDeploymentDefinition.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment] 2019-06-13 18:06
Hi @ahmedspiir, Sorry to hear that link doesn't seem to be working - thanks for reaching out. We'll be in touch soon.

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri2, devops-ecosystem/tech, devops/prod, doc-bug
