### ISSUE TITLE
Running docker inside docker

### ISSUE THREAD

**Issue by smiklos** [MicrosoftDocs/azure-devops-docs#6070] opened 2019-10-20 15:49 UTC
Hi, 

It appears that one can't use docker inside docker even if we bind-mount the nested container because in the agent this feature is not supported https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Worker/ContainerOperationProvider.cs#L62

Shouldn't the document be changed or be more specific? I assume with bind mount we can build and push images but it's still not possible to run a pipeline inside a container when the agent is also in a container already.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by firestonem** [comment] 2019-11-21 17:48
I was able to get it working by bind mounting both the docker socket and the docker command from the host:

- /var/run/docker.sock:/var/run/docker.sock
- /usr/bin/docker:/usr/bin/docker

**Comment by kagarlickij** [comment] 2020-01-22 09:56
I run `docker run -e VSTS_ACCOUNT='kagarlickij' -e VSTS_POOL='Self-Hosted' -e VSTS_TOKEN='a***q' -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker mcr.microsoft.com/azure-pipelines/vsts-agent:ubuntu-16.04-docker-18.06.1-ce` and get `[error]Container feature is not supported when agent is already running inside container. Please reference documentation (https://go.microsoft.com/fwlink/?linkid=875268)`

**Comment by mscbpi** [comment] 2020-04-23 20:45
you may install docker to get the binary inside your agent. Don't start the service, but since socket is mounted it accesses the host's.

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
