### ISSUE TITLE
Ability to 'Open test plan' is not available on the test plan context menu

### ISSUE THREAD

**Issue by djfoz** [MicrosoftDocs/azure-devops-docs#4003] opened 2019-04-18 12:21 UTC
Under the section 'Q: Can I rename my test plan' - this displays a screen shot of been able to right click on the high level test plan and then 'open' it. This option no longer appears to be available in Azure DevOps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985ecee3-e347-43bb-5ed2-08ce3aee7621
* Version Independent ID: fdf465fc-a9e1-0198-2e8c-e859c74252b3
* Content: [FAQs and problem solutions - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/reference-qa?view=azure-devops#q-can-i-rename-my-test-plan)
* Content Source: [docs/test/reference-qa.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/reference-qa.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri1, devops-test/tech, devops/prod, doc-bug
