### ISSUE TITLE
I have a troubleshooting suggestion

### ISSUE THREAD

**Issue by eugen-nw** [MicrosoftDocs/azure-devops-docs#7547] opened 2020-03-09 23:02 UTC
This is for the situation when you're dealing with a failing build pipeline and have no idea on what and where got built.  This is painful because you cannot download artifacts if the build pipeline fails, you can just stare at the logs.

Add into the build pipeline an "AzureBlob File Copy" Task, set its Source field to $(Build.Repository.LocalPath) and fill the 'RM Storage Account' and 'Container Name' fields with the details of your destination Blob Container.   That's all you need, everything will get dumped there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e834fd0-59c9-3f45-a09d-88571d94c62e
* Version Independent ID: b798ba39-ef08-55eb-3fa0-731782a1d7e0
* Content: [Troubleshoot builds and releases - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=azure-devops)
* Content Source: [docs/pipelines/troubleshooting.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/troubleshooting.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by eugen-nw** [comment] 2020-03-10 20:11
"Azure File Copy" is the correct name of the task.

**Comment by steved0x** [comment] 2020-05-19 21:47
@eugen-nw Thank you for this idea - I am updating this article with some other changes and I would like to include this tip. To clarify, your suggestion is, for a failing pipeline running on Microsoft-hosted agents (since you can control access to self-hosted agents and inspect them after the fact) - to put this task somewhere to copy out the build directory so you can inspect it for clues? Where would you put the task? As the last step of a job, with previous steps containing continueOnError? Or am I misunderstanding? Thank you.

**Comment by eugen-nw** [comment] 2020-05-20 16:12
Hi @steved0x  Yes, the problem I were wrestling with was taking place in an Azure build pipeline, agent that I could not access.  I do not remember exactly where did I insert the "AzureBlob File Copy" Task, most likely just before the task that was failing.  I am not that sophisticated as to know about continueOnError - cannot say how many people are - so that was certainly not the spot I've used.

**Comment by eugen-nw** [comment] 2020-05-20 16:17
The problem I was having was that the build could not find something and I had no idea of what exists and where.

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
