### ISSUE TITLE
Service hook - Pull request updated WebHook missing notificationType

### ISSUE THREAD

**Issue by tombates-pdr** [MicrosoftDocs/azure-devops-docs#3565] opened 2019-03-05 13:27 UTC
It states [here](
https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?toc=/azure/devops/integrate/toc.json&bc=/azure/devops/integrate/breadcrumb/toc.json&view=azure-devops#git.pullrequest.updated) that the Pull request Updated ServiceHook contains a `notificationType` however it seems to be missing from the payload. It doesn't even appear to be in the sample response.

I am not sure if this is a documentation issue or a bug as a result I have raised both: [Bug](https://developercommunity.visualstudio.com/content/problem/478535/servicehook-pull-request-updated-webhook-missing-n.html)

**Comment by steved0x** [comment] 2019-03-06 17:01
@DrTomBates Thanks for letting us know and filing the associated bug. We will update the documentation once we find out if it is a documentation error or a bug.

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri3, devops-collab/tech, devops/prod, doc-bug
