### ISSUE TITLE
TFVC 源发布时报如下错误

### ISSUE THREAD

**Issue by zhongjq** [MicrosoftDocs/azure-devops-docs#2331] opened 2018-11-02 09:04 UTC
当前版本中，发布管理不支持项目类型 GitRef 的下载

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: febd44ab-caac-85c9-23dc-c9d5fdc14891
* Version Independent ID: e08a8970-baaa-012c-cc98-827a49cd8000
* Content: [Build TFVC repositories - Azure Pipelines & TFS](https://docs.microsoft.com/zh-cn/azure/devops/pipelines/repos/tfvc?view=vsts)
* Content Source: [docs/pipelines/repos/tfvc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/tfvc.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thomps23** [comment] 2019-05-13 20:00
Translation: In the current version, publishing management does not support the download of project type GitRef

Filing as doc-bug

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
