### ISSUE TITLE
helm install/upgrade chartName

### ISSUE THREAD

**Issue by mmisztal1980** [MicrosoftDocs/azure-devops-docs#7318] opened 2020-02-17 19:07 UTC
The documentation does not indicate the expected "chartName" input when the chart hosted from a chart registry. 
When using the HELM cmdline and having the chart under source control (from the chart's folder), the expected argument (instead of the chart name) is typically ".", which tells the helm client to implicitly assume that we're in a HELM chart folder, telling it to look for Chart.yaml. 

What is the expected input in this case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7eeb7f-4e6b-8fee-1d7f-582cfb018b02
* Version Independent ID: 00fb3082-1069-9060-012c-0b6d75ef120b
* Content: [Package and Deploy Helm Charts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/helm-deploy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/helm-deploy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **atulmal**

**Comment by cxwtool** [comment] 2020-11-24 23:31
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:31 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug

**Comment by FilBot3** [comment] 2021-09-24 21:11
Fresh issue here: 

* https://github.com/MicrosoftDocs/azure-devops-docs/issues/11412
