### ISSUE TITLE
How can we bump the version of the package

### ISSUE THREAD

**Issue by sularome** [MicrosoftDocs/azure-devops-docs#4240] opened 2019-05-16 12:54 UTC
I think it will be nice to mention how can we increase the version of the package. Normally i would do `npm version patch` , but since it is doing automatic commit and tag i'm not sure how it should be integrated in the release process. Otherwise we have to manually tag and change package.json right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bbb17f-15a7-25d6-239c-2087d2b644b7
* Version Independent ID: f4949587-0bd0-6bfc-590f-0c4f6386dd7a
* Content: [Use npm to store JavaScript packages in Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-npm?view=azure-devops&tabs=windows#feedback)
* Content Source: [docs/artifacts/get-started-npm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/get-started-npm.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment] 2019-05-16 15:29
Hi @sularome , you can pass `--no-git-tag-version` to avoid the automatic commit and tag. If you *do* want the commit and tag, a simple `git push` afterward may be sufficient. I guess it really depends on the workflow you want. Here is the [npm version docs](https://docs.npmjs.com/cli/version), and here is what one of our team members created/uses for simple scenarios: https://mitchdenny.com/git2semver/. Let me know if this helps

**Comment by sularome** [comment] 2019-05-17 07:32
I believe that the version increase should happen on vsts, not manually, so i do want npm version patch to commit, but we have for example the following workflow: 
* Build and save artifacts
* create a release
* deploy to test envyronment
* if QA confirms that it's ok to release (e.g bugs are fixed) publish on npm. The problem here is that from artifacts folder we do not have option to increase version and git push. If we increase version and git push during build phase on the other hand we might be increasing version without actually releasing because the bug wasn't fixed. 
So i think it will be good to add some information about good practices on how to increase version when working with artifacts. 

P.S: When it comes to the link that you sent about git2semver, we are using in the project which has also nice versioning tool [Conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)

**Comment by t-walker** [comment] 2020-01-17 00:35
+1 here, my team is hosting an npm package in an Artifacts feed and it'd be nice to not have to do all of the versioning manually

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri2, devops-artifacts/tech, devops/prod, doc-bug
