### ISSUE TITLE
.artifactignore is ignored by Pipeline Artifact 

### ISSUE THREAD

**Issue by XmlmXmlmX** [MicrosoftDocs/azure-devops-docs#4874] opened 2019-07-16 08:09 UTC
I've created a Build Pipeline which publishes a Pipeline Artifact. My `.artifactignore` file is located in the root of my git repository and contains following:
```
coverage
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local
npm-debug.log*
yarn-debug.log*
yarn-error.log*
/junit.xml
node_modules
npm-debug.log
Dockerfile*
docker-compose*
.dockerignore
.git
.gitignore
README.md
LICENSE
.vscode
.npmrc
.eslintignore
.editorconfig
.adr-dir
setenv.sh
sonar-project.properties
yarn.lock
package-json.lock
tsconfig.json
.scannerwork
```

The Publish Task doesn't ignore those files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40b39086-3718-419d-d850-914422097cde
* Version Independent ID: 4f23e54f-f59b-85ab-2eb0-6a58eb0ad088
* Content: [Use the .artifactignore file](https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/artifactignore?view=azure-devops)
* Content Source: [docs/artifacts/reference/artifactignore.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/reference/artifactignore.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by the-glima** [comment] 2019-07-17 08:05
Check this issue on GitHub: https://github.com/MicrosoftDocs/vsts-docs/issues/4004

Try adding `.artifactignore` inside of the folder that you have in target path for the publishing.

**Comment by Apholisha** [comment] 2019-10-04 12:07
Hi 
I have the same issue.
I have .artifactignore in the root of the repo.
I do copy it in the $(build.artifactstagingdirectory) and then then I publish. 

What I ended up is a .artifactignore as part of the artifact ( which I do not want) and the files that it is supposed to ignore are still there. 

- task: CopyFiles@2
  displayName: 'Copy artifactignore to: $(build.artifactstagingdirectory)'
  inputs:
    Contents: '**/.artifactignore'
    TargetFolder: '$(build.artifactstagingdirectory)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: drop
  condition: succeededOrFailed()

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri2, devops-artifacts/tech, devops/prod, doc-bug
