### ISSUE TITLE
Azure DevOps Helm Errors Link To This Page For "Troubleshooting."

### ISSUE THREAD

**Issue by dhmorrison** [MicrosoftDocs/azure-devops-docs#6954] opened 2020-01-16 02:06 UTC
During the release pipeline, the helm upgrade task fails in a greenfield Azure DevOps Project (node.js, sail, and kubernetes).  First off, it's really not optimal that an Azure "service" fails on its maiden voyage.  The takeaway is that the Azure DevOps Project template needs to be fixed.   Second, when you examine the failure in the release pipeline, there is a "troubleshooting" link that leads here. This is not a troubleshooting article. This appears to be loosely "informational." If there is a troubleshooting page for help update failing in Azure DevOps build pipeline, that is to what the link in the build logs should point. Not this page though.

Thanks,

David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7eeb7f-4e6b-8fee-1d7f-582cfb018b02
* Version Independent ID: 00fb3082-1069-9060-012c-0b6d75ef120b
* Content: [Package and Deploy Helm Charts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/helm-deploy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/helm-deploy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **shasb**

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
