### ISSUE TITLE
What happens to the forks when deleting the original repository?

### ISSUE THREAD

**Issue by serhatataman** [MicrosoftDocs/azure-devops-docs#6295] opened 2019-11-07 13:54 UTC
Hi,
We have been using Azure DevOps for repositories. I have a question regarding forks. We have recently forked a repository and the original repository will be deleted in the future. Would deletion of the original repository affect the repository we are working on which has been forked from the original? All of our repositories are private.
It would also be nice if you could include this information into the documentation. 
Thanks,
Serhat

**Comment by msebolt** [comment] 2019-11-07 22:08
@serhatataman Thank you for the question.

There should be no effect to a forked repo after deleting the original.

Assigning this to the author to confirm and review the request for added information, please refer to [Forks](https://docs.microsoft.com/azure/devops/repos/git/forks).

**Comment by Tenseiga** [comment] 2019-11-12 16:07
follow

**Comment by serhatataman** [comment] 2019-11-14 08:03
Thank you @msebolt . If you checkout github's documentation (https://help.github.com/en/github/administering-a-repository/deleting-a-repository) you can clearly see that if private repository is forked, all forked repositories will be deleted **in case of deletion**. I would have been beautiful to see whether Azure DevOps has the same mentality or not :)

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri3, doc-enhancement
