### ISSUE TITLE
Provide documentation on how to get path to where the repo is stored

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/azure-devops-docs#6918] opened 2020-01-13 17:04 UTC
One of the big benefits of checking out the repo is so that your YAML files can access other files in the repo without cluttering the main repo. For example you might have a build repo where your build scripts reside. In this repo are config files used to configure the tools the build scripts use. However there is no easy way to reference these config files from the build repo because there is no relative path that would work.

Build repo - build-tools
   build.yml
   build.config

In `build.yml`
```yaml
steps:
   - powershell Get-Content build.config
```

The script is run relative to `Build.SourcesDirectory` I believe. Hence you cannot reference any files relative to the YAML file itself which is needed in this case. The only alternative I can see right now is to include the path to the build repo but that is defined in the main repo's YAML file and could vary by pipelines. So one build may checkout to `build-tools` while another may use `build-stuff` and therefore the `build.yml` wouldn't have any way to know which path to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
