### ISSUE TITLE
Exporting Test Results

### ISSUE THREAD

**Issue by Sunnyerin** [MicrosoftDocs/azure-devops-docs#8210] opened 2020-05-06 14:41 UTC
Prior to the new page there was a feature to export test results that was really nice.  Not having this is a huge loss of functionality.  Is there any plan to bring it back?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#feedback)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @ravishan-msft
* Microsoft Alias: **ravishan-msft**

**Comment by ravishan-msft** [comment] 2020-05-06 18:18
Export option is still available in the new view, @Sunnyerin - click the context menu on any suite in the suite hierarchy and you will see the "Export" option. 
Look at the 2nd section on Suite Tree on the New Test Plans page.

**Comment by Sunnyerin** [comment] 2020-05-06 18:25
OK.  We are looking for exporting Test Execution Results by test case.  It was there before the new view.  We know how to export the test cases themselves.  I just tried the recommendation and it isn’t exporting the actual results with corresponding screen shot like it did in the past.

Erin

**Comment by ravishan-msft** [comment] 2020-05-07 06:05
Erin, can you please share a screenshot from the old view about the functionality you are describing. You can turn-off the new test plans page from the Preview Features option.

**Comment by kelos-01** [comment] 2020-05-07 07:07
I'm also battling to figure out how to export. I don't see the 3 ellipses.
I have administrator level access.
https://imgur.com/gwFO6rh - Screen shot

**Comment by pkuma-msft** [comment] 2020-05-07 07:47
Hi @kelos-01 .. can you tell us which browser you're trying it on? And also if possible, can you try on Chrome or Edge Chromium (if not already done). 

So as I'm seeing, you are not seeing the 3 dots when you hover the mouse over the suite name, is that correct?

**Comment by kelos-01** [comment] 2020-05-07 07:56
I have tried using different browsers. None of them are showing the 3 dots. I'm not sure what more to do?

**Comment by Sunnyerin** [comment] 2020-05-07 11:56
It was  chrome and the functionality is gone.  I tried replicating what we were able to do about 6 months ago and it is gone.  You can close this.  It is unfortunate that it isn’t there anymore.  Our Risk and Control team really liked the email we sent that included all the screen shots.  I can at least get the outcome though so thank you for your help in that.

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri1, devops-test/tech, devops/prod, product-question
