### ISSUE TITLE
Inconsistency between arguments descriptions and YAML

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/azure-devops-docs#4256] opened 2019-05-19 09:53 UTC
The argument description for "tag" says "(required)", however the YAML above makes it more concrete: "Required when action == Edit || Action == Delete || TagSource == Manual". These two have to be the same to avoid confusion. There may be other such cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b12d2c4-f871-1d14-0c16-91e58fb1130b
* Version Independent ID: 6b9e1d67-f303-7445-e573-830309ba49a4
* Content: [GitHub Release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/github-release.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/github-release.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
