### ISSUE TITLE
Bad Links

### ISSUE THREAD

**Issue by BijanSafai** [MicrosoftDocs/azure-devops-docs#4102] opened 2019-04-30 17:43 UTC
Both links in step one and two in the Create Az Rm template link to the general DevTestLabs doc page, not helpful documentation on how to create the template. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22c509e4-dac8-9d73-1087-87aad0017012
* Version Independent ID: 98070d8d-aab5-60f0-73e0-fe5d7137293c
* Content: [Manage a VM in DevTest Labs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/azure/deploy-provision-devtest-lab?view=azure-devops#feedback)
* Content Source: [docs/pipelines/apps/cd/azure/deploy-provision-devtest-lab.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/azure/deploy-provision-devtest-lab.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by tanmayeekamath** [comment] 2019-06-20 20:54
Thanks for your feedback
Looks like the doc above is not created or maintained by the DevTest Labs team.
Here is a doc from our product docs: https://docs.microsoft.com/en-us/azure/lab-services/devtest-lab-integrate-ci-cd-vsts

Can we please replace this doc with the link I shared above?

Thanks,
Tanmayee

**Comment by tanmayeekamath** [comment] 2019-07-29 20:09
@RoopeshNair, can you please address my comment above? 

Tanmayee

**Comment by RoopeshNair** [comment] 2019-07-30 05:33
@steved0x  - can you please do the needful?

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
