### ISSUE TITLE
Messy documentation

### ISSUE THREAD

**Issue by fernandezjose** [MicrosoftDocs/azure-devops-docs#4964] opened 2019-07-22 22:07 UTC
YAML snippet vs. Arguments vs. Examples is just a big ball of 'figure it out'. 

When PUSHing a package I get mixed signals. 
YAML says... `publishFeedCredentials`
Arguments... doesn't show `publishFeedCredentials` anywhere. Instead, `externalEndpoint(s)`
Example... Both, `externalEndpoint` and `externalEndpoints`.

I've been struggling with this for hours now. Aren't these Tasks supposed to be an 'easier' declarative way to do this?

Come on Microsoft... you're better than this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
