### ISSUE TITLE
How to queue a build to Azure Pipeline via the REST API

### ISSUE THREAD

**Issue by zhongyi-zhang** [MicrosoftDocs/azure-devops-docs#3618] opened 2019-03-12 09:43 UTC
Hi, I am reading https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/queue?view=azure-devops-rest-5.0. I can't figure out how to get a similar experience with using an explorer -- click "queue" in the pipeline view, choose a branch, and possible specified commitment and variables, then "queue" again.
![image](https://user-images.githubusercontent.com/13326941/54189643-2fb77180-44ed-11e9-9827-b1367aa26529.png)
Say, it should only require pipeline id, branch name, optional commitment & variables, and a token, shouldn't it?

Could you give an example how to do this via the REST API? Thanks a bunch!
The doc has a lot of parameters listed in the request body section. Some of them even look like read-only. I feel hard to figure out which are required :(.

**Comment by andyjlewis** [comment] 2019-06-30 15:03
@vijayma for REST API doc question

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri3, devops-cicd/tech, devops/prod, doc-bug
