### ISSUE TITLE
modifyOutputPath: true doesn't seem to work

### ISSUE THREAD

**Issue by dastewa** [MicrosoftDocs/azure-devops-docs#7779] opened 2020-04-01 08:45 UTC
Hi Team,

I'm not sure where I'm going wrong, but modifyOutputPath doesn't seem to work. I'm seeing a similar issue as reported at: https://developercommunity.visualstudio.com/content/problem/950824/dotnetbuild-modifyoutputpath-not-working-as-docume.html and https://github.com/microsoft/azure-pipelines-tasks/issues/11130#issuecomment-566580882, where I'm not seeing a subfolder get created with the project file's name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by WilliamAntonRohm** [comment] 2020-04-03 01:21
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation.  Please upvote the issues you mentioned.  You also welcome to [file a new bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

**Comment by dastewa** [comment] 2020-04-03 03:11
Hi @WilliamAntonRohm, I see your point - thank you! My thought was that it would be an issue for both since the modifyOutputPath section reads: 
> If true, folders created by the publish command will have project file name prefixed to their folder names when output path is specified explicitly in arguments. This is useful if you want to publish multiple projects to the same folder.
But that's not the current behavior users will see. I'll follow up on the other issues - thanks!

**Comment by WilliamAntonRohm** [comment] 2020-05-05 22:00
@dastewa -- D, thank you for clarifying.  My apologies for the delay in responding.

@pulkitaggarwl -- Pulkit, please look into this issue.

**Comment by beatcracker** [comment] 2020-05-07 12:42
Does `modifyOutputPath` work for publishing solutions (`*.sln`)?

**Comment by cxwtool** [comment] 2020-11-24 23:28
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:28 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, doc-bug
