### ISSUE TITLE
Doco fails to mention pipeline triggers require upstream pipeline to create artifacts

### ISSUE THREAD

**Issue by a30001539** [MicrosoftDocs/azure-devops-docs#6847] opened 2020-01-08 00:35 UTC
I am chasing an issue with one pipeline declaring an upstream pipeline as a trigger resource, and part of the fix is the upstream pipeline must create an artifact, see (Pipelines resources)[https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pipeline-resource].

The doco on this page should include that information here too.

See issue on (community portal)[https://developercommunity.visualstudio.com/content/problem/876663/dependant-pipeline-triggering-is-not-working.html] as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#pipeline-triggers)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2020-01-08 06:04
@a30001539 Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
