### ISSUE TITLE
Can the version input be "2.1.1xx"?

### ISSUE THREAD

**Issue by AArnott** [MicrosoftDocs/azure-devops-docs#4413] opened 2019-06-02 00:54 UTC
With .NET Core SDK, it's enough to have the latest of a particular "hundreds" patch version of an SDK. For example, if the global.json requires 2.1.101, then having 2.1.105 is good enough, but 2.1.200 is not acceptable. 
Can we set the version input to 2.1.1xx to indicate we want the latest version in that particular hundreds set?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9660c58-3366-f1be-8380-d6cf1d3c0150
* Version Independent ID: 226a4fd8-bce8-3333-d8d6-7af933c7b060
* Content: [.NET Core Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/dotnet-core-tool-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/dotnet-core-tool-installer.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by plkt** [comment] 2019-08-12 08:07
Thanks for reaching out. Currently 2.1.1x is not supported. We will add this to our backlog.

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
