### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by imran-siddique** [MicrosoftDocs/azure-devops-docs#7605] opened 2020-03-13 18:29 UTC
The link in section https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/azure/build-azure-vm-template?view=azure-devops#create-the-build-pipeline talks about how to author build pipeline and suggests a few things like Publish Artifact. 

But the link https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-tutorial-use-azure-pipelines#create-a-pipeline doesn't talk much about publish artifact.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6a020f-35b0-8d92-9f8b-d05e658236e8
* Version Independent ID: e6208061-614b-a084-9c91-ab2ea12c7e2b
* Content: [Build a VM using RM templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/azure/build-azure-vm-template?view=azure-devops#create-the-build-pipeline)
* Content Source: [docs/pipelines/apps/cd/azure/build-azure-vm-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/azure/build-azure-vm-template.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:29
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:29 UTC
Labels: Pri2, devops-cicd-apps/tech, devops/prod, doc-bug
