### ISSUE TITLE
I don't understand how to push your first dependencies to Azure Artifacts

### ISSUE THREAD

**Issue by aufbakanleitung** [MicrosoftDocs/azure-devops-docs#7112] opened 2020-01-30 09:26 UTC
I have a company specific parent-pom that I need in my Azure Artifacts feed. You're guide states the following under "Install an artifact from your feed":
2. In Azure Artifacts, browse to the artifact that you want to install and copy the contents of the &lt;dependency&gt; element.

How can I browse to the artifact I want to install in a completely empty Artifact Repository? First I have to migrate all my dependencies to Azure artifacts, right? Shouldn't this guide explain how to do this first?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a845b604-ed87-fb81-fcea-3ef43062f445
* Version Independent ID: 45762c44-81aa-9c59-6011-b57e5f8f4796
* Content: [Get started with Maven packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-maven?view=azure-devops#feedback)
* Content Source: [docs/artifacts/get-started-maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/get-started-maven.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment] 2020-02-03 19:18
@aufbakanleitung Thank you for the feedback, we're sorry for any confusion caused by the article steps.

Assigning this to the author for further review.

**Comment by ramiMSFT** [comment] 2020-06-18 21:49
@aufbakanleitung Thank you for your feedback. 

> You're guide states the following under "Install an artifact from your feed":
> 2. In Azure Artifacts, browse to the artifact that you want to install and copy the contents of the <dependency> element.
> 

The paragraph you are referring to is under **Install an artifact from your feed** section. What you need is [How to publish your Maven Artifact](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-maven?view=azure-devops#publish-an-artifact) which is the previous section in that same article.

You can also refer to this [article](https://docs.microsoft.com/en-us/azure/devops/artifacts/maven/publish?view=azure-devops) to learn how to publish your Maven Artifacts from the command line.

**Closed by ramiMSFT** 2020-06-18 21:49 UTC
Labels: Pri2, devops-artifacts/tech, devops/prod, doc-enhancement
