### ISSUE TITLE
documentation for test file format?

### ISSUE THREAD

**Issue by larryclaman** [MicrosoftDocs/azure-devops-docs#5879] opened 2019-10-08 00:14 UTC
Could you document the format of the yaml/json file used for describing the tests?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecd40694-540e-98c1-32ef-87af48fde27d
* Version Independent ID: d1b89b4b-e36e-9cd2-2010-f12b3e2506d6
* Content: [Container Structure Test Task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/container-structure-test-task?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/test/container-structure-test-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/container-structure-test-task.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @Additi
* Microsoft Alias: **admahesh**

**Comment by msebolt** [comment] 2019-10-08 16:41
@larryms  Thank you for the feedback, assigning this to the author now.

**Comment by tashrifbillah** [comment] 2019-10-18 21:13
Following ...

**Comment by RamyTemim** [comment] 2019-11-26 21:51
I think it's the same framework ;-) : 
 - https://github.com/GoogleContainerTools/container-structure-test

**Comment by tashrifbillah** [comment] 2019-11-26 22:06
@RamyTemim, that's right. I figured this out. However, their container-structure-test tool isn't properly set up yet. See my issue [here](https://github.com/MicrosoftDocs/vsts-docs/issues/6067).

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
