### ISSUE TITLE
Capabilities of Script are not well described

### ISSUE THREAD

**Issue by MTomBosch** [MicrosoftDocs/azure-devops-docs#8201] opened 2020-05-05 14:47 UTC
When I enter something into a "script" does it mean that under the hood these commands are just delegated to the respective shell of the executing agent? If that is the case when should I choose Script over Bash (that is available on Win, Lin and MacOS)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 797838e7-f32b-868e-8766-8d96973bf18f
* Version Independent ID: 20c9e62d-56ec-f5a0-c3f9-6f72bf96252e
* Content: [Cross-platform scripting - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/scripts/cross-platform-scripting.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/scripts/cross-platform-scripting.md)
* Product: **devops**
* Technology: **devops-cicd-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment] 2020-05-06 16:26
@MTomBosch Thank you for the question.

Using the **Script** task is really meant to support the Window's CMD platform.  For all other needs you should be using **Bash**.  

For limitations of the **Bash** task on Windows, see [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about) and [Git Bash](https://gitforwindows.org/) for more information.

Assigning this to the author for further review.

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri2, devops-cicd-scripts/tech, devops/prod, doc-enhancement
