### ISSUE TITLE
What does string format actually mean?

### ISSUE THREAD

**Issue by ausfestivus** [MicrosoftDocs/azure-devops-docs#7440] opened 2020-02-27 21:54 UTC
I note that the doco says certificates are downloaded in string format. Can you please explain what this means precisely? Particularly in regards to the handling of eol and nl whitespace character handling?

Im having to pull my cert from a KV, inject the resulting var into a .pem file, then split the private key and crt content into seperate files so my app can then use the two files to setup its TLS config.

Im spending a lot of time building pipeline yaml  to understand the handling of the TLS data and its formatting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69ff8e50-4187-3622-1beb-155f006af5f5
* Version Independent ID: bc56fa96-bded-95f8-39a4-a9e5242db1bf
* Content: [Azure Key Vault task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-key-vault?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-key-vault.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by N-Usha** [comment] 2020-03-04 09:50
When Azure Key vault task is used for retrieving a certificate, it is stored as a string, from which the pfx needs to be retrieved.  Please refer to [this Azure key vault product documentation](https://docs.microsoft.com/en-us/archive/blogs/kv/get-started-with-azure-key-vault-certificates#retrieve-pfx-file--add-password-back) for more details.

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, doc-bug
