### ISSUE TITLE
Still complicated

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/azure-devops-docs#8117] opened 2020-04-28 12:34 UTC
Hello guys. I read this page and still can not understand timing of all transformations with variables. Could you draw a diagram like ASP Net control lifecycle so everyone could understand when template is unwrap, when runtime variables take place, when ordinary variables begin to works and most important how it all ties together?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment] 2020-04-29 17:57
@VerdonTrigance We'll take a look at adding a chart. In the meantime, the [Pipeline run sequence article](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runs?view=azure-devops#process-the-pipeline) may be helpful.

**Comment by akempe** [comment] 2020-04-30 05:59
Please also detail parameter lifetime in relation to the variable lifetime in this chart to help #8101

**Comment by akempe** [comment] 2020-04-30 06:26
@juliakm that page is good, and the diagrams helpful, but we are hitting too many edge cases where variables/parameters don’t behave/aren’t available as expected. 

Please consider these contexts:

- variables defined outside the yaml (secrets and overridable ones - notably in case of cli triggering)
- variables defined within the yaml, but at different points
  - top level scope
  - stage/job/etc scopes
  - how does the shorthand job/stage definitions affect scope (ie. you don’t have to define a stage, how does this affect variable/parameters definitions/scope/expansion
-  parameters whose values are passed into the pipeline vs their defaults

I assume at some point we will be able to specify parameter values from the cli - if not, this is a major oversight. Understanding this additional context is important too given that variables have odd behaviour when coming from outside the yaml. 

Thanks! 😌

**Comment by sdg002** [comment] 2020-05-07 22:29
This works. But, I had to spend over 30 minutes to get it working. Microsoft should consider simplifying so that developers can better utilize their in building solutions which bring value to the end customer.

E.g. The expressions for capture an output variable for multiple stages does not have to be so complex. The classic UI should provide tabular data entry which will let the user to specify the output environment variable names and their respective values using PowerShell variables.

The UI should be intuitive enough so that me as the Devops can get it right in the first attempt and move on to other tasks.

Thank you

**Comment by VerdonTrigance** [comment] 2020-05-18 12:38
> This works. But, I had to spend over 30 minutes to get it working. Microsoft should consider simplifying so that developers can better utilize their in building solutions which bring value to the end customer.
> 
> E.g. The expressions for capture an output variable for multiple stages does not have to be so complex. The classic UI should provide tabular data entry which will let the user to specify the output environment variable names and their respective values using PowerShell variables.
> 
> The UI should be intuitive enough so that me as the Devops can get it right in the first attempt and move on to other tasks.
> 
> Thank you

Yeah, it was always like that in Microsoft - they do something not for those who use it but for themself. 
I'm looking another solution from different providers. I am tired to struggling with MS.

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri1, devops-cicd-process/tech, devops/prod, doc-enhancement
