### ISSUE TITLE
No 'Configure' step, container registry dropdown empty

### ISSUE THREAD

**Issue by BenjaminWFox-Lumedic** [MicrosoftDocs/azure-devops-docs#8318] opened 2020-05-14 00:35 UTC
Two notes:

1. When I ran through the setup, the 'Configure' tab never appeared. It went straight to 'Review'.

2. When I tried to add a 'Docker' option, the 'Container Registry' Dropdown was empty. I had to go to "Project Settings &gt; Service conenctions" and explicitly add the container repository I wanted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ba2ebe-27c4-111b-18b4-0192d8c3fb3a
* Version Independent ID: f48fdf00-e04f-b406-93f3-20b7fad568be
* Content: [Build and push to Azure Container Registry - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/acr-template?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/containers/acr-template.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/containers/acr-template.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri1, devops-cicd-ecosystems/tech, devops/prod, doc-bug
