### ISSUE TITLE
Template reference - Variables Template is incorrect

### ISSUE THREAD

**Issue by cbb330** [MicrosoftDocs/azure-devops-docs#6878] opened 2020-01-09 20:34 UTC
1. Note says: 'to use variable templates, you must use sequence syntax.' This is not correct and the mapping syntax works as well for defining variables.
2. More clarification is needed on using template variables as I can import a template, and reference variables with regular variable syntax: $() rather than ${{ variable.key }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#variable-templates)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cbb330** [comment] 2020-01-09 21:12
Thinking more on 1., perhaps the note should specify that including the template itself must be sequence syntax; however, variables defined within the template can follow mapping syntax.

**Comment by msebolt** [comment] 2020-01-10 17:13
@cbb330 Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
