### ISSUE TITLE
Installation of agent missing unzip as dependency for certain deployment tasks

### ISSUE THREAD

**Issue by dariuszparys** [MicrosoftDocs/azure-devops-docs#4843] opened 2019-07-12 05:48 UTC
When configuring the agent on a custom machine as described above there are still deployment tasks that need dependencies that are not installed by default. In my case I used Ubuntu 18.04 LTS and I'm doing a chart deployment with Helm. Downloading helm and doing `helm init` requires the package `unzip` which is not installed by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a Azure Pipelines agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
