### ISSUE TITLE
Script to select iOS SDK is vague

### ISSUE THREAD

**Issue by Gaisuru** [MicrosoftDocs/azure-devops-docs#6390] opened 2019-11-15 18:58 UTC
1. To select a Xamarin SDK, you input a Mono Version? How backwards is that? You should input the version of the SDK you want.
2. The mac os image documentation just has a list of mono version and a list of Xamarin SDK versions. It does not tell you which versions correlate so you can try to select the version of Xamarin that you want.
3. The image should also tell you what the default mono and ios sdk is like it does for default version of xcode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=designer&viewFallbackFrom=azdevops#feedback)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
