### ISSUE TITLE
tf [vc] branch /notes and/or /recursive documentation: missing or wrong

### ISSUE THREAD

**Issue by per-ok** [MicrosoftDocs/azure-devops-docs#13412] opened 2023-06-17 10:04 UTC
The `tf branch /notes` parameter is only mentioned when running  `tf branch /?`.  `/recursive`  is not mentioned there.
The `tf branch /recursive` parameter is only mentioned  on this page.  Not when running the help command.

What is correct, missing or wrong?

I am running TF.exe version 17.5.33417.12 installed via the VS 2022 installation on Windows 11.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 761dc0a7-a74a-5e1b-1f38-d3f5a9238844
* Version Independent ID: eea02d4b-a9d1-f5fb-aa60-ced3c3274991
* Content: [Branch TFVC command - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/tfvc/branch-command?view=azure-devops)
* Content Source: [docs/repos/tfvc/branch-command.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/tfvc/branch-command.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-tfvc**
* GitHub Login: @MaximMalygin
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment] 2023-06-19 06:47
Duplicate of #13414

**Closed by WilliamAntonRohm** 2023-06-19 06:47 UTC
Labels: duplicate, cba, Pri2, azure-devops-repos/svc, azure-devops-repos-tfvc/subsvc
