### ISSUE TITLE
Does the step template support the common properties like condition?

### ISSUE THREAD

**Issue by johnbooze** [MicrosoftDocs/azure-devops-docs#7258] opened 2020-02-12 21:43 UTC
Under the steps section (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#steps) it says "All steps, regardless of whether they're documented in this article, support the following properties" and lists common properties like displayName and condition.

However, when I try to use a common property like displayName with the "template" step I get an error: "Unexpected value 'displayName''".  Does the step template support the common properties?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#template-references)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by lvlie** [comment] 2020-03-20 11:08
Unfortunately it doesnt seem to support "condition", which I would really like to use on a template inclusion (otherwise I would have to do a conditional job, but I would have to include a build matrix twice as that is not templatable afaik)...

Any news on this?

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
