### ISSUE TITLE
What happen to to Manual build Trigger documentation?

### ISSUE THREAD

**Issue by SimonShor** [MicrosoftDocs/azure-devops-docs#7027] opened 2020-01-22 21:46 UTC
Can not longer find how to manually trigger a pipeline ?  If a Stage is set to Manual Trigger, I can no longer find documentation of how to trigger/run it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e313c5-9120-9172-bc27-c21d10fcd5ae
* Version Independent ID: 1a837182-591f-3cbc-1632-7b50d857b13c
* Content: [Release triggers for stages, branches, and pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by JTravis76** [comment] 2020-04-22 13:38
* Click `Create a release`. All stages will be disabled (light gray). Select artifact, then click Create button. This will create a blank release ready for deployment.
* Click the newly created Release-##. Mouse-over the stage, click Deploy button that appears. Or click `+ Deploy` button in menu. Select the stage(s). Click Deploy

These are the steps in my on-premise version

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
