### ISSUE TITLE
*dev.azure.com vs *.dev.azure.com

### ISSUE THREAD

**Issue by Calidus** [MicrosoftDocs/azure-devops-docs#6377] opened 2019-11-14 21:35 UTC
URL: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops

The documentation in the url above lists both "*dev.azure.com"  and "*.dev.azure.com". Is this a typo? It has caused some confusion in our organization. 

![image](https://user-images.githubusercontent.com/1683712/68898022-a8b23d00-06fc-11ea-89a5-a4f9df458e19.png)

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri3, doc-bug
