### ISSUE TITLE
Invalid JSON in Release Deployment Completed Sample Payload

### ISSUE THREAD

**Issue by roman-may** [MicrosoftDocs/azure-devops-docs#6945] opened 2020-01-15 14:17 UTC
The Json in the sample payload seems to be invalid.

https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops#sample-payload-5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033d681-9093-547c-20fd-b31183c2bb33
* Version Independent ID: 0d92e3f0-7fb4-57e5-d913-f305a055a819
* Content: [Service hooks event reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops#available-event-types)
* Content Source: [docs/service-hooks/events.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/events.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment] 2020-01-16 07:27
@roman-may Thank you for the feedback, assigning this to the author for further review.

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri2, devops-collab/tech, devops/prod, doc-bug
