### ISSUE TITLE
Provide documentation on exactly what `Enable system diagnostics` does

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/azure-devops-docs#6922] opened 2020-01-13 21:10 UTC
When trying to debug issues with YAML builds it seems like `Enable system diagnostics` is the correct box to check but the docs don't really clarify what it does. Furthermore we already have `system.debug` and now, it appears, `agent.diagnostics` variables that can be set on builds. If I'm creating custom YAML scripts or tasks then which of these variables should I be relying on if I want diagnostics? More specifically which of these, if any, are set when I select `Enable system diagnostics`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e834fd0-59c9-3f45-a09d-88571d94c62e
* Version Independent ID: b798ba39-ef08-55eb-3fa0-731782a1d7e0
* Content: [Troubleshoot builds and releases - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=azure-devops)
* Content Source: [docs/pipelines/troubleshooting.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/troubleshooting.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2020-01-14 17:18
@CoolDadTx Thank you for the feedback, assigning this to the author for review.

**Comment by steved0x** [comment] 2020-05-19 21:33
@CoolDadTx Thank you for this feedback, I am updating this article and will see if I can add more info on exactly what that setting does. I'll keep this issue open until the updates are published.

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement

**Comment by samrueby** [comment] 2022-04-18 18:32
Still very interested in this!
