### ISSUE TITLE
Pipeline and resource identifiers need additional clarity

### ISSUE THREAD

**Issue by stewartadam** [MicrosoftDocs/azure-devops-docs#7276] opened 2020-02-13 18:14 UTC
The page is not clear on terminology used for pipeline references, and how to download an artifact published by another pipeline. 

The [download task](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#download) references "pipeline resource identifier" but there is insufficient detail on what that value is. Is that a value that is user-assigned, or pulled from the pipelines somewhere?

I presume that users are intended to create [pipeline references under the resources](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pipeline-resource) section and refer to that resource in the download task, but [that documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#pipeline-) is also unclear on which values are user-assigned, or need to be pulled from the pipeline definition.

After lots of wasted time and reading from various snippets around the web, I suspect that users need to add a resource pipeline reference, and define their own name for it in the `pipeline` property and use the actual pipeline's name under `source`, and [these](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#pipeline-resource-variables) pipeline resource variables that provide various IDs are made available as a virtue of having a `pipeline` referenced under the `resources`  section, but unused by any of the "IDs" required download tasks:
```
resources
  pipelines:
    - pipeline: my_assigned_name
      source: mypipelineCI
```
Then later, `download` references **my** pipeline reference name, not the pipeline's actual name or identifier:
```
steps:
- download: my_assigned_name
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#download)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by stewartadam** [comment] 2020-11-25 14:44
@WilliamAntonRohm @steved0x Users don't have permissions to re-open issues on this repo, and you should probably configure the bot to not close issues when it's assigned to MSFT :)

**Comment by mijacobs** [comment] 2020-11-25 18:57
@steved0x can you take a look?

**Comment by FH-Inway** [comment] 2021-10-03 11:43
Also stumbled over this today. Kudos to @stewartadam , the issue description helped me defining the download step in my pipeline. The documentation could use some more examples.

**Comment by tkent** [comment] 2022-05-30 00:22
This really needs to be addressed and for the reason the original reporter stated over 2 years ago.

**Comment by mijacobs** [comment] 2022-06-16 23:22
@steved0x, can you take a look? Has this issue been addressed in our yaml schema updates?

**Comment by steved0x** [comment] 2022-06-17 13:26
@stewartadam Sorry that this one has fallen through the cracks. We have made several updates to the documentation to call out that it is the pipeline resource name (user defined in the YAML when configuring the pipeline resource, like `pipeline: userDefinedPipelineID`, that is used later on when referring to that pipeline resource.

Our YAML schema reference has been refactored, and here is the new page for pipeline resource:
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline?view=azure-pipelines

We have also added clarification here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#define-a-pipelines-resource

And here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops#configure-pipeline-resource-triggers

I have 2 small PRs going right now to emphasize this even more, when they publish it will automatically close this issue.

Knowing what label to use when referring to a pipeline in a pipeline resource has been confusing for our customers. IF you find any other spots related to this that could use clarification, please let us know and we'll update them.

Thank you

Steve

**Comment by stewartadam** [comment] 2022-06-17 17:27
Thank you Steve!

**Comment by CodePint** [comment] 2022-11-29 18:24
Still unclear...
https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-download?view=azure-pipelines

```
download

string

Required as first parameter. Specify current, pipeline resource identifier, or none to disable automatic download.
```

**Comment by WilliamAntonRohm** [comment] 2022-11-29 19:24
@CodePint -- George, thank you for your follow-up.  Please explain which part of that description is unclear, and I'll update it.

**Closed** 2022-12-12 05:49 UTC
Labels: devops/prod, devops-cicd/tech, needs-more-info, doc-bug, cba, Pri1
