### ISSUE TITLE
Rename page to Agentless job

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/azure-devops-docs#3947] opened 2019-04-12 13:07 UTC
Given that the current Azure DevOps pipeline editor uses the terminology 'Add an agentless job' on the _releaseDefinition page, and if this is what is meant by this page about Server jobs:

Should this page be renamed from Server jobs to Agentless jobs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb951805-1beb-5f01-344a-8bbe96bd38f2
* Version Independent ID: 5ad8d8fa-e0eb-4f78-ba3a-c1669f7cd5ac
* Content: [Server jobs in Azure pipelines Build and Release - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/server-phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/server-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/server-phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alewis
* Microsoft Alias: **alewis**

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
