### ISSUE TITLE
roles?

### ISSUE THREAD

**Issue by iampeterdaniels** [MicrosoftDocs/azure-devops-docs#6379] opened 2019-11-14 22:37 UTC
Page says: "Click the pool on the left side of the page and then click Roles." .  As mentioned above, there is no pool on eth left side of the page. When I select a pool on the right side of the page, there is no "roles".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6363cd0f-8cbf-2a33-41cc-69ba3295d402
* Version Independent ID: 42156366-e5d7-2e86-b12d-7320067571fb
* Content: [Prepare permissions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/prepare-permissions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/prepare-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/prepare-permissions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment] 2019-11-15 00:59
Related to https://github.com/MicrosoftDocs/vsts-docs/issues/6378

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
