### ISSUE TITLE
Delete all directories in the root folder, except test1 and test2

### ISSUE THREAD

**Issue by iwhp** [MicrosoftDocs/azure-devops-docs#7981] opened 2020-04-17 14:11 UTC
I would like to delete all directories in the root folder, except for 2 (test1 and test2). I have tried several, but I cannot figure out what the syntax should be. Please help! Thankx, Harry

/!({test1,teset2})
*/!({test1,test2})
**/!({test1,test2})

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd0e110-4b14-2d96-f28e-d2d2ef53b966
* Version Independent ID: 76cb1df7-c2c5-2de0-fd14-93175838934f
* Content: [Delete Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delete-files?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/delete-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/delete-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by steved0x** [comment] 2020-04-17 21:27
@iwhp Have you tried: `**/*({test1,teset2})` (although no guarantee....)

Let me find out f this is possible and if so what is the syntax, and we'll get an example added.

**Comment by iwhp** [comment] 2020-04-18 07:15
Thankx Steve! 
Yes I have tried `**/*!({test1,test2})`, same issue, **all files and directories are delete**.

**Comment by Hyperdingo** [comment] 2020-04-21 11:04
Documentation is wrong, syntax is:
!(test1|test2)

**Comment by iwhp** [comment] 2020-04-21 11:37
Perfect! Thankx a lot! Harry

**Comment by dominik-weber** [comment] 2020-04-25 09:34
thanks a lot @Hyperdingo ! :) why is this issue closed? the documentation is still wrong @vtbassmatt

**Comment by vtbassmatt** [comment] 2020-04-27 13:01
Thanks @dominik-weber - the original issue filer closed it. @steved0x can you fix this one?

**Comment by diptejsaner** [comment] 2020-05-13 22:53
@steved0x Please add more examples for matching folders. I too spent a lot of time into figuring out the regex.

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod
