### ISSUE TITLE
Cannot use the Copy Files over SSH task to deploy to Solaris 11.4 servers

### ISSUE THREAD

**Issue by egoicovici** [MicrosoftDocs/azure-devops-docs#4027] opened 2019-04-22 15:14 UTC
I cannot use the "Copy Files over SSH" Azure DevOps task inside a release pipeline to deploy artifacts to Solaris 11.4 servers via SSH. I have successfully used this Azure DevOps task to deploy files to Solaris 10. But when using it against Solaris 11, the task freezes indefinitely without any debug information (when System.Debug variable is set to true inside the release pipeline).

After further investigations on this issue, it seems that this problem occurs only when SSH server identifies itself with a banner string that ends with whitespaces. This problem has been fixed in [this commit](https://github.com/mscdex/ssh2-streams/commit/09c5884eccd702eb0723b319966c8018d9e06fde) inside the ssh2-streams javascript library on which the Copy Files Over SSH task depends to. This changeset has been incorporated in **ssh2-streams v0.1.20** .  But the Copy Files Over SSH Azure DevOps task currently uses [scp2](https://github.com/spmjs/node-scp2) version 0.5.0 which depends on [ssh2](https://github.com/mscdex/ssh2) version 0.5.4 which uses ssh2-streams version 0.1.15, therefore this bug is present.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89132320-da86-8a4e-4468-cf651561892c
* Version Independent ID: 4946284d-9666-4a15-9e03-72377693ecb0
* Content: [Copy Files Over SSH task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/copy-files-over-ssh?view=azure-devops#is-this-task-supported-for-target-machines-running-operating-systems-other-than-linux)
* Content Source: [docs/pipelines/tasks/deploy/copy-files-over-ssh.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/copy-files-over-ssh.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by egoicovici** [comment] 2019-04-22 15:21
The [scp2](https://github.com/spmjs/node-scp2) javascript library is not actively maintained thus there were no recent releases, but if you take a look on its repository, its dependency to the **ssh2** library has been updated from version 0.5.4 to version 0.6.0, and the **ssh2 v0.6.0** depends on **ssh2-streams v0.2.0** , thus includes the bugfix for the problem described above.

**Comment by egoicovici** [comment] 2019-04-22 15:26
On the other hand the **[SSH Deployment Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/ssh?view=azure-devops)** depends on ssh2 v0.8.2 javascript library, thus I can successfully use this Azure DevOps task to remotely run commands on a given Solaris 11.4 server.

The reported problem occurs only for the **Copy Files Over SSH** task.

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
