### ISSUE TITLE
Missing Task in documentation

### ISSUE THREAD

**Issue by Hazmes** [MicrosoftDocs/azure-devops-docs#5175] opened 2019-08-08 11:17 UTC
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops

The Doc for Azure IoT Edge Tasks in DevOps specifies 3 Tasks:

- Build module Images
- Push module Images
- Deploy to IoT Edge devices

There are no other IoT Edge Tasks defined here as far as I could tell (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=azure-devops)

In Release Pipelines, there is another Task, called 'Generate Deployment Manifest'
What is this Task for and how is it different from Deploy to IoT Edge devices.

![image](https://user-images.githubusercontent.com/26164958/62699018-d0e41e80-b9de-11e9-818e-52398d082822.png)

**Comment by cxwtool** [comment] 2020-11-24 23:40
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:40 UTC
Labels: Pri3, doc-bug
