### ISSUE TITLE
dependsOn type & "*list" param examples

### ISSUE THREAD

**Issue by mmisztal1980** [MicrosoftDocs/azure-devops-docs#7559] opened 2020-03-10 15:22 UTC
This page fails to illustrate cases where the `dependsOn` parameter is dependent on multiple dependencies.

- What if `dependsOn` was to be provided from a template param
- What would be the desired type?
- Please provide examples of jobList usage
- Please provide examples of deploymentList usage
- Please provide examples of stageList usage 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops#parameter-data-types)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by chowarth** [comment] 2020-03-30 14:43
I absolutely agree that there needs to be some examples here regarding different types, specifically `*list` types. After a bit of trial and error I realised that you can do this by setting `object` as the type, and, as that will accept any YAML structure you can pass an array to it e.g.

#### Parameter
- name: dependsOn
  type: object
  default: []

#### Usage
- `dependsOn: [ 'PreBuild', 'UnitTests']`

**Comment by mmisztal1980** [comment] 2020-03-31 18:53
that's a nice hint! I'll try it out

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri1, devops-cicd-process/tech, devops/prod, doc-bug

**Comment by bd-clara** [comment] 2022-05-30 08:59
Should be in examples please reopen
