### ISSUE TITLE
Delete slot

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/azure-devops-docs#6969] opened 2020-01-17 09:23 UTC
This doc needs to be updated to mention that you can also delete slots.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f07461b2-a8a2-ec6f-769b-14b384777be3
* Version Independent ID: 2c72f09d-b198-461c-fc0d-1c3bd0a870c4
* Content: [Azure App Service Manage task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-app-service-manage?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-app-service-manage.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-app-service-manage.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment] 2020-01-18 01:15
@dazinator Thank you for providing feedback to Microsoft.

Assigning this to the author for further review.

**Comment by RoopeshNair** [comment] 2020-01-20 08:00
We encourage contributions, please do submit changes that can improve the documentation.

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement, help wanted

**Comment by dazinator** [comment] 2020-11-25 10:42
think this is still an issue unless - I am unable to "re open" though.

**Comment by mijacobs** [comment] 2020-11-25 18:44
@dazinator: We accept contributions--if you have the info that needs added to the doc, can you open a pull request against the article? We have a team standing by to review and accept PRs.
