### ISSUE TITLE
Cannot navigate to an https url.

### ISSUE THREAD

**Issue by MarkKharitonov** [MicrosoftDocs/azure-devops-docs#6819] opened 2020-01-05 00:40 UTC
Following the documentation does not work.
Please, see https://stackoverflow.com/questions/59587973/docker-unable-to-navigate-to-a-web-site-using-https OR https://social.msdn.microsoft.com/Forums/en-US/a64a99f2-b761-4ce3-b70e-2b2711c233f6/how-to-visit-a-url-using-https-from-a-windows-container?forum=windowscontainers

I have a feeling that no one in the whole world uses Windows Containers, at least not on Windows 10. Because no example I find on the internet works as expected.

**Comment by msebolt** [comment] 2020-01-06 21:47
@MarkKharitonov Thank you for the feedback and apologies for the documentation issues.

Please provide a link to document in question and we will assign this to an author for review.

**Comment by MarkKharitonov** [comment] 2020-01-07 03:51
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops

When following the guide I had these problems:

1. Downloading agent failed because of the presence of zscaler in our environment. To make it work one needs to import the zscaler root certificate into the LocalMachine\Root certificate store in the container.
1. The user which PAT is used must be able to create agent pools and register agents. The documentation should emphasize it.

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri3, doc-bug
