### ISSUE TITLE
No docs on additionalCodeCoverageFiles input

### ISSUE THREAD

**Issue by bartduncan** [MicrosoftDocs/azure-devops-docs#8122] opened 2020-04-28 17:25 UTC
Documentation of the additionalCodeCoverageFiles optional input is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by avilde** [comment] 2020-05-13 08:17
I tried to use this argument, doesn't impact the result.
It's a pity that there is no option to merge 2 cobertura reports into one and publish the result.

IMHO, the 2 reports are a common use case:
1) back-end code coverage report (.NET Core tests -> cobertura)
2) front-end code coverage report (create react app -> jest -> cobertura)

Only one of them can be published though.

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, doc-bug

**Comment by georgelviv** [comment] 2021-01-08 12:01
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops

Seems like no any updates related to `additionalCodeCoverageFiles` argument
