### ISSUE TITLE
What does the 'diagnosticsEnabled' option do?

### ISSUE THREAD

**Issue by jimmylewis** [MicrosoftDocs/azure-devops-docs#3838] opened 2019-04-02 16:41 UTC
It's listed in the YAML snippet, but there's no explanation of what this does.  Does it collect diagnostic logs, and if so where?  Output to the console session (build logs)?  It's not clear that this is equivalent to the `--Diag` parameter for vstest.console.exe, since that takes a file path and trace level, not a boolean.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by polszewski** [comment] 2019-05-29 11:55
Any news on this one?

**Comment by randyram-at-ms** [comment] 2019-08-02 20:59
I'd like an answer to this too.

**Comment by PBoraMSFT** [comment] 2019-12-06 08:37
@steved0x - sent you a mail with details on the fix required. Can you please help with updating the doc?

**Comment by cxwtool** [comment] 2020-11-24 23:45
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:45 UTC
Labels: Pri1, devops-cicd/tech, devops/prod

**Comment by xt1** [comment] 2021-04-21 14:33
Would like this re-opened and answered.


> **diagnosticsEnabled** When this option is checked, a sequence XML file is generated and attached to the test run. The sequence file contains information about the sequence in which tests ran, so that a potentially culprit test can be identified.Default value: false

Where is the file? What's it called - how do we collect it? 

> **collectDumpOn**

Same question: Where is the dump file generated and how are we supposed to collect it?
When a test run times out because of some deadlock in the system-under-test, this would be suuuper useful - but nothing in the logs hints at if a dump is generated, and where it might be.
