### ISSUE TITLE
How do you create jenkins service hook 

### ISSUE THREAD

**Issue by MSIH** [MicrosoftDocs/azure-devops-docs#3189] opened 2019-01-30 22:08 UTC
i am still not clear how to create a jenkins service hook. what json will i need to pass to create service hook url?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 274c7cc8-3496-59a2-b9ca-43da778b1b62
* Version Independent ID: ae4f66ff-46a6-5b1c-365b-0d869d66cd93
* Content: [Service hooks consumers for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/service-hooks/consumers?view=azdevops#jenkins)
* Content Source: [docs/service-hooks/consumers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/consumers.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-collab/tech, devops/prod, doc-bug
