### ISSUE TITLE
.Net Sample code Error while Building Pipleline

### ISSUE THREAD

**Issue by smabbaszaidi** [MicrosoftDocs/azure-devops-docs#3713] opened 2019-03-21 21:08 UTC
Got error while adding sample code (.net) from GitHub 
**Bash wrote one or more lines to the standard error stream..

How to fix this for sample code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f7a23b-ebd4-af3e-68a2-275f7e45c33e
* Version Independent ID: f552a18c-ba29-00d4-03b6-254d7556d319
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=azure-devops#feedback)
* Content Source: [docs/pipelines/get-started-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by sdbzcm** [comment] 2019-03-22 18:45
Hi,did you fix it?I got the same issue with you.

**Comment by smabbaszaidi** [comment] 2019-03-22 19:38
no :(

**Comment by smabbaszaidi** [comment] 2019-03-22 19:39
I am expecting solution from MS personals have worked on this sample....

**Comment by sdbzcm** [comment] 2019-03-22 21:45
Hope you can solve it soon.I tired to add another sample and it worked,but for the .net core it always showed this error no matter how many times I ran it.

**Comment by sdbzcm** [comment] 2019-03-22 21:47
BTW, can you go to next steps without fixing this issue?

**Comment by I-Sokolov** [comment] 2019-03-23 16:44
You can comment dotnetcore-tests/UnitTest1.cs:line 35 to suspend the error

**Comment by sdbzcm** [comment] 2019-03-25 05:22
After I comment dotnetcore-tests/UnitTest1.cs:line 35,it showed below:
UnitTest1.cs(37,2): error CS1513: } expected [/home/vsts/work/1/s/dotnetcore-tests/dotnetcore-tests.csproj]
##[error]Bash exited with code '1'.

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
