### ISSUE TITLE
Some confusing bits

### ISSUE THREAD

**Issue by iampeterdaniels** [MicrosoftDocs/azure-devops-docs#6378] opened 2019-11-14 22:35 UTC
"Click the pool on the left side of the page and then click Roles." - there is no pool on the left side of the page.  There are two pools on the right side - "Azure Pipelines" and "Default".

Also, our URL is &lt;org&gt;.visualstudio.com.  Not "either your Azure DevOps organization (https://dev.azure.com/{your_organization}) or your Team Foundation Server web portal (https://{your-server}:8080/tfs/)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6363cd0f-8cbf-2a33-41cc-69ba3295d402
* Version Independent ID: 42156366-e5d7-2e86-b12d-7320067571fb
* Content: [Prepare permissions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/prepare-permissions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/prepare-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/prepare-permissions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
