### ISSUE TITLE
Which branch is deployed to https://docs.microsoft.com?

### ISSUE THREAD

**Issue by pascalberger** [MicrosoftDocs/azure-devops-docs#2476] opened 2018-11-17 22:55 UTC
I tried to fix something in the [feature timeline](https://docs.microsoft.com/en-us/azure/devops/release-notes/) for the November 12th notes, but the https://github.com/MicrosoftDocs/vsts-docs/blob/master/release-notes/index.md file on the `master`  branch contains only the notes until the October 22nd deployment.

**Comment by steved0x** [comment] 2018-11-30 22:16
@pascalberger We are having an issue right now with the syncing between our internal private repo, and this public repo which is for customers to submit feedback issues and PRs. All of the customer changes up through about 2 weeks ago should be merged into our private repo, and live at docs.microsoft.com. However this public repo is about a couple of weeks behind. Our ops team is going to get it fixed and they should be in sync soon.

If you point me to the PR where you made your change, I will follow up and see what happened to it, and do what I can to get it published. Did you make the PR in our internal repo (are you an MS employee?) or did you make it here in this public GitHub repo?

**Comment by pascalberger** [comment] 2018-12-01 08:39
@steved0x I didn't made the PR as the file in this repo is outdated and didn't contain the parts I wanted to fix (I'm not an MSFT Employee).

**Comment by pascalberger** [comment] 2019-03-01 11:16
@steved0x Before this is automatically close, has this issue been solved in the meantime?

**Comment by thomps23** [comment] 2019-05-13 20:49
@steved0x Can you review this and see if the issue you last mentioned was resolved and the expected update appeared, or what next steps are?

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri3, doc-bug
