### ISSUE TITLE
This documentation just doesn't work

### ISSUE THREAD

**Issue by adriantorrie** [MicrosoftDocs/azure-devops-docs#3812] opened 2019-03-29 09:16 UTC
`source activate &lt;env_name` commands result in "activate: No such file or directory", with subsequent commands which rely on environment activation failing with "command not found errors".

Adding conda to the path doesn't fix anything, nor does taking ownership of the folder.

I'm adding back the deprecated "Conda envrionment" task until this rubbish is fixed.

Wasted 4 hours.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b99fb08-2474-be71-62db-cbafec749cb3
* Version Independent ID: af525f70-f636-4fb2-e4e6-03a2dd759c24
* Content: [Run pipelines with Anaconda environments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/anaconda?view=azure-devops&tabs=ubuntu-16-04#add-conda-to-your-system-path)
* Content Source: [docs/pipelines/languages/anaconda.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/anaconda.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **brcrista**

**Comment by bee-keeper** [comment] 2019-04-01 18:05
Can confirm..

##[error]'conda' is not recognized as an internal or external command,
##[error]operable program or batch file.

**Comment by kim0** [comment] 2019-07-03 20:23
Hi @steved0x .. I think I'm hitting this too .. Any workaround till it is fixed ?

**Comment by dhruv-balakrishnan** [comment] 2019-08-13 05:32
For those who are having this issue, I've stumbled upon a work around. 

1. Use the depricated Conda Environment Task. I wasn't able to create environments correctly here, so all I did was let it add to the path and update to the latest version of Anaconda.

2. Get a CMD task, create your environment. For me, I have a .yml file with the anaconda and pip requirements, so I just run conda env create -n <name> -f <Path to env file>

3. If you have any other packages in the env file that you need to install, you can install packages to your environment with C:\Miniconda\envs\<envname>\Scripts\pip

4. Run your python files. You don't need to activate the environment. I didn't have to. I tried figuring out how to activate it - you need to init a different shell - but I was too tired to try anything more. 

Hope this helps.

**Comment by RyanPicco** [comment] 2020-02-27 22:18
Here is 1 liner workaround...

You can activate the env by providing full paths to condas base install and the env like so...
source <path to base conda>/bin/activate <path to env>/<env name>
like... source /base/conda/miniconda3/bin/activate /my/home/.conda/envs/myenvname

**Comment by ShadenSmith** [comment] 2020-05-06 16:18
I can confirm that the fix from @RyanPicco works and was needed for my environment.

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri2, devops-cicd/tech, devops/prod
