### ISSUE TITLE
Clarify that "edit" will create a release if not existing yet

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/azure-devops-docs#4263] opened 2019-05-19 14:33 UTC
Travis CI / Appveyor don't have the concept of "create" or "edit", they just do what would be "createOrEdit". Since on Azure Pipelines I need to decide between "create" or "edit", I was in a dilemma, since really I just want to "createOrEdit", as multiple jobs are pushing their artifacts to a GitHub release, and whoever is the first should then also create the (draft) release.

However, I found: https://github.com/microsoft/azure-pipelines-tasks/blob/c4dc3ed710b1c36f4756e21eee13c53f14e3f3d2/Tasks/GitHubReleaseV0/main.ts#L74-L83

Which means: If I use "edit", then it behaves like create or edit, which is exactly what I want. Can this be clarified in the docs?

EDIT: It looks like, though, if I use "edit", then I also have to specify "tag" manually, see [code](https://github.com/microsoft/azure-pipelines-tasks/blob/c4dc3ed710b1c36f4756e21eee13c53f14e3f3d2/Tasks/GitHubReleaseV0/operations/Utility.ts#L230-L240). I could use `$(Build.SourceBranchName)` I guess as work-around, but it all feels a bit klunky. Maybe there should be a separate "createOrEdit" action with support for "auto" tag source?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b12d2c4-f871-1d14-0c16-91e58fb1130b
* Version Independent ID: 6b9e1d67-f303-7445-e573-830309ba49a4
* Content: [GitHub Release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/github-release.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/github-release.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
