### ISSUE TITLE
az account show

### ISSUE THREAD

**Issue by winstonhenke** [MicrosoftDocs/azure-devops-docs#5898] opened 2019-10-08 22:59 UTC
Using Azure CLI v2.0.2

If I print `az account show` from a script it seems to print the user context that triggered the pipeline rather than the service principle linked to the azureSubscription. But the the SP does seem to be used since I had a script that was failing until I updated some access policies on the SP after which it succeeded. 

I would have expected `az account show` to print the SP details. Is this behavior expected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
