### ISSUE TITLE
Step 4 needs RSA key coverage

### ISSUE THREAD

**Issue by carct** [MicrosoftDocs/azure-devops-docs#7944] opened 2020-04-15 14:14 UTC
At step 4 of creating the VMSS (the actual az cli command) there should be information that you need to either:
a) provide RSA key
b) use  --generate-ssh-keys command arg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment] 2020-05-01 21:23
@carct These aren't required for Scale set agents in Azure pipelines, can you share more details of your scenario? If we provide a note here and a link to `az vmss create` would that provide the required information?

**Comment by carct** [comment] 2020-05-21 11:35
> @carct These aren't required for Scale set agents in Azure pipelines, can you share more details of your scenario? If we provide a note here and a link to `az vmss create` would that provide the required information?

![image](https://user-images.githubusercontent.com/34916068/82555298-32d9d300-9b70-11ea-94b7-aae550e5219b.png)
in the instructions, you give this command as per screenshot, this will not work! 
you need to either provide a RSA key or use the command argument --generate-ssh-keys

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri1, devops-cicd-agents/tech, devops/prod, doc-bug
