### ISSUE TITLE
WriteHost missing from PS samples

### ISSUE THREAD

**Issue by sbparsons** [MicrosoftDocs/azure-devops-docs#5907] opened 2019-10-09 12:05 UTC
I have just come here to learn more about logging commands and I see that at the beginning of the article the WriteHost preceeds the actual command to be issued.
I'm assuming this is always required, though the later samples just show the command (starting with ##vso[...)
Am I correct in assuming that the WriteHost is assumed to be there in the latter samples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=powershell#feedback)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **phwilson**

**Comment by tkawchak** [comment] 2020-01-28 17:03
I just had this issue too.  It would be good to include the Write-Host in all powershell samples.  I just verified this is needed for the ##vso[task.uploadsummary] logging command.

**Comment by cxwtool** [comment] 2020-11-24 23:38
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:38 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
