### ISSUE TITLE
Key Vault variable

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/azure-devops-docs#7355] opened 2020-02-20 17:31 UTC
The document says: "Values are retrieved as strings. For example, if there is a secret named connectionString, a task variable connectionString is created".
Isn't the task variable actually $(connectionString)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51c58837-c915-0dad-ec76-716dd45be7bb
* Version Independent ID: 3212c33a-fdbd-688a-5670-079d858a97ec
* Content: [Azure Key Vault task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-key-vault?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-key-vault.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:31
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:31 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
