### ISSUE TITLE
Minimum Docker version requirement

### ISSUE THREAD

**Issue by dferretti** [MicrosoftDocs/azure-devops-docs#2987] opened 2019-01-11 02:05 UTC
In the Requirements section, can you add the minimum docker version? I tried testing a container job on an old build server and got this error: 
`Min required docker server version is '17.12', your docker ('/usr/local/bin/docker') server version is '17.9.1'`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by gabrielfsousa** [comment] 2019-03-16 01:54
i have the same problem ?
tried the solution docker in docker, but had other problem....

**Comment by KyleRAnderson** [comment] 2019-03-18 19:20
Yes, please help. My docker server version used to be at 18.x.x and for whatever reason (nobody did anything) it's now at 3.x.x and builds are failing because of this.

**Comment by mloskot** [comment] 2019-05-14 17:36
I'm being hit by the same bug:

![image](https://user-images.githubusercontent.com/80741/57719190-d41c7800-7644-11e9-91ba-4e21760c00d2.png)

```
jobs:
  - job: 'Documentation'
    pool:
      vmImage: 'ubuntu-16.04'
    container:
      image: osgeo/proj-docs
      options: --privileged
...
```

**Comment by andyjlewis** [comment] 2019-07-01 19:12
Thank you for reporting this issue. I'm sorry for the long delay in response. I was out of the office for a long period of time earlier this year.

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
