### ISSUE TITLE
General confusion

### ISSUE THREAD

**Issue by phil-lgr** [MicrosoftDocs/azure-devops-docs#2721] opened 2018-12-11 02:27 UTC
I read: 

"Installing the Cordova Build task
To setup a Cordova build in Azure Pipelines or TFS 2015, you will need to install the Cordova Build task in your collection.

Azure Pipelines: Simply install the VSTS Extension for Cordova."

Ok and then what? I installed it, but I don't see a cordova option anywhere in Azure Pipelines? :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f13eb3-d83b-f208-30df-77c261061b02
* Version Independent ID: 487dd1ee-b6df-4ba4-3fec-c6ba423185d3
* Content: [Build and Test Cordova Projects - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/archive/apps/mobile/cordova-build?view=vsts)
* Content Source: [docs/pipelines/archive/apps/mobile/cordova-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/archive/apps/mobile/cordova-build.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by phil-lgr** [comment] 2018-12-11 02:36
I don't understand how the Cordova build is supposed to be accessed? Do I need VS Studio?

**Comment by DavidStaheli** [comment] 2019-03-11 15:27
Keep-alive

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
