### ISSUE TITLE
Needs updating for AML Devops extension

### ISSUE THREAD

**Issue by revodavid** [MicrosoftDocs/azure-devops-docs#4790] opened 2019-07-09 10:12 UTC
This article is out of sync with README.md in https://github.com/MicrosoftDocs/pipelines-azureml . Specifically, it doesn't mention use of the Machine Learning DevOps extension for Azure Pipelines, and doesn't describe how to set up a service connection for the AML Service workspace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa0194a9-ffa7-fa79-e6c7-8ecb5e8c93ec
* Version Independent ID: 4f5a9f04-b629-b8b1-1332-9260c95d13b7
* Content: [Azure Machine Learning service training and deployment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-machine-learning?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-machine-learning.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/azure-machine-learning.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @jpe316
* Microsoft Alias: **jordane**

**Comment by charleswm** [comment] 2019-10-03 19:38
+1 especially about the part about setting up the service connection.

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
