### ISSUE TITLE
Give an example for a directory with spaces.

### ISSUE THREAD

**Issue by Eddie-Hartman** [MicrosoftDocs/azure-devops-docs#6923] opened 2020-01-13 21:31 UTC
Please add an example for pattern matching a directory with spaces. I've tried WebHelp/Online\ Help/** as an example, but it didn't seem to match anything. I'm not asking for specific help here, I'm just saying that an example like this should exist in the documentation since directories with spaces are a common use case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd54e81-9a0c-c5e5-fb89-9534372805ff
* Version Independent ID: f3d49618-32d7-0abc-1c33-8211eb7dd073
* Content: [File matching patterns reference - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops)
* Content Source: [docs/pipelines/tasks/file-matching-patterns.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/file-matching-patterns.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2020-01-14 17:31
@Eddie-Hartman Thank you for the feedback, assigning this to the author for review.

The document references the use of [glob](http://man7.org/linux/man-pages/man7/glob.7.html), which means spaces would be referenced using brackets, denoted as `[ ]`.

**Comment by Eddie-Hartman** [comment] 2020-01-14 17:39
I figured it out. In my case, I simply needed 'WebHelp\Online Help\**' as spaces aren't considered special characters for these filters. The reason I used the example I gave (escaping the space character as '\ ') is that spaces are considered special characters that need escaped for some matching patterns. The documentation does not say that spaces are special characters or not. It just doesn't address them in any way.

Later I could make a pr adding a simple example, but I'm not sure if there are any "gotchas" that I should point out.

**Comment by jbeesonnuva** [comment] 2020-04-02 21:39
What about a directory with spaces and a wild card?

so given 

File Directory-12345/file1.txt
File Directory-12345/file2.txt

Something like !File Directory-*/** should work but it doesn't

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
