### ISSUE TITLE
WebAppKind allowable values and default value

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/azure-devops-docs#7359] opened 2020-02-20 20:31 UTC
The description of the WebAppKind parameter includes a list of allowable values, and specifies a default type, but the default value is not included in the list of allowable values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b648a9b-9a8d-423f-94c9-cb56ec458273
* Version Independent ID: efe57b89-fbac-8a5c-4607-102ebfd57b54
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops#sample-post-deployment-script)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by martingbrown** [comment] 2020-03-08 10:31
I use VS Code to edit these files and the list of values it accepts as valid is completely different to those listed in this article. It says 'Valid values: "webApp", "webAppLinux", "webAppContainer", "functionApp", "functionAppLinux", "functionAppContainer", "apiApp", "mobileApp".'

**Comment by cxwtool** [comment] 2020-11-24 23:31
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:31 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug

**Comment by HughDevlin** [comment] 2020-12-02 21:07
Please re-open this issue.

Please clarify the documentation for the WebAppKind argument.

**Comment by martingbrown** [comment] 2020-12-03 14:25
I don't really get why people use bots to close cases just because of how old they are. Just because no one has bothered to fix the issue does not mean it isn't an issue any more. Basically by closing old issues without giving a reason it gives the impression that no one cares that customers are having issues. I get the impression MS would rather we used GitHub instead of DevOps.

**Comment by HughDevlin** [comment] 2020-12-03 15:58
I am working off of a paid in full subscription. I take time to report an issue with the docs. Agree, MS apparently feels if they can successfully ignore an issue for 6 months they can close it, too. I guess November 2020 was a banner month for doc quality thanks to the efforts of cxwtool. cxwtool is MS's most productive team member.

**Comment by martingbrown** [comment] 2020-12-03 16:13
It wouldn't bother me so if we were allowed to simply reopen the tickets. Howey, all the tickets I've raised that had this happen, I didn't seem to have permission to reopen.
