### ISSUE TITLE
Add NOTE that Artifact Name will not show build artifact if publish was in same pipeline, different phase

### ISSUE THREAD

**Issue by rguthriemsft** [MicrosoftDocs/azure-devops-docs#2436] opened 2018-11-14 00:04 UTC
If you want to download the artifact published by the same build in a different phase, you have to manually type the artifact name.  See https://github.com/Microsoft/azure-pipelines-tasks/issues/8809 for full explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a16bcf-af6c-e278-f0a6-8ec95012ce4a
* Version Independent ID: ae442106-33b3-786f-2158-34eed3fed6e0
* Content: [Download Build Artifacts task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment] 2018-12-13 15:16
@Lovakumar does your team own this task and its docs?  If so, could you please assign this issue appropriately?

**Comment by elbatk** [comment] 2019-02-04 17:21
Hi @lovakumar, do you have a status on this? You may need to be added to this repo to be assigned, @steved0x can help with that :)

**Comment by x10an14** [comment] 2020-02-12 20:52
We are very much interested in how to solve this! Any status?? =) 
@steved0x

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug, help wanted
