### ISSUE TITLE
AV Exclusions

### ISSUE THREAD

**Issue by chris-moceri** [MicrosoftDocs/azure-devops-docs#3633] opened 2019-03-13 17:45 UTC
Should we have the Windows agent folders excluded from Windows Defender/AV? What is best practice for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
