### ISSUE TITLE
Webpack section seems a bit confused

### ISSUE THREAD

**Issue by bevans-allmeds** [MicrosoftDocs/azure-devops-docs#2953] opened 2019-01-07 23:32 UTC
npx, at least in my experience, is a tool used to run npm package binaries installed locally in a project. If you install webpack globally, you do not need npx. That said, it doesn't seem like a good idea to install webpack globally to build your project, ignoring the version of webpack that should be specified in your package.json.

The YAML and the Designer sections of the documentation appear to disagree here as well, with YAML installing locally and Designer installing globally.

If I were to suggest the ideal way, it would be to run npm install, to install the webpack version specified in the relevant package.json file, then run npx webpack which will run the relevant webpack.config.js. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c99686eb-6c78-0336-1ec3-802a53c9868d
* Version Independent ID: 6eaf1acb-24d4-5bb7-3935-17abe7e59dd9
* Content: [Build, test, and deploy JavaScript and Node.js apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=vsts&tabs=designer#angularjs)
* Content Source: [docs/pipelines/languages/javascript.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/javascript.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
