### ISSUE TITLE
In which folder is the key installed?

### ISSUE THREAD

**Issue by akunaatrium** [MicrosoftDocs/azure-devops-docs#1621] opened 2018-08-30 10:54 UTC
The documentation doesn't tell in which folder the key is installed. I would need to run a Docker container as a subsequent task and mount that folder inside of the container so that the container could get access to a certain machine over SSH.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce9d017-fc43-c904-d94b-87cf91265ffc
* Version Independent ID: ecf3b0b7-6c2c-1cd9-33a9-2cf562932e2b
* Content: [Install SSH Key](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/install-ssh-key?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/install-ssh-key.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-ssh-key.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment] 2019-03-10 18:43
Keep-alive

**Comment by panzer-planet** [comment] 2019-05-27 16:51
This makes almost no sense. How could something simple be made so confusing.

**Comment by cerw** [comment] 2019-06-06 07:24
This is def not solved.

**Comment by davidtom** [comment] 2019-06-20 01:34
> This makes almost no sense. How could something simple be made so confusing.

This is pretty much Azure DevOp's tagline...it would be funny if it wasn't so painful.

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
