### ISSUE TITLE
Replacing UserVoice references in "release notes" page

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/azure-devops-docs#2350] opened 2018-11-05 21:55 UTC
On the release notes page, it talks about UserVoice https://github.com/MicrosoftDocs/vsts-docs/edit/master/release-notes/index.md
I'm guessing most references would get swapped for https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=idea

The reference
>Some features are linked to a blog post and/or UserVoice entry where you can learn more and comment
Is now replaced with https://dev.azure.com/mseng/Azure%20DevOps%20Roadmap/ I think

**Comment by steved0x** [comment] 2018-11-06 14:07
@nschonni I believe that's right, let me verify and I'll do a bulk replace.

**Comment by nschonni** [comment] 2019-02-28 17:05
Shoo Stalebot

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri3, devops-release-notes/tech, devops/prod, doc-bug
