### ISSUE TITLE
Update Service Fabric Manifests task requires Windows Desktop PowerShell

### ISSUE THREAD

**Issue by moikot** [MicrosoftDocs/azure-devops-docs#8166] opened 2020-05-01 15:51 UTC
The fact that ServiceFabricUpdateManifests@2 requires Windows Desktop PowerShell and doesn't work on Linux is not reflected in the documentation.

You'll get the following message if you try to run it on a Linux agent:
```shell
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
##[debug]System.InvalidOperationException: The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
``` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7a355ee-4a55-38b0-d430-ede22728182b
* Version Independent ID: 49ce85aa-224e-544a-edab-cebdb4385fff
* Content: [Update Service Fabric Manifests task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/service-fabric-versioning?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/service-fabric-versioning.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/service-fabric-versioning.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment] 2020-05-06 18:34
@RoopeshNair -- please review [private PR 1379](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1379).

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod
