### ISSUE TITLE
Document "inputMode" property of inputs

### ISSUE THREAD

**Issue by davidcorrigan714** [MicrosoftDocs/azure-devops-docs#4024] opened 2019-04-22 14:21 UTC
As used here:
https://github.com/Microsoft/vsts-extension-multivalue-control/blob/master/vss-extension.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e6cb0ed-c129-901c-10a2-909354aa562f
* Version Independent ID: ceb10d41-b306-0d3f-ccb2-124a3ba69332
* Content: [Add a custom control to the work item form](https://docs.microsoft.com/en-us/azure/devops/extend/develop/custom-control?view=azure-devops)
* Content Source: [docs/extend/develop/custom-control.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/custom-control.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment] 2019-05-22 19:55
Hi @davidcorrigan714, I'm sorry for the delayed response. Thanks for the feedback. I've assigned this issue to @chasewilson. Have a great day!

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri2, devops-ecosystem/tech, devops/prod, doc-bug
