### ISSUE TITLE
Expansion of variables in TaskGroup steps

### ISSUE THREAD

**Issue by jg11jg** [MicrosoftDocs/azure-devops-docs#3501] opened 2019-02-27 19:09 UTC
Can you clarify: "Variables are expanded once when the run is started, and again, at the beginning of each step" - in the context of steps within a task group. 

I have a task group which creates an enviroment variable in one step, then uses that variable as an input in a subsequent step in the same task group.  It seems to me that the variable is NOT getting re-expanded when the task group step starts. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=designer%2Cpowershell)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by jg11jg** [comment] 2019-02-27 19:11
Note: I'm using Visual Designer and setting the variable using powershell ##vso set.taskVariable (have used this in several places just fine, it's only in context of task group that seems I can't get variables defined in one step to be reexpanded in subsequent steps).

**Comment by jg11jg** [comment] 2019-02-27 19:35
scratch this - think it must have been a goof my end (incorrect capitalization of variable I think) - now it's working.

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
