### ISSUE TITLE
Custom destination path

### ISSUE THREAD

**Issue by gpj1** [MicrosoftDocs/azure-devops-docs#7550] opened 2020-03-10 05:28 UTC
Looks like this task downloads the specified file to $(Agent.TempDirectory). Can I specify custom path so that file is downloaded to different location? This saves me from running another script for movement downloaded file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* Content: [Download Secure File task - Azure Pipelines](https://docs.microsoft.com/en-in/azure/devops/pipelines/tasks/utility/download-secure-file?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-secure-file.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by jpdias92** [comment] 2020-03-17 13:40
I have the same requirement, it would make my pipelines a lot cleaner!

**Comment by GizmoMKD** [comment] 2020-03-19 11:41
looking forward for this update!

**Comment by DavidNorena** [comment] 2020-05-12 06:00
any updates on this guys ! ?

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, doc-bug

**Comment by alexcrowdpharm** [comment] 2022-07-08 15:33
This is a basic requirement that should be implemented.
