### ISSUE TITLE
This doc is confusing with respect to signing Android APK

### ISSUE THREAD

**Issue by basher** [MicrosoftDocs/azure-devops-docs#4393] opened 2019-05-30 14:06 UTC
1. I stored "jarsignerKeyPassword" and "jarsignerKeystorePassword" variables in the build definition variables tab, but I have no idea how to set "pathToYourKeystoreFile" as it needs to reference a tab:

![azure](https://user-images.githubusercontent.com/452809/58638715-536ca580-82ed-11e9-9cf6-647fdc59b792.jpg)

2. Secondly, what does "yourKeystoreAlias" relate to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955d694a-7285-45b6-56b9-3a86ddbb0820
* Version Independent ID: 0d226e23-1ddd-f6de-abf7-5b112533ec78
* Content: [Build, test, and deploy Android apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/android?view=azure-devops#feedback)
* Content Source: [docs/pipelines/languages/android.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/android.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **dastahel**

**Comment by basher** [comment] 2019-06-04 10:11
I've now created a blank pipeline without using YAML file, and the "Android Signing" task allows me to reference the variables, and point to my keystore file, etc.

The "Android Signing" page - https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/android-signing?view=azure-devops# - explains everything in much more detail.

**Comment by cxwtool** [comment] 2020-11-24 23:43
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:43 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
