### ISSUE TITLE
No mention of programmatic creation of pools

### ISSUE THREAD

**Issue by techspeque** [MicrosoftDocs/azure-devops-docs#6998] opened 2020-01-20 10:57 UTC
It would be utmost useful to align this page with mentions of the new cli being developed. 

What I am more interested seeing is on how to manage Azure DevOps and more specifically using API/cli to create the agent pools and queues. 

At the moment this being an enterprise product it is quite difficult to do any automation without docs being properly referenced or easily accessible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser#feedback)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2020-01-21 17:47
@techspeque Thank you for the feedback.

Please refer to [Get started with the REST](https://docs.microsoft.com/rest/api/azure/devops) for help on the [Pools](https://docs.microsoft.com/rest/api/azure/devops/distributedtask/pools) and [Queues](https://docs.microsoft.com/rest/api/azure/devops/distributedtask/queues) API.

Or, see [Get started with Azure CLI](https://docs.microsoft.com/cli/azure/get-started-with-azure-cli) for help with the [pool](https://docs.microsoft.com/cli/azure/ext/azure-devops/pipelines/pool) and [queue](https://docs.microsoft.com/cli/azure/ext/azure-devops/pipelines/queue) commands.

Assigning this to the author for further review.

**Comment by techspeque** [comment] 2020-01-22 10:17
@msebolt These are great pointers, thanks for this. 

Where can I get information on the roadmap for az cli support for the support of creation of pools? 

As per docs provided there is no support for `create` or `add` tasks as yet, but there are also no timelines.

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
