### ISSUE TITLE
Clarify that DayOfYear is always 3 digits long

### ISSUE THREAD

**Issue by altxt** [MicrosoftDocs/azure-devops-docs#1599] opened 2018-08-24 13:03 UTC
According to Eddie Chen here https://stackoverflow.com/questions/38058548/build-variable-dayofyear-with-preceding-zeros , $(DayOfYear) always produces a string with leading zeros to make it 3 digits long.
It would be nice if the docs mentioned this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa5a83c-70fd-6925-a8c8-256b21c21a2e
* Version Independent ID: 75f4a136-7245-7878-2953-6b68272fe4ec
* Content: [Build pipeline options](https://docs.microsoft.com/en-us/vsts/pipelines/build/options?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/build/options.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/options.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by altxt** [comment] 2019-03-11 08:40
The documentation did not receive the proposed update yet.

**Comment by larrynburris** [comment] 2019-04-03 21:31
Builds on TFS version 15.105.25910.0 are not producing 3 digits. Any recommendations?

**Comment by jespersh** [comment] 2019-10-14 14:07
The doc is now at https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number

**Comment by cxwtool** [comment] 2020-11-24 23:49
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:49 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug

**Comment by gimlichael** [comment] 2021-03-18 17:50
> The doc is now at https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number

But is it with leading zeros in case of days of year less than 100?
