### ISSUE TITLE
.Net Core Task does not publish code coverage results (maybe on Linux only)

### ISSUE THREAD

**Issue by geofflamrock** [MicrosoftDocs/azure-devops-docs#4934] opened 2019-07-19 11:34 UTC
Hi,

This documentation says that the built in task for .Net Core provides the option to publish code coverage to the pipeline, however it doesn't seem to be publishing the code coverage unless I also use the PublishCodeCoverageResults task. 

I found this line in the source code for the task reference: https://github.com/microsoft/azure-pipelines-tasks/blob/aabd9b04664c43ded7660ad7e9226325bdbeb380/Tasks/DotNetCoreCLIV2/task.json#L134 which seems to indicate that the publication doesn't work on Linux agents (which I am using), only on Windows, is that the case? If so, would it be possible to update this documentation to indicate this please?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabbd5e2-993f-89da-665f-f39ab63d7c42
* Version Independent ID: 493c2582-69a4-1bbe-03b5-0bb5f1d41aed
* Content: [Review code coverage - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops#feedback)
* Content Source: [docs/pipelines/test/review-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/review-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vinodjo
* Microsoft Alias: **vinojos**

**Comment by vinodjo** [comment] 2019-07-30 04:07
Adding @PBoraMSFT to provide the relevant guidance on this

**Comment by urig** [comment] 2020-04-09 11:15
Hello, Can I ask for an update on this issue? @PBoraMSFT ?

**Comment by urig** [comment] 2020-04-09 11:19
@geofflamrock hi. Would it be possible for you to share how you've managed to work around the issue using the `PublishCodeCoverageResults` task? tx 🙏🏻

**Comment by urig** [comment] 2020-04-09 11:35
Found a possible workaround in this SO answer: https://stackoverflow.com/a/60894835/33404

**Comment by urig** [comment] 2020-04-11 19:53
Documentation now states "If you're building on Windows" so I suppose that resolves this issue. I've created an issue in the VS dev community site, asking for Linux support: https://developercommunity.visualstudio.com/content/problem/986995/net-core-task-does-not-publish-code-coverage-resul.html

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
