### ISSUE TITLE
"Two reviewers is an optimal number based on research." link broken?

### ISSUE THREAD

**Issue by Bebo2345** [MicrosoftDocs/azure-devops-docs#3699] opened 2019-03-20 17:49 UTC
The link in the phrase "Two reviewers is an optimal number based on research." is broken.

It is currently pointing to
https://www.microsoft.com/research/publication/convergent-software-peer-review-practices/

It works if it is
https://www.microsoft.com/en-us/research/publication/convergent-software-peer-review-practices/

Maybe it is a good link, it is just https://www.microsoft.com/en-us/research/ is not forwarding correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe168fc3-2ed2-b3e6-ce30-cac721165ceb
* Version Independent ID: 8d63fbd7-12c4-9a94-92f6-969e7eb41037
* Content: [Git branching guidance - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops)
* Content Source: [docs/repos/git/git-branching-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/git-branching-guidance.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cxwtool** [comment] 2020-11-24 23:46
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:46 UTC
Labels: Pri1, devops/prod
