### ISSUE TITLE
reportDirectory Now Useless?

### ISSUE THREAD

**Issue by MarkKoz** [MicrosoftDocs/azure-devops-docs#4605] opened 2019-06-23 03:19 UTC
Since microsoft/azure-pipelines-tasks#9704, coverage HTML is automatically generated. HTML files specified with `reportDirectory` will be ignored. Does this mean this argument is now useless? This behaviour should be documented on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by atariq6298** [comment] 2019-07-18 13:35
I think those files are uploaded to server as Artifacts as mentioned in the docs:

"(Optional) Path of the code coverage HTML report directory. The report directory is published for later viewing as an artifact of the build. The value may contain minimatch patterns. For example: $(System.DefaultWorkingDirectory)/MyApp//site/cobertura"

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
