### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by lambdakris** [MicrosoftDocs/azure-devops-docs#6886] opened 2020-01-10 15:27 UTC
Something basic that seems to be missing is what are the rules around naming files if any, and what are the effects of file names if any. Can I name my files like so azure-pipelines-dev.yml? Or is number - azure-pipelines-1.yml - the only supported way of having multiple yml files?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2020-01-13 16:44
@lambdakris Thank you for the feedback, assigning this to the author for review.

Please see [this post](https://devops.stackexchange.com/questions/9657/rename-build-pipeline-yml-files-in-azure-devops) for how to use a different *.yml* filename.

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
