### ISSUE TITLE
Provide documentation on how to emulate single repo path behavior with multiple repos

### ISSUE THREAD

**Issue by mtaylorfsmb** [MicrosoftDocs/azure-devops-docs#6895] opened 2020-01-10 20:56 UTC
One issue with multi repos is that `Build.SourcesDirectory` is no longer correct if you are using paths relative to it because each repos goes into a subfolder. If you read through these docs it is clear on this matter but what isn't quite so clear is that you can still get this behavior in multi-repos. This would be important for code that either relies on this or can be used in single/multi-repo situations (e.g. templates). It would be nice to document the steps to make this happen. Here's what seems to be working for me right now.

1. For the `self` checkout set `path` to `s`. This causes the main repo to go into the same folder it does in single repo builds.
1. All other checkout repos need to set `path` to either a separate folder (perhaps off of the base directory as documented) or ensure they do not conflict with folders in the main repo. 

For example this YAML 
```yaml
steps:
- checkout: self
  path: s
- checkout: templates
  path: build-tools
```
Produces a structure like this:
\a
\b
\build-tools
\s 
And `Build.SourcesDirectory` works as it did before. This yaml would work as well provided the main repo didn't have a `build-tools` folder (assuming the repo name lined up).
```yaml
steps:
- checkout: self
  path: s
- checkout: templates
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2020-01-13 21:47
@mtaylorfsmb Thank you for the feedback and for providing a working sample.

Assigning this to the author for further review.

**Comment by robal** [comment] 2020-03-18 17:35
Many thanks @mtaylorfsmb
I've just spent half a day debugging the single / multi repo folder structure behaviour.
It's a bit over-complicated (possibly for valid reasons), but your suggestion works great.
The only problem I see is that Microsoft may at some point change the default sources directory from "s" to something else and then we'll be stuffed (again).

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
