### ISSUE TITLE
Is it possible to trigger based on another pipeline?

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/azure-devops-docs#8300] opened 2020-05-13 08:15 UTC
Previous (classic) builds completion may cause triggering another builds. For example, my utilities project completion trigger all other dependent projects to build. Is it possible with yaml?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#ci-triggers)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2020-05-14 05:24
@VerdonTrigance Thank you for the question.

Please see [Triggers for classic build pipelines and YAML pipelines](https://docs.microsoft.com/azure/devops/pipelines/build/triggers?view=azure-devops) and let us know if you need further information.

**Comment by msebolt** [comment] 2020-05-18 06:41
Closing this issue now.

**Closed by msebolt** 2020-05-18 06:41 UTC
Labels: Pri1, devops-cicd-repos/tech, devops/prod, product-question

**Comment by VerdonTrigance** [comment] 2020-05-18 12:33
> @VerdonTrigance Thank you for the question.
> 
> Please see [Triggers for classic build pipelines and YAML pipelines](https://docs.microsoft.com/azure/devops/pipelines/build/triggers?view=azure-devops) and let us know if you need further information.

Seriously? Are you kidding me? You point me back from where I come? There is nothing about it! That's why I am asking YOU here. 
Once more: is it possible to trigger build based on completion of another?

**Comment by msebolt** [comment] 2020-05-18 16:41
Please see if [runtime parameters](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/runtime-parameters.md) from issue https://github.com/MicrosoftDocs/azure-devops-docs/issues/3702 is what you are looking for.

**Comment by VerdonTrigance** [comment] 2020-05-18 16:46
> Please see if [runtime parameters](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/runtime-parameters.md) from issue #3702 is what you are looking for.

No, it's not. At least I don't see any connection between runtime params and triggering another builds.

**Comment by msebolt** [comment] 2020-05-18 17:43
You would trigger the build, then use runtime params as [conditions](https://docs.microsoft.com/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml).

There has been discussion on easier ways to trigger builds, for example [this post](https://developercommunity.visualstudio.com/content/problem/380221/yaml-build-pipeline-path-triggers-do-not-support-v.html), however the outcome was designated as *by design*.

If you'd like to revisit the issue and/or solicit additional feedback from the product team, please refer to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by VerdonTrigance** [comment] 2020-05-28 09:46
> You would trigger the build, then use runtime params as [conditions](https://docs.microsoft.com/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml).
> 
> There has been discussion on easier ways to trigger builds, for example [this post](https://developercommunity.visualstudio.com/content/problem/380221/yaml-build-pipeline-path-triggers-do-not-support-v.html), however the outcome was designated as _by design_.
> 
> If you'd like to revisit the issue and/or solicit additional feedback from the product team, please refer to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Again you are telling about triggering single build, but I asking about triggering another build after first one was completed. Your link is nothing about it again.

**Comment by VerdonTrigance** [comment] 2020-06-09 12:32
For those who is looking for solution: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml more specific description.
