### ISSUE TITLE
Build yaml usefile

### ISSUE THREAD

**Issue by adamtuliper** [MicrosoftDocs/azure-devops-docs#7135] opened 2020-01-31 22:56 UTC
There are other yaml samples on the page except for the build. Since someone may be adding this into an existing pipeline it would be nice to show the build yaml here so we don't have to create a new one and pluck it out. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8b12f39-46e7-7928-3384-ae8b99c67b6c
* Version Independent ID: 2110797a-6604-0989-1504-3e4fe619f899
* Content: [Deploy a function app to Azure Functions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-functions?view=azure-devops&tabs=dotnet-core%2Cyaml#feedback)
* Content Source: [docs/pipelines/targets/azure-functions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/azure-functions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
