### ISSUE TITLE
Helm Charts

### ISSUE THREAD

**Issue by gdv820** [MicrosoftDocs/azure-devops-docs#6117] opened 2019-10-23 23:43 UTC
You've mentioned that the previous CI build pipeline packaged and published the helm charts needed for the later stages. Can you provide the link to that tutorial please ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa99181-afb1-98c4-5978-6dab603b55f9
* Version Independent ID: 8f4ec1e8-f3b2-f427-0b3f-4e658a573095
* Content: [Deploy a Docker container app to AKS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-aks?view=azure-devops&tabs=java#feedback)
* Content Source: [docs/pipelines/apps/cd/deploy-aks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-aks.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by PatrickBig** [comment] 2019-11-26 23:01
Was just wondering the same thing, I searched for a while and can't find this.

**Comment by AndrewConniff** [comment] 2019-12-02 09:12
Went through all the links to previous steps and checked out all the source code repositories and I also cannot find the reference to any helm charts (which should be a file directory in source control )  Possibly the links are not correct?

**Comment by viniciusx** [comment] 2020-04-16 18:11
We're 8 months after this issue was posted and no responde yet from Microsoft. Has anyone found any mention of the helm chart?

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement

**Comment by terle** [comment] 2021-01-12 06:47
Now it's 15 months after the issue was created.  And it's still not clear how the Helm chart is created.
I want to learn and even pay for AKS, but please. Help me learn
