### ISSUE TITLE
Build schedule not working if specified differently in branch

### ISSUE THREAD

**Issue by bpasero** [MicrosoftDocs/azure-devops-docs#8036] opened 2020-04-22 07:14 UTC
Hi,

VSCode defines a build that runs daily [using the following configuration](https://github.com/microsoft/vscode/blob/master/build/azure-pipelines/product-build.yml#L147):

```
schedules:
- cron: "0 5 * * Mon-Fri"
displayName: Mon-Fri at 7:00
branches:
include:
- master
```

At the same time we have a branch called `electron-8.0.x` that [changes this configuration](https://github.com/microsoft/vscode/blob/electron-8.0.x/build/azure-pipelines/product-build.yml#L150) to be:

```
schedules:
- cron: "0 6 * * Mon-Fri"
displayName: Mon-Fri at 8:00
branches:
include:
- electron-8.0.x
```

So that it runs 1h after the `master` build. However this build is never triggered as you can see from the scheduled builds UI:

![image](https://user-images.githubusercontent.com/900690/79951782-a0afb380-8479-11ea-8894-3e9718fb2ceb.png)

Any help is appreciated.

**Comment by leantk** [comment] 2020-04-22 15:28
@bpasero could you try making an edit to the YAML file in the `electron-8.0.x` branch and commit it and see if that gets the schedules to be added for you? Sometimes the schedule update isn't picked up and an edit to the YAML file causes us to reload the schedules. We are looking at adding a feature to allow you to refresh schedules without having to make a commit but haven't gotten to it yet. Apologies for the weird workaround.

**Comment by bpasero** [comment] 2020-04-22 15:38
Oh yeah looks like that helped:

![image](https://user-images.githubusercontent.com/900690/80002554-1474af00-84c0-11ea-8e56-9a30f5710612.png)

A way to enforce a refresh of the schedule would be good to have, this is a bit magic to be honest because my initial check-in to that branch was also a change to that file.

**Comment by leantk** [comment] 2020-04-22 15:47
Yep 100% agreed. This is not a viable, discoverable solution and we will work on getting something more straight-forward and easy in place.

**Comment by Anupamvi** [comment] 2020-04-22 15:55
Why is this work item assigned to me? It seems to be build related, nothing to do with Azure network security or DDoS protection?

**Comment by cxwtool** [comment] 2020-11-24 23:27
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:27 UTC
Labels: Pri3
