### ISSUE TITLE
project: ##[error]Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).

### ISSUE THREAD

**Issue by randyram-at-ms** [MicrosoftDocs/azure-devops-docs#4632] opened 2019-06-25 21:48 UTC
I put your project name, 'OS' in the project param, but it wants the GUID for projectId. 
##[error]Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by chasewilson** [comment] 2019-07-03 14:29
@randyram-at-ms Thanks for keeping up on this page. I went ahead and updated the description to read "The project GUID from which to download the pipeline artifacts." I think this clarifies. @willsmythe feel free to close this issue if you agree with the fix.

**Comment by kevincummings** [comment] 2019-07-03 21:01
In the docs, it says that the 'project' argument takes the project's guid. Where can I find my project's guid?

**Comment by MakotoE** [comment] 2019-07-04 00:33
This is what I used to get my project's guid: https://docs.microsoft.com/en-us/rest/api/azure/devops/core/projects/list?view=azure-devops-rest-5.0.

**Comment by 3tcsoftware** [comment] 2019-07-18 11:42
Unfortunately all of the examples still reference a textual project name.
Also, it would be useful if there was something that explained how to get the pipeline id and project guids as they don't seem to be exposed through the UI

**Comment by jftl6y** [comment] 2019-07-31 22:38
Sorry but this page is really not helpful.  The arguments in no way match the YAML snippet.  As noted by others, the "project" value is not the friendly name but a GUID (which by the way, making users dig for a GUID is really not intuitive).  Is it pipeline or pipelineId?  Is it Artifact or ArtifactName?  In Azure DevOps when I add this, it has a value called "definition" which appears to be pipeline(?).  Again, what does "Definition: 30" or "Pipeline: 12" even mean?  

To download a pipeline artifact, you should need the name of the pipeline which generated the artifact (not a GUID), artifact name from the publish, build version (latest or specific), etc.  Please make this friendlier for users, not archaic and cryptic.

**Comment by lbrownell-gpsw** [comment] 2019-08-06 22:53
Agree with what all the above say, and to be clear, it's not just about this page, it's also about the ADO product.

This guid we seek -- there is absolutely nowhere in the ADO UI I can find one.  Also, the specific task argument is "project", not "pipeline" (btw, the example shows 'FabrikamFiber' as a possible value, which isn't a GUID).  The hierarchy at the top of my browser when looking at a build's results is like so:

<my-org> / <my-PROJECT> / Pipelines / Builds / <the-name-of-the-pipeline> / #<specific-build-number>

See that project?  Not the project you're looking for, and no guid there.

I've been fighting with trying to find a way to download an pipeline artifact that the PREVIOUS build uploaded. Can't seem to get there.

So far, I haven't needed to use the REST API.  I need to for this?  If so, could you document it?  This place wold be handy for things like that.

**Comment by lbrownell-gpsw** [comment] 2019-08-06 22:56
Arrrg, the above comment had angle-brackets around those items that were in-between the "/ /" text above.  Removed to avoid html injection, apparently.  Should have been:

/ MY-ORG / Pipelines / Builds / MY-PIPELINE-NAME / #BUILD-DATE-AND-NUMBER

**Comment by qwertoyo** [comment] 2019-08-27 09:26
I tried using the SYSTEM_DEFINITIONID of the 'source' pipeline as written in this page but got this error.
I also did not understand where I should find that Guid... I'll try to copy anything that looks like a Guid from the source pipeline build variables... 

Btw as it is this page looks wrong and misleading 😅. What's that 12?

**Comment by qwertoyo** [comment] 2019-08-27 09:50
I had it working, in case it helps someone else:
`- task: DownloadPipelineArtifact@2
  inputs: # artifact is not specified, will download all of them
    source: 'specific'
    project: '{project guid, 'project' as ADO root pj}' # GET https://dev.azure.com/{org}/_apis/projects?api-version=5.0 
    pipeline: 7693  #to get this, run the source build and check SYSTEM_DEFINITIONID variable 
    runVersion: 'latestFromBranch' # take the latest from 
    runBranch: 'refs/heads/master' # master`

**Comment by henry-padilla** [comment] 2019-09-04 14:57
You can also get the pipelineId from the URL when viewing the pipeline. 
Be careful: if you are viewing a specific run you will see the runId, not the pipelineId. View the pipeline list of runs and that will be the pipelineId. 
In keeping with the random names approach it's called 'definitionId' in the URL.

**Comment by henry-padilla** [comment] 2019-09-13 11:15
@vsalvino - That is more helpful than not mentioning it at all (I'm looking at you MS). But it assumes the Project Id and Pipeline Id you want to use are the current ones. I have separate build and deployment pipelines so, the ProjectId I can use but the Pipeline Id I still have to take a different tack.

I use a REST API call to get the RunId and I am trying to change it to get the Pipeline Id too. Here's the RunId if anyone can use it (how you set the variables for useLatestInternal, buildBranch, and BaseVersionNumber are up to you):

- powershell: |
    # Need to convert ${{parameters.useLatest}} from 'true' to a Powershell boolean.
    $parametersUseLatest = [System.Convert]::ToBoolean( '$(useLatestInternal)' )
    if ( $parametersUseLatest -eq $true) {
      $runUrl = 'https://dev.azure.com/{organization}/{project}/_apis/build/builds?api-version=5.0&branchName=$(buildBranch)&$top=1&queryOrder=finishTimeDescending'
    } else {
      $runUrl = "https://dev.azure.com/{organization}/{project}/_apis/build/builds?api-version=5.0&branchName=$(buildBranch)&buildNumber=$(BaseVersionNumber)"
    }

    Write-Host "URL: $runUrl"
    $runList = Invoke-RestMethod -Uri $runUrl -Headers @{ Authorization = "Bearer $(System.AccessToken)" }          
    if ($runList.Count -ne 1) {
      Write-Host "runList is not one. There's something wrong."
      Write-Host "$runList"
      Write-Host "##vso[task.logissue type=error]Version $(BaseVersionNumber) has $($runList.Count) runs. The runCount must be 1."
      Write-Host "##vso[task.complete result=Failed]"
    }

    $runId = $runList.value.Id
    Write-Host "RunId = $runId"
    # This is the way to set variables to be used in the pipeline
    Write-Host "##vso[task.setvariable variable=runId]$runId"
  displayName: Getting runId

**Comment by wimhollebrandse** [comment] 2019-11-06 10:52
@henry-padilla - that looks useful, but I think if you want to limit this based on a specific Git repository, you'd need to specify repositoryId which is a Guid that requires looking up (in the ADO UI).
This lookup would really need to be done dynamically in order to be useful in a YAML build/release pipeline, and I currently cannot see an easy way to do this.
MS needs to sort this out and allow the friendly and the unique names of repos, pipelines, runs etc. for a lot of these YAML tasks that under the hood rely on Guids.

More info on the Build API and its parameters can be found here:
https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-5.1

**Comment by wimhollebrandse** [comment] 2019-11-06 10:56
OK, looks like $(Build.Repository.ID) can be used...! Which works for the current repo.

**Comment by rfontijn** [comment] 2019-12-18 12:39
Maybe a good idead to change the examples as well on this...

**Comment by YEMEAC** [comment] 2020-01-17 09:00
the documentation need to be updated not easy way to find this Guid...

'$(System.TeamProjectId)'
GET https://dev.azure.com/{organization}/_apis/projects?api-version=5.0

**Comment by cxwtool** [comment] 2020-11-24 23:42
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:42 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
