### ISSUE TITLE
Example for running command in service container

### ISSUE THREAD

**Issue by cgreenza** [MicrosoftDocs/azure-devops-docs#5493] opened 2019-09-05 07:52 UTC
Please add an example of how one can run a command (or startup script) in a service container i.e. the equivalent of using docker exec

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1c794c-d676-fc7e-758e-3464f16a1554
* Version Independent ID: 941de04a-2d34-ec82-8612-00e4070de673
* Content: [Service Containers - Azure Pipelines & TFS](https://docs.microsoft.com/en-za/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/service-containers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/service-containers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @dakale
* Microsoft Alias: **dakale**

**Comment by aunsbjerg** [comment] 2020-02-19 15:11
Seconded. I need to download some pipeline artifacts into my service containers and run a script, but is this even possible?

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-enhancement
