### ISSUE TITLE
Does this support .Net Core 2.1 unit tests while specifying a Test Plan?

### ISSUE THREAD

**Issue by Bebo2345** [MicrosoftDocs/azure-devops-docs#3591] opened 2019-03-08 15:02 UTC
Does the VSTest task support running tests via a Test Plan associated via Test Cases to unit tests written in .Net Core 2.1?

The documentation says "Tests that target the .NET core framework can be executed by specifying the appropriate target framework value."
However, when I specify "Test Plan" for "Select tests using" I always get the warning:
##[warning]Other console options is not supported when using the multi-agent phase setting. This option will be ignored.

So it seems like it ends up ignoring the framework I specify. I am only running on one agent.

So next I try to specify the framework via a runsettings file, but I am unable to specify .Net Core 2.1. Maybe it is because of this issue: https://github.com/MicrosoftDocs/visualstudio-docs/issues/1305

Ultimately, VSTest task always errors out with "No test assemblies found".

I'm using TFS 2017 Update 3 On-Prem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by selangley-wa** [comment] 2019-07-24 16:54
Is there any difference between the capabilities of the Visual Studio Test task and the dotnet test command? Or can they both used to achieve the same results?

**Comment by kaadhina** [comment] 2019-10-09 09:09
This is a supported scenario. Both the test command and vstest use the same underlying platform to run the tests. If you face issues with this scenario, please open an issue here in this repo with the appropriate logs : https://github.com/microsoft/azure-pipelines-tasks/issues

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
