### ISSUE TITLE
Topic has outdated screenshot that mentions Visual Studio Team Services

### ISSUE THREAD

**Issue by ecfan** [MicrosoftDocs/azure-devops-docs#3375] opened 2019-02-14 21:41 UTC
This topic has an outdated screenshot that also references Visual Studio Team Services:

![image](https://user-images.githubusercontent.com/13206671/52819451-2b1eab00-305e-11e9-9df0-ec0f43f72f3c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98def25b-48a6-8a17-e321-21b8f55173b5
* Version Independent ID: 4d55763c-0dd1-4ae3-1d02-89e21ea3d69e
* Content: [Use the Azure portal to create a pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-azure-devops-project?view=azure-devops)
* Content Source: [docs/pipelines/get-started-azure-devops-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-azure-devops-project.md)
* Product: **devops**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by mlearned** [comment] 2019-07-16 10:32
these are being updated now, and we should be able to close this soon.

**Comment by nick-taylor4730** [comment] 2019-11-01 15:21
4 months later~

**Comment by cxwtool** [comment] 2020-11-24 23:47
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:47 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
