### ISSUE TITLE
InlineScript is mandatory even script location is File path - Confusion in AzureCLI@2 task Docs

### ISSUE THREAD

**Issue by ChendrayanV** [MicrosoftDocs/azure-devops-docs#5867] opened 2019-10-07 08:29 UTC
scriptLocation values are mentioned as file path and inlineScript and default value is scriptPath 

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: 'DEMO'
    scriptType: pwsh
    scriptPath: 'Azure/AzInventory.ps1'

In this case scriptLocation is not mandatory - Please update the docs and add file path example. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**

**Comment by constructdian** [comment] 2019-10-18 12:14
Indeed, documentation around this is confusing and in parts just plain wrong. Please fix this. So much wasted time due to poor docs here.

**Comment by cxwtool** [comment] 2020-11-24 23:39
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:39 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
