### ISSUE TITLE
Windows docker instructions use base image that won't work

### ISSUE THREAD

**Issue by chadbert** [MicrosoftDocs/azure-devops-docs#8263] opened 2020-05-09 19:24 UTC
According to the Visual Studio documentation and my own experience, the windows server core base image won't run the build tools properly. See VS2019 documentation here: https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2020-05-11 20:55
@chadbert  Please see if [this recent post](https://developercommunity.visualstudio.com/content/problem/926040/docker-build-task-in-azure-devops-for-windows-cont.html) addresses your issue.

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri1, devops-cicd-agents/tech, devops/prod, doc-bug
