### ISSUE TITLE
Sample UWP Repository does not exist

### ISSUE THREAD

**Issue by justindbaur** [MicrosoftDocs/azure-devops-docs#6862] opened 2020-01-08 18:12 UTC
This repository no longer exists https://github.com/Microsoft/UWPQuickStart . A different UWP should be used as the sample repo then.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef534262-046d-f433-5196-70ab5a5423e1
* Version Independent ID: f625de29-5faa-702e-a49d-d1b4e636e268
* Content: [Build your Universal Windows Platform app - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/windows/universal?view=azure-devops&tabs=vsts#feedback)
* Content Source: [docs/pipelines/apps/windows/universal.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/windows/universal.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment] 2020-01-09 16:56
@justindbaur Thank you for the feedback, assigning this to the author for review.

In the meantime, please refer to [this repo](https://github.com/microsoft/Windows-universal-samples) for the latest UWP examples.

**Comment by cxwtool** [comment] 2020-11-24 23:34
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:34 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
