### ISSUE TITLE
RHEL 7.5: Needs JDK 1.8+ instead of minimum JDK 1.6 version for TFVC

### ISSUE THREAD

**Issue by RSTZZZ** [MicrosoftDocs/azure-devops-docs#7277] opened 2020-02-13 18:52 UTC
The documentation states that:

"If you'll be using TFVC, you will also need the Oracle Java JDK 1.6 or higher. (The Oracle JRE and OpenJDK are not sufficient for this purpose.)"

On Red Hat Enterprise Linux version 7.5 with on-prem agent, JDK 1.7 throws exit code 100 when trying to query workspaces, with JWT authorization failing.

##[error]Exit code 100 returned from process: file name 'tf', arguments 'workspaces -format:xml "-collection:https://xxxx/xxx/" -jwt:*** -noprompt'.

Updating to JDK 1.8 solves the issue.

**Comment by WilliamAntonRohm** [comment] 2020-02-15 21:27
@RSTZZZ -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to process your issue, please let us know which topic you’re referencing.

**Comment by RSTZZZ** [comment] 2020-02-15 22:48
@WilliamAntonRohm -- I'm referencing this documentation: https://docs.microsoft.com/en-ca/azure/devops/pipelines/agents/v2-linux?view=azure-devops#check-prerequisites

**Comment by WilliamAntonRohm** [comment] 2020-02-21 00:52
@RSTZZZ -- thank you for clarifying.

@steved0x -- please look into this issue.

**Comment by cxwtool** [comment] 2020-11-24 23:32
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:32 UTC
Labels: Pri3, doc-bug
