### ISSUE TITLE
Precedence of preferTriggeringPipeline

### ISSUE THREAD

**Issue by reynoldsbd** [MicrosoftDocs/azure-devops-docs#8277] opened 2020-05-11 19:52 UTC
Consider the following task inputs:

```yaml
runVersion: latestFromBranch
runBranch: $(Build.SourceBranch)
preferTriggeringPipeline: true
```

Does `preferTriggeringPipeline` take precedence?

In other words, if the current pipeline was triggered by an earlier run of another pipeline, but a later run of that other pipeline has already completed, will I still get artifacts from the earlier run since it was the one responsible for triggering me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by cxwtool** [comment] 2020-11-24 23:26
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:26 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, doc-enhancement
