### ISSUE TITLE
Unable to Specify certPwd Using Secret from KeyVault

### ISSUE THREAD

**Issue by diffractious** [MicrosoftDocs/azure-devops-docs#4141] opened 2019-05-04 23:19 UTC
Looks like the `Pre-job: InstallAppleCertificate` task that needs the password happens before the `Download Secrets` task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e4f249c-c229-4a5c-7970-4e566026b560
* Version Independent ID: 7062bdf1-7b38-b42b-e117-c3041e09aae7
* Content: [Install Apple Certificate task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-certificate?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/install-apple-certificate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-apple-certificate.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by snicol21** [comment] 2019-06-15 04:38
I am having this same exact issue. Has anybody found a workaround?

**Comment by diffractious** [comment] 2019-06-16 20:46
@snicol21 Only workaround for now is to specify the password as a secret variable, either from the Library or in the pipeline itself.

**Comment by peterschen** [comment] 2019-07-04 14:56
Just stumbled across the same thing. At least there should be a note to this task that it is executed as a pre-job before any other things (especially key vault retrieval tasks) are happening. It might be possible to work around this issue by running a separate job before and pass the variable along. But I haven't had the time to try this.

**Comment by witekkij** [comment] 2020-05-06 13:34
This is still failing

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
