### ISSUE TITLE
artifact.upload undocumented parameter ?

### ISSUE THREAD

**Issue by ncourtiller** [MicrosoftDocs/azure-devops-docs#6974] opened 2020-01-17 14:10 UTC
I'v tried  the `artifact.upload` command in a _release_ pipeline and I get this error (*) : 

	2020-01-17T12:04:18.3260397Z ##[error]Unable to process command '##vso[artifact.upload containerfolder=icone;artifactname=image;]D:\AAlog\error.html' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
	2020-01-17T12:04:18.3260397Z ##[error]Value cannot be null.
	Parameter name: containerId

So, is there an undocumented parameter `containerId` that is mandatory for a _release_ pipeline ?

(*) no problem for me in a _build_ pipeline.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/fr-fr/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#task-commands)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **phwilson**

**Comment by cxwtool** [comment] 2020-11-24 23:33
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:33 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
