### ISSUE TITLE
Evaluation sequence

### ISSUE THREAD

**Issue by fleed** [MicrosoftDocs/azure-devops-docs#6291] opened 2019-11-07 10:06 UTC
Is there a specific sequence / priority in evaluation?
I'd like to understand which value is resolved if specified multiple times (e.g.: same name in different linked variable groups, same name defined locally and in one or more variable groups, etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#feedback)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment] 2019-11-07 18:00
@fleed Thank you for the question.

For variable precedence, see [Expansion of variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#expansion-of-variables) and for variable groups, see issue https://github.com/MicrosoftDocs/vsts-docs/issues/1142.

This appears to be a popular question, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
