### ISSUE TITLE
Clarify how errors are handled

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/azure-devops-docs#3264] opened 2019-02-06 23:37 UTC
In particular, is `set -x` prepended to the script? If not, then some advice should be given to make devs aware of that. Also, is the exit code of the script taken into account? What makes the task "fail"? The description only talks about "Fail on Standard Error" but that can't be the full story.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36fff5ec-d766-b589-39ff-9c69ab26dd5b
* Version Independent ID: 12deb045-2511-b5bf-9e41-0d223bef516b
* Content: [Shell Script task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/shell-script?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/shell-script.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/shell-script.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by buddyspike** [comment] 2019-03-21 20:05
It would be good to get some clarity around this. We have a pipeline that has a failing script task. It seems like non-zero exit code is ignored. Downside is a subsequent step is failing with a cryptic error.

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
