### ISSUE TITLE
Documentation doesn’t cover how views and complete graphs are expected to work together

### ISSUE THREAD

**Issue by jrdodds** [MicrosoftDocs/azure-devops-docs#5058] opened 2019-07-30 13:32 UTC
How are views and Complete graphs expected to work together?
As a hypothetical if I use a @Release view, then I need to promote all dependencies to the Release view including packages from an upstream source like NuGet.org for a complete graph.
In that hypothetical situation if I have a version of a package in the Release view and start a new version in the Prerelease view but both versions share a common dependency, how can I have a complete graph in both the Release and Prerelease views? The documentation doesn’t explain.
Please update the documentation to explain how views and complete graphs are expected to work together.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a891e9b-bf26-ea09-1da3-ebe3e57b7e26
* Version Independent ID: bf53c51c-c1c1-1931-44ef-81433746e5ec
* Content: [Views on Azure DevOps Services feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/views?view=azure-devops-2019#feedback)
* Content Source: [docs/artifacts/concepts/views.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/views.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by hintbw** [comment] 2020-01-19 14:15
This is an area where I agree the documentation is incomplete and could be improved to provide a better understanding of these concepts work together.

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri2, devops-artifacts/tech, devops/prod, doc-bug
