### ISSUE TITLE
Import Documentation | Should we add a note regarding Premium Machines

### ISSUE THREAD

**Issue by danielstocker** [MicrosoftDocs/azure-devops-docs#2496] opened 2018-11-19 21:36 UTC
I have a couple of feedback/discussion points around the section of the below article where we talk about imports of large collections that use an Azure VM. 

Article:
https://docs.microsoft.com/en-us/azure/devops/articles/migration-import

Section I am referring to:
Below are some additional recommended configurations for your SQL Azure VM. [...]

1. It's recommended that **D Series VMs be used as they're optimized for database operations.**
2. Ensure that the D Series VM has at least 28GBs of ram. Azure **D12** V2 VM sizes are recommended for imports.
[...]
4. If your source database is still over 1TB after reducing the size then **you will need to attach additional 1TB disks and combine them into a single partition to restore your database on the VM**. 
5. Collection databases over 1TB in size should consider using **Solid State Drives (SSDs)** for both the temporary database and collection database. 

Feedback:

- If SSDs are used, shouldn't a D*S* size be recommended rather than just a D size? 
- Should the D12 recommendation read "D12 v2 or newer/larger"? One of the users I talked to said that they thought they needed a D12 exactly. 
- Should we mention the fact that you can now have disks that are larger than 1TB? Having several 1 TB disks and creating a stroage space between them is obviously still an option, but can be more cumbersome than just provisioning a larger disk. https://docs.microsoft.com/en-gb/azure/virtual-machines/windows/managed-disks-overview

**Comment by roofers** [comment] 2019-02-04 22:23
@danielstocker - This is excellent feedback! That section does need a little bit of updating. I'll be making an import documentation update during this month. I'll include this feedback in that push.

**Comment by danielstocker** [comment] 2019-02-05 06:34
thanks @roofers 
sounds good

**Comment by elbatk** [comment] 2019-10-02 15:48
Hey @roofers , did this get updated? Don't want to close if it didn't.

**Comment by cxwtool** [comment] 2020-11-24 23:48
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:48 UTC
Labels: Pri3, devops-whitepapers/tech, devops/prod, doc-bug, help wanted
