### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mcurko** [MicrosoftDocs/azure-devops-docs#6157] opened 2019-10-28 09:34 UTC
I'm trying to follow these quickstarts in Azure Test Plans. The user interface doesn't even look like what I see here and I don't understand the purpose of what is described here. You should describe what are you trying to achieve and why should someone use Azure Test Plans, and than add a detailed and easy to follow description of steps to achieve the result. (see Azure Pipelines)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf72265-156c-de8c-d729-ba7b3b90193d
* Version Independent ID: 1a0c7272-6d36-6036-06cf-5801b55e2f70
* Content: [Create manual tests - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/create-test-cases?view=azure-devops#test-cases)
* Content Source: [docs/test/create-test-cases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/create-test-cases.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2019-10-28 20:02
@mcurko  Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:37
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:37 UTC
Labels: Pri1, devops-test/tech, devops/prod, doc-enhancement
