### ISSUE TITLE
The job running on agent Azure Pipelines 2 ran longer than the maximum time of 60 minutes. 

### ISSUE THREAD

**Issue by monajalal** [MicrosoftDocs/azure-devops-docs#13306] opened 2023-05-09 12:55 UTC
I am using Azure Pipeline Templates and in the `pipeline.yaml` file, I have the following and I am not sure where I can insert either of the following variables?

    `cancelTimeoutInMinutes: 180`
    `timeoutInMinutes: 180`

From the documentation in https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts it's not very clear where and how I should change the timeout in `pipeline.yaml` file?

```
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

# <inputs_and_outputs>
inputs:
  # training_images:
  training_data:
    type: uri_folder
    mode: download # pick ro_mount, rw_mount or download
    path: azureml:FAT:1
# </inputs_and_outputs>

    

# <jobs>
settings:
  default_datastore: azureml:MYDATASTORE
  continue_on_step_failure: true

jobs:
  train:
    # cancelTimeoutInMinutes: 180
    # timeoutInMinutes: 180
    type: command
    component: file:train.yaml
    compute: azureml:pose-4node-NC24r #16GPUs w r
    resources:
      instance_count: 4    # number of nodes
    distribution:
      type: pytorch
      process_count_per_instance: 4 # number of gpus

    # NOTE: set env var if needed
    environment_variables:
      NCCL_DEBUG: "INFO" # adjusts the level of info from NCCL tests
      # NCCL_TOPO_FILE: "/opt/microsoft/ndv4-topo.xml" # Use specific topology file for A100

      # NCCL_IB_PCI_RELAXED_ORDERING: "1" # Relaxed Ordering can greatly help the performance of Infiniband networks in virtualized environments.
      # NCCL_IB_DISABLE: "1" # force disable infiniband (if set to "1")
      # NCCL_NET_PLUGIN: "none" # to force NET/Plugin off (no rdma/sharp plugin at all)
      # NCCL_NET: "Socket" # to force node-to-node comm to use Socket (slow)
      NCCL_SOCKET_IFNAME: "lo" # to force Socket comm to use eth0 (use NCCL_NET=Socket)

      # UCX_IB_PCI_RELAXED_ORDERING: "on"
      # UCX_TLS: "tcp"
      # UCX_NET_DEVICES: "eth0" # if you have Error: Failed to resolve UCX endpoint...

      CUDA_DEVICE_ORDER: "PCI_BUS_ID" # ordering of gpus

      TORCH_DISTRIBUTED_DEBUG: "DETAIL"

    inputs:
      # data inputs
      train_data: ${{parent.inputs.training_data}}

      # data loading
      batch_size: 32
      manualseed: 42
      num_workers: 5
      prefetch_factor: 4
      persistent_workers: true
      pin_memory: true
      non_blocking: false

      # model
      model_arch: "vgg16"
      model_arch_pretrained: true

      # training
      num_epochs: 1 # for testing purposes
      learning_rate: 0.0001

      # profiling
      enable_profiling: false
      # multiprocessing_sharing_strategy: "file_system" # WARNING: this can cause hang at job completion

      # Model Registrataion
      register_model_as: "MY_MODEL_NAME"


# </jobs>

```

This is due to an error I keep getting as BUILD FAILED via email:

![Screenshot from 2023-05-09 07-49-16](https://github.com/MicrosoftDocs/azure-devops-docs/assets/1892917/0123b048-5346-46da-989a-e48512766714)

Here's also how my project structure look like using MLOps Pipeline Template.

![Screenshot from 2023-05-09 07-50-34](https://github.com/MicrosoftDocs/azure-devops-docs/assets/1892917/f4d0e819-1192-4955-8cdc-6a0a466764db)

Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by WilliamAntonRohm** [comment] 2023-05-12 17:12
Duplicate of #13305

**Closed by WilliamAntonRohm** 2023-05-12 17:12 UTC
Labels: duplicate, cba, Pri3
