### ISSUE TITLE
Why has the documentation not been updated for v3?

### ISSUE THREAD

**Issue by dnh-developer** [MicrosoftDocs/azure-devops-docs#8323] opened 2020-05-14 10:31 UTC
If I attempt to use AzureResourceManagerTemplateDeployment@2 I get warnings that task type is not valid.

When I click on the link (https://aka.ms/armtaskreadme) in Azure DevOps -&gt; Edit Pipeline for help it shows me a page on git for AzureResourceManagerTemplateDeployment@3, but it looks like the parameters are different from v2 and therefore this page is not helpful, plus there is no page I can find for proper documentation for v3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:25
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:25 UTC
Labels: Pri1, devops-cicd-tasks/tech, devops/prod, doc-enhancement
