### ISSUE TITLE
Document the specifySlotOrASE parameter.

### ISSUE THREAD

**Issue by bowlerma** [MicrosoftDocs/azure-devops-docs#8909] opened 2020-07-22 08:26 UTC
Hi,

There's currently no documentation around what the 'specifySlotOrASE' parameter does.

I'm not sure if it is intentional or not, but in order to be able to stop/start a deployment slot on an app service, this parameter must be set to 'true'.  If not set, only the production slot will stop/start, regardless of what is entered in the 'slot' parameter.  This should be documented.

Regards,

Mark

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f07461b2-a8a2-ec6f-769b-14b384777be3
* Version Independent ID: 2c72f09d-b198-461c-fc0d-1c3bd0a870c4
* Content: [Azure App Service Manage task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-app-service-manage?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-app-service-manage.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-app-service-manage.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:19
This issue hasn't been updated in more than 120 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:19 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod, doc-enhancement

**Comment by bowlerma** [comment] 2020-11-24 23:28
gee, thanks.
