### ISSUE TITLE
New York Support

### ISSUE THREAD

**Issue by liamfoneill** [MicrosoftDocs/azure-devops-docs#6351] opened 2019-11-13 11:22 UTC
This ServiceNow app has been updated on 12th Nov 2019 to support New York. Please update this page to reflect that. https://store.servicenow.com/sn_appstore_store.do#!/store/application/fa788cb5dbb5630040669c27db961940/4.161.0?referer=sn_appstore_store.do%23!%2Fstore%2Fsearch%3Fq%3Dazure

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d07f29c5-affb-47bb-5f68-fc49e691c741
* Version Independent ID: 661d3781-8784-868d-261f-1e994a154a35
* Content: [Control deployments by using ServiceNow - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/servicenow?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/approvals/servicenow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/approvals/servicenow.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
