### ISSUE TITLE
Specify Artifact Trigger behavior and format for filter if artifact is ACR image

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/azure-devops-docs#4159] opened 2019-05-07 00:56 UTC
Ok, it's clear how to filter branches as a pre-deployment trigger if our artifacts if a git repo.
But it's unclear how to filter if my artifact is docker image from ACR.
Please, specify more samples.

I'm asking, because I can't save neither "dev-[0-9]" not just "latest". It's either a bug, or misconfiguration 
![image](https://user-images.githubusercontent.com/578954/57264711-63fc6980-7028-11e9-8c81-143264010c52.png)
Doesn't matter what I included as a filter, Azure DevOps will not save it.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e313c5-9120-9172-bc27-c21d10fcd5ae
* Version Independent ID: 1a837182-591f-3cbc-1632-7b50d857b13c
* Content: [Release triggers for stages, branches, and pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment] 2019-06-19 06:29
@azooinmyluggage  - can  you please take a look?

**Comment by SychevIgor** [comment] 2019-08-31 05:26
@azooinmyluggage will be nice to have any answers. @azooinmyluggage

**Comment by SychevIgor** [comment] 2020-03-30 07:46
any updates?

**Comment by cxwtool** [comment] 2020-11-24 23:44
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:44 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug

**Comment by SychevIgor** [comment] 2020-11-26 11:36
@cxwtool @shashankbarsin @azooinmyluggage could you fix this issue, not just close! 180 days without update from Microsoft side, not from my.
