### ISSUE TITLE
Confusing instructions for using cache with Docker.

### ISSUE THREAD

**Issue by twastvedt** [MicrosoftDocs/azure-devops-docs#10887] opened 2021-06-08 20:23 UTC
The Docker Cache@2 example says:

> Replace caching-docker.yml with your own pipeline YAML file.

But the code example makes no reference to `caching-docker.yml` so I am not sure how to use the example in my build. Do I run the example steps at the beginning of my pipeline?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#docker-images)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment] 2021-06-08 21:45
This looks like a duplicate of MicrosoftDocs/azure-devops-docs/issues/10577

I'll close this one.

@twastvedt Thanks for finding this one. The fix is in progress.

**Closed** 2021-06-08 21:46 UTC
Labels: cba, devops-cicd-release/tech, devops/prod, duplicate
