### ISSUE TITLE
Highlight that this task is not necessary for Android Signing

### ISSUE THREAD

**Issue by xyfoo** [MicrosoftDocs/azure-devops-docs#4927] opened 2019-07-19 08:05 UTC
Similar to how iOS certificate is highlighted

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* Content: [Download Secure File task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-secure-file.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by pmullins-ewn** [comment] 2019-08-02 14:44
@xyfoo, any chance you can point me to docs that show how to sign an Android APK without downloading secure files? Looks like I've run into an issue with access to secure files, so a workaround would be nice :)

**Comment by xyfoo** [comment] 2019-08-02 15:10
@pmullins-ewn, my observation with Xamarin.Android project is that you don't explicitly need a ```DownloadSecureFile``` task, and supply the variable name into the ```AndroidSigning``` task.

You can just directly supply the secure file name to the ```AndroidSigning``` task, and it would download the secure file as part of the task.

```
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: MySecureFileNameInPipelineLibrary
    apksignerKeystorePassword: '$(android.signing.keystore.password)'
    apksignerKeystoreAlias: '$(android.signing.keystore.alias)'
    apksignerKeyPassword: '$(android.signing.password)'
```

**Comment by pmullins-ewn** [comment] 2019-08-02 15:19
Neat, thanks for the quick response. I'll give that a go. My issues were related to some strange file authorization problems, so I'm not sure if this will work for me, but it does save me from that `DownloadSecureFile` whenever I do get it figured out. Thank you!

**Comment by pmullins-ewn** [comment] 2019-08-02 15:54
@xyfoo that actually circumvented my issue! thanks a million :)

**Comment by cxwtool** [comment] 2020-11-24 23:41
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:41 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
