### ISSUE TITLE
XML Transformation - transform file order

### ISSUE THREAD

**Issue by ajklotz** [MicrosoftDocs/azure-devops-docs#7543] opened 2020-03-09 15:37 UTC
We use a build configuration called Release and we have a release pipeline with a staged called AzureQA. We have two transform files called App.Release.config and App.AzureQA.config. At release, we use XML transformation to change the configuration. We noticed after deployment that some of the values were incorrect. It was determined that the App.Release.config file had the wrong values and transformed them into the App.config. The App.AzureQA.config had the correct values.

So the question here is, which transform file is applied first? In the documentation, it shows that the App.Release.config file is applied first, then the *.&lt;stage&gt;.config file is applied.

In our scenario, I would have expected the App.AzureQA.config would have overwritten the settings from App.Release.config. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b149977a-3e5e-4d49-b37a-ef1da1821184
* Version Independent ID: 0c52a667-5b32-6b9b-fd70-5e47444f41c5
* Content: [File transforms and variable substitution - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops&tabs=Classic#configuration-transform-file-naming-conventions)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment] 2020-11-24 23:30
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:30 UTC
Labels: Pri2, devops-cicd-tasks/tech, devops/prod
