### ISSUE TITLE
2013 can't access default nuget v3 api feeds

### ISSUE THREAD

**Issue by zowazHC5** [MicrosoftDocs/azure-devops-docs#6364] opened 2019-11-13 22:51 UTC
The 'Using Visual Studio 2013 or earlier' section. It's not enough to just setup a PAT. You also need to use the v2 nuget API feed. If you use the current v3 api feed, you wont be able to access the feed.

This info needs to be added to the 2013 or earlier section as there is no way to have 2013 use the default v3 api feed.

devdiv bug 1010133 has more info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a10a409-5468-9532-f0dc-5a28cdd566d8
* Version Independent ID: 2ef20266-bc45-448b-27f5-e5c3bffed2ef
* Content: [Get started with NuGet packages in Azure DevOps Services and TFS - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops#feedback)
* Content Source: [docs/artifacts/get-started-nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/get-started-nuget.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment] 2019-11-14 05:43
@zowazHC5  Thank you for the feedback, assigning this to the author for review.

**Comment by cxwtool** [comment] 2020-11-24 23:36
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Closed by cxwtool** 2020-11-24 23:36 UTC
Labels: Pri1, devops-artifacts/tech, devops/prod, doc-enhancement
